import { describe, expect, it } from "vitest";
import { AI_BOT_MISSED_GRACE_MS } from "@/lib/ai-bot-auto-trade.server";
import { createDailySessions, createEmptyTradingStore, markExpiredSessionsMissed, placeUserTrade, settleUserTrade, syncAdditionalEligibility } from "@/lib/ai-trading-engine";

describe("AI Bot multi-session behavior",()=>{
  const sessions=createDailySessions("2026-07-22",0,"Asia/Kolkata");
  it("places Session 1, Session 2, and Session 3 independently",()=>{let store=createEmptyTradingStore();for(const session of sessions.slice(0,3))store=placeUserTrade({store,session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom,placementSource:"AI_BOT"}).store;expect(store.trades.map(item=>item.sessionId)).toEqual(sessions.slice(0,3).map(item=>item.id).reverse());expect(store.trades.every(item=>item.placementSource==="AI_BOT")).toBe(true)});
  it("adds the eligible 10 PM trade without consuming a regular session",()=>{let store=syncAdditionalEligibility(createEmptyTradingStore(),"2026-07-22",true);for(const session of sessions)store=placeUserTrade({store,session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom,placementSource:"AI_BOT"}).store;expect(store.trades).toHaveLength(4);expect(new Set(store.trades.map(item=>item.sessionId)).size).toBe(4)});
  it("does not let Session 1 or a restarted worker block Session 2",()=>{const first=placeUserTrade({store:createEmptyTradingStore(),session:sessions[0],userId:"user-1",userUid:"BV100001",futureBalance:1000,now:sessions[0].liveFrom,placementSource:"AI_BOT"}),restart=placeUserTrade({store:first.store,session:sessions[0],userId:"user-1",userUid:"BV100001",futureBalance:1000,now:sessions[0].liveFrom+1,placementSource:"AI_BOT"}),second=placeUserTrade({store:restart.store,session:sessions[1],userId:"user-1",userUid:"BV100001",futureBalance:990,now:sessions[1].liveFrom,placementSource:"AI_BOT"});expect(restart.created).toBe(false);expect(second.created).toBe(true);expect(second.store.trades).toHaveLength(2)});
  it("prevents a bot-placed session from receiving a Manual Missed record",()=>{const placed=placeUserTrade({store:createEmptyTradingStore(),session:sessions[0],userId:"user-1",userUid:"BV100001",futureBalance:1000,now:sessions[0].liveFrom,placementSource:"AI_BOT"}).store,after=markExpiredSessionsMissed(placed,[sessions[0]],"user-1","BV100001",sessions[0].placementClosesAt+AI_BOT_MISSED_GRACE_MS);expect(after.trades).toHaveLength(1);expect(after.trades[0].status).toBe("PLACED")});
  it("waits through the worker grace period before marking a bot session missed",()=>{const before=markExpiredSessionsMissed(createEmptyTradingStore(),[sessions[0]],"user-1","BV100001",sessions[0].placementClosesAt+AI_BOT_MISSED_GRACE_MS-1,AI_BOT_MISSED_GRACE_MS),after=markExpiredSessionsMissed(createEmptyTradingStore(),[sessions[0]],"user-1","BV100001",sessions[0].placementClosesAt+AI_BOT_MISSED_GRACE_MS,AI_BOT_MISSED_GRACE_MS);expect(before.trades).toHaveLength(0);expect(after.trades).toHaveLength(1)});
  it("settles every session independently",()=>{let store=createEmptyTradingStore();const placed=sessions.slice(0,3).map(session=>{const result=placeUserTrade({store,session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom,placementSource:"AI_BOT"});store=result.store;return{session,trade:result.trade}});for(const item of placed)store=settleUserTrade(store,item.trade.id,item.session,item.session.settlesAt).store;expect(store.trades).toHaveLength(3);expect(store.trades.every(item=>item.status==="SETTLED")).toBe(true);expect(store.notifications.filter(item=>item.type==="PROFIT_CREDITED")).toHaveLength(3)});
});
