import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { requestOpenAiStream } from "../lib/openai-support";
import { detectAttachmentType, validateAttachmentBytes } from "../lib/support-attachment";
import { decodeCursor, encodeCursor } from "../lib/support-pagination";
vi.mock("server-only",()=>({}));
const base={apiKey:"hidden-key",model:"gpt-5-mini",body:{input:"private"},chatSessionId:"session",userId:"user",sleep:async()=>undefined,random:()=>0};
describe("AI Support production hardening",()=>{
  it("retries 429 and 503 but not a validation failure",async()=>{for(const status of [429,503]){const fetcher=vi.fn().mockResolvedValueOnce(new Response("",{status})).mockResolvedValueOnce(new Response("ok",{status:200}));await requestOpenAiStream({...base,fetcher,maxRetries:2,logger:()=>undefined});expect(fetcher).toHaveBeenCalledTimes(2)}const fetcher=vi.fn().mockResolvedValue(new Response("bad",{status:400}));await expect(requestOpenAiStream({...base,fetcher,maxRetries:2,logger:()=>undefined})).rejects.toThrow("OPENAI_400");expect(fetcher).toHaveBeenCalledOnce()});
  it("aborts an OpenAI request at timeout and logs no secret or prompt",async()=>{vi.useFakeTimers();const logs:unknown[]=[];const fetcher=vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")))) as Promise<Response>);const pending=requestOpenAiStream({...base,fetcher,timeoutMs:1000,maxRetries:0,logger:value=>logs.push(value)}),assertion=expect(pending).rejects.toThrow();await vi.advanceTimersByTimeAsync(1001);await assertion;expect(JSON.stringify(logs)).not.toContain("hidden-key");expect(JSON.stringify(logs)).not.toContain("private");vi.useRealTimers()});
  it("validates attachment signatures and rejects MIME mismatch",()=>{const jpeg=new Uint8Array([0xff,0xd8,0xff,1,2,3,4,5,6,7,0xff,0xd9]);expect(detectAttachmentType(jpeg)).toBe("image/jpeg");expect(()=>validateAttachmentBytes(jpeg,"image/png")).toThrow("ATTACHMENT_MIME_MISMATCH");expect(()=>validateAttachmentBytes(new TextEncoder().encode("MZ executable payload"),"application/pdf")).toThrow()});
  it("round trips stable cursor pagination keys",()=>{const at=new Date("2026-07-20T12:00:00.000Z"),value=decodeCursor(encodeCursor(at,"row-id"));expect(value).toEqual({at,id:"row-id"});expect(decodeCursor("invalid")).toBeNull()});
  it("rejects cross-site or provenance-free mutations and accepts a signed same-origin request",async()=>{process.env.AUTH_SECRET="test-only-secret";const{assertMutationRequest,issueCsrfToken}=await import("../lib/support-security.server"),token=issueCsrfToken("user");expect(()=>assertMutationRequest(new Request("https://bitvora.test/api",{method:"POST",headers:{"x-csrf-token":token}}),"user")).toThrow("MISSING_REQUEST_PROVENANCE");expect(()=>assertMutationRequest(new Request("https://bitvora.test/api",{method:"POST",headers:{origin:"https://evil.test","sec-fetch-site":"cross-site","x-csrf-token":token}}),"user")).toThrow();expect(()=>assertMutationRequest(new Request("https://bitvora.test/api",{method:"POST",headers:{origin:"https://bitvora.test","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","x-csrf-token":token}}),"user")).not.toThrow()});
  it("contains cancellation, stale recovery, idempotency, sequence dedupe, SSE scoping and metadata-only ticket selects",()=>{const chat=readFileSync("app/api/support/chat/route.ts","utf8"),session=readFileSync("app/api/support/chats/[id]/route.ts","utf8"),events=readFileSync("app/api/support/events/route.ts","utf8"),tickets=readFileSync("app/api/support/route.ts","utf8"),client=readFileSync("components/support-module.tsx","utf8");expect(chat).toContain('generationStatus:"STREAMING"');expect(chat).toContain("idempotencyKey");expect(chat).toContain("sequence<=lastSequence");expect(session).toContain("STALE_GENERATION");expect(events).toContain("userId:user.id");expect(tickets).toContain("ticketSelect");expect(tickets).not.toContain("attachmentData:true");expect(client).toContain("AbortController");expect(client).toContain("Stop generation")});
});
