import { describe,expect,it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Prisma } from "@prisma/client";
import { createDailySessions } from "@/lib/ai-trading-engine";
import { calculatePrincipal,existingProfitRate } from "@/lib/ai-trade-scale/amount";
import { isAdditionalTradeEligible } from "@/lib/ai-trade-scale/eligibility";
const source=(file:string)=>readFileSync(resolve(process.cwd(),file),"utf8");
describe("AI trading consolidation",()=>{
  const start=new Date("2026-08-01T10:00:00.000Z"),end=new Date(start.getTime()+10*24*60*60_000),window={eligible:true,eligibilityStartedAt:start,eligibilityEndsAt:end};
  it("accepts the eligibility start boundary",()=>expect(isAdditionalTradeEligible(window,start.getTime())).toBe(true));
  it("accepts the final instant before the ten-day boundary",()=>expect(isAdditionalTradeEligible(window,end.getTime()-1)).toBe(true));
  it("rejects the exact eligibility end boundary",()=>expect(isAdditionalTradeEligible(window,end.getTime())).toBe(false));
  it("rejects day eleven",()=>expect(isAdditionalTradeEligible(window,end.getTime()+24*60*60_000)).toBe(false));
  it("rejects a consumed below-minimum opportunity",()=>expect(isAdditionalTradeEligible({...window,eligible:false,eligibilityEndsAt:null},start.getTime())).toBe(false));
  it.each([[12,1],[16,2],[20,3],[22,"ADDITIONAL"]] as const)("creates the %s local session",(hour,sequence)=>{const sessions=createDailySessions("2026-08-01",0,"Asia/Kolkata"),session=sessions.find(item=>item.sequence===sequence)!;expect(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",hour:"numeric",hourCycle:"h23"}).format(session.liveFrom)).toBe(String(hour))});
  it("calculates principal with Decimal",()=>expect(calculatePrincipal(new Prisma.Decimal("87.12345678")).toFixed(2)).toBe("0.87"));
  it("keeps regular deterministic daily rate divided across sessions",()=>{const rate=existingProfitRate("BV100001","2026-08-01","REGULAR");expect(rate.mul(3).gte(1)&&rate.mul(3).lte(2)).toBe(true)});
  it("keeps additional deterministic rate in range",()=>{const rate=existingProfitRate("BV100001","2026-08-01","ADDITIONAL");expect(rate.gte("0.40")&&rate.lte("0.50")).toBe(true)});
  it("auto-join no longer imports the legacy service",()=>{const route=source("app/api/ai-bot/auto-join/route.ts");expect(route).toContain("enqueueUserSessionTrade");expect(route).not.toContain("ai-bot-auto-trade.server")});
  it("removes browser polling execution from the app shell",()=>expect(source("components/app-shell.tsx")).not.toContain("AiBotRunner"));
  it("does not create new legacy execution records",()=>expect(source("lib/ai-trade-scale/financial.ts")).not.toContain("aiBotTradeExecution.create"));
  it("does not write authoritative trades to JSON",()=>expect(source("lib/ai-trade-scale/financial.ts")).not.toContain("trading:"));
  it("uses the relational wallet for trade decisions",()=>expect(source("lib/ai-trade-scale/financial.ts")).toContain("lockFutureWallet"));
  it("uses immutable transfer ledger keys",()=>expect(source("app/api/account/transfer/route.ts")).toContain("FUTURE_TRANSFER:"));
  it("has unique additional eligibility per user",()=>expect(source("prisma/schema.prisma")).toMatch(/model AiAdditionalTradeEligibility[\s\S]*userId\s+String\s+@id/));
  it("has one unique execution key",()=>expect(source("prisma/schema.prisma")).toMatch(/executionKey\s+String\s+@unique/));
  it("uses row locks",()=>expect(source("lib/future-wallet.server.ts")).toContain('FOR UPDATE'));
  it("uses serializable transactions",()=>expect(source("lib/future-wallet.server.ts")).toContain("Serializable"));
  it("makes the legacy placement path opt-in disabled",()=>expect(source("lib/ai-bot-auto-trade.server.ts")).toContain('LEGACY_AI_TRADE_ALLOW_NEW!=="YES"'));
  it("keeps the legacy PM2 worker absent",()=>expect(source("ecosystem.config.js")).not.toContain("bitvora-ai-auto-trade-worker"));
  it("guards production-like load execution",()=>expect(source("scripts/ai-trade-production-load.ts")).toContain('AI_TRADE_LOAD_TEST_CONFIRM!=="YES"'));
  it("provides dry-run legacy migration",()=>expect(source("package.json")).toContain("ai-trade:migrate-legacy"));
  it("provides wallet reconciliation",()=>expect(source("package.json")).toContain("future-wallet:reconcile"));
});
