import { describe, expect, it } from "vitest";
import { addTargetCompletedNotification, createDailySessions, createEmptyTradingStore, createSessionsBetween, ensureAdditionalEligibility, FIRST_DEPOSIT_BONUS_MS, getSessionById, getSessionPhase, getTradingDate, getUserSessionStatus, isFirstDepositBonusActive, markExpiredSessionsMissed, placeUserTrade, reconcileSessionNotifications, removeStaleMissedSessions, settleUserTrade, syncAdditionalEligibility } from "@/lib/ai-trading-engine";

describe("automatic AI trading sessions",()=>{
  it("derives stable user-local sessions and phase boundaries",()=>{const date="2026-07-17",first=createDailySessions(date,0,"Asia/Kolkata"),again=createDailySessions(date,Date.now(),"Asia/Kolkata");expect(again.map(({id,pair,chartSymbol,signalDirection})=>({id,pair,chartSymbol,signalDirection}))).toEqual(first.map(({id,pair,chartSymbol,signalDirection})=>({id,pair,chartSymbol,signalDirection})));expect(first.map(item=>new Date(item.liveFrom).toISOString())).toEqual(["2026-07-17T06:30:00.000Z","2026-07-17T10:30:00.000Z","2026-07-17T14:30:00.000Z","2026-07-17T16:30:00.000Z"]);const session=first[2];expect(getSessionPhase(session,session.liveFrom-1)).toBe("UPCOMING");expect(getSessionPhase(session,session.liveFrom)).toBe("LIVE");expect(getSessionPhase(session,session.placementClosesAt)).toBe("PROCESSING");expect(getSessionPhase(session,session.settlesAt)).toBe("SETTLED")});
  it("keeps 12 PM, 4 PM, 8 PM, and 10 PM local across offset and DST zones",()=>{expect(createDailySessions("2026-07-17",0,"Asia/Kathmandu").map(item=>new Date(item.liveFrom).toISOString())).toEqual(["2026-07-17T06:15:00.000Z","2026-07-17T10:15:00.000Z","2026-07-17T14:15:00.000Z","2026-07-17T16:15:00.000Z"]);expect(createDailySessions("2026-07-17",0,"America/New_York").map(item=>new Date(item.liveFrom).toISOString())).toEqual(["2026-07-17T16:00:00.000Z","2026-07-17T20:00:00.000Z","2026-07-18T00:00:00.000Z","2026-07-18T02:00:00.000Z"])});
  it("uses the shared direction and keeps placement and settlement idempotent",()=>{const session=createDailySessions("2026-07-17",0)[0],input={session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom};const placed=placeUserTrade({store:createEmptyTradingStore(),...input});expect(placed.trade.direction).toBe(session.signalDirection);const duplicate=placeUserTrade({store:placed.store,...input});expect(duplicate.created).toBe(false);expect(duplicate.store.trades).toHaveLength(1);expect(()=>placeUserTrade({store:createEmptyTradingStore(),...input,now:session.placementClosesAt})).toThrow(/not LIVE/);const settled=settleUserTrade(placed.store,placed.trade.id,session,session.settlesAt);expect(settled.trade.status).toBe("SETTLED");expect(settleUserTrade(settled.store,placed.trade.id,session,session.settlesAt+1).settled).toBe(false)});
  it("uses scheduled time for late settlement entitlement",()=>{const session=createDailySessions("2026-07-17",0)[0],placed=placeUserTrade({store:createEmptyTradingStore(),session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom}),reopenedAt=session.settlesAt+8*60*60_000,settled=settleUserTrade(placed.store,placed.trade.id,session,reopenedAt);expect(settled.trade.settledAt).toBe(session.settlesAt);expect(settled.store.notifications.filter(item=>item.type==="TRADE_SETTLED")).toHaveLength(1);expect(settleUserTrade(settled.store,placed.trade.id,session,reopenedAt+1000).store.notifications).toHaveLength(settled.store.notifications.length)});
  it("catches up across midnight in the user's timezone",()=>{const before=Date.parse("2026-07-17T18:29:59.000Z"),after=Date.parse("2026-07-17T18:30:01.000Z"),zone="Asia/Kolkata";expect(getTradingDate(before,zone)).toBe("2026-07-17");expect(getTradingDate(after,zone)).toBe("2026-07-18");expect(new Set(createSessionsBetween(before,after,zone).map(item=>item.tradingDate))).toEqual(new Set(["2026-07-17","2026-07-18"]));expect(getSessionById("AI_SESSION:2026-07-17:3",after,zone)?.tradingDate).toBe("2026-07-17")});
  it("expires first-deposit bonus eligibility after exactly ten days and resets it daily",()=>{const confirmed=Date.parse("2026-07-01T10:00:00Z");expect(isFirstDepositBonusActive(confirmed,confirmed)).toBe(true);expect(isFirstDepositBonusActive(confirmed,confirmed+FIRST_DEPOSIT_BONUS_MS-1)).toBe(true);expect(isFirstDepositBonusActive(confirmed,confirmed+FIRST_DEPOSIT_BONUS_MS)).toBe(false);const dayOne=syncAdditionalEligibility(createEmptyTradingStore(),"2026-07-01",true),used={...dayOne,trades:[{id:"used",userId:"u",userUid:"BV100001",sessionId:"AI_SESSION:2026-07-01:ADDITIONAL",direction:"CALL" as const,balanceSnapshot:1,dailyProfitBase:1,tradeCapital:1,profitRate:1,profitAmount:1,status:"SETTLED" as const,placedAt:1,settledAt:2,idempotencyKey:"used",placementSource:"MANUAL" as const}]},sameDay=syncAdditionalEligibility(used,"2026-07-01",true),nextDay=syncAdditionalEligibility(sameDay,"2026-07-02",true);expect(sameDay.additional.additionalTradeUsed).toBe(true);expect(nextDay.additional.additionalTradeUsed).toBe(false);expect(syncAdditionalEligibility(nextDay,"2026-07-02",false).additional.additionalTradeEligibilityDate).toBeNull()});
  it("records missed and expired Additional Trades once",()=>{const sessions=createDailySessions("2026-07-17",0),eligible=ensureAdditionalEligibility(createEmptyTradingStore(),"2026-07-17",1000),now=Math.max(...sessions.map(session=>session.placementClosesAt)),missed=markExpiredSessionsMissed(eligible,sessions,"user-1","BV100001",now),again=markExpiredSessionsMissed(missed,sessions,"user-1","BV100001",now+1000);expect(missed.trades.filter(item=>item.status==="MISSED")).toHaveLength(4);expect(again.trades).toHaveLength(4);expect(again.additional.additionalTradeUsed).toBe(true);expect(ensureAdditionalEligibility(again,"2026-07-18",1000).additional.additionalTradeEligibilityDate).toBe("2026-07-17")});
  it("deduplicates LIVE and Additional notifications across refreshes",()=>{const sessions=createDailySessions("2026-07-17",0),eligible=ensureAdditionalEligibility(createEmptyTradingStore(),"2026-07-17",1000),now=sessions[3].liveFrom,once=reconcileSessionNotifications(eligible,sessions,"user-1",now),twice=reconcileSessionNotifications(once,sessions,"user-1",now);expect(twice.notifications).toEqual(once.notifications);expect(new Set(twice.notifications.map(item=>item.id)).size).toBe(twice.notifications.length);expect(twice.notifications.some(item=>item.type==="ADDITIONAL_AVAILABLE")).toBe(true)});
  it("creates the 70% completion notification only once",()=>{const once=addTargetCompletedNotification(createEmptyTradingStore(),"user-1",100),twice=addTargetCompletedNotification(once,"user-1",200);expect(twice.notifications).toHaveLength(1);expect(twice.notifications[0].createdAt).toBe(100)});
  it("keeps Session 3 status and countdown boundaries consistent",()=>{const session=createDailySessions("2026-07-17",0)[2];expect(getUserSessionStatus(session,undefined,session.liveFrom-1)).toBe("UPCOMING");expect(getUserSessionStatus(session,undefined,session.liveFrom)).toBe("LIVE");expect(getUserSessionStatus(session,undefined,session.placementClosesAt-1)).toBe("LIVE");expect(getUserSessionStatus(session,undefined,session.placementClosesAt)).toBe("MISSED");const placed=placeUserTrade({store:createEmptyTradingStore(),session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom}).trade;expect(getUserSessionStatus(session,placed,session.liveFrom)).toBe("JOINED");expect(getUserSessionStatus(session,{...placed,status:"SETTLED"},session.settlesAt)).toBe("COMPLETED")});
  it("removes a stale missed marker created using an old Session 3 close",()=>{const sessions=createDailySessions("2026-07-17",0),session=sessions[2],missed=markExpiredSessionsMissed(createEmptyTradingStore(),[session],"user-1","BV100001",session.placementClosesAt),stale={...missed,trades:missed.trades.map(trade=>({...trade,placedAt:trade.placedAt-30*60_000}))};expect(removeStaleMissedSessions(stale,sessions,"user-1").trades).toHaveLength(0)});
});
