import { describe, expect, it } from "vitest";
import { addTargetCompletedNotification, createDailySessions, createEmptyTradingStore, createSessionsBetween, ensureAdditionalEligibility, getSessionById, getSessionPhase, getTradingDate, markExpiredSessionsMissed, placeUserTrade, reconcileSessionNotifications, settleUserTrade } from "@/lib/ai-trading-engine";

describe("automatic AI trading sessions",()=>{
  it("derives stable shared sessions and phase boundaries",()=>{const date="2026-07-17",first=createDailySessions(date,0),again=createDailySessions(date,Date.now());expect(again.map(({id,pair,chartSymbol,signalDirection})=>({id,pair,chartSymbol,signalDirection}))).toEqual(first.map(({id,pair,chartSymbol,signalDirection})=>({id,pair,chartSymbol,signalDirection})));expect(first.map(item=>new Date(item.liveFrom).toISOString())).toEqual(["2026-07-17T09:30:00.000Z","2026-07-17T13:30:00.000Z","2026-07-17T15:30:00.000Z","2026-07-17T16:30:00.000Z"]);const session=first[0];expect(getSessionPhase(session,session.liveFrom-1)).toBe("UPCOMING");expect(getSessionPhase(session,session.liveFrom)).toBe("LIVE");expect(getSessionPhase(session,session.placementClosesAt)).toBe("PROCESSING");expect(getSessionPhase(session,session.settlesAt)).toBe("SETTLED")});
  it("uses the shared direction and keeps placement and settlement idempotent",()=>{const session=createDailySessions("2026-07-17",0)[0],input={session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom};const placed=placeUserTrade({store:createEmptyTradingStore(),...input});expect(placed.trade.direction).toBe(session.signalDirection);const duplicate=placeUserTrade({store:placed.store,...input});expect(duplicate.created).toBe(false);expect(duplicate.store.trades).toHaveLength(1);expect(()=>placeUserTrade({store:createEmptyTradingStore(),...input,now:session.placementClosesAt})).toThrow(/not LIVE/);const settled=settleUserTrade(placed.store,placed.trade.id,session,session.settlesAt);expect(settled.trade.status).toBe("SETTLED");expect(settleUserTrade(settled.store,placed.trade.id,session,session.settlesAt+1).settled).toBe(false)});
  it("uses scheduled time for late settlement entitlement",()=>{const session=createDailySessions("2026-07-17",0)[0],placed=placeUserTrade({store:createEmptyTradingStore(),session,userId:"user-1",userUid:"BV100001",futureBalance:1000,now:session.liveFrom}),reopenedAt=session.settlesAt+8*60*60_000,settled=settleUserTrade(placed.store,placed.trade.id,session,reopenedAt);expect(settled.trade.settledAt).toBe(session.settlesAt);expect(settled.store.notifications.filter(item=>item.type==="TRADE_SETTLED")).toHaveLength(1);expect(settleUserTrade(settled.store,placed.trade.id,session,reopenedAt+1000).store.notifications).toHaveLength(settled.store.notifications.length)});
  it("catches up across midnight using Asia/Kolkata dates",()=>{const before=Date.parse("2026-07-17T18:29:59.000Z"),after=Date.parse("2026-07-17T18:30:01.000Z");expect(getTradingDate(before)).toBe("2026-07-17");expect(getTradingDate(after)).toBe("2026-07-18");expect(new Set(createSessionsBetween(before,after).map(item=>item.tradingDate))).toEqual(new Set(["2026-07-17","2026-07-18"]));expect(getSessionById("AI_SESSION:2026-07-17:3",after)?.tradingDate).toBe("2026-07-17")});
  it("records missed and expired Additional Trades once",()=>{const sessions=createDailySessions("2026-07-17",0),eligible=ensureAdditionalEligibility(createEmptyTradingStore(),"2026-07-17",1000),now=sessions[3].placementClosesAt,missed=markExpiredSessionsMissed(eligible,sessions,"user-1","BV100001",now),again=markExpiredSessionsMissed(missed,sessions,"user-1","BV100001",now+1000);expect(missed.trades.filter(item=>item.status==="MISSED")).toHaveLength(4);expect(again.trades).toHaveLength(4);expect(again.additional.additionalTradeUsed).toBe(true);expect(ensureAdditionalEligibility(again,"2026-07-18",1000).additional.additionalTradeEligibilityDate).toBe("2026-07-17")});
  it("deduplicates LIVE and Additional notifications across refreshes",()=>{const sessions=createDailySessions("2026-07-17",0),eligible=ensureAdditionalEligibility(createEmptyTradingStore(),"2026-07-17",1000),now=sessions[3].liveFrom,once=reconcileSessionNotifications(eligible,sessions,"user-1",now),twice=reconcileSessionNotifications(once,sessions,"user-1",now);expect(twice.notifications).toEqual(once.notifications);expect(new Set(twice.notifications.map(item=>item.id)).size).toBe(twice.notifications.length);expect(twice.notifications.some(item=>item.type==="ADDITIONAL_AVAILABLE")).toBe(true)});
  it("creates the 70% completion notification only once",()=>{const once=addTargetCompletedNotification(createEmptyTradingStore(),"user-1",100),twice=addTargetCompletedNotification(once,"user-1",200);expect(twice.notifications).toHaveLength(1);expect(twice.notifications[0].createdAt).toBe(100)});
});
