import { createHmac, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { canonicalizeIpnPayload, verifyIpnSignature } from "@/lib/nowpayments/client.server";
import { NOWPAYMENTS_NETWORKS, normalizePaymentStatus } from "@/lib/nowpayments/config";
import { createDeposit, createDepositSchema, reconcileProviderPayment, refreshDeposit } from "@/lib/nowpayments/deposit-service.server";
import type { DemoDepositRecord } from "@/lib/nowpayments/deposit-types";
import { DEPOSIT_STORE_KEY, readDepositRecords, writeDepositRecords } from "@/lib/nowpayments/deposit-types";
import { cloneWalletSeed, creditNowPaymentsDeposit } from "@/lib/wallet-data";

const original={enabled:process.env.NOWPAYMENTS_DEPOSIT_ENABLED,mock:process.env.NOWPAYMENTS_MOCK_MODE,secret:process.env.NOWPAYMENTS_IPN_SECRET,key:process.env.NOWPAYMENTS_API_KEY,url:process.env.NEXT_PUBLIC_APP_URL,databaseUrl:process.env.DATABASE_URL};
const user={id:`test-user-${randomUUID()}`,uid:"BV900001"};
const baseRecord=():DemoDepositRecord=>({id:`record-${randomUUID()}`,userId:user.id,userUid:user.uid,provider:"NOWPAYMENTS",providerPaymentId:"123456",orderId:"BITVORA_DEPOSIT:BV900001:1:abcd",requestedAmount:10,payAmount:10,payCurrency:"usdtbsc",network:"USDT_BEP20",payAddress:"0xBscAddress",paymentStatus:"WAITING",actuallyPaid:0,amountCredited:0,creditStatus:"NOT_CREDITED",txHash:null,idempotencyKey:randomUUID(),createdAt:1,updatedAt:1,finishedAt:null,expiresAt:null,mock:false});
const payment=(overrides:Record<string,unknown>={})=>({payment_id:"123456",payment_status:"finished",pay_address:"0xBscAddress",price_amount:10,price_currency:"usd",pay_amount:10,pay_currency:"usdtbsc",order_id:"BITVORA_DEPOSIT:BV900001:1:abcd",actually_paid:10,updated_at:"2026-07-17T10:00:00.000Z",payin_hash:"tx123",...overrides});

describe.sequential("NOWPayments deposits",()=>{
  beforeAll(()=>{process.env.NOWPAYMENTS_DEPOSIT_ENABLED="true";process.env.NOWPAYMENTS_MOCK_MODE="true";process.env.NOWPAYMENTS_IPN_SECRET="test-ipn-secret";process.env.NEXT_PUBLIC_APP_URL="https://example.test";delete process.env.DATABASE_URL});
  afterAll(()=>{for(const[key,value]of Object.entries(original)){const envKey={enabled:"NOWPAYMENTS_DEPOSIT_ENABLED",mock:"NOWPAYMENTS_MOCK_MODE",secret:"NOWPAYMENTS_IPN_SECRET",key:"NOWPAYMENTS_API_KEY",url:"NEXT_PUBLIC_APP_URL",databaseUrl:"DATABASE_URL"}[key]!;if(value===undefined)delete process.env[envKey];else process.env[envKey]=value}});
  it("1. creates a valid development deposit",async()=>{const record=await createDeposit(user,{amount:25,network:"USDT_BEP20",idempotencyKey:randomUUID()});expect(record.providerPaymentId).toMatch(/^MOCK_NP_/);expect(record.payCurrency).toBe("usdtbsc");expect(record.userId).toBe(user.id)});
  it("2. rejects an invalid amount",()=>{expect(()=>createDepositSchema.parse({amount:0,network:"USDT_BEP20",idempotencyKey:randomUUID()})).toThrow()});
  it("3. rejects an unsupported network",()=>{expect(()=>createDepositSchema.parse({amount:10,network:"USDT_ERC20",idempotencyKey:randomUUID()})).toThrow()});
  it("4. rejects an amount below the minimum",async()=>{await expect(createDeposit(user,{amount:1,network:"USDT_BEP20",idempotencyKey:randomUUID()})).rejects.toMatchObject({code:"BELOW_MINIMUM"})});
  it("5. normalizes provider create failures",async()=>{process.env.NOWPAYMENTS_MOCK_MODE="false";process.env.NOWPAYMENTS_API_KEY="test-key";const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("failure",{status:500}));await expect(createDeposit(user,{amount:10,network:"USDT_BEP20",idempotencyKey:randomUUID()})).rejects.toMatchObject({code:"PROVIDER_ERROR"});fetchMock.mockRestore();process.env.NOWPAYMENTS_MOCK_MODE="true"});
  it("6. normalizes all supported statuses",()=>{expect(["waiting","confirming","confirmed","sending","partially_paid","finished","failed","refunded","expired"].map(normalizePaymentStatus)).toEqual(["WAITING","CONFIRMING","CONFIRMED","SENDING","PARTIALLY_PAID","FINISHED","FAILED","REFUNDED","EXPIRED"])});
  it("7. accepts a valid IPN signature",()=>{const payload={payment_id:1,payment_status:"finished",nested:{b:2,a:1}},signature=createHmac("sha512","test-ipn-secret").update(canonicalizeIpnPayload(payload)).digest("hex");expect(verifyIpnSignature(payload,signature)).toBe(true)});
  it("8. rejects an invalid IPN signature",()=>{expect(verifyIpnSignature({payment_id:1},"00".repeat(64))).toBe(false)});
  it("9. FINISHED credits Spot once",()=>{const record=reconcileProviderPayment(baseRecord(),payment()),wallet=creditNowPaymentsDeposit(cloneWalletSeed(),{providerPaymentId:record.providerPaymentId,orderId:record.orderId,network:record.network,amount:record.amountCredited,txHash:record.txHash,timestamp:record.finishedAt!});expect(wallet.wallets.spot.balance).toBe(cloneWalletSeed().wallets.spot.balance+10);expect(wallet.wallets.future.balance).toBe(cloneWalletSeed().wallets.future.balance)});
  it("10. repeated IPN cannot duplicate credit",()=>{const input={providerPaymentId:"repeat-ipn",orderId:"order",network:"TRC20",amount:10,txHash:"tx",timestamp:1},once=creditNowPaymentsDeposit(cloneWalletSeed(),input),twice=creditNowPaymentsDeposit(once,input);expect(twice).toEqual(once)});
  it("11. manual refresh after IPN cannot duplicate credit",()=>{const input={providerPaymentId:"ipn-refresh",orderId:"order",network:"TRC20",amount:10,txHash:"tx",timestamp:1},afterIpn=creditNowPaymentsDeposit(cloneWalletSeed(),input),afterRefresh=creditNowPaymentsDeposit(afterIpn,input);expect(afterRefresh.transactions.filter(item=>item.reference.includes("ipn-refresh"))).toHaveLength(1)});
  it("12. PARTIALLY_PAID requires review and does not credit",()=>{const record=reconcileProviderPayment(baseRecord(),payment({payment_status:"partially_paid",actually_paid:4}));expect(record.creditStatus).toBe("MANUAL_REVIEW");expect(record.amountCredited).toBe(0)});
  it("13. EXPIRED does not credit",()=>{const record=reconcileProviderPayment(baseRecord(),payment({payment_status:"expired",actually_paid:0}));expect(record.paymentStatus).toBe("EXPIRED");expect(record.creditStatus).toBe("NOT_CREDITED")});
  it("14. FAILED does not credit",()=>{const record=reconcileProviderPayment(baseRecord(),payment({payment_status:"failed",actually_paid:0}));expect(record.paymentStatus).toBe("FAILED");expect(record.amountCredited).toBe(0)});
  it("15. rejects payment/order mismatch",()=>{expect(()=>reconcileProviderPayment(baseRecord(),payment({order_id:"another-order"}))).toThrow(/does not match/)});
  it("16. rejects currency/network mismatch",()=>{expect(()=>reconcileProviderPayment(baseRecord(),payment({pay_currency:"usdttrc20"}))).toThrow(/currency or network/)});
  it("17. another user cannot claim a payment",async()=>{const record=await createDeposit(user,{amount:20,network:"USDT_BEP20",idempotencyKey:randomUUID()});await expect(refreshDeposit({id:"another-user",uid:"BV900002"},record.providerPaymentId)).rejects.toMatchObject({code:"NOT_FOUND"})});
  it("18. does not expose the API key to client code",async()=>{const source=await readFile("components/wallet-deposit-module.tsx","utf8");expect(source).not.toContain("NOWPAYMENTS_API_KEY");expect(source).not.toContain("client.server")});
  it("19. mock payments cannot be confused with real payments",async()=>{const record=await createDeposit(user,{amount:20,network:"USDT_BEP20",idempotencyKey:randomUUID()});expect(record.mock).toBe(true);expect(record.providerPaymentId).toMatch(/^MOCK_NP_/);expect(record.payAddress).toContain("NOT_FOR_REAL_FUNDS");expect(NOWPAYMENTS_NETWORKS[record.network].payCurrency).toBe("usdtbsc")});
  it("20. survives a demo page refresh",()=>{const memory=new Map<string,string>();Object.defineProperty(globalThis,"localStorage",{configurable:true,value:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value)}});const record=baseRecord();writeDepositRecords([record]);expect(memory.has(DEPOSIT_STORE_KEY)).toBe(true);expect(readDepositRecords()).toEqual([record])});
});
