import { describe,expect,it } from "vitest";
import { readFileSync } from "node:fs";
import { diagnoseSupportRule,matchSupportRule,normalizeSupportText,renderSupportResponse,supportRuleSeeds,type MatchableRule,type SupportAccountContext } from "@/lib/support-rules";
import { supportSeedPatch } from "@/scripts/seed-support-rules";
const rules:MatchableRule[]=supportRuleSeeds.map((seed,index)=>({...seed,id:`rule-${index}`}));
const required:[string,string][]=[
  ["Wallet","SPOT_WALLET"],["My wallet","SPOT_WALLET"],["Mera wallet","SPOT_WALLET"],["Spot Wallet","SPOT_WALLET"],["Spot balance","SPOT_WALLET"],["My Spot balance","SPOT_WALLET"],["Mera Spot balance kitna hai?","SPOT_WALLET"],["Future Wallet","FUTURE_WALLET"],["My Future balance","FUTURE_WALLET"],["Deposit","DEPOSIT"],["Deposit kaise karu?","DEPOSIT"],["Withdraw","WITHDRAWAL"],["How do I withdraw?","WITHDRAWAL"],["Withdrawal kaise kare?","WITHDRAWAL"],["Referral Income","REFERRAL_INCOME"],["My referral income","REFERRAL_INCOME"],["Mera referral income","REFERRAL_INCOME"],["Level Income","LEVEL_INCOME"],["My level income","LEVEL_INCOME"],["Mera level income","LEVEL_INCOME"],["Rank","RANK"],["My rank","RANK"],["Mera rank kya hai?","RANK"],["Salary","SALARY"],["My salary","SALARY"],["Reward","REWARDS"],["My reward","REWARDS"],["Qualified Team","QUALIFIED_TEAM"],["Total Team","TOTAL_TEAM"],["My team","TOTAL_TEAM"],["Total Business","TOTAL_BUSINESS"],["My business","TOTAL_BUSINESS"],["KYC","KYC"],["My KYC status","KYC"],["AI Bot","AI_BOT_SUBSCRIPTION"],["My AI Bot","AI_BOT_SUBSCRIPTION"],["Bot expiry","BOT_EXPIRY"],["Copy Trading","COPY_TRADING"],["Current Trades","CURRENT_TRADES"],["Trade History","TRADE_HISTORY"],["Referral Link","REFERRAL_LINK"],["Sponsor UID","SPONSOR_UID"],["Login problem","LOGIN_PROBLEM"],["Password reset","PASSWORD_SECURITY"],["Deposit pending","DEPOSIT_PENDING"],["Withdrawal pending","WITHDRAWAL_PENDING"],["Income not received","INCOME_NOT_RECEIVED"],["Team member not showing","TEAM_MEMBER_NOT_SHOWING"],["Rank not updated","RANK_NOT_UPDATED"],["Create support ticket","SUPPORT_TICKET"]
];
const context:SupportAccountContext={uid:"BV100001",spotWallet:125.5,futureWallet:80.25,currentRank:3,referralIncome:15,levelIncome:8,salary:30,reward:60,kycStatus:"APPROVED",aiBotStatus:"ACTIVE",botExpiry:"2027-01-01T00:00:00.000Z",referralLink:"/register?ref=BV100001",qualifiedTeam:25,totalTeam:42,business:1250,sponsorUid:"BV999999",pendingDeposits:1,pendingWithdrawals:2};
describe("Support required query coverage",()=>{
  it.each(required)("matches %s",(message,intent)=>expect(matchSupportRule(message,rules)?.rule.intentKey).toBe(intent));
  it("normalizes contractions, punctuation, percentages, spelling and whitespace",()=>{expect(normalizeSupportText("  What's   my Spot balance?! ")).toBe("what is my spot balance");expect(normalizeSupportText("20% WITHDRAWL")).toBe("20 percent withdrawal")});
  it("uses exact examples before keyword scoring",()=>expect(diagnoseSupportRule("How do I deposit?",rules).match?.matchType).toBe("EXACT_EXAMPLE"));
  it("breaks equal-score ties by priority then intent key",()=>{const base=rules[0],items=[{...base,id:"b",intentKey:"B",priority:1,keywords:["special phrase"],examples:[]},{...base,id:"a",intentKey:"A",priority:2,keywords:["special phrase"],examples:[]}];expect(matchSupportRule("special phrase",items)?.rule.intentKey).toBe("A")});
  it("ignores inactive and safely falls back below confidence",()=>{expect(matchSupportRule("Wallet",rules.map(rule=>rule.intentKey==="SPOT_WALLET"?{...rule,isActive:false}:rule))?.rule.intentKey).not.toBe("SPOT_WALLET");expect(diagnoseSupportRule("hello unrelated words",rules).fallbackReason).toBe("LOW_CONFIDENCE")});
  it("detects an empty active knowledge base",()=>expect(diagnoseSupportRule("wallet",[]).fallbackReason).toBe("NO_ACTIVE_RULES"));
});
describe("Support personalization and integration contracts",()=>{
  it.each([["SPOT_WALLET","$125.50"],["FUTURE_WALLET","$80.25"],["REFERRAL_INCOME","$15.00"],["LEVEL_INCOME","$8.00"],["RANK","3 Star"],["SALARY","$30.00"],["REWARDS","$60.00"],["KYC","APPROVED"],["AI_BOT_SUBSCRIPTION","ACTIVE"],["TOTAL_TEAM","42"],["TOTAL_BUSINESS","$1250.00"]])("renders %s from authenticated context",(intent,expected)=>expect(renderSupportResponse(rules.find(rule=>rule.intentKey===intent)!.response,context)).toContain(expected));
  it("renders AI Bot expiry",()=>expect(renderSupportResponse(rules.find(rule=>rule.intentKey==="AI_BOT_SUBSCRIPTION")!.response,context)).toContain("Jan 1, 2027"));
  it("binds account lookup only to authenticated user.id",()=>{const source=readFileSync("lib/support-account-context.server.ts","utf8"),api=readFileSync("app/api/support/chat/route.ts","utf8");expect(api).toContain("buildSupportAccountContext(user.id)");expect(source).toContain("where:{id:userId}");expect(api).not.toMatch(/targetUser|targetUid/)});
  it("persists unmatched messages and returns explicit metadata",()=>{const api=readFileSync("app/api/support/chat/route.ts","utf8");expect(api).toContain("supportUnmatchedQuery.create");for(const field of ["matched:Boolean(matched)","intentKey:","ruleId","matchScore:score","fallbackReason:"])expect(api).toContain(field)});
  it("uses canonical topic-button questions",()=>{const ui=readFileSync("components/support-module.tsx","utf8");for(const question of ["My Spot balance","How do I deposit?","How do I withdraw?","My referral income","My level income","My KYC status","My rank and salary","My AI Bot status"])expect(ui).toContain(question)});
  it("loads active rules on every request and admin responses are no-store",()=>{const api=readFileSync("app/api/support/chat/route.ts","utf8"),admin=readFileSync("app/api/admin/support/rules/route.ts","utf8");expect(api).toContain("prisma.supportRule.findMany");expect(admin).toContain('"Cache-Control":"private, no-store"')});
  it("idempotent seed preserves valid admin edits and repairs missing arrays",()=>{const seed=supportRuleSeeds[0],preserved=supportSeedPatch({response:"Admin response",keywordsJson:["admin"],examplesJson:["admin example"],followUpsJson:[]},seed);expect(preserved).toEqual({});const repaired=supportSeedPatch({response:"Admin response",keywordsJson:[],examplesJson:[],followUpsJson:{}},seed);expect(repaired).toEqual({keywordsJson:seed.keywords,examplesJson:seed.examples,followUpsJson:seed.followUps})});
});
