import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { FALLBACK_RESPONSE, matchSupportRule, normalizeSupportText, renderSupportResponse, supportRuleSeeds, type MatchableRule, type SupportAccountContext } from "../lib/support-rules";
const rules=supportRuleSeeds.map((item,index)=>({...item,id:`rule-${index}`}));
const context:SupportAccountContext={uid:"BV123456",spotWallet:125.5,futureWallet:80,kycStatus:"APPROVED",currentRank:2,referralIncome:5,levelIncome:3,salary:10,reward:30,aiBotStatus:"ACTIVE",botExpiry:"2026-08-20T00:00:00.000Z",referralLink:"/register?ref=BV123456",qualifiedTeam:4,totalTeam:8,business:400,sponsorUid:"BV654321",pendingDeposits:1,pendingWithdrawals:2};
describe("rule-based Support chatbot",()=>{
  it("seeds all 38 supported intents",()=>expect(supportRuleSeeds).toHaveLength(38));
  it.each([["How do I deposit?","DEPOSIT"],["Mera Spot balance kitna hai?","SPOT_WALLET"],["Future wallet se spot me kaise transfer karu?","FUTURE_TO_SPOT"],["Mera withdrawal pending hai","WITHDRAWAL_PENDING"],["Referral income kyu nahi aayi?","INCOME_NOT_RECEIVED"],["Mera rank update nahi hua","RANK_NOT_UPDATED"]])("matches English or Hinglish: %s",(question,intent)=>expect(matchSupportRule(question,rules)?.rule.intentKey).toBe(intent));
  it("uses rule priority to resolve equal keyword scores",()=>{const overlapping:MatchableRule[]=[{...rules[0],id:"low",intentKey:"LOW",keywords:["wallet help"],examples:[],priority:1},{...rules[0],id:"high",intentKey:"HIGH",keywords:["wallet help"],examples:[],priority:100}];expect(matchSupportRule("wallet help",overlapping)?.rule.intentKey).toBe("HIGH")});
  it("returns no match below confidence and ignores inactive rules",()=>{expect(matchSupportRule("hello dost",rules)).toBeNull();expect(matchSupportRule("deposit",rules.map(item=>item.intentKey==="DEPOSIT"?{...item,isActive:false}:item))?.rule.intentKey).not.toBe("DEPOSIT");expect(FALLBACK_RESPONSE).toContain("could not understand")});
  it("renders only supplied authenticated account context",()=>{const spot=rules.find(item=>item.intentKey==="SPOT_WALLET")!;expect(renderSupportResponse(spot.response,context)).toContain("$125.50");const kyc=rules.find(item=>item.intentKey==="KYC")!;expect(renderSupportResponse(kyc.response,context)).toContain("APPROVED")});
  it("normalizes percentage punctuation consistently",()=>expect(normalizeSupportText("Why 20% deduction?!")).toBe("why 20 percent deduction"));
  it("persists chats, match metadata and unmatched queries without external requests",()=>{const source=readFileSync("app/api/support/chat/route.ts","utf8");expect(source).toContain("supportUnmatchedQuery.create");expect(source).toContain("matchedIntent:intentKey");expect(source).toContain("idempotencyKey:value.idempotencyKey");expect(source).toContain("userId:user.id");expect(source).not.toContain("fetch(")});
  it("keeps cross-user access denied and ticket escalation available",()=>{const history=readFileSync("app/api/support/chats/[id]/route.ts","utf8"),client=readFileSync("components/support-module.tsx","utf8");expect(history).toContain("userId:user.id");expect(client).toContain("Create Support Ticket")});
  it("provides authenticated admin rule updates",()=>{const admin=readFileSync("app/api/admin/support/rules/route.ts","utf8");expect(admin).toContain("requireAdminUser");expect(admin).toContain("assertMutationRequest");expect(admin).toContain("supportRule.update")});
});
