import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertMutationRequest } from "@/lib/support-security.server";
const fields=z.object({intentKey:z.string().trim().toUpperCase().regex(/^[A-Z0-9_]{3,80}$/),category:z.string().trim().min(2).max(80),title:z.string().trim().min(2).max(120),response:z.string().trim().min(5).max(4000),keywords:z.array(z.string().trim().min(1).max(100)).min(1).max(100),examples:z.array(z.string().trim().min(1).max(300)).max(50),followUps:z.array(z.string().trim().min(1).max(100)).max(20),priority:z.number().int().min(0).max(1000),isActive:z.boolean()}),createInput=fields.extend({sourceQueryId:z.string().cuid().optional()}),updateInput=fields.partial().extend({id:z.string().cuid()});
export async function GET(){try{await requireAdminUser();const rules=await prisma.supportRule.findMany({orderBy:[{priority:"desc"},{intentKey:"asc"}]});return NextResponse.json({rules:rules.map(rule=>({...rule,keywords:rule.keywordsJson,examples:rule.examplesJson,followUps:rule.followUpsJson}))},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Admin access required."},{status:401})}}
export async function POST(request:Request){try{const admin=await requireAdminUser();assertMutationRequest(request,admin.id);const value=createInput.parse(await request.json()),created=await prisma.$transaction(async tx=>{const rule=await tx.supportRule.create({data:{intentKey:value.intentKey,category:value.category,title:value.title,response:value.response,keywordsJson:value.keywords,examplesJson:value.examples,followUpsJson:value.followUps,priority:value.priority,isActive:value.isActive}});if(value.sourceQueryId)await tx.supportUnmatchedQuery.updateMany({where:{id:value.sourceQueryId,status:"OPEN"},data:{resolvedRuleId:rule.id,status:"RESOLVED"}});return rule});return NextResponse.json({rule:created,message:"Support rule created."},{status:201})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message??"Invalid rule.":"Unable to create rule."},{status:400})}}
export async function PATCH(request:Request){try{const admin=await requireAdminUser();assertMutationRequest(request,admin.id);const value=updateInput.parse(await request.json()),{id,...changes}=value,data={...changes,...(changes.keywords?{keywordsJson:changes.keywords}:{}),...(changes.examples?{examplesJson:changes.examples}:{}),...(changes.followUps?{followUpsJson:changes.followUps}:{})};delete (data as Record<string,unknown>).keywords;delete (data as Record<string,unknown>).examples;delete (data as Record<string,unknown>).followUps;const rule=await prisma.supportRule.update({where:{id},data});return NextResponse.json({rule,message:"Support rule updated."})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message??"Invalid rule update.":"Unable to update rule."},{status:400})}}

