import { NextResponse } from "next/server";
import { addTargetCompletedNotification, canUseAdditional, createDailySessions, getSessionById, getSessionPhase, getTradingDate, getUserSessionStatus, markExpiredSessionsMissed, migrateTradingStore, reconcileSessionNotifications, removeStaleMissedSessions, settleUserTrade } from "@/lib/ai-trading-engine";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { getFutureMetrics, migrateWalletStore, settleFutureTrade } from "@/lib/wallet-data";
import { formatUserTimestamp, localCalendarDate, resolveUserTimeZone } from "@/lib/timezone.server";
export const dynamic="force-dynamic";

export async function GET(){
  try{
    const user=await requireAuthenticatedUser(),serverNow=Date.now(),tradingDate=getTradingDate(serverNow),sessions=createDailySessions(tradingDate,serverNow).sort((a,b)=>a.liveFrom-b.liveFrom);
    const result=await prisma.$transaction(async transaction=>{
      const record=await transaction.user.findUnique({where:{id:user.id},select:{uid:true,timezone:true,country:true,state:{select:{id:true,trading:true,wallet:true}}}});
      if(!record)throw new Error("UNAUTHENTICATED");
      let wallet=migrateWalletStore(record.state?.wallet);const original=migrateTradingStore(record.state?.trading),cleaned=removeStaleMissedSessions(original,sessions,user.id);let reconciled=markExpiredSessionsMissed(reconcileSessionNotifications(cleaned,sessions,user.id,serverNow),sessions,user.id,record.uid,serverNow);
      for(const trade of reconciled.trades.filter(item=>item.status==="PLACED")){
        const session=getSessionById(trade.sessionId,serverNow);if(!session||serverNow<session.settlesAt)continue;
        const before=getFutureMetrics(wallet),key=`AI_SETTLE:${trade.id}`,details={userUid:record.uid,tradeId:trade.id,sessionId:session.id,pair:session.pair,direction:trade.direction,source:trade.placementSource,grossFutureBalance:trade.balanceSnapshot,tradeCapital:trade.tradeCapital,profitPercentage:trade.profitRate,profitAmount:trade.profitAmount};
        wallet=settleFutureTrade(wallet,{capital:trade.tradeCapital,profit:trade.profitAmount,key,additional:session.type==="ADDITIONAL",details,timestamp:session.settlesAt});reconciled=settleUserTrade(reconciled,trade.id,session,serverNow).store;
        if(!before.futureToSpotUnlocked&&before.totalCompletedTradingProfit+trade.profitAmount>=before.requiredProfitForUnlock)reconciled=addTargetCompletedNotification(reconciled,user.id,session.settlesAt);
      }
      if(record.state&&(JSON.stringify(reconciled)!==JSON.stringify(original)||JSON.stringify(wallet)!==JSON.stringify(migrateWalletStore(record.state.wallet))))await transaction.userState.update({where:{userId:user.id},data:{trading:reconciled as object,wallet:wallet as object}});
      return{record,store:reconciled,wallet};
    });
    const{record,store,wallet}=result,timezone=resolveUserTimeZone(record.timezone,record.country),today=localCalendarDate(serverNow,timezone),todayFutureWalletNetChange=wallet.transactions.filter(item=>item.wallet==="future"&&localCalendarDate(item.timestamp,timezone)===today).reduce((cents,item)=>cents+Math.round(item.amount*100),0)/100,eligible=sessions.filter(session=>session.type==="REGULAR"||canUseAdditional(store,session)),current=eligible.find(session=>{const phase=getSessionPhase(session,serverNow),trade=store.trades.find(item=>item.userId===user.id&&item.sessionId===session.id);return phase==="UPCOMING"||phase==="LIVE"||Boolean(trade?.status==="PLACED"&&phase==="PROCESSING")})??null,trade=current?store.trades.find(item=>item.userId===user.id&&item.sessionId===current.id):null,status=current?getUserSessionStatus(current,trade,serverNow):"COMPLETED",eligibleToTrade=Boolean(current&&status==="LIVE"&&!trade&&wallet.wallets.future.balance>0),blockReason=!current?"No eligible session.":status==="UPCOMING"?"Trade unlocks when the backend marks this session LIVE.":status==="JOINED"||status==="COMPLETED"?"This session was already joined.":status==="MISSED"?"This session has expired.":wallet.wallets.future.balance<=0?"Insufficient Future Wallet balance.":null;
    if(current?.sequence===3)console.info("[ai-session-status]",{sessionId:current.id,businessDate:tradingDate,scheduledAt:new Date(current.scheduledAt).toISOString(),liveStartsAt:new Date(current.liveFrom).toISOString(),liveEndsAt:new Date(current.placementClosesAt).toISOString(),serverNow:new Date(serverNow).toISOString(),computedStatus:status,userId:user.id,userDisplayTimezone:timezone,eligible:eligibleToTrade});
    const groupedTrades=store.trades.filter(item=>item.userId===user.id).map(item=>{const session=getSessionById(item.sessionId,serverNow),phase=session?getSessionPhase(session,serverNow):null,isCurrent=item.status==="PLACED";return{id:item.id,pair:session?.pair??item.sessionId,direction:item.direction==="CALL"?"BUY" as const:"SELL" as const,placementSource:item.placementSource,sourceLabel:item.placementSource==="AI_BOT"?"AI Bot":"Manual",status:item.status==="SETTLED"?"SETTLED" as const:item.status==="MISSED"?"MISSED" as const:phase==="PROCESSING"?"PENDING_SETTLEMENT" as const:"CAPITAL_LOCKED" as const,tradeCapital:item.tradeCapital,principalReturned:item.status==="SETTLED"?item.tradeCapital:null,profitReceived:item.status==="SETTLED"?item.profitAmount:null,placedAt:item.placedAt,settledAt:item.settledAt,missedAt:item.status==="MISSED"?item.placedAt:null,sortTime:item.settledAt??item.placedAt,isCurrent}}).sort((a,b)=>b.sortTime-a.sortTime),currentTrades=groupedTrades.filter(item=>item.isCurrent),tradeHistory=groupedTrades.filter(item=>!item.isCurrent);
    return NextResponse.json({serverNow,tradingDate,futureWalletBalance:wallet.wallets.future.balance,todayFutureWalletNetChange,currentTrades,tradeHistory,sessions:sessions.map(session=>({...session,displayStartTime:formatUserTimestamp(session.liveFrom,timezone).localTime,displayLiveWindow:`${formatUserTimestamp(session.liveFrom,timezone).localTime} – ${formatUserTimestamp(session.placementClosesAt,timezone).localTime}`,displaySettlementTime:formatUserTimestamp(session.settlesAt,timezone).localTime})),currentSession:current?{id:current.id,scheduledAt:current.scheduledAt,liveStartsAtUtc:new Date(current.liveFrom).toISOString(),liveEndsAtUtc:new Date(current.placementClosesAt).toISOString(),liveStartsAt:current.liveFrom,liveEndsAt:current.placementClosesAt,startTime:current.liveFrom,displayStartTime:formatUserTimestamp(current.liveFrom,timezone).localTime,displayLiveWindow:`${formatUserTimestamp(current.liveFrom,timezone).localTime} – ${formatUserTimestamp(current.placementClosesAt,timezone).localTime}`,countdownTarget:status==="LIVE"?current.placementClosesAt:current.liveFrom,pair:current.pair,signal:current.signalDirection==="CALL"?"BUY":"SELL",eligible:eligibleToTrade,status,blockReason,placementSource:trade?.placementSource??null}:null},{headers:{"Cache-Control":"private, no-store"}})
  }catch(error){console.error("[ai-session-status] request_failed",{message:error instanceof Error?error.message:"unknown"});return NextResponse.json({error:"Authentication required."},{status:401})}
}
