import { NextResponse } from "next/server";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { createDailySessions,getSessionPhase,getTradingDate } from "@/lib/ai-trading-engine";
import { getWalletReadSnapshot } from "@/lib/future-wallet.server";
import { loadVisibleTradeHistory } from "@/lib/trade-history-compat.server";
import { formatUserTimestamp,isValidIanaTimeZone,localCalendarDate,resolveUserTimeZone } from "@/lib/timezone.server";
export const dynamic="force-dynamic";

export async function GET(request:Request){try{
  const auth=await requireAuthenticatedUser(),serverNow=Date.now(),browserZone=request.headers.get("x-user-timezone"),record=await prisma.user.findUniqueOrThrow({where:{id:auth.id},select:{timezone:true,country:true,additionalTradeEligibility:true}}),timezone=isValidIanaTimeZone(browserZone)?browserZone:resolveUserTimeZone(record.timezone,record.country);if(timezone!==record.timezone)await prisma.user.update({where:{id:auth.id},data:{timezone}});
  const tradingDate=getTradingDate(serverNow,timezone),sessions=createDailySessions(tradingDate,serverNow,timezone).sort((a,b)=>a.liveFrom-b.liveFrom),[financial,trades,visibleTrades,activeBot,ledger]=await Promise.all([getWalletReadSnapshot(auth.id),prisma.aiFinancialTrade.findMany({where:{userId:auth.id},include:{sessionRun:true},orderBy:{officialStartedAt:"desc"},take:200}),loadVisibleTradeHistory(auth.id,200),prisma.aiBotSubscription.findFirst({where:{userId:auth.id,status:"ACTIVE",activatedAt:{lte:new Date(serverNow)},expiresAt:{gt:new Date(serverNow)}},select:{id:true}}),prisma.aiWalletLedger.findMany({where:{userId:auth.id,officialAt:{gte:new Date(serverNow-48*60*60_000)}},select:{amount:true,officialAt:true}})]),eligibility=record.additionalTradeEligibility,bonusSession=sessions.find(item=>item.type==="ADDITIONAL"),bonusSessionEligible=Boolean(bonusSession&&eligibility?.eligible&&eligibility.eligibilityStartedAt.getTime()<=bonusSession.liveFrom&&eligibility.eligibilityEndsAt&&eligibility.eligibilityEndsAt.getTime()>bonusSession.liveFrom),eligible=sessions.filter(session=>session.type==="REGULAR"||bonusSessionEligible),bySlot=new Map(trades.filter(t=>t.localTradingDate===tradingDate&&t.userTimeZone===timezone).map(t=>[t.localSessionSlot,t])),current=eligible.find(session=>{const trade=bySlot.get(String(session.sequence)),phase=getSessionPhase(session,serverNow);return phase==="UPCOMING"||phase==="LIVE"||Boolean(trade&&trade.status!=="SETTLED")})??null,currentTrade=current?bySlot.get(String(current.sequence)):null,phase=current?getSessionPhase(current,serverNow):null,status=currentTrade?currentTrade.status==="SETTLED"?"COMPLETED":"JOINED":phase==="UPCOMING"?"UPCOMING":phase==="LIVE"?"LIVE":"MISSED",eligibleToTrade=Boolean(current&&status==="LIVE"&&!currentTrade&&financial.authoritativeReady&&financial.availableFuture.isPositive()),blockReason=!current?"No eligible session.":status==="UPCOMING"?"Trade unlocks when the backend marks this session LIVE.":status==="JOINED"||status==="COMPLETED"?"This session was already joined.":status==="MISSED"?"This session has expired.":!financial.authoritativeReady?"Future Wallet migration is pending.":!financial.availableFuture.isPositive()?"Insufficient Future Wallet balance.":null;
  const groupedTrades=visibleTrades.map(trade=>({...trade,sourceLabel:trade.placementSource==="AI_BOT"?"AI Bot":"Manual",isCurrent:trade.status==="CAPITAL_LOCKED"})),currentTrades=groupedTrades.filter(item=>item.isCurrent),tradeHistory=groupedTrades.filter(item=>!item.isCurrent),today=localCalendarDate(serverNow,timezone),todayFutureWalletNetChange=ledger.filter(item=>localCalendarDate(item.officialAt.getTime(),timezone)===today).reduce((sum,item)=>sum+Number(item.amount.toString()),0),localized=sessions.map(session=>({...session,displayStartTime:formatUserTimestamp(session.liveFrom,timezone).localTime,displayLiveWindow:`${formatUserTimestamp(session.liveFrom,timezone).localTime} – ${formatUserTimestamp(session.placementClosesAt,timezone).localTime}`,displaySettlementTime:formatUserTimestamp(session.settlesAt,timezone).localTime}));
  return NextResponse.json({serverNow,tradingDate,timeZone:timezone,bonus:{active:Boolean(eligibility?.eligible&&eligibility.eligibilityEndsAt&&eligibility.eligibilityEndsAt.getTime()>serverNow),availableToday:bonusSessionEligible,expiresAt:eligibility?.eligibilityEndsAt?.getTime()??null},futureWalletBalance:Number(financial.availableFuture.toString()),futureWalletSource:financial.source,todayFutureWalletNetChange,currentTrades,tradeHistory,sessions:localized,currentSession:current?{id:current.id,sequence:current.sequence,type:current.type,scheduledAt:current.scheduledAt,liveStartsAt:current.liveFrom,liveEndsAt:current.placementClosesAt,startTime:current.liveFrom,displayStartTime:formatUserTimestamp(current.liveFrom,timezone).localTime,displayLiveWindow:`${formatUserTimestamp(current.liveFrom,timezone).localTime} – ${formatUserTimestamp(current.placementClosesAt,timezone).localTime}`,countdownTarget:status==="LIVE"?current.placementClosesAt:current.liveFrom,pair:current.pair,signal:current.signalDirection==="CALL"?"BUY":"SELL",eligible:eligibleToTrade,status,blockReason,placementSource:currentTrade?.placementSource??null}:null,aiBotActive:Boolean(activeBot)},{headers:{"Cache-Control":"private, no-store"}})
}catch(error){console.error("[ai-session-status] request_failed",{message:error instanceof Error?error.message:"unknown"});return NextResponse.json({error:"Authentication required."},{status:401})}}
