import { NextResponse } from "next/server";
import { requireDemoAdmin } from "@/lib/admin/admin-auth.server";
import { createEmptyTradingStore, migrateTradingStore } from "@/lib/ai-trading-engine";
import { cloneWalletSeed, getFutureMetrics, migrateWalletStore } from "@/lib/wallet-data";
import { prisma } from "@/lib/prisma";

export async function GET(){
  try{
    await requireDemoAdmin();
    const records=await prisma.user.findMany({include:{state:true},orderBy:{createdAt:"desc"}}),users=records.map(record=>{const wallet=migrateWalletStore(record.state?.wallet),metrics=getFutureMetrics(wallet);return{id:record.id,uid:record.uid,name:record.name,email:record.email,sponsorUid:record.sponsorUid??"",createdAt:record.createdAt.getTime(),spotBalance:wallet.wallets.spot.balance,futureBalance:wallet.wallets.future.balance,lockedCapital:wallet.lockedFutureTradeCapital,qualifyingPrincipal:wallet.totalFuturePrincipal,completedAiProfit:wallet.totalCompletedTradingProfit,progress:metrics.unlockProgressPercentage,currentStar:wallet.rankAccount.currentStar,highestStar:Math.max(wallet.rankAccount.currentStar,...wallet.rankAccount.rewardedRanks,0),qualifiedTeamSize:wallet.rankAccount.qualifiedTeamCount,active:wallet.totalFuturePrincipal>0,qualified:wallet.totalFuturePrincipal>=50}}),wallets=records.map(record=>migrateWalletStore(record.state?.wallet)),tradings=records.map(record=>record.state?migrateTradingStore(record.state.trading):createEmptyTradingStore()),transactions=wallets.flatMap(item=>item.transactions),withdrawals=records.flatMap(record=>migrateWalletStore(record.state?.wallet).transactions.filter(item=>item.type==="SPOT_WITHDRAWAL"&&item.withdrawalDetails).map(item=>({id:item.id,userId:record.id,userUid:record.uid,requestedAmount:item.withdrawalDetails!.requestedAmount,fee:item.withdrawalDetails!.fee,netAmount:item.withdrawalDetails!.netAmount,network:item.withdrawalDetails!.network,status:item.status,createdAt:item.timestamp}))).sort((a,b)=>b.createdAt-a.createdAt),trades=tradings.flatMap(item=>item.trades),metrics={totalRegisteredUsers:users.length,activeUsers:users.filter(item=>item.active).length,qualifiedUsers:users.filter(item=>item.qualified).length,totalSpotBalance:users.reduce((sum,item)=>sum+item.spotBalance,0),totalFutureBalance:users.reduce((sum,item)=>sum+item.futureBalance,0),totalLockedCapital:users.reduce((sum,item)=>sum+item.lockedCapital,0),totalAiProfit:users.reduce((sum,item)=>sum+item.completedAiProfit,0),directIncome:transactions.filter(item=>item.type==="SPOT_REFERRAL_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),levelIncome:transactions.filter(item=>item.type==="SPOT_LEVEL_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),rankRewards:transactions.filter(item=>item.type==="SPOT_REWARD_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),salaryPaid:transactions.filter(item=>item.type==="SPOT_SALARY_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),pendingWithdrawals:transactions.filter(item=>item.type==="SPOT_WITHDRAWAL"&&item.status==="PENDING").length,completedWithdrawals:transactions.filter(item=>item.type==="SPOT_WITHDRAWAL"&&item.status==="COMPLETED").length};
    return NextResponse.json({users,wallet:cloneWalletSeed(),withdrawals,trades:trades.length,settledTrades:trades.filter(item=>item.status==="SETTLED").length,missedTrades:trades.filter(item=>item.status==="MISSED").length,metrics},{headers:{"Cache-Control":"no-store"}})
  }catch{return NextResponse.json({error:"Admin access required."},{status:401})}
}
