import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { migrateWalletStore,money } from "@/lib/wallet-data";
import { resolveUserTimeZone,startOfLocalMonthUtc } from "@/lib/timezone.server";
import { retainedFuturePrincipal } from "@/lib/rank-recalculation.server";
const querySchema=z.object({parentUid:z.string().trim().toUpperCase().regex(/^BV\d{6}$/).optional(),search:z.string().trim().max(100).default(""),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(50).default(20)});
type ParentRow={id:string;uid:string;name:string;selfUid:string;selfName:string;sponsorUid:string|null;sponsorName:string|null;timezone:string;country:string|null};
type MemberRow={id:string;uid:string;name:string;email:string;createdAt:Date;wallet:Prisma.JsonValue|null;availableFuture:Prisma.Decimal;retainedPrincipal:Prisma.Decimal};
type AggregateRow={rootId:string;totalTeam:bigint;qualifiedTeam:bigint;directCount:bigint;newThisMonth:bigint;totalBusiness:Prisma.Decimal;personalBusiness:Prisma.Decimal};
export async function GET(request:Request){try{
  const current=await requireAuthenticatedUser(),input=querySchema.parse(Object.fromEntries(new URL(request.url).searchParams)),parentUid=input.parentUid??current.uid,parents=await prisma.$queryRaw<ParentRow[]>`WITH RECURSIVE allowed AS (SELECT u."id",u."uid",u."name",ARRAY[u."id"] path FROM "User" u WHERE u."id"=${current.id} UNION ALL SELECT child."id",child."uid",child."name",parent.path||child."id" FROM "User" child JOIN allowed parent ON child."sponsorId"=parent."id" WHERE NOT child."id"=ANY(parent.path)) SELECT allowed."id",allowed."uid",allowed."name",root."uid" "selfUid",root."name" "selfName",sponsor."uid" "sponsorUid",sponsor."name" "sponsorName",root."timezone",root."country" FROM allowed CROSS JOIN "User" root LEFT JOIN "User" sponsor ON sponsor."id"=root."sponsorId" WHERE root."id"=${current.id} AND allowed."uid"=${parentUid} LIMIT 1`,record=parents[0];if(!record)return NextResponse.json({error:"Genealogy branch is not available."},{status:403});
  const parent={id:record.id,uid:record.uid,name:record.name},identity={self:{uid:record.selfUid,name:record.selfName},sponsor:record.sponsorUid?{uid:record.sponsorUid,name:record.sponsorName??"—"}:null},monthStart=startOfLocalMonthUtc(Date.now(),resolveUserTimeZone(record.timezone,record.country)),pattern=`%${input.search.replace(/[\\%_]/g,value=>`\\${value}`)}%`,offset=(input.page-1)*input.pageSize;
  const[countRows,members]=await Promise.all([prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint count FROM "User" u WHERE u."sponsorId"=${parent.id} AND (${input.search}='' OR u."name" ILIKE ${pattern} ESCAPE '\\' OR u."email" ILIKE ${pattern} ESCAPE '\\' OR u."uid" ILIKE ${pattern} ESCAPE '\\')`,prisma.$queryRaw<MemberRow[]>`SELECT u."id",u."uid",u."name",u."email",u."createdAt",s."wallet",COALESCE(w."availableFuture",0) "availableFuture",COALESCE(w."retainedPrincipal",0) "retainedPrincipal" FROM "User" u LEFT JOIN "UserState" s ON s."userId"=u."id" LEFT JOIN "AiFinancialWallet" w ON w."userId"=u."id" WHERE u."sponsorId"=${parent.id} AND (${input.search}='' OR u."name" ILIKE ${pattern} ESCAPE '\\' OR u."email" ILIKE ${pattern} ESCAPE '\\' OR u."uid" ILIKE ${pattern} ESCAPE '\\') ORDER BY u."createdAt" DESC,u."id" ASC LIMIT ${input.pageSize} OFFSET ${offset}`]),rootIds=[current.id,...members.map(member=>member.id)],aggregates=rootIds.length?await prisma.$queryRaw<AggregateRow[]>`WITH RECURSIVE tree AS (SELECT u."id" "rootId",u."id",u."sponsorId",u."createdAt",ARRAY[u."id"] path FROM "User" u WHERE u."id" IN (${Prisma.join(rootIds)}) UNION ALL SELECT tree."rootId",child."id",child."sponsorId",child."createdAt",tree.path||child."id" FROM "User" child JOIN tree ON child."sponsorId"=tree."id" WHERE NOT child."id"=ANY(tree.path)) SELECT tree."rootId",(COUNT(*)-1)::bigint "totalTeam",COUNT(*) FILTER(WHERE tree."id"<>tree."rootId" AND COALESCE(w."retainedPrincipal",0)>=50)::bigint "qualifiedTeam",COUNT(*) FILTER(WHERE tree."sponsorId"=tree."rootId")::bigint "directCount",COUNT(*) FILTER(WHERE tree."id"<>tree."rootId" AND tree."createdAt">=${monthStart})::bigint "newThisMonth",COALESCE(SUM(w."retainedPrincipal") FILTER(WHERE tree."id"<>tree."rootId"),0) "totalBusiness",COALESCE(MAX(w."retainedPrincipal") FILTER(WHERE tree."id"=tree."rootId"),0) "personalBusiness" FROM tree LEFT JOIN "AiFinancialWallet" w ON w."userId"=tree."id" GROUP BY tree."rootId"`:[],byRoot=new Map(aggregates.map(row=>[row.rootId,row]));
  const serialize=(member:MemberRow)=>{const wallet=migrateWalletStore(member.wallet),aggregate=byRoot.get(member.id),principal=member.retainedPrincipal===undefined?retainedFuturePrincipal(member.wallet).retainedFuturePrincipal:Number(member.retainedPrincipal),available=member.availableFuture===undefined?wallet.wallets.future.balance:Number(member.availableFuture);return{id:member.id,uid:member.uid,name:member.name,email:member.email,rank:wallet.rankAccount.currentStar,futureWalletBalance:available,totalTeam:Number(aggregate?.totalTeam??0),totalBusiness:money(Number(aggregate?.totalBusiness??0)),qualified:principal>=50,directCount:Number(aggregate?.directCount??0),createdAt:member.createdAt.toISOString()}},root=byRoot.get(current.id),totalNetwork=Number(root?.totalTeam??0),qualifiedTeam=Number(root?.qualifiedTeam??0),total=countRows[0]?Number(countRows[0].count):0;
  return NextResponse.json({identity,parent,members:members.map(serialize),pagination:{page:input.page,pageSize:input.pageSize,total,totalPages:Math.max(1,Math.ceil(total/input.pageSize))},summary:{totalNetwork,directTeam:Number(root?.directCount??0),qualifiedTeam,unqualifiedTeam:totalNetwork-qualifiedTeam,newThisMonth:Number(root?.newThisMonth??0),qualifyingBusiness:money(Number(root?.personalBusiness??0))}},{headers:{"Cache-Control":"private, no-store"}})
}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Invalid team query."},{status:400});return NextResponse.json({error:error instanceof Error&&error.message==="UNAUTHENTICATED"?"Authentication required.":"Unable to load team."},{status:error instanceof Error&&error.message==="UNAUTHENTICATED"?401:500})}}
