import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { createEmptyTradingStore, migrateTradingStore } from "@/lib/ai-trading-engine";
import { cloneWalletSeed, migrateWalletStore } from "@/lib/wallet-data";
import { prisma } from "@/lib/prisma";
import { recalculateAuthoritativeNetwork } from "@/lib/rank-recalculation.server";
import { formatUserTimestamp, localCalendarDate, resolveUserTimeZone } from "@/lib/timezone.server";

const input=z.object({wallet:z.unknown().optional(),trading:z.unknown().optional()}).refine(value=>value.wallet!==undefined||value.trading!==undefined);
export async function GET(){try{const user=await requireAuthenticatedUser(),[state,record]=await Promise.all([prisma.userState.findUnique({where:{userId:user.id}}),prisma.user.findUnique({where:{id:user.id},select:{timezone:true,country:true}})]),timeZone=resolveUserTimeZone(record?.timezone,record?.country),wallet=migrateWalletStore(state?.wallet??cloneWalletSeed()),trading=migrateTradingStore(state?.trading??createEmptyTradingStore()),displayWallet={...wallet,transactions:wallet.transactions.map(item=>({...item,...formatUserTimestamp(item.timestamp,timeZone),localDateKey:localCalendarDate(item.timestamp,timeZone)})),referralCommissions:wallet.referralCommissions.map(item=>({...item,...formatUserTimestamp(item.timestamp,timeZone)}))},displayTrading={...trading,trades:trading.trades.map(item=>({...item,displayPlacedAt:formatUserTimestamp(item.placedAt,timeZone).localDateTime,displaySettledAt:item.settledAt?formatUserTimestamp(item.settledAt,timeZone).localDateTime:null}))};return NextResponse.json({wallet:displayWallet,trading:displayTrading},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"Authentication required."},{status:401})}}
export async function PUT(request:Request){try{const user=await requireAuthenticatedUser(),value=input.parse(await request.json()),state=await prisma.$transaction(async tx=>{const create={userId:user.id,wallet:(value.wallet??cloneWalletSeed()) as object,trading:(value.trading??createEmptyTradingStore()) as object},update:{wallet?:object;trading?:object}={};if(value.wallet!==undefined)update.wallet=value.wallet as object;if(value.trading!==undefined)update.trading=value.trading as object;await tx.userState.upsert({where:{userId:user.id},create,update});if(value.wallet!==undefined)await recalculateAuthoritativeNetwork(tx);return tx.userState.findUniqueOrThrow({where:{userId:user.id}})});return NextResponse.json({wallet:state.wallet,trading:state.trading})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Invalid account state.":"Unable to save account state."},{status:400})}}
