import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { createEmptyTradingStore,migrateTradingStore } from "@/lib/ai-trading-engine";
import { cloneWalletSeed,migrateWalletStore } from "@/lib/wallet-data";
import { prisma } from "@/lib/prisma";
import { recalculateAuthoritativeNetwork } from "@/lib/rank-recalculation.server";
import { formatUserTimestamp,localCalendarDate,resolveUserTimeZone } from "@/lib/timezone.server";
import { getWalletReadSnapshot,lockFutureWallet,reconcileLegacyMirror } from "@/lib/future-wallet.server";
import { loadVisibleTradeHistory } from "@/lib/trade-history-compat.server";
const input=z.object({wallet:z.unknown().optional(),trading:z.unknown().optional()}).refine(value=>value.wallet!==undefined||value.trading!==undefined);

export async function GET(){try{const user=await requireAuthenticatedUser(),[state,record,financial,trades]=await Promise.all([prisma.userState.findUnique({where:{userId:user.id}}),prisma.user.findUnique({where:{id:user.id},select:{timezone:true,country:true}}),getWalletReadSnapshot(user.id),loadVisibleTradeHistory(user.id,500)]),timeZone=resolveUserTimeZone(record?.timezone,record?.country),base=migrateWalletStore(state?.wallet??cloneWalletSeed()),wallet={...base,wallets:{...base.wallets,future:{...base.wallets.future,balance:Number(financial.availableFuture.toString())}},lockedFutureTradeCapital:Number(financial.lockedFuture.toString()),totalCompletedTradingProfit:Number(financial.completedProfit.toString()),totalFuturePrincipal:Number(financial.retainedPrincipal.toString())},legacyTrading=migrateTradingStore(state?.trading??createEmptyTradingStore()),displayWallet={...wallet,financialSource:financial.source,transactions:wallet.transactions.map(item=>({...item,...formatUserTimestamp(item.timestamp,timeZone),localDateKey:localCalendarDate(item.timestamp,timeZone)})),referralCommissions:wallet.referralCommissions.map(item=>({...item,...formatUserTimestamp(item.timestamp,timeZone)}))},displayTrading={...legacyTrading,trades:trades.map(trade=>({id:trade.id,userId:user.id,userUid:user.uid,sessionId:trade.sessionId,direction:trade.direction==="BUY"?"CALL" as const:"PUT" as const,balanceSnapshot:trade.balanceSnapshot,dailyProfitBase:trade.balanceSnapshot,tradeCapital:trade.principal,profitRate:trade.profitRate,profitAmount:trade.profitReceived??0,status:trade.status==="SETTLED"?"SETTLED" as const:trade.status==="MISSED"?"MISSED" as const:"PLACED" as const,placedAt:trade.placedAt,settledAt:trade.settledAt,idempotencyKey:trade.executionKey,placementSource:trade.placementSource,source:trade.source,displayPlacedAt:formatUserTimestamp(trade.placedAt,timeZone).localDateTime,displaySettledAt:trade.settledAt?formatUserTimestamp(trade.settledAt,timeZone).localDateTime:null}))};return NextResponse.json({wallet:displayWallet,trading:displayTrading},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"Authentication required."},{status:401})}}
export async function PUT(request:Request){try{const user=await requireAuthenticatedUser(),value=input.parse(await request.json()),state=await prisma.$transaction(async tx=>{await lockFutureWallet(tx,user.id);const create={userId:user.id,wallet:(value.wallet??cloneWalletSeed()) as object,trading:(value.trading??createEmptyTradingStore()) as object},update:{wallet?:object;trading?:object}={};if(value.wallet!==undefined)update.wallet=value.wallet as object;if(value.trading!==undefined)update.trading=value.trading as object;await tx.userState.upsert({where:{userId:user.id},create,update});await reconcileLegacyMirror(tx,user.id);if(value.wallet!==undefined)await recalculateAuthoritativeNetwork(tx);return tx.userState.findUniqueOrThrow({where:{userId:user.id}})},{isolationLevel:"Serializable"});return NextResponse.json({wallet:state.wallet,trading:state.trading})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Invalid account state.":"Unable to save account state."},{status:400})}}
