import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertSameOrigin, SUPPORT_ATTACHMENT_LIMIT, SUPPORT_ATTACHMENT_TYPES } from "@/lib/support-security.server";
import type { SupportReply, SupportTicket } from "@prisma/client";
const input=z.object({subject:z.string().trim().min(3).max(120),category:z.enum(["ACCOUNT","DEPOSIT","WITHDRAWAL","TRADING","AI_BOT","KYC","TECHNICAL","OTHER"]),message:z.string().trim().min(10).max(4000),priority:z.enum(["LOW","NORMAL","HIGH","URGENT"]),sessionId:z.string().cuid().optional()});
type TicketRecord=SupportTicket&{replies:SupportReply[]};
const view=(ticket:TicketRecord)=>({id:ticket.id,subject:ticket.subject,category:ticket.category,message:ticket.message,status:ticket.status,priority:ticket.priority,sessionId:ticket.sessionId,attachmentName:ticket.attachmentName,attachmentMimeType:ticket.attachmentMimeType,attachmentSize:ticket.attachmentSize,hasAttachment:Boolean(ticket.attachmentName),createdAt:ticket.createdAt.getTime(),updatedAt:ticket.updatedAt.getTime(),replies:ticket.replies.length?ticket.replies.map(reply=>({...reply,createdAt:reply.createdAt.getTime()})):ticket.adminReply?[{id:`legacy-${ticket.id}`,ticketId:ticket.id,adminId:"legacy",message:ticket.adminReply,createdAt:ticket.updatedAt.getTime()}]:[]});
export async function GET(){try{const user=await requireAuthenticatedUser(),[tickets,configuration]=await Promise.all([prisma.supportTicket.findMany({where:{userId:user.id},include:{replies:{orderBy:{createdAt:"asc"}}},orderBy:{createdAt:"desc"},take:100}),prisma.supportConfiguration.findUnique({where:{id:"default"}})]);return NextResponse.json({tickets:tickets.map(view),contact:configuration?{email:configuration.supportEmail,whatsappUrl:configuration.whatsappUrl,telegramUrl:configuration.telegramUrl,helpCenterUrl:configuration.helpCenterUrl}:null},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Authentication required."},{status:401})}}
export async function POST(request:Request){try{assertSameOrigin(request);const user=await requireAuthenticatedUser(),form=await request.formData(),value=input.parse({subject:form.get("subject"),category:form.get("category"),message:form.get("message"),priority:form.get("priority")||"NORMAL",sessionId:form.get("sessionId")||undefined}),session=value.sessionId?await prisma.chatSession.findFirst({where:{id:value.sessionId,userId:user.id,deletedAt:null}}):null;if(value.sessionId&&!session)return NextResponse.json({error:"Chat not found."},{status:404});const file=form.get("attachment");let attachment={};if(file instanceof File&&file.size){if(file.size>SUPPORT_ATTACHMENT_LIMIT)return NextResponse.json({error:"Attachment must be 5 MB or smaller."},{status:400});if(!SUPPORT_ATTACHMENT_TYPES.has(file.type))return NextResponse.json({error:"Use a JPG, PNG, WebP, or PDF attachment."},{status:400});attachment={attachmentName:file.name.slice(0,180),attachmentMimeType:file.type,attachmentSize:file.size,attachmentData:Buffer.from(await file.arrayBuffer())}}const ticket=await prisma.supportTicket.create({data:{userId:user.id,...value,...attachment},include:{replies:true}});return NextResponse.json({ticket:view(ticket),message:"Support ticket submitted."},{status:201})}catch(error){const message=error instanceof z.ZodError?error.issues[0]?.message??"Invalid ticket.":error instanceof Error&&error.message==="INVALID_ORIGIN"?"Invalid request origin.":"Unable to submit support ticket.";return NextResponse.json({error:message},{status:400})}}
