import { NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertMutationRequest, SUPPORT_ATTACHMENT_LIMIT, SUPPORT_ATTACHMENT_TYPES } from "@/lib/support-security.server";
import { validateAttachmentBytes } from "@/lib/support-attachment";
import { decodeCursor, encodeCursor, pageSize } from "@/lib/support-pagination";
const input=z.object({subject:z.string().trim().min(3).max(120),category:z.enum(["ACCOUNT","DEPOSIT","WITHDRAWAL","TRADING","AI_BOT","KYC","TECHNICAL","OTHER"]),message:z.string().trim().min(10).max(4000),priority:z.enum(["LOW","NORMAL","HIGH","URGENT"]),sessionId:z.string().cuid().optional()});
const ticketSelect={id:true,userId:true,subject:true,category:true,message:true,status:true,adminReply:true,priority:true,sessionId:true,attachmentName:true,attachmentMimeType:true,attachmentSize:true,createdAt:true,updatedAt:true,replies:{orderBy:{createdAt:"asc" as const},select:{id:true,ticketId:true,adminId:true,message:true,createdAt:true}}} satisfies Prisma.SupportTicketSelect;
type TicketView=Prisma.SupportTicketGetPayload<{select:typeof ticketSelect}>;
const view=(ticket:TicketView)=>({id:ticket.id,subject:ticket.subject,category:ticket.category,message:ticket.message,status:ticket.status,priority:ticket.priority,sessionId:ticket.sessionId,attachmentName:ticket.attachmentName,attachmentMimeType:ticket.attachmentMimeType,attachmentSize:ticket.attachmentSize,hasAttachment:Boolean(ticket.attachmentName),createdAt:ticket.createdAt.getTime(),updatedAt:ticket.updatedAt.getTime(),replies:ticket.replies.length?ticket.replies.map(reply=>({...reply,createdAt:reply.createdAt.getTime()})):ticket.adminReply?[{id:`legacy-${ticket.id}`,ticketId:ticket.id,adminId:"legacy",message:ticket.adminReply,createdAt:ticket.updatedAt.getTime()}]:[]});
export async function GET(request:Request){try{const user=await requireAuthenticatedUser(),url=new URL(request.url),take=pageSize(url.searchParams.get("limit")),cursor=decodeCursor(url.searchParams.get("cursor")),[rows,configuration]=await Promise.all([prisma.supportTicket.findMany({where:{userId:user.id,...(cursor?{OR:[{createdAt:{lt:cursor.at}},{createdAt:cursor.at,id:{lt:cursor.id}}]}:{})},select:ticketSelect,orderBy:[{createdAt:"desc"},{id:"desc"}],take:take+1}),prisma.supportConfiguration.findUnique({where:{id:"default"}})]),hasMore=rows.length>take,tickets=hasMore?rows.slice(0,take):rows,last=tickets.at(-1);return NextResponse.json({tickets:tickets.map(view),nextCursor:hasMore&&last?encodeCursor(last.createdAt,last.id):null,contact:configuration?{email:configuration.supportEmail,whatsappUrl:configuration.whatsappUrl,telegramUrl:configuration.telegramUrl,helpCenterUrl:configuration.helpCenterUrl}:null},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Authentication required."},{status:401})}}
export async function POST(request:Request){try{const user=await requireAuthenticatedUser();assertMutationRequest(request,user.id);const form=await request.formData(),value=input.parse({subject:form.get("subject"),category:form.get("category"),message:form.get("message"),priority:form.get("priority")||"NORMAL",sessionId:form.get("sessionId")||undefined}),session=value.sessionId?await prisma.chatSession.findFirst({where:{id:value.sessionId,userId:user.id,deletedAt:null}}):null;if(value.sessionId&&!session)return NextResponse.json({error:"Chat not found."},{status:404});const file=form.get("attachment");let attachment={};if(file instanceof File&&file.size){if(file.size>SUPPORT_ATTACHMENT_LIMIT)return NextResponse.json({error:`Attachment must be ${Math.floor(SUPPORT_ATTACHMENT_LIMIT/1024/1024)} MB or smaller.`},{status:400});if(!SUPPORT_ATTACHMENT_TYPES.has(file.type))return NextResponse.json({error:"Use a JPG, PNG, WebP, or PDF attachment."},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());validateAttachmentBytes(bytes,file.type);attachment={attachmentName:file.name.slice(0,180),attachmentMimeType:file.type,attachmentSize:file.size,attachmentData:Buffer.from(bytes)}}const created=await prisma.supportTicket.create({data:{userId:user.id,...value,...attachment},select:{id:true}}),ticket=await prisma.supportTicket.findUniqueOrThrow({where:{id:created.id},select:ticketSelect});return NextResponse.json({ticket:view(ticket),message:"Support ticket submitted."},{status:201})}catch(error){const code=error instanceof Error?error.message:"";const message=error instanceof z.ZodError?error.issues[0]?.message??"Invalid ticket.":code.includes("ATTACHMENT")||code==="UNSAFE_ATTACHMENT"?"The attachment content does not match a safe supported file.":code.startsWith("INVALID_")||code==="MISSING_REQUEST_PROVENANCE"?"Request security validation failed.":"Unable to submit support ticket.";return NextResponse.json({error:message},{status:400})}}
