"use client";
import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { signOut } from "next-auth/react";
import { Bell, ChartNoAxesCombined, ChevronRight, CircleUserRound, FileCheck2, Headphones, History, House, KeyRound, LogOut, Menu, Settings, ShieldCheck, UsersRound, X, Zap } from "lucide-react";
import { Logo } from "./brand";
import { SessionGuard } from "./session-guard";
import { useCurrentUser } from "@/hooks/use-current-user";
import { formatLocalDateTime, setDateTimeFallbackCountry } from "@/lib/date-time";
import { NavigationRecovery } from "./navigation-recovery";
import { WalletPortal } from "./wallet-ui";

const nav=[{href:"/home",label:"Home",icon:House},{href:"/markets",label:"Markets",icon:ChartNoAxesCombined},{href:"/trade",label:"Trade",icon:Zap,primary:true},{href:"/team",label:"Team",icon:UsersRound},{href:"/profile",label:"Profile",icon:CircleUserRound}];
const menu=[{href:"/profile",label:"Profile",icon:CircleUserRound},{href:"/kyc",label:"KYC Verification",icon:FileCheck2},{href:"/transactions",label:"Transaction History",icon:History},{href:"/settings",label:"Settings",icon:Settings},{href:"/support",label:"Support",icon:Headphones}];
type HeaderNotification={id:string;title:string;message:string;type:string;createdAt:number;localDateTime:string};

export function AppShell({children}:{children:ReactNode}) {
  const pathname=usePathname(),[menuOpen,setMenuOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[passwordOpen,setPasswordOpen]=useState(false),[logoutConfirm,setLogoutConfirm]=useState(false),[kycStatus,setKycStatus]=useState("NOT_SUBMITTED"),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[passwordMessage,setPasswordMessage]=useState(""),[passwordBusy,setPasswordBusy]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[notifications,setNotifications]=useState<HeaderNotification[]>([]),[notificationsLoading,setNotificationsLoading]=useState(false),[currentRank,setCurrentRank]=useState(0),dashboard=pathname==="/home"||pathname==="/dashboard";
  const user=useCurrentUser();
  useEffect(()=>setDateTimeFallbackCountry(user?.country),[user?.country]);
  const initials=(user?.name??user?.email??"").split(/\s+|@/).filter(Boolean).slice(0,2).map(value=>value[0]?.toUpperCase()).join("")||"—";
  useEffect(()=>{const open=()=>{setNotificationsOpen(false);setMenuOpen(true)};window.addEventListener("bitvora:open-menu",open);return()=>window.removeEventListener("bitvora:open-menu",open)},[]);
  useEffect(()=>{setMenuOpen(false);setNotificationsOpen(false)},[pathname]);
  useEffect(()=>{if(!dashboard)return;let active=true;const loadRank=()=>void fetch("/api/account/state",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(data=>{const rank=Number(data?.wallet?.rankAccount?.currentStar);if(active)setCurrentRank(Number.isFinite(rank)?Math.max(0,Math.min(7,Math.trunc(rank))):0)}).catch(()=>{if(active)setCurrentRank(0)});loadRank();window.addEventListener("bitvora-wallet-updated",loadRank);return()=>{active=false;window.removeEventListener("bitvora-wallet-updated",loadRank)}},[dashboard]);
  const openNotifications=async()=>{setMenuOpen(false);setNotificationsOpen(true);setNotificationsLoading(true);try{const response=await fetch("/api/notifications",{cache:"no-store"}),data=await response.json();setNotifications(response.ok?(data.notifications??[]).map((item:HeaderNotification)=>({...item,localDateTime:formatLocalDateTime(item.createdAt)})):[])}finally{setNotificationsLoading(false)}};
  const openMenu=()=>{setNotificationsOpen(false);setMenuOpen(true)};
  const openProfile=()=>{setMenuOpen(false);setNotificationsOpen(false);setPasswordOpen(false);setPasswordMessage("");setProfileOpen(true);void fetch("/api/kyc/me",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(data=>setKycStatus(data?.status??"NOT_SUBMITTED")).catch(()=>setKycStatus("NOT_SUBMITTED"))};
  const changePassword=async(event:React.FormEvent)=>{event.preventDefault();setPasswordMessage("");if(newPassword.length<8||newPassword.trim().length<8){setPasswordMessage("New password must be at least 8 characters.");return}if(newPassword!==confirmPassword){setPasswordMessage("Confirm password must match the new password.");return}setPasswordBusy(true);try{const response=await fetch("/api/account/change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword,newPassword})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to update password.");setPasswordMessage(data.message??"Password updated successfully.");setCurrentPassword("");setNewPassword("");setConfirmPassword("")}catch(error){setPasswordMessage(error instanceof Error?error.message:"Unable to update password.")}finally{setPasswordBusy(false)}};
  const logout=async()=>{localStorage.clear();sessionStorage.clear();await signOut({callbackUrl:"/login"})};
  const actions=<div className="flex items-center gap-2"><motion.button whileTap={{scale:.9}} onClick={()=>void openNotifications()} aria-label="Notifications" className="icon-button"><Bell size={17}/></motion.button><motion.button whileTap={{scale:.9}} onClick={openMenu} aria-label="Open menu" className="icon-button"><Menu size={18}/></motion.button></div>;
  return <div className="app-bg min-h-screen text-slate-300"><SessionGuard/><NavigationRecovery/><div className="noise-layer"/><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="ambient ambient-three"/>
    <header className="premium-header sticky top-0 z-40"><div className={`mx-auto max-w-6xl px-4 sm:px-6 ${dashboard?"":"flex h-16 items-center justify-between"}`}>
      {dashboard?<><div className="target-header-top"><Logo onClick={openProfile}/>{actions}</div><div className="target-header-user"><div className="target-header-avatar">{initials}</div><div><small>Hello,</small><div className="target-header-name-line"><strong>{user?.name||"User"}</strong><span className="target-rank-stars" aria-label={`Rank ${currentRank} of 7`}>{Array.from({length:7},(_,index)=><i className={index<currentRank?"achieved":"locked"} key={index}>{index<currentRank?"★":"☆"}</i>)}</span></div><span>ID · {user?.uid||"—"}</span></div></div></>:<><Logo/><div className="flex items-center gap-2">{actions}</div></>}
    </div></header>
    <AnimatePresence mode="wait"><motion.main key={pathname} initial={{opacity:0,y:10,filter:"blur(4px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}} exit={{opacity:0,y:-6,filter:"blur(3px)"}} transition={{duration:.28,ease:[.22,.8,.2,1]}} className="inner-page-main relative z-0 min-h-screen w-full max-w-none px-4 pb-32 pt-6 md:mx-auto md:max-w-6xl md:px-6 lg:pb-12">{children}</motion.main></AnimatePresence>
    <nav aria-label="Primary navigation" className="floating-nav pointer-events-auto fixed bottom-4 left-1/2 z-[100] isolate flex w-[calc(100%-2rem)] max-w-md -translate-x-1/2 items-center justify-around px-2 py-2 lg:bottom-6">{nav.map(({href,label,icon:Icon,primary})=>{const active=pathname===href;return <Link href={href} prefetch={false} className={`nav-item pointer-events-auto ${active?"active":""} ${primary?"nav-primary":""}`} key={href}>{active&&<i/>}<Icon size={19}/><span>{label}</span></Link>})}</nav>
    <AnimatePresence>{menuOpen&&<><motion.button aria-label="Close menu" onClick={()=>setMenuOpen(false)} className="menu-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.22}}/><motion.aside className="premium-sheet" initial={{y:"105%"}} animate={{y:0}} exit={{y:"105%"}} transition={{duration:.26,ease:[.22,.8,.2,1]}}><div className="sheet-handle"/><div className="sheet-title"><div><small>Bitvora</small><h2>Account menu</h2></div><button onClick={()=>setMenuOpen(false)} aria-label="Close"><X size={18}/></button></div><div className="sheet-grid">{menu.map(({href,label,icon:Icon},i)=><Link href={href} onClick={()=>setMenuOpen(false)} key={`${label}-${i}`}><span><Icon size={17}/></span><b>{label}</b></Link>)}<button className="sheet-logout" onClick={()=>void signOut({callbackUrl:"/login"})}><span><LogOut size={17}/></span><b>Logout</b></button></div></motion.aside></>}</AnimatePresence>
    <AnimatePresence>{notificationsOpen&&<><motion.button aria-label="Close notifications" onClick={()=>setNotificationsOpen(false)} className="menu-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.22}}/><motion.aside className="notification-sheet" initial={{x:"105%"}} animate={{x:0}} exit={{x:"105%"}} transition={{duration:.26,ease:[.22,.8,.2,1]}}><div className="sheet-title"><div><small>Updates</small><h2>Notifications</h2></div><button onClick={()=>setNotificationsOpen(false)} aria-label="Close"><X size={18}/></button></div><div className="notification-list">{notificationsLoading?<p className="notification-empty">Loading notifications…</p>:notifications.length?notifications.map(item=><article key={item.id}><span><Bell size={15}/></span><div><strong>{item.title}</strong><p>{item.message}</p><small>{item.localDateTime}</small></div></article>):<p className="notification-empty">No notifications yet.</p>}</div></motion.aside></>}</AnimatePresence>
    <AnimatePresence>{profileOpen&&<><motion.button aria-label="Close Bitvora account menu" onClick={()=>setProfileOpen(false)} className="menu-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="premium-sheet profile-logo-sheet" role="dialog" aria-modal="true" aria-label="Bitvora account menu" initial={{y:"105%"}} animate={{y:0}} exit={{y:"105%"}} transition={{duration:.26,ease:[.22,.8,.2,1]}}><div className="sheet-handle"/><div className="profile-logo-identity"><small>BITVORA</small><strong>{user?.name||"User"}</strong><span>{user?.uid||"—"}</span></div>{passwordOpen?<form className="profile-password-form" onSubmit={changePassword}><div className="sheet-title"><div><small>Security</small><h2>Change Password</h2></div><button type="button" onClick={()=>{setPasswordOpen(false);setPasswordMessage("")}} aria-label="Back to account menu"><X size={18}/></button></div><label>Current Password<input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/></label><label>New Password<input type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={event=>setNewPassword(event.target.value)} required/></label><label>Confirm New Password<input type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} required/></label>{passwordMessage&&<p className={passwordMessage.includes("successfully")?"success":"error"}>{passwordMessage}</p>}<button className="profile-password-submit" disabled={passwordBusy}>{passwordBusy?"Updating…":"Update Password"}</button></form>:<div className="profile-logo-actions"><Link href="/profile/kyc" onClick={()=>setProfileOpen(false)}><span><ShieldCheck size={19}/></span><div><strong>Account Verification</strong><small className={kycStatus==="APPROVED"?"verified":"not-verified"}>{kycStatus==="APPROVED"?"✓ Verified":"○ Not Verified"}</small></div><ChevronRight size={16}/></Link><button type="button" onClick={()=>{setPasswordOpen(true);setPasswordMessage("")}}><span><KeyRound size={19}/></span><div><strong>Change Password</strong><small>Update account password</small></div><ChevronRight size={16}/></button><button type="button" className="danger" onClick={()=>setLogoutConfirm(true)}><span><LogOut size={19}/></span><div><strong>Logout</strong><small>End this session</small></div><ChevronRight size={16}/></button></div>}</motion.aside></>}</AnimatePresence>
    <WalletPortal><AnimatePresence>{logoutConfirm&&<motion.div className="logout-confirm-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button aria-label="Cancel logout" onClick={()=>setLogoutConfirm(false)} className="logout-confirm-scrim"/><motion.div className="logout-confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="logout-title" initial={{opacity:0,scale:.94,y:10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.96}}><span><LogOut size={22}/></span><h2 id="logout-title">Logout</h2><p>Are you sure you want to logout?</p><div><button onClick={()=>setLogoutConfirm(false)}>Cancel</button><button onClick={()=>void logout()}>Logout</button></div></motion.div></motion.div>}</AnimatePresence></WalletPortal>
  </div>;
}
