"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Star } from "lucide-react";
import type { CoinDefinition } from "@/lib/coins";
import { formatCurrency } from "@/lib/currency";
import { useMarketData } from "@/hooks/use-market-data";
import { TradingViewAdvancedChart } from "./tradingview-advanced-chart";
import { MarketDepthPanel } from "./market-depth-panel";
import { SpotOrderSheet } from "./spot-order-sheet";

const FAVOURITES_KEY="bitvora-market-favourites";
export function CoinDetail({coin}:{coin:CoinDefinition}){const catalogue=useMemo(()=>[coin],[coin]),symbols=useMemo(()=>[coin.symbol],[coin.symbol]),{markets}=useMarketData(catalogue,symbols),market=markets[0],positive=market.change>=0,[favourite,setFavourite]=useState(false),[orderSide,setOrderSide]=useState<"BUY"|"SELL"|null>(null);useEffect(()=>{try{setFavourite(new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]")).has(coin.symbol))}catch{setFavourite(false)}},[coin.symbol]);const toggleFavourite=()=>{try{const values=new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]"));if(values.has(coin.symbol))values.delete(coin.symbol);else values.add(coin.symbol);localStorage.setItem(FAVOURITES_KEY,JSON.stringify([...values]));setFavourite(values.has(coin.symbol))}catch{}};
  return <div className="coin-market-page"><section className="coin-market-summary"><div className="coin-summary-top"><Link href="/markets" className="market-back" aria-label="Back to markets"><ArrowLeft size={18}/></Link><h1>{coin.pair}</h1><button className={favourite?"active":""} onClick={toggleFavourite} aria-label={`${favourite?"Remove from":"Add to"} watchlist`}><Star size={19} fill={favourite?"currentColor":"none"}/></button></div><div className="coin-summary-market"><div className="coin-summary-price"><strong>{formatCurrency(market.price,{maximumFractionDigits:market.price<1?8:2})}</strong><span className={positive?"positive":"negative"}>{positive?"+":""}{market.change.toFixed(2)}%</span></div><dl className="coin-summary-stats"><div><dt>24h High</dt><dd>{formatCurrency(market.high,{maximumFractionDigits:market.high<1?8:2})}</dd></div><div><dt>24h Low</dt><dd>{formatCurrency(market.low,{maximumFractionDigits:market.low<1?8:2})}</dd></div><div><dt>24h Volume</dt><dd>{formatCurrency(market.volume,{notation:"compact",maximumFractionDigits:2})}</dd></div></dl></div></section><TradingViewAdvancedChart symbol={coin.tradingViewSymbol} marketName={`${coin.name} / TetherUS`}/><MarketDepthPanel symbol={`${coin.symbol}USDT`}/><div className="market-action-spacer"/><div className="market-sticky-actions"><button onClick={()=>setOrderSide("BUY")}>Buy</button><button onClick={()=>setOrderSide("SELL")}>Sell</button></div>{orderSide&&<SpotOrderSheet pair={coin.pair} side={orderSide} marketPrice={market.price} onClose={()=>setOrderSide(null)}/>}</div>}
