"use client";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Star, X } from "lucide-react";
import type { CoinDefinition } from "@/lib/coins";
import { formatCurrency } from "@/lib/currency";
import { useMarketData } from "@/hooks/use-market-data";
import { TradingViewAdvancedChart } from "./tradingview-advanced-chart";
import { MarketDepthPanel } from "./market-depth-panel";
import { SpotOrderSheet } from "./spot-order-sheet";

const FAVOURITES_KEY="bitvora-market-favourites";
type AiContext={pair:string;signal:"BUY"|"SELL";liveFrom:number;placementClosesAt:number;displayStartTime:string};
type AiSuccess={trade:{tradeCapital:number;status:string};session:AiContext};
export function CoinDetail({coin}:{coin:CoinDefinition}){const catalogue=useMemo(()=>[coin],[coin]),symbols=useMemo(()=>[coin.symbol],[coin.symbol]),{markets}=useMarketData(catalogue,symbols),market=markets[0],positive=market.change>=0,[favourite,setFavourite]=useState(false),[orderSide,setOrderSide]=useState<"BUY"|"SELL"|null>(null),[mounted,setMounted]=useState(false),[aiToken,setAiToken]=useState(""),[aiContext,setAiContext]=useState<AiContext|null>(null),[aiError,setAiError]=useState(""),[aiBusy,setAiBusy]=useState(false),[aiSuccess,setAiSuccess]=useState<AiSuccess|null>(null);useEffect(()=>{setMounted(true);const token=new URLSearchParams(window.location.search).get("aiIntent")??"";if(!token)return;setAiToken(token);fetch(`/api/ai-trading/intent?token=${encodeURIComponent(token)}`,{cache:"no-store"}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error??"Trading signal unavailable.");if(value.session.pair!==coin.pair)throw new Error("This signal belongs to a different market.");setAiContext(value.session)}).catch(error=>setAiError(error instanceof Error?error.message:"Trading signal unavailable."))},[coin.pair]);useEffect(()=>{try{setFavourite(new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]")).has(coin.symbol))}catch{setFavourite(false)}},[coin.symbol]);const toggleFavourite=()=>{try{const values=new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]"));if(values.has(coin.symbol))values.delete(coin.symbol);else values.add(coin.symbol);localStorage.setItem(FAVOURITES_KEY,JSON.stringify([...values]));setFavourite(values.has(coin.symbol))}catch{}};const action=async(side:"BUY"|"SELL")=>{if(!aiToken){setOrderSide(side);return}if(!aiContext)return setAiError("Trading signal is unavailable or expired.");setAiBusy(true);setAiError("");const response=await fetch("/api/ai-trading/intent",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({token:aiToken,side})}),value=await response.json();if(response.ok){setAiSuccess(value);window.dispatchEvent(new CustomEvent("bitvora-wallet-updated"))}else setAiError(value.error??"Trade placement failed.");setAiBusy(false)};
  return <div className="coin-market-page"><section className="coin-market-summary"><div className="coin-summary-top"><Link href="/markets" className="market-back" aria-label="Back to markets"><ArrowLeft size={18}/></Link><h1>{coin.pair}</h1><button className={favourite?"active":""} onClick={toggleFavourite} aria-label={`${favourite?"Remove from":"Add to"} watchlist`}><Star size={19} fill={favourite?"currentColor":"none"}/></button></div><div className="coin-summary-market"><div className="coin-summary-price"><strong>{formatCurrency(market.price,{maximumFractionDigits:market.price<1?8:2})}</strong><span className={positive?"positive":"negative"}>{positive?"+":""}{market.change.toFixed(2)}%</span></div><dl className="coin-summary-stats"><div><dt>24h High</dt><dd>{formatCurrency(market.high,{maximumFractionDigits:market.high<1?8:2})}</dd></div><div><dt>24h Low</dt><dd>{formatCurrency(market.low,{maximumFractionDigits:market.low<1?8:2})}</dd></div><div><dt>24h Volume</dt><dd>{formatCurrency(market.volume,{notation:"compact",maximumFractionDigits:2})}</dd></div></dl></div>{aiContext&&<div className={`ai-chart-signal ${aiContext.signal.toLowerCase()}`}>AI Copy Trading signal: <strong>{aiContext.signal}</strong> · {aiContext.pair}</div>}{aiError&&<div className="ai-chart-signal error">{aiError}</div>}</section><TradingViewAdvancedChart symbol={coin.tradingViewSymbol} marketName={`${coin.name} / TetherUS`}/><MarketDepthPanel symbol={`${coin.symbol}USDT`}/>{mounted&&createPortal(<><div className="market-sticky-actions"><div className="market-sticky-actions-inner"><button disabled={aiBusy||Boolean(aiContext&&aiContext.signal!=="BUY")} title={aiContext?.signal==="SELL"?"This session signal is SELL.":undefined} onClick={()=>void action("BUY")}>{aiBusy?"Processing…":"Buy"}</button><button disabled={aiBusy||Boolean(aiContext&&aiContext.signal!=="SELL")} title={aiContext?.signal==="BUY"?"This session signal is BUY.":undefined} onClick={()=>void action("SELL")}>{aiBusy?"Processing…":"Sell"}</button></div></div>{orderSide&&<SpotOrderSheet pair={coin.pair} side={orderSide} marketPrice={market.price} onClose={()=>setOrderSide(null)}/>} {aiSuccess&&<div className="copy-modal-backdrop"><div className="copy-modal ai-trade-success" role="dialog" aria-modal="true"><button className="copy-modal-close" onClick={()=>setAiSuccess(null)}><X size={17}/></button><span className="copy-modal-icon"><CheckCircle2 size={24}/></span><h2>Congratulations!</h2><p>Your trade has been successfully placed.</p><dl><dt>Pair</dt><dd>{aiSuccess.session.pair}</dd><dt>Signal</dt><dd>{aiSuccess.session.signal}</dd><dt>Trade amount</dt><dd>{formatCurrency(aiSuccess.trade.tradeCapital)}</dd><dt>Session</dt><dd>{aiSuccess.session.displayStartTime}</dd><dt>Status</dt><dd>{aiSuccess.trade.status}</dd></dl><div className="copy-modal-actions"><Link href="/trade">Back to Copy Trading</Link></div></div></div>}</>,document.body)}</div>}
