/* eslint-disable @next/next/no-img-element */
"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Star, Wifi, WifiOff } from "lucide-react";
import type { CoinDefinition } from "@/lib/coins";
import { formatCurrency } from "@/lib/currency";
import { useMarketData } from "@/hooks/use-market-data";
import { TradingViewAdvancedChart } from "./tradingview-advanced-chart";
import { MarketDepthPanel } from "./market-depth-panel";
import { SpotOrderSheet } from "./spot-order-sheet";

const FAVOURITES_KEY="bitvora-market-favourites";
export function CoinDetail({coin}:{coin:CoinDefinition}){const catalogue=useMemo(()=>[coin],[coin]),symbols=useMemo(()=>[coin.symbol],[coin.symbol]),{markets,loading,fallback,streaming,refresh}=useMarketData(catalogue,symbols),market=markets[0],positive=market.change>=0,[favourite,setFavourite]=useState(false),[orderSide,setOrderSide]=useState<"BUY"|"SELL"|null>(null);useEffect(()=>{try{setFavourite(new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]")).has(coin.symbol))}catch{setFavourite(false)}},[coin.symbol]);const toggleFavourite=()=>{try{const values=new Set<string>(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]"));if(values.has(coin.symbol))values.delete(coin.symbol);else values.add(coin.symbol);localStorage.setItem(FAVOURITES_KEY,JSON.stringify([...values]));setFavourite(values.has(coin.symbol))}catch{}};
  return <div className="coin-market-page"><section className="coin-detail-hero"><div className="coin-detail-nav"><Link href="/markets" className="market-back"><ArrowLeft size={17}/></Link><div className="coin-detail-title"><img src={coin.logo} alt={`${coin.name} logo`}/><div><span>{coin.pair}</span><h1>{coin.name}</h1><p>{streaming?<Wifi size={12}/>:<WifiOff size={12}/>} {fallback?"Market data unavailable":"Live market"}</p></div></div><button className={favourite?"active":""} onClick={toggleFavourite} aria-label={`${favourite?"Remove from":"Add to"} watchlist`}><Star size={18} fill={favourite?"currentColor":"none"}/></button></div><button className="coin-refresh" onClick={()=>void refresh()}>{loading?"Refreshing…":"Refresh"}</button><div className="coin-detail-price"><strong>{formatCurrency(market.price,{maximumFractionDigits:market.price<1?8:2})}</strong><span className={positive?"positive":"negative"}>{positive?"+":""}{market.change.toFixed(2)}%</span></div><div className="coin-detail-stats"><div><span>24h high</span><strong>{formatCurrency(market.high,{maximumFractionDigits:market.high<1?8:2})}</strong></div><div><span>24h low</span><strong>{formatCurrency(market.low,{maximumFractionDigits:market.low<1?8:2})}</strong></div><div><span>24h volume</span><strong>{formatCurrency(market.volume,{notation:"compact",maximumFractionDigits:2})}</strong></div></div></section><TradingViewAdvancedChart symbol={coin.tradingViewSymbol} marketName={`${coin.name} / TetherUS`}/><MarketDepthPanel symbol={`${coin.symbol}USDT`}/><div className="market-action-spacer"/><div className="market-sticky-actions"><button onClick={()=>setOrderSide("BUY")}>Buy</button><button onClick={()=>setOrderSide("SELL")}>Sell</button></div>{orderSide&&<SpotOrderSheet pair={coin.pair} side={orderSide} marketPrice={market.price} onClose={()=>setOrderSide(null)}/>}</div>}
