"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowRight, Bell, History, WalletCards, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useAiTrading, type AiTradeListItem, type CurrentAiSession } from "@/hooks/use-ai-trading";
import { formatCurrency } from "@/lib/currency";
import { formatLocalDateTime, formatLocalTime } from "@/lib/date-time";
import { PageHeader } from "./ui";
import { TradingViewCompactChart } from "./tradingview-compact-chart";

type Signal={token:string;session:{id:string;pair:string;signal:"BUY"|"SELL";liveFrom:number;placementClosesAt:number;chartSymbol:string;displayStartTime:string}};
type Notice={id:number;title:string;text:string;kind:"info"|"success"|"warning"};

export function CopyTradingModule(){const router=useRouter(),user=useCurrentUser(),{store:wallet}=useWalletStore(),userId=user?.id??"",userUid=user?.uid??"",trading=useAiTrading(userId,userUid,wallet.wallets.future.balance),[signal,setSignal]=useState<Signal|null>(null),[notices,setNotices]=useState<Notice[]>([]),[loading,setLoading]=useState(false),noticeId=useRef(0);const notify=(title:string,text:string,kind:Notice["kind"]="info")=>{const id=++noticeId.current;setNotices(current=>[{id,title,text,kind},...current].slice(0,3))};
  const openSignal=async()=>{if(!trading.currentSession||trading.currentSession.status!=="LIVE"||!trading.currentSession.eligible||loading)return;setLoading(true);try{const response=await fetch("/api/ai-trading/intent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:trading.currentSession.id}),signal:AbortSignal.timeout(10_000)}),value=await response.json();if(response.ok)setSignal({...value,session:{...value.session,displayStartTime:formatLocalTime(trading.currentSession.startTime)}});else notify("Trade unavailable",value.error??"Unable to open signal.","warning")}catch(error){notify("Trade unavailable",error instanceof Error&&error.name==="TimeoutError"?"Trading request timed out. Please retry.":"Unable to open signal.","warning")}finally{setLoading(false)}};
  const next=()=>{if(!signal)return;const symbol=signal.session.chartSymbol.split(":").pop()?.replace(/USDT$/i,"").toLowerCase();if(!symbol)return;router.push(`/markets/${symbol}?aiIntent=${encodeURIComponent(signal.token)}`)};
  const summary=trading.futureWalletSummary,net=summary?.todayNetChange??0;
  return <div className="copy-module"><PageHeader eyebrow="AI Copy Trading"/><Portal><NoticeStack notices={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/></Portal><section className="copy-hero future-wallet-hero"><div className="copy-hero-top"><div><span className="copy-kicker">FUTURE WALLET</span></div><span className="copy-hero-orb"><WalletCards size={23}/></span></div><strong className="future-wallet-total">{summary?formatCurrency(summary.balance):"$0"}</strong><span className={`future-wallet-today ${net>0?"positive":net<0?"negative":""}`}>{net>=0?"+":""}{formatCurrency(net)} Today</span></section><TradingViewCompactChart/><CurrentSessionCard session={trading.currentSession} now={trading.now} loading={loading} onTrade={openSignal}/><CurrentTrades trades={trading.currentTrades}/><TradeHistory trades={trading.tradeHistory}/><Portal>{signal&&<SignalModal signal={signal} onClose={()=>setSignal(null)} onNext={next}/>}</Portal></div>}

function CurrentSessionCard({session,now,loading,onTrade}:{session:CurrentAiSession|null;now:number;loading:boolean;onTrade:()=>void}){const canTrade=Boolean(session&&session.status==="LIVE"&&session.eligible&&!loading),remaining=session?Math.max(0,session.countdownTarget-now):0,total=Math.ceil(remaining/1000),countdown=`${String(Math.floor(total/3600)).padStart(2,"0")}:${String(Math.floor(total%3600/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;return <section className="copy-trade-card copy-current-session"><div className="copy-card-heading"><div><span>{session?.type==="ADDITIONAL"?"Additional Trade":session?`Trade Session ${session.sequence}`:"Trade Session"}</span><small>{countdown}</small></div><button disabled={!canTrade} onClick={onTrade}>Trade</button></div></section>}
function CurrentTrades({trades}:{trades:AiTradeListItem[]}){return <section id="copy-current-trades"><div className="copy-section-label">Current Trades</div><div className="copy-history-list">{trades.length?trades.map(trade=><TradeRow trade={trade} current key={trade.id}/>):<div className="copy-demo-note">No active trades.</div>}</div></section>}
function TradeHistory({trades}:{trades:AiTradeListItem[]}){return <section id="copy-history"><div className="copy-section-label">Trade History</div><div className="copy-history-list">{trades.length?trades.map(trade=><TradeRow trade={trade} key={trade.id}/>):<div className="copy-demo-note">No trade history.</div>}</div></section>}
const tradeStatusLabel=(status:AiTradeListItem["status"])=>(
  ({CAPITAL_LOCKED:"Active",PENDING_SETTLEMENT:"Active",SETTLING:"Processing",SETTLED:"Completed",FAILED:"Failed",CANCELLED:"Cancelled",MISSED:"Missed"})[status]
);
function TradeRow({trade,current=false}:{trade:AiTradeListItem;current?:boolean}){const status=tradeStatusLabel(trade.status),statusClass=current?"live":trade.status==="SETTLED"?"completed":"missed";return <div className="copy-history-row"><div className="copy-history-icon"><History size={16}/></div><div className="copy-history-main"><div><strong>{trade.pair} · {trade.direction} · {trade.sourceLabel}</strong><span className={`copy-status ${statusClass}`}>{status}</span></div>{current?<><p>Trade {status}</p><small>Placed at {formatLocalTime(trade.placedAt)}</small></>:trade.status==="SETTLED"?<><p>Profit received: {formatCurrency(trade.profitReceived??0)}</p><small>Completed at {formatLocalDateTime(trade.settledAt)}</small></>:trade.status==="MISSED"?<><p>Session missed</p><small>{formatLocalDateTime(trade.missedAt)}</small></>:<><p>Trade {status}</p><small>Placed at {formatLocalDateTime(trade.placedAt)}</small></>}</div></div>}
function SignalModal({signal,onClose,onNext}:{signal:Signal;onClose:()=>void;onNext:()=>void}){return <div className="copy-modal-backdrop"><div className="copy-modal copy-signal-modal" role="dialog" aria-modal="true"><button className="copy-modal-close" onClick={onClose}><X size={17}/></button><span>Trading Signal</span><h2>Trade now in {signal.session.pair}</h2><div className={`copy-signal-direction ${signal.session.signal.toLowerCase()}`}>Signal: {signal.session.signal}</div><dl><dt>Pair</dt><dd>{signal.session.pair}</dd><dt>Direction</dt><dd>{signal.session.signal}</dd><dt>Session time</dt><dd>{signal.session.displayStartTime}</dd></dl><div className="copy-modal-actions"><button onClick={onClose}>Close</button><button onClick={onNext}>Next <ArrowRight size={15}/></button></div></div></div>}
function NoticeStack({notices,dismiss}:{notices:Notice[];dismiss:(id:number)=>void}){return <div className="copy-notifications">{notices.map(item=><button className={`copy-notice ${item.kind}`} onClick={()=>dismiss(item.id)} key={item.id}><Bell size={15}/><div><strong>{item.title}</strong><span>{item.text}</span></div><X size={13}/></button>)}</div>}
function Portal({children}:{children:React.ReactNode}){const[mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);return mounted?createPortal(children,document.body):null}
