"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowRight, Bell, Clock3, History, WalletCards, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useAiTrading, type CurrentAiSession } from "@/hooks/use-ai-trading";
import { formatCurrency } from "@/lib/currency";
import { getSessionById, type TradeSession, type UserTrade } from "@/lib/ai-trading-engine";
import { PageHeader } from "./ui";
import { TradingViewCompactChart } from "./tradingview-compact-chart";

type Signal={token:string;session:{id:string;pair:string;signal:"BUY"|"SELL";liveFrom:number;placementClosesAt:number;chartSymbol:string}};
type Notice={id:number;title:string;text:string;kind:"info"|"success"|"warning"};
const formatTime=(value:number,timeZone="UTC")=>new Intl.DateTimeFormat("en-US",{timeZone,hour:"numeric",minute:"2-digit"}).format(value);
const remaining=(target:number,now:number)=>{const seconds=Math.max(0,Math.ceil((target-now)/1000));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};

export function CopyTradingModule(){const router=useRouter(),user=useCurrentUser(),{store:wallet}=useWalletStore(),userId=user?.id??"",userUid=user?.uid??"",trading=useAiTrading(userId,userUid,wallet.wallets.future.balance),[signal,setSignal]=useState<Signal|null>(null),[notices,setNotices]=useState<Notice[]>([]),[loading,setLoading]=useState(false),noticeId=useRef(0),trades=trading.store.trades.filter(item=>item.userId===userId),historicalSessions=useMemo(()=>new Map(trades.flatMap(trade=>{const session=getSessionById(trade.sessionId,trading.now);return session?[[trade.sessionId,session] as const]:[]})),[trades,trading.now]);const notify=(title:string,text:string,kind:Notice["kind"]="info")=>{const id=++noticeId.current;setNotices(current=>[{id,title,text,kind},...current].slice(0,3))};
  const openSignal=async()=>{if(!trading.currentSession||trading.currentSession.status!=="LIVE"||loading)return;setLoading(true);const response=await fetch("/api/ai-trading/intent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:trading.currentSession.id})}),value=await response.json();if(response.ok)setSignal(value);else notify("Trade unavailable",value.error??"Unable to open signal.","warning");setLoading(false)};
  const next=()=>{if(!signal)return;const symbol=signal.session.chartSymbol.split(":").pop()?.replace(/USDT$/i,"").toLowerCase();if(!symbol)return;router.push(`/markets/${symbol}?aiIntent=${encodeURIComponent(signal.token)}`)};
  const summary=trading.futureWalletSummary,net=summary?.todayNetChange??0;
  const timeZone=summary?.timezone??"UTC";return <div className="copy-module"><PageHeader eyebrow="AI Copy Trading" action={<span className="copy-live available"><i/> {timeZone}</span>}/><Portal><NoticeStack notices={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/></Portal><section className="copy-hero future-wallet-hero"><div className="copy-hero-top"><div><span className="copy-kicker">FUTURE WALLET</span></div><span className="copy-hero-orb"><WalletCards size={23}/></span></div><strong className="future-wallet-total">{summary?formatCurrency(summary.balance):"$0"}</strong><span className={`future-wallet-today ${net>0?"positive":net<0?"negative":""}`}>{net>=0?"+":""}{formatCurrency(net)} Today</span></section><TradingViewCompactChart/><CurrentSessionCard session={trading.currentSession} now={trading.now} loading={loading} onTrade={openSignal}/><TradeHistory trades={trades} sessions={historicalSessions} timeZone={timeZone}/><Portal>{signal&&<SignalModal signal={signal} onClose={()=>setSignal(null)} onNext={next}/>}</Portal></div>}
function CurrentSessionCard({session,now,loading,onTrade}:{session:CurrentAiSession|null;now:number;loading:boolean;onTrade:()=>void}){if(!session)return <section className="copy-trade-card copy-current-session"><div className="copy-card-heading"><div><span>Copy Trading</span><h2>No eligible session</h2></div><button disabled>Trade</button></div><p className="copy-demo-note">The next eligible session will appear automatically.</p></section>;const countdown=remaining(session.countdownTarget,now),canTrade=session.status==="LIVE"&&session.eligible&&!loading,countdownLabel=session.status==="LIVE"?`Closes in ${countdown}`:session.status==="UPCOMING"?`Starts in ${countdown}`:session.status==="JOINED"?"Session joined":session.status==="COMPLETED"?"Session completed":"Session expired";return <section className="copy-trade-card copy-current-session"><div className="copy-card-heading"><div><span>Copy Trading</span><h2>{formatTime(session.startTime)} session</h2></div><button className="copy-trade-button" disabled={!canTrade} onClick={onTrade}>{loading?"Opening…":session.placementSource==="AI_BOT"?"Auto placed":"Trade"}</button></div><div className="copy-current-details"><span className={`copy-status ${session.status.toLowerCase()}`}>{session.status}</span><strong><Clock3 size={16}/>{countdownLabel}</strong><small>{canTrade?"Signal ready":session.blockReason??"Trade is unavailable."}</small></div></section>}
function SignalModal({signal,onClose,onNext}:{signal:Signal;onClose:()=>void;onNext:()=>void}){return <div className="copy-modal-backdrop"><div className="copy-modal copy-signal-modal" role="dialog" aria-modal="true"><button className="copy-modal-close" onClick={onClose}><X size={17}/></button><span>Trading Signal</span><h2>Trade now in {signal.session.pair}</h2><div className={`copy-signal-direction ${signal.session.signal.toLowerCase()}`}>Signal: {signal.session.signal}</div><dl><dt>Pair</dt><dd>{signal.session.pair}</dd><dt>Direction</dt><dd>{signal.session.signal}</dd><dt>Session time</dt><dd>{formatTime(signal.session.liveFrom)}</dd></dl><div className="copy-modal-actions"><button onClick={onClose}>Close</button><button onClick={onNext}>Next <ArrowRight size={15}/></button></div></div></div>}
const formatDateTime=(value:number,timeZone:string)=>new Intl.DateTimeFormat("en-US",{timeZone,day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(value);
function TradeHistory({trades,sessions,timeZone}:{trades:UserTrade[];sessions:Map<string,TradeSession>;timeZone:string}){return <section id="copy-history"><div className="copy-section-label">AI Trade History</div><div className="copy-history-list">{trades.length?trades.map(trade=>{const session=sessions.get(trade.sessionId),status=trade.status==="MISSED"?"Missed":trade.status==="SETTLED"?"Settled":"Pending Settlement",direction=trade.direction==="CALL"?"BUY":"SELL";return <div className="copy-history-row" key={trade.id}><div className="copy-history-icon"><History size={16}/></div><div className="copy-history-main"><div><strong>{trade.status==="PLACED"?"Capital Locked":session?.pair??trade.sessionId}</strong><span className={`copy-status ${trade.status==="SETTLED"?"completed":trade.status==="PLACED"?"live":"missed"}`}>{status}</span></div><p>{session?.pair??trade.sessionId} · {direction} · {trade.placementSource==="AI_BOT"?"AI Bot":"Manual"}</p><small>{trade.status==="MISSED"?"Session missed":trade.status==="PLACED"?`${formatCurrency(trade.tradeCapital)} capital locked · Placed at ${formatDateTime(trade.placedAt,timeZone)} · Settlement pending`:`${formatCurrency(trade.tradeCapital)} principal returned · Profit ${formatCurrency(trade.profitAmount)} · Settled at ${formatDateTime(trade.settledAt!,timeZone)}`}</small></div></div>}):<div className="copy-demo-note">No sessions joined yet.</div>}</div></section>}
function NoticeStack({notices,dismiss}:{notices:Notice[];dismiss:(id:number)=>void}){return <div className="copy-notifications">{notices.map(item=><button className={`copy-notice ${item.kind}`} onClick={()=>dismiss(item.id)} key={item.id}><Bell size={15}/><div><strong>{item.title}</strong><span>{item.text}</span></div><X size={13}/></button>)}</div>}
function Portal({children}:{children:React.ReactNode}){const[mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);return mounted?createPortal(children,document.body):null}
