"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Activity, Bell, Clock3, History, ShieldAlert, Sparkles, TrendingUp, X } from "lucide-react";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useAiTrading } from "@/hooks/use-ai-trading";
import { getFutureMetrics, lockFutureTradeCapital, settleFutureTrade } from "@/lib/wallet-data";
import { formatCurrency } from "@/lib/currency";
import { addTargetCompletedNotification, canUseAdditional, getSessionById, getSessionPhase, placeUserTrade, settleUserTrade, type TradeSession, type TradingNotification, type UserTrade } from "@/lib/ai-trading-engine";
import { Sparkline } from "./charts";
import { PageHeader } from "./ui";

type Notice={id:number;title:string;text:string;kind:"info"|"success"|"warning"};
const formatTime=(value:number)=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",hour:"numeric",minute:"2-digit"}).format(value);
const remaining=(target:number,now:number)=>{const seconds=Math.max(0,Math.ceil((target-now)/1000));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};
const chartData=(symbol:string)=>Array.from({length:32},(_,index)=>{let value=100;for(let cursor=0;cursor<=index;cursor+=1)value+=((symbol.charCodeAt(cursor%symbol.length)+cursor*7)%13-6)*.21;return Number(value.toFixed(2))});

export function CopyTradingModule(){const user=useCurrentUser(),{store:wallet,update}=useWalletStore(),userId=user?.id??"BTV10001",userUid=user?.uid??"BV100001",trading=useAiTrading(userId,userUid,wallet.wallets.future.balance),[chart,setChart]=useState<TradeSession|null>(null),[notices,setNotices]=useState<Notice[]>([]),noticeId=useRef(0),settling=useRef(new Set<string>());const notify=(title:string,text:string,kind:Notice["kind"]="info")=>{const id=++noticeId.current;setNotices(current=>[{id,title,text,kind},...current].slice(0,4));setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),5000)};
  const sessions=trading.sessions.filter(session=>session.type==="REGULAR"||canUseAdditional(trading.store,session)||trading.store.trades.some(item=>item.sessionId===session.id&&item.userId===userId)),trades=trading.store.trades.filter(item=>item.userId===userId),notifications=trading.store.notifications.filter(item=>item.userId===userId),historicalSessions=useMemo(()=>new Map(trades.flatMap(trade=>{const session=getSessionById(trade.sessionId,trading.now);return session?[[trade.sessionId,session] as const]:[]})),[trades,trading.now]);
  useEffect(()=>{for(const trade of trades){if(trade.status!=="PLACED"||settling.current.has(trade.id))continue;const session=historicalSessions.get(trade.sessionId);if(!session||trading.now<session.settlesAt)continue;settling.current.add(trade.id);const key=`AI_SETTLE:${session.id}:${userId}`,before=getFutureMetrics(wallet);update(current=>settleFutureTrade(current,{capital:trade.tradeCapital,profit:trade.profitAmount,key,additional:session.type==="ADDITIONAL",details:{userUid,sessionId:session.id,pair:session.pair,direction:trade.direction,grossFutureBalance:trade.balanceSnapshot,tradeCapital:trade.tradeCapital,profitPercentage:trade.profitRate,profitAmount:trade.profitAmount},timestamp:session.settlesAt}));trading.persist(current=>{let next=settleUserTrade(current,trade.id,session,trading.now).store;if(!before.futureToSpotUnlocked&&before.totalCompletedTradingProfit+trade.profitAmount>=before.requiredProfitForUnlock)next=addTargetCompletedNotification(next,userId,session.settlesAt);return next});notify("Trade Completed","Trade completed successfully. Your trade capital and profit have been credited to Future Wallet.","success")}},[trades,historicalSessions,trading,update,userId,userUid,wallet]);
  const copy=(session:TradeSession)=>{try{const result=placeUserTrade({store:trading.store,session,userId,userUid,futureBalance:wallet.wallets.future.balance,now:trading.now});if(!result.created){notify("Trade Already Placed","You already joined this session.","warning");setChart(null);return}const trade=result.trade,key=trade.idempotencyKey;update(current=>lockFutureTradeCapital(current,trade.tradeCapital,key,{userUid,sessionId:session.id,pair:session.pair,direction:trade.direction,grossFutureBalance:trade.balanceSnapshot,tradeCapital:trade.tradeCapital,profitPercentage:trade.profitRate,profitAmount:trade.profitAmount},trading.now));trading.persist(()=>result.store);setChart(null);notify("Trade Placed",`The shared ${trade.direction} signal was copied automatically.`,"success")}catch(error){notify("Trade Not Placed",error instanceof Error?error.message:"Unable to place trade.","warning")}};
  const regularAssignment=trading.store.assignments.find(item=>item.userId===userId&&item.tradingDate===sessions[0]?.tradingDate),settledProfit=trades.filter(item=>item.status==="SETTLED").reduce((sum,item)=>sum+item.profitAmount,0);
  return <div className="copy-module"><PageHeader eyebrow="AI Copy Trading" title="Trade workspace" action={<span className="copy-live available"><i/> Asia/Kolkata</span>}/><Portal><NotificationStack notices={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/></Portal>
    <section className="copy-hero"><div className="copy-hero-top"><div><span className="copy-kicker"><Activity size={13}/> Today&apos;s sessions</span><h2>Three shared AI signals</h2></div><span className="copy-hero-orb"><Sparkles size={23}/></span></div><div className="copy-hero-grid copy-hero-summary"><Metric label="Available balance" value={formatCurrency(wallet.wallets.future.balance)} hint="Future Wallet only"/><Metric label="Today&apos;s profit" value={formatCurrency(settledProfit)} hint={regularAssignment?`${regularAssignment.dailyProfitRate.toFixed(2)}% daily rate`:"Rate stored on first trade"}/></div></section>
    <section className="copy-trade-card"><div className="copy-card-heading"><div><span>Scheduled signals</span><h2>Daily trade sessions</h2></div><span className="copy-pair">IST</span></div><div className="copy-history-list">{sessions.map(session=><SessionRow key={session.id} session={session} trade={trades.find(item=>item.sessionId===session.id)} now={trading.now} onTrade={()=>setChart(session)}/>)}</div></section>
    <TradeHistory trades={trades} sessions={historicalSessions} now={trading.now}/><NotificationCenter notifications={notifications}/><Portal>{chart&&<ChartModal session={chart} now={trading.now} onClose={()=>setChart(null)} onCopy={()=>copy(chart)}/>}</Portal></div>}

function SessionRow({session,trade,now,onTrade}:{session:TradeSession;trade?:UserTrade;now:number;onTrade:()=>void}){const phase=getSessionPhase(session,now),phaseLabel=phase==="PROCESSING"?"IN PROGRESS":phase,display=trade?.status??phaseLabel,target=phase==="UPCOMING"?session.liveFrom:phase==="LIVE"?session.placementClosesAt:session.settlesAt;return <article className="copy-history-row"><div className="copy-history-icon"><Clock3 size={16}/></div><div className="copy-history-main"><div><strong>{session.sequence==="ADDITIONAL"?"New User Additional":`Trade ${session.sequence}`} · {session.pair}</strong><span className={`copy-status ${String(display).toLowerCase()}`}>{display}</span></div><p>{formatTime(session.liveFrom)} · {session.signalDirection}</p><small>{phase==="SETTLED"?"Session completed":`${phaseLabel} · ${remaining(target,now)}`}</small></div><button className="copy-trade-button" disabled={phase!=="LIVE"||Boolean(trade)} onClick={onTrade}>{trade?trade.status:phase==="LIVE"?"Copy signal":"Unavailable"}</button></article>}
function ChartModal({session,now,onClose,onCopy}:{session:TradeSession;now:number;onClose:()=>void;onCopy:()=>void}){const data=useMemo(()=>chartData(session.chartSymbol),[session.chartSymbol]);return <div className="copy-modal-backdrop"><div className="copy-modal copy-chart-modal" role="dialog" aria-modal="true"><button className="copy-modal-close" onClick={onClose}><X size={17}/></button><span className="copy-modal-icon"><TrendingUp size={22}/></span><span>Shared AI signal · {session.chartSymbol}</span><h2>{session.pair} — {session.signalDirection}</h2><div className="copy-session-chart"><Sparkline data={data} color="#7c6cff"/></div><div className="copy-warning"><ShieldAlert size={17}/><p>Bitvora assigns the pair and direction automatically for every user in this session.</p></div><p className="copy-demo-note">LIVE closes in {remaining(session.placementClosesAt,now)}</p><div className="copy-modal-actions"><button onClick={onClose}>Close</button><button onClick={onCopy}>Copy shared signal</button></div></div></div>}
const formatDate=(value:number)=>new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",day:"2-digit",month:"short",year:"numeric"}).format(value);
const formatDateTime=(value:number)=>new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(value);
function historyStatus(trade:UserTrade,session:TradeSession|undefined,now:number){if(trade.status==="MISSED")return"Missed";if(trade.status==="SETTLED"||session&&now>=session.settlesAt)return"Completed";if(session&&now>=session.placementClosesAt)return"In Progress";return"Live"}
function TradeHistory({trades,sessions,now}:{trades:UserTrade[];sessions:Map<string,TradeSession>;now:number}){const ordered=[...trades].sort((a,b)=>(sessions.get(b.sessionId)?.liveFrom??b.placedAt)-(sessions.get(a.sessionId)?.liveFrom??a.placedAt));return <section id="copy-history"><div className="copy-section-label">AI Trade History</div><div className="copy-history-list">{ordered.length?ordered.map(trade=>{const session=sessions.get(trade.sessionId),status=historyStatus(trade,session,now);return <div className="copy-history-row" key={trade.id}><div className="copy-history-icon"><History size={16}/></div><div className="copy-history-main"><div><strong>{session?.pair??trade.sessionId}</strong><span className={`copy-status ${status.toLowerCase()}`}>{status}</span></div><p>{session?formatDate(session.liveFrom):"Unknown date"} · {session?formatTime(session.liveFrom):"—"} · {trade.direction}</p><small>Capital {formatCurrency(trade.tradeCapital)} · Profit {trade.status==="MISSED"?"—":formatCurrency(trade.profitAmount)} · Settlement {session?formatDateTime(session.settlesAt):"—"}</small></div><div className="copy-history-profit"><strong>{status==="Completed"?`+${formatCurrency(trade.profitAmount)}`:"—"}</strong><span>{trade.profitRate.toFixed(4)}%</span></div></div>}):<div className="copy-demo-note">No sessions joined yet.</div>}</div></section>}
function NotificationCenter({notifications}:{notifications:TradingNotification[]}){return <section><div className="copy-section-label">Notification Center</div><div className="copy-history-list">{notifications.length?notifications.map(item=><div className="copy-history-row" key={item.id}><div className="copy-history-icon"><Bell size={16}/></div><div className="copy-history-main"><div><strong>{item.title}</strong><span className={`copy-status ${item.kind}`}>{item.type.replaceAll("_"," ")}</span></div><p>{item.text}</p><small>{formatDateTime(item.createdAt)}</small></div></div>):<div className="copy-demo-note">No trading notifications yet.</div>}</div></section>}
function Metric({label,value,hint}:{label:string;value:string;hint?:string}){return <div className="copy-metric"><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</div>}
function NotificationStack({notices,dismiss}:{notices:Notice[];dismiss:(id:number)=>void}){return <div className="copy-notifications" aria-live="polite">{notices.map(item=><button className={`copy-notice ${item.kind}`} onClick={()=>dismiss(item.id)} key={item.id}><Bell size={15}/><div><strong>{item.title}</strong><span>{item.text}</span></div><X size={13}/></button>)}</div>}
function Portal({children}:{children:React.ReactNode}){const[mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);return mounted?createPortal(children,document.body):null}
