"use client";
import { useState } from "react";
import { useBinanceMarketStream, type DepthLevel } from "@/hooks/use-binance-market-stream";

const number=(value:number,digits=8)=>value.toLocaleString("en-US",{maximumFractionDigits:digits});
function depthStyle(level:DepthLevel,max:number,color:string){return{background:`linear-gradient(270deg, ${color} ${Math.max(3,level.quantity/max*100)}%, transparent 0)`}}

export function MarketDepthPanel({symbol}:{symbol:string}){const[data,setTab]=useState<"book"|"records">("book"),stream=useBinanceMarketStream(symbol),max=Math.max(1,...stream.bids.map(item=>item.quantity),...stream.asks.map(item=>item.quantity)),bestBid=stream.bids[0]?.price,bestAsk=stream.asks[0]?.price,spread=bestBid&&bestAsk?bestAsk-bestBid:null;
  return <section className="market-depth-card"><div className="market-depth-tabs"><button className={data==="book"?"active":""} onClick={()=>setTab("book")}>Order Book</button><button className={data==="records"?"active":""} onClick={()=>setTab("records")}>Records</button><span className={stream.connected?"live":""}>{stream.connected?"Live":"Reconnecting"}</span></div>{stream.unsupported?<div className="market-stream-empty">Live market depth is unavailable for this symbol.</div>:data==="book"?<><div className="book-head"><span>Buy quantity</span><span>Bid price</span><span>Ask price</span><span>Sell quantity</span></div><div className="book-rows">{Array.from({length:Math.max(stream.bids.length,stream.asks.length,10)},(_,index)=>{const bid=stream.bids[index],ask=stream.asks[index];return <div className="book-row" key={index}><span style={bid?depthStyle(bid,max,"rgba(38,190,126,.16)"):undefined}>{bid?number(bid.quantity,6):"—"}</span><strong className="bid">{bid?number(bid.price):"—"}</strong><strong className="ask">{ask?number(ask.price):"—"}</strong><span style={ask?depthStyle(ask,max,"rgba(238,82,105,.16)"):undefined}>{ask?number(ask.quantity,6):"—"}</span></div>})}</div><div className="book-center"><div><span>Best bid</span><strong className="bid">{bestBid?number(bestBid):"—"}</strong></div><div><span>Spread</span><strong>{spread!==null?number(spread):"—"}</strong></div><div><span>Best ask</span><strong className="ask">{bestAsk?number(bestAsk):"—"}</strong></div></div></>:<><div className="records-head"><span>Price</span><span>Amount</span><span>Time</span><span>Side</span></div><div className="records-list">{stream.trades.length?stream.trades.map(trade=><div className="record-row" key={trade.id}><strong className={trade.side==="BUY"?"bid":"ask"}>{number(trade.price)}</strong><span>{number(trade.amount,6)}</span><span>{new Date(trade.time).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</span><b className={trade.side.toLowerCase()}>{trade.side}</b></div>):<div className="market-stream-empty">Waiting for live trades…</div>}</div></>}</section>}
