"use client";
import { useState } from "react";
import { Award, Bell, CalendarDays, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Crown, LockKeyhole, Medal, ShieldCheck, Sparkles, Star, TrendingUp, UsersRound, WalletCards, XCircle } from "lucide-react";
import { eligibilityChecklist, rankHistory, rankSalaryNotifications, salaryCycles, salaryHistory, salaryProjection, totalSalaryEarned } from "@/lib/rank-salary-data";
import { rankSalaryDemo, ranks, salaryPlan } from "@/lib/config";
import { formatCurrency } from "@/lib/currency";
import { useRankSalaryState } from "@/hooks/use-rank-salary-state";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { NoticeStack, type DemoNotice } from "./referral-team-ui";

const displayDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
function StarMedal({star,size="md"}:{star:number;size?:"sm"|"md"|"lg"}){return <span className={`rs-medal ${size}`}><Star fill="currentColor"/><b>{star}</b><i/></span>}

function RankPanel({notify}:{notify:(notice:DemoNotice)=>void}){const {store}=useWalletStore(),star=store.rankAccount.currentStar,currentRank=ranks.find(rank=>rank.star===star)??ranks[0],nextRank=ranks.find(rank=>rank.star>star)??ranks[ranks.length-1],teamCompletion=Math.min(100,Math.round(store.rankAccount.qualifiedTeamCount/nextRank.team*100)),directStarCompletion=nextRank.directStars.count===0?100:Math.min(100,Math.round(store.rankAccount.directRankCount/nextRank.directStars.count*100)),overallRankCompletion=Math.min(teamCompletion,directStarCompletion),remainingTeam=Math.max(0,nextRank.team-store.rankAccount.qualifiedTeamCount),totalRewardsEarned=store.rankAccount.rewardedRanks.reduce((sum,rewardedStar)=>sum+(ranks.find(rank=>rank.star===rewardedStar)?.reward??0),0),rankTimeline=ranks.map(rank=>({...rank,name:`${rank.star} Star`,status:rank.star<star?"Achieved":rank.star===star?"Current":"Locked",achievedDate:store.rankAccount.rewardedRanks.includes(rank.star)?rankSalaryDemo.rankAchievedDate:null}));return <div className="rs-panel">
  <section className="rank-current-hero"><div className="rank-current-main"><StarMedal star={currentRank.star} size="lg"/><div><span>Current achievement</span><h2>{star>0?`${star} Star`:"Unqualified"}</h2><p>{star>0?"Currently qualified":"Complete the live rank requirements"}</p></div><button onClick={()=>notify(rankSalaryNotifications[0])}><Bell size={15}/></button></div><div className="rank-current-grid"><div><UsersRound size={14}/><span>Qualified team</span><strong>{store.rankAccount.qualifiedTeamCount}</strong></div><div><CheckCircle2 size={14}/><span>Matching directs</span><strong>{store.rankAccount.directRankCount}</strong></div><div><CircleDollarSign size={14}/><span>Salary per cycle</span><strong>{formatCurrency(star>0?currentRank.salary:0)}</strong></div><div><Award size={14}/><span>Rewards earned</span><strong>{formatCurrency(totalRewardsEarned)}</strong></div></div><div className="rank-hero-footer"><span><CalendarDays size={13}/> Next salary: {displayDate(rankSalaryDemo.nextSalaryDate)}</span><b>{star>0?"Eligible while qualified":"Not currently eligible"}</b></div></section>
  <section className="next-rank-card"><div className="next-rank-copy"><span>Next achievement</span><h2>{nextRank.star} Star</h2><p>{store.rankAccount.qualifiedTeamCount} of {nextRank.team} qualified team members</p><div className="next-rank-stats"><div><strong>{remainingTeam}</strong><span>members remaining</span></div><div><strong>{store.rankAccount.directRankCount}/{nextRank.directStars.count}</strong><span>direct {nextRank.directStars.star} Star users</span></div></div></div><div className="rank-progress-ring" style={{"--rank-progress":`${overallRankCompletion*3.6}deg`} as React.CSSProperties}><div><strong>{overallRankCompletion}%</strong><span>complete</span></div></div><div className="rank-progress-detail"><div><span>Team progress</span><b>{teamCompletion}%</b><i><em style={{width:`${teamCompletion}%`}}/></i></div><div><span>Direct-star progress</span><b>{directStarCompletion}%</b><i><em style={{width:`${directStarCompletion}%`}}/></i></div><p><ShieldCheck size={13}/>{nextRank.qualification}</p></div></section>
  <section><div className="rs-section-title"><div><span>Achievement path</span><h2>Rank timeline</h2></div><b>7 levels</b></div><div className="rank-timeline">{rankTimeline.map(rank=><article className={rank.status.toLowerCase()} key={rank.star}><div className="rank-track"><StarMedal star={rank.star}/><i/></div><div className="rank-timeline-main"><div><strong>{rank.name}</strong><span className={`rank-state ${rank.status.toLowerCase()}`}>{rank.status}</span></div><p>{rank.qualification}</p><dl><div><dt>Team</dt><dd>{rank.team.toLocaleString()}</dd></div><div><dt>Reward</dt><dd>{formatCurrency(rank.reward)}</dd></div><div><dt>Salary</dt><dd>{formatCurrency(rank.salary)} × 2</dd></div></dl>{rank.achievedDate&&<small><Check size={11}/> Achieved {displayDate(rank.achievedDate)}</small>}</div><span className="rank-tail">{rank.status==="Locked"?<LockKeyhole size={14}/>:<ChevronRight size={14}/>}</span></article>)}</div></section>
  <section><div className="rs-section-title"><div><span>What you unlock</span><h2>Rank benefits</h2></div></div><div className="rank-benefits"><article><Award size={17}/><strong>{formatCurrency(currentRank.reward)}</strong><span>One-time reward</span></article><article><CircleDollarSign size={17}/><strong>{formatCurrency(currentRank.salary)}</strong><span>Twice-monthly salary</span></article><article><Medal size={17}/><strong>Metallic badge</strong><span>Visible achievement</span></article><article><Crown size={17}/><strong>Recognition</strong><span>2nd Star status</span></article></div><div className="rank-qualification-summary"><ShieldCheck size={16}/><div><strong>Qualification summary</strong><p>{currentRank.team} team members and {currentRank.qualification.toLowerCase()}.</p></div></div></section>
  <section><div className="rs-section-title"><div><span>Achievement ledger</span><h2>Rank history</h2></div><b>{rankHistory.length} records</b></div><div className="rank-history-list">{rankHistory.map(record=><article key={record.id}><StarMedal star={Number(record.rank[0])} size="sm"/><div><strong>{record.rank}</strong><p>{displayDate(record.achievedDate)} · {record.teamCount} team</p><small>{record.id}</small></div><aside><strong>{formatCurrency(record.reward,{sign:"always"})}</strong><span>{record.status}</span></aside></article>)}</div></section>
</div>}

function SalaryPanel({notify}:{notify:(notice:DemoNotice)=>void}){const {store}=useWalletStore(),star=store.rankAccount.currentStar,currentRank=ranks.find(rank=>rank.star===star)??ranks[0],eligible=star>0;return <div className="rs-panel">
  <section className="salary-summary"><div className="salary-summary-top"><span><WalletCards size={19}/></span><div><small>Salary wallet · presentation</small><h2>{formatCurrency(totalSalaryEarned)}</h2><p>Paid only while rank-qualified</p></div><b>{eligible?"Eligible":"Unqualified"}</b></div><div className="salary-summary-grid"><div><span>Current rank</span><strong>{eligible?`${star} Star`:"Unqualified"}</strong></div><div><span>Per cycle</span><strong>{formatCurrency(eligible?currentRank.salary:0)}</strong></div><div><span>Total earned</span><strong>{formatCurrency(totalSalaryEarned)}</strong></div><div><span>Next salary</span><strong>{displayDate(rankSalaryDemo.nextSalaryDate)}</strong></div></div><button disabled={!eligible} onClick={()=>notify(rankSalaryNotifications[3])}><CalendarDays size={14}/> Upcoming salary reminder</button></section>
  <section><div className="rs-section-title"><div><span>{salaryPlan.paymentDays.map(day=>`${day}${day===1?"st":"th"}`).join(" and ")} monthly</span><h2>Salary calendar</h2></div><b>{salaryPlan.frequencyLabel}</b></div><div className="salary-calendar">{salaryCycles.map(cycle=><article className={cycle.status.toLowerCase()} key={cycle.id}><div className="salary-date"><strong>{new Date(`${cycle.date}T12:00:00`).toLocaleDateString("en-US",{day:"2-digit"})}</strong><span>{new Date(`${cycle.date}T12:00:00`).toLocaleDateString("en-US",{month:"short"})}</span></div><div><strong>{cycle.cycle}</strong><p>{cycle.rank} · {formatCurrency(cycle.amount)}</p></div><span className={`salary-status ${cycle.status.toLowerCase()}`}>{cycle.status}</span></article>)}</div></section>
  <section><div className="rs-section-title"><div><span>Qualification status</span><h2>Eligibility checklist</h2></div><b>{eligibilityChecklist.filter(item=>item.complete).length}/{eligibilityChecklist.length}</b></div><div className="salary-eligibility">{eligibilityChecklist.map(item=><article key={item.id}><span className={item.complete?"complete":"incomplete"}>{item.complete?<Check size={14}/>:<XCircle size={14}/>}</span><div><strong>{item.label}</strong><p>{item.detail}</p></div><b>{item.complete?"Complete":"Required"}</b></article>)}</div></section>
  <section><div className="rs-section-title"><div><span>Estimate only</span><h2>Salary projection</h2></div><b>24 cycles/year</b></div><div className="salary-projection"><article><span>Current annualized</span><strong>{formatCurrency(salaryProjection.currentAnnual)}</strong><small>At 2nd Star</small></article><article><span>Next-rank estimate</span><strong>{formatCurrency(salaryProjection.nextAnnual)}</strong><small>At 3rd Star</small></article><div><TrendingUp size={16}/><span>Potential yearly increase</span><strong>{formatCurrency(salaryProjection.increase,{sign:"always"})}</strong></div><p>Projection estimates assume continuous eligibility for all {salaryPlan.cyclesPerYear} demo salary cycles.</p></div></section>
  <section><div className="rs-section-title"><div><span>Demo ledger</span><h2>Salary history</h2></div><b>{salaryHistory.length} records</b></div><div className="salary-history-list">{salaryHistory.map(record=><article key={record.id}><span className={`salary-history-icon ${record.status.toLowerCase()}`}>{record.status==="Paid"?<Check size={14}/>:record.status==="Missed"?<XCircle size={14}/>:<Clock3 size={14}/>}</span><div><strong>{record.cycle}</strong><p>{record.rank} · {displayDate(record.date)}</p><small>{record.id}</small></div><aside><strong>{formatCurrency(record.amount)}</strong><span className={`salary-status ${record.status.toLowerCase()}`}>{record.status}</span></aside></article>)}</div></section>
</div>}

export function RankSalaryModule(){const {activeTab,setActiveTab,dismissedNotifications,dismissNotification}=useRankSalaryState();const [notices,setNotices]=useState<DemoNotice[]>([]);const notify=(notice:DemoNotice)=>{if(!dismissedNotifications.includes(notice.id))setNotices(current=>[notice,...current].slice(0,3))};return <div className="rank-salary-module"><header className="rs-page-header"><div><span>Achievement centre</span><h1>Rank & Salary</h1><p>Track qualifications and demo salary cycles.</p></div><button onClick={()=>notify(rankSalaryNotifications[5])}><Sparkles size={15}/> Progress update</button></header><nav className="rs-tabs"><button className={activeTab==="rank"?"active":""} onClick={()=>setActiveTab("rank")}><Crown size={16}/> Rank</button><button className={activeTab==="salary"?"active":""} onClick={()=>setActiveTab("salary")}><CircleDollarSign size={16}/> Salary</button></nav>{activeTab==="rank"?<RankPanel notify={notify}/>:<SalaryPanel notify={notify}/>}<section className="rs-demo-notifications"><div><Bell size={16}/><span><strong>Demo notifications</strong><small>Local presentation events only.</small></span></div><div>{rankSalaryNotifications.map(item=><button disabled={dismissedNotifications.includes(item.id)} onClick={()=>notify(item)} key={item.id}>{item.title}</button>)}</div></section><NoticeStack notices={notices} onClose={id=>{setNotices(current=>current.filter(item=>item.id!==id));dismissNotification(id)}}/></div>}
