"use client";
import { useMemo, useState } from "react";
import { Check, CheckCircle2, Copy, ExternalLink, Gift, Info, Link2, Share2, ShieldCheck, UserCheck, UserPlus, UsersRound, WalletCards, XCircle } from "lucide-react";
import { directReferrals, incomeTotals, referralHistory, referralNotifications, type TeamMember } from "@/lib/referral-team-data";
import { referralPlan } from "@/lib/config";
import { formatCurrency } from "@/lib/currency";
import { useReferralTeamState } from "@/hooks/use-referral-team-state";
import { useCurrentUser } from "@/hooks/use-current-user";
import { MemberAvatar, MemberDrawer, NoticeStack, StatusBadge, type DemoNotice } from "./referral-team-ui";

const PAGE_SIZE=8;
export function ReferralModule(){
  const [copied,setCopied]=useState<string|null>(null);const [selected,setSelected]=useState<TeamMember|null>(null);const [notices,setNotices]=useState<DemoNotice[]>([]);const [historyType,setHistoryType]=useState("All");const [page,setPage]=useState(1);
  const {favourites,toggleFavourite}=useReferralTeamState();
  const currentUser=useCurrentUser(),referralCode=currentUser?.uid??"—",referralLink=typeof window==="undefined"?`/register?ref=${referralCode}`:`${window.location.origin}/register?ref=${referralCode}`;
  const active=directReferrals.filter(member=>member.status==="Active").length;const qualified=directReferrals.filter(member=>member.planStatus==="Working Plan").length;
  const history=useMemo(()=>referralHistory.filter(record=>historyType==="All"||record.kind===historyType),[historyType]);const pages=Math.max(1,Math.ceil(history.length/PAGE_SIZE));const visible=history.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const notify=(notice:DemoNotice)=>setNotices(current=>[notice,...current].slice(0,3));
  const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value)}catch{const input=document.createElement("textarea");input.value=value;input.style.position="fixed";input.style.opacity="0";document.body.appendChild(input);input.select();document.execCommand("copy");input.remove()}setCopied(label);notify({id:`copy-${Date.now()}`,title:`${label} copied`,text:"Ready to share from your device."});setTimeout(()=>setCopied(null),1600)};
  const share=async()=>{if(navigator.share){await navigator.share({title:"Join Bitvora",text:"Use my Bitvora referral link",url:referralLink})}else await copy(referralLink,"Referral link")};
  return <div className="referral-module">
    <header className="rt-page-header"><div><span>Network growth</span><h1>Referral</h1><p>Invite, qualify, and track demo commissions.</p></div><button onClick={()=>notify(referralNotifications[0])}><UserPlus size={16}/> Demo event</button></header>
    <section className="referral-summary"><div className="referral-summary-top"><span><UsersRound size={18}/></span><div><small>Your UID</small><strong>{referralCode}</strong></div><button onClick={()=>copy(referralCode,"UID")}>{copied==="UID"?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="referral-link"><Link2 size={15}/><span>{referralLink}</span><button onClick={()=>copy(referralLink,"Referral link")}><Copy size={15}/></button><button onClick={share}><Share2 size={15}/></button></div><div className="referral-summary-stats"><div><span>Direct referrals</span><strong>{directReferrals.length}</strong></div><div><span>Active directs</span><strong>{active}</strong></div><div><span>Total income</span><strong>{formatCurrency(incomeTotals.direct+incomeTotals.level,{minimumFractionDigits:2})}</strong></div><div><span>Pending qualification</span><strong>{directReferrals.length-qualified}</strong></div></div></section>
    <section className="rt-income-grid"><article><span><WalletCards size={16}/></span><small>Direct income</small><strong>{formatCurrency(incomeTotals.direct,{minimumFractionDigits:2})}</strong><p>{referralPlan.directIncomePercent}% first Future transfer</p></article><article><span><UsersRound size={16}/></span><small>Level income</small><strong>{formatCurrency(incomeTotals.level,{minimumFractionDigits:2})}</strong><p>1% on Levels 1–5</p></article><article><span><Gift size={16}/></span><small>Today</small><strong>{formatCurrency(12.5,{sign:"always",minimumFractionDigits:2})}</strong><p>Demo presentation</p></article><article><span><UserCheck size={16}/></span><small>This month</small><strong>{formatCurrency(284.7,{minimumFractionDigits:2})}</strong><p>{incomeTotals.transactions} transactions</p></article></section>
    <section className="qualification-card"><div className="qualification-head"><span><ShieldCheck size={18}/></span><div><small>First-transfer qualification</small><h2>One transfer. One commission.</h2></div><b>Demo rules</b></div><div className="qualification-grid"><div><CheckCircle2 size={15}/><p><strong>Minimum {formatCurrency(referralPlan.eligiblePlan)}</strong><span>First Spot to Future transfer only.</span></p></div><div><CheckCircle2 size={15}/><p><strong>{referralPlan.directIncomePercent}% direct income</strong><span>Paid once on a qualifying first transfer.</span></p></div><div><CheckCircle2 size={15}/><p><strong>{referralPlan.levelIncomePercent}% per level</strong><span>Levels 1–5 receive 1% each.</span></p></div><div><XCircle size={15}/><p><strong>Opportunity consumed once</strong><span>A first transfer below $50 permanently generates no commission.</span></p></div></div></section>
    <section><div className="rt-section-title"><div><span>Level 1 network</span><h2>Direct referrals</h2></div><b>{qualified} qualified</b></div><div className="direct-list">{directReferrals.map(member=><article key={member.id}><MemberAvatar member={member}/><div className="direct-main"><div><strong>{member.name}</strong><span>{member.rank}</span></div><p>{member.uid} · Joined {new Date(member.joinDate).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"2-digit"})}</p><div><StatusBadge active={member.status==="Active"}/><b className={member.planStatus==="Working Plan"?"qualified":"unqualified"}>{member.planStatus}</b></div></div><div className="direct-money"><span>First Future transfer</span><strong>{formatCurrency(member.firstFutureTransfer)}</strong><small>{member.planStatus==="Working Plan"?`${formatCurrency(member.firstFutureTransfer*referralPlan.directIncomePercent/100,{sign:"always",minimumFractionDigits:2})} earned`:"Opportunity consumed"}</small><button onClick={()=>setSelected(member)}>Details <ExternalLink size={11}/></button></div></article>)}</div></section>
    <section><div className="rt-section-title"><div><span>Presentation ledger</span><h2>Referral history</h2></div><div className="rt-segmented">{["All","Direct","Level"].map(type=><button className={historyType===type?"active":""} onClick={()=>{setHistoryType(type);setPage(1)}} key={type}>{type}</button>)}</div></div><div className="referral-history">{visible.map(record=><article key={record.id}><span className={`history-kind ${record.kind.toLowerCase()}`}>{record.kind==="Direct"?"D":`L${record.level}`}</span><div><strong>{record.member}</strong><p>Level {record.level} · {formatCurrency(record.transfer)} first Future transfer · {record.percent}%</p><small>{new Date(record.date).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div><aside><strong className={record.amount?"positive":""}>{record.amount?formatCurrency(record.amount,{sign:"always",minimumFractionDigits:2}):formatCurrency(0)}</strong><span className={`history-status ${record.status.toLowerCase()}`}>{record.status}</span></aside></article>)}</div><div className="rt-pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {pages} · {history.length} records</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></section>
    <section className="rt-demo-notifications"><div><Info size={17}/><span><strong>Demo notifications</strong><small>Preview referral and team events locally.</small></span></div><div>{referralNotifications.map(notification=><button onClick={()=>notify(notification)} key={notification.id}>{notification.title}</button>)}</div></section>
    <MemberDrawer member={selected} onClose={()=>setSelected(null)} favourite={selected?favourites.includes(selected.id):false} onFavourite={toggleFavourite}/><NoticeStack notices={notices} onClose={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
  </div>
}
