"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, Copy, Crown, Gift, LogOut, QrCode, Send, ShieldCheck, Star, TrendingUp, UsersRound, WalletCards } from "lucide-react";
import { coins, DEMO_SESSION_KEY, demoAccount, teamMembers, transactions } from "@/lib/mock-data";
import { CURRENCY_SYMBOL, formatCurrency } from "@/lib/currency";
import { ranks, referralPlan, tradingPlan } from "@/lib/config";
import { Card, EmptyState, PageHeader, SectionTitle, Stat } from "./ui";


export function CopyTradingScreen() { const [active,setActive] = useState(false); return <><PageHeader eyebrow="Copy trading" title="Today’s opportunity"/><Card className="trade-hero trade-focus standalone-trade"><div className="trade-orb"/><div className="relative z-10"><span className="status-pill"><span/> Strategy online</span><h2 className="mt-5 text-2xl font-semibold text-white">Smart Momentum Pool</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-400">A diversified demo strategy across leading digital assets with a fixed 30-minute cycle.</p><div className="mt-7 grid grid-cols-3 gap-3"><Stat label="Amount" value={formatCurrency(demoAccount.copyTradingWallet)}/><Stat label="Profit range" value="1%–2%"/><Stat label="Duration" value="30 min"/></div><div className="standalone-progress"><div className={`trade-progress-ring ${active?"is-active":""}`}><div><strong>{active?"29:59":"30:00"}</strong><small>{active?"remaining":"duration"}</small></div></div><div><p className="text-sm font-medium text-white">{active?"Trade in progress":"Today’s trade is ready"}</p><p className="mt-1 text-xs leading-5 text-slate-500">Estimated profit · {formatCurrency(26.25)}–{formatCurrency(52.5)}</p><span className="extra-trade-badge"><Star size={11}/> Extra trade active · 8 days</span></div></div><button onClick={()=>setActive(true)} className="primary-button trade-glow mt-7 w-full" disabled={active}>{active ? "Trade is now in progress" : "Trade Now"}</button></div></Card><div className="mt-5 grid gap-5 sm:grid-cols-2"><Card><SectionTitle title="Daily availability"/><div className="space-y-3"><Counter label="Regular trade" value="1 available"/><Counter label="Extra deposit trade" value="1 available"/><Counter label="Extra benefit" value="8 days remaining"/></div></Card><Card><SectionTitle title="Plan timeline"/><Timeline/></Card></div><Card className="mt-5"><SectionTitle title="Plan details"/><div className="grid grid-cols-2 gap-5 sm:grid-cols-4"><Stat label="Start plan" value={formatCurrency(tradingPlan.startPlan)}/><Stat label="Working plan" value={formatCurrency(tradingPlan.workingPlan)}/><Stat label="Fund unlock" value={`${tradingPlan.fundUnlockDays} days`}/><Stat label="Growth target" value={`${tradingPlan.targetMultiple}x / ${tradingPlan.targetDays}d`}/></div><p className="mt-5 border-t border-white/[.06] pt-4 text-xs leading-5 text-slate-500">Demo presentation only. No real trades, deductions, profit guarantees, or financial processing are performed.</p></Card></>; }

function Counter({label,value}:{label:string;value:string}) { return <div className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] p-3"><span className="text-sm text-slate-400">{label}</span><span className="text-xs font-medium text-blue-300">{value}</span></div>; }
function Timeline() { return <div className="space-y-4">{[["Trade placed","Manual confirmation"],["30-minute cycle","Strategy runs"],["Profit credited","Wallet updated"]].map((v,i)=><div className="flex gap-3" key={v[0]}><span className="timeline-dot">{i+1}</span><div><p className="text-sm text-white">{v[0]}</p><p className="text-xs text-slate-500">{v[1]}</p></div></div>)}</div>; }

export function WalletScreen() { const assetValues=[12850,282.27,132.27,208.46]; return <><PageHeader eyebrow="Portfolio" title="Your wallet"/><Card className="balance-card elevated-wallet"><p className="text-xs text-blue-100/70">Total balance</p><p className="mt-2 text-4xl font-semibold text-white">{formatCurrency(demoAccount.totalBalance)}</p><div className="mt-7 grid grid-cols-3 gap-3"><Stat label="Available" value={formatCurrency(demoAccount.availableBalance)}/><Stat label="Trading" value={formatCurrency(demoAccount.copyTradingWallet)}/><Stat label="Profit" value={formatCurrency(demoAccount.totalProfit)}/></div></Card><div className="my-5 grid grid-cols-3 gap-3"><WalletAction href="/deposit" icon={ArrowDownLeft} label="Deposit"/><WalletAction href="/withdraw" icon={ArrowUpRight} label="Withdraw"/><WalletAction href="/transfer" icon={Send} label="Transfer"/></div><SectionTitle title="Your assets"/><Card className="asset-list divide-y divide-white/[.06] p-0">{coins.slice(0,4).map((coin,i)=><div className="asset-row flex items-center justify-between p-4" key={coin.symbol}><div className="flex items-center gap-3"><span className="coin-icon" style={{color:coin.color,background:`${coin.color}18`}}>{coin.symbol[0]}</span><div><p className="text-sm text-white">{coin.symbol}</p><p className="text-xs text-slate-500">{coin.name}</p></div></div><div className="text-right"><p className="text-sm text-white">{[12850,0.08,0.22,1.4][i]} {coin.symbol}</p><p className="text-xs text-slate-500">{formatCurrency(assetValues[i])}</p></div></div>)}</Card></>; }
function WalletAction({href,icon:Icon,label}:{href:string;icon:typeof Send;label:string}) { return <Link href={href} className="action-tile"><span><Icon size={19}/></span><b>{label}</b></Link>; }

export function MoneyScreen({type}:{type:"deposit"|"withdraw"|"transfer"}) { const data={deposit:{title:"Deposit funds",icon:ArrowDownLeft,button:"Generate deposit address"},withdraw:{title:"Withdraw funds",icon:ArrowUpRight,button:"Review withdrawal"},transfer:{title:"Transfer funds",icon:Send,button:"Review transfer"}}[type]; const Icon=data.icon; return <><PageHeader eyebrow="Wallet" title={data.title}/><Card><div className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3"><span className="coin-icon text-blue-300">{CURRENCY_SYMBOL}</span><div className="flex-1"><p className="text-[11px] text-slate-500">Selected asset</p><p className="text-sm font-medium text-white">Dollar balance <span className="text-xs font-normal text-slate-500">· TRC20</span></p></div><ChevronRight size={17}/></div>{type==="deposit" ? <div className="my-8 flex flex-col items-center"><div className="qr-placeholder"><QrCode size={82}/></div><p className="mt-4 text-center text-xs text-slate-500">Your demo wallet address will appear here</p></div> : <div className="mt-6 space-y-4"><label className="field"><span>{type==="transfer" ? "Recipient username or ID" : "Wallet address"}</span><div><WalletCards size={17}/><input placeholder={type==="transfer" ? "Enter member ID" : "Enter wallet address"}/></div></label><label className="field"><span>Amount</span><div><span className="text-sm">{CURRENCY_SYMBOL}</span><input type="number" placeholder="0.00"/><button className="text-xs text-blue-300">MAX</button></div></label><div className="flex justify-between text-xs text-slate-500"><span>Available balance</span><span className="text-white">{formatCurrency(demoAccount.availableBalance)}</span></div></div>}<button className="primary-button mt-6 w-full"><Icon size={17}/>{data.button}</button></Card><Card className="mt-5"><div className="flex gap-3"><ShieldCheck className="text-blue-300" size={20}/><div><p className="text-sm text-white">Demo wallet operation</p><p className="mt-1 text-xs leading-5 text-slate-500">This screen does not move real funds. Backend validation and financial processing are intentionally not implemented.</p></div></div></Card></>; }

export function HistoryScreen() { return <><PageHeader eyebrow="Wallet activity" title="Transaction history"/><div className="mb-5 flex gap-2 overflow-x-auto">{["All","Deposits","Trading","Rewards","Transfers"].map((v,i)=><button className={`filter-pill ${i===0?"active":""}`} key={v}>{v}</button>)}</div>{transactions.length ? <Card className="history-list divide-y divide-white/[.06] p-0">{transactions.concat(transactions.slice(0,2)).map((tx,i)=><div className="history-row flex items-center justify-between p-4" key={`${tx.date}-${i}`}><div className="flex items-center gap-3"><TransactionTypeIcon type={tx.type}/><div><p className="text-sm text-white">{tx.title}</p><p className="text-[11px] text-slate-500">{tx.date} · {tx.type}</p></div></div><span className={tx.amount>=0?"text-sm text-emerald-400":"text-sm text-white"}>{formatCurrency(tx.amount,{sign:tx.amount>=0?"always":"negative-only",minimumFractionDigits:2})}</span></div>)}</Card>:<EmptyState/>}</>; }

function TransactionTypeIcon({type}:{type:string}) { const Icon=type==="Deposit"?ArrowDownLeft:type==="Trade"?TrendingUp:type==="Reward"?Gift:Send; return <span className={`transaction-icon type-${type.toLowerCase()}`}><Icon size={16}/></span>; }

export function TeamScreen() { return <><PageHeader eyebrow="Your network" title="Team overview"/><div className="team-stat-grid grid grid-cols-3 gap-3"><Card className="p-4"><Stat label="Total team" value="86"/></Card><Card className="p-4"><Stat label="Direct" value="12"/></Card><Card className="p-4"><Stat label="Active" value="74"/></Card></div><Card className="team-network my-5"><div className="network-head"><div className="avatar avatar-premium">AM</div><span/><div className="network-nodes"><i>MC</i><i>NW</i><i>AP</i><i>+9</i></div></div><div className="mt-5 flex justify-between text-xs"><span>Team growth to 3rd Star</span><span className="text-white">86 / 125</span></div><div className="progress mt-3"><i style={{width:"69%"}}/></div><p className="mt-3 text-xs text-slate-500">Invite 39 more active members to complete the next team goal.</p></Card><SectionTitle title="Direct members"/><Card className="member-list divide-y divide-white/[.06] p-0">{teamMembers.map((member)=><div className="member-row flex items-center justify-between p-4" key={member.name}><div className="flex items-center gap-3"><div className="avatar small">{member.name.split(" ").map(v=>v[0]).join("")}</div><div><p className="text-sm text-white">{member.name}</p><p className="text-xs text-slate-500">{member.rank} · {formatCurrency(member.volume)}</p></div></div><span className={member.status==="Active"?"member-status active":"member-status"}>{member.status}</span></div>)}</Card></>; }

export function ReferralScreen() { const [copied,setCopied]=useState(false); return <><PageHeader eyebrow="Grow together" title="Referral plan"/><Card className="referral-card text-center"><span className="icon-bubble mx-auto"><Gift size={20}/></span><p className="mt-4 text-xs text-slate-500">Your referral code</p><h2 className="mt-1 text-2xl font-semibold tracking-[.15em] text-white">BITVORA24</h2><button onClick={()=>setCopied(true)} className="secondary-button mx-auto mt-5"><Copy size={15}/>{copied?"Copied":"Copy invite link"}</button></Card><div className="mt-5 grid gap-5 sm:grid-cols-2"><Card><SectionTitle title="Direct income"/><p className="text-3xl font-semibold gradient-text">{referralPlan.directIncomePercent}%</p><p className="mt-3 text-sm leading-6 text-slate-500">Paid once when a referred member’s first Spot to Future transfer is at least {formatCurrency(referralPlan.eligiblePlan)}.</p></Card><Card><SectionTitle title="Level income"/><p className="text-3xl font-semibold gradient-text">{referralPlan.levelIncomePercent}%</p><p className="mt-3 text-sm leading-6 text-slate-500">Paid once per level across Levels 1 through {referralPlan.levels}.</p></Card></div><Card className="level-breakdown mt-5"><SectionTitle title="Level breakdown"/>{Array.from({length:5},(_,i)=><div className="level-row flex items-center justify-between border-b border-white/[.06] py-3 last:border-0" key={i}><span className="text-sm text-slate-400">Level {i+1}</span><span className="text-sm text-white">1% first-transfer income</span></div>)}<p className="mt-4 text-xs text-slate-500">The first-transfer opportunity is consumed permanently, including when the amount is below $50.</p></Card></>; }

export function RankScreen() { return <><PageHeader eyebrow="Recognition & rewards" title="Rank and salary"/><Card className="rank-hero"><div className="relative z-10 flex items-center gap-4"><span className="rank-medal"><Crown size={26}/></span><div><p className="text-xs text-blue-200/70">Current rank</p><h2 className="text-2xl font-semibold text-white">2nd Star</h2><p className="mt-1 text-xs text-blue-100/60">Salary: {formatCurrency(30)} · paid twice monthly</p></div></div><div className="relative z-10 mt-6"><div className="flex justify-between text-xs"><span>Next: 3rd Star</span><span>86 / 125 members</span></div><div className="progress mt-2"><i style={{width:"69%"}}/></div><p className="mt-2 text-xs text-blue-100/60">39 members remaining · progressive direct-star qualification applies</p></div></Card><div className="rank-timeline mt-5 space-y-3">{ranks.map((rank,i)=><Card className={`rank-card p-4 ${i<2?"achieved":""}`} key={rank.star}><div className="rank-line"/><div className="flex items-center gap-3"><span className={`star-badge ${i===1?"current":""}`}><Star size={16} fill="currentColor"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><p className="font-medium text-white">{rank.star}{rank.star===1?"st":rank.star===2?"nd":rank.star===3?"rd":"th"} Star</p><span className="text-xs text-slate-500">{rank.team.toLocaleString()} team</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><span className="text-slate-500">Reward <b className="text-white">{formatCurrency(rank.reward)}</b></span><span className="text-slate-500">Twice-monthly <b className="text-white">{formatCurrency(rank.salary)}</b></span></div><p className="mt-2 text-[11px] text-blue-300/80">{rank.qualification}</p></div></div></Card>)}</div><p className="mt-5 text-center text-xs text-slate-600">Frontend qualification display only · salaries are not processed</p></>; }

export function ProfileScreen() { const router=useRouter(); const logout=()=>{localStorage.removeItem(DEMO_SESSION_KEY);router.replace("/login")}; return <><PageHeader eyebrow="Account" title="Profile"/><Card className="profile-hero text-center"><div className="profile-avatar-wrap"><div className="avatar avatar-premium large mx-auto">{demoAccount.initials}</div><span><Crown size={12}/></span></div><h2 className="mt-4 text-xl font-semibold text-white">{demoAccount.name}</h2><p className="text-sm text-slate-500">{demoAccount.email}</p><p className="mt-1 text-xs text-slate-600">ID · {demoAccount.userId}</p><span className="rank-pill mt-4"><Star size={12} fill="currentColor"/> {demoAccount.currentRank}</span></Card><div className="profile-stats mt-4 grid grid-cols-3 gap-3"><Card className="p-3 text-center"><Stat label="Direct" value="12"/></Card><Card className="p-3 text-center"><Stat label="Team" value="86"/></Card><Card className="p-3 text-center"><Stat label="Profit" value={formatCurrency(demoAccount.totalProfit,{notation:"compact",maximumFractionDigits:1})}/></Card></div><div className="mt-5 space-y-3">{[[WalletCards,"Wallet & assets","Manage your portfolio","/wallet"],[UsersRound,"Referral plan","Invite and earn","/referral"],[Star,"Rank & salary",demoAccount.currentRank,"/rank-salary"],[ShieldCheck,"KYC verification","Required only for withdrawals","/profile/kyc"]].map(([Icon,title,desc,href])=>{const I=Icon as typeof Star;return <Link href={String(href)} className="glass-card profile-row flex items-center gap-3 p-4" key={String(title)}><span className="icon-bubble"><I size={18}/></span><div className="flex-1"><p className="text-sm text-white">{String(title)}</p><p className="text-xs text-slate-500">{String(desc)}</p></div><ChevronRight size={17}/></Link>})}</div><button onClick={logout} className="secondary-button mt-6 w-full"><LogOut size={17}/> Logout</button><p className="mt-3 text-center text-[10px] text-slate-600">Logging out clears only the local frontend demo session.</p></>; }
