"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, CheckCircle2, KeyRound, ShieldCheck, WalletCards } from "lucide-react";
import { PageHeader } from "./ui";

type Settings={emailNotifications:boolean;pushNotifications:boolean;tradeNotifications:boolean};
const defaults:Settings={emailNotifications:true,pushNotifications:true,tradeNotifications:true};
export function SettingsModule(){const[settings,setSettings]=useState(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[kyc,setKyc]=useState("NOT_SUBMITTED"),[passwords,setPasswords]=useState({currentPassword:"",newPassword:"",confirmPassword:""}),[passwordMessage,setPasswordMessage]=useState(""),[passwordBusy,setPasswordBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();void Promise.all([fetch("/api/account/settings",{cache:"no-store",signal:controller.signal}).then(async r=>r.ok?r.json():null),fetch("/api/kyc/me",{cache:"no-store",signal:controller.signal}).then(async r=>r.ok?r.json():null)]).then(([preference,verification])=>{if(preference?.settings)setSettings(preference.settings);setKyc(verification?.status??"NOT_SUBMITTED")}).catch(()=>{}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
  const save=async()=>{setSaving(true);setMessage("");try{const response=await fetch("/api/account/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)}),data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to save settings.");setSettings(data.settings);setMessage(data.message)}catch(error){setMessage(error instanceof Error?error.message:"Unable to save settings.")}finally{setSaving(false)}};
  const changePassword=async(event:React.FormEvent)=>{event.preventDefault();setPasswordMessage("");if(passwords.newPassword!==passwords.confirmPassword){setPasswordMessage("Confirm password must match the new password.");return}setPasswordBusy(true);try{const response=await fetch("/api/account/change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword:passwords.currentPassword,newPassword:passwords.newPassword})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to update password.");setPasswords({currentPassword:"",newPassword:"",confirmPassword:""});setPasswordMessage(data.message)}catch(error){setPasswordMessage(error instanceof Error?error.message:"Unable to update password.")}finally{setPasswordBusy(false)}};
  return <div className="account-page"><PageHeader eyebrow="Account preferences" title="Settings"/><section className="account-panel"><div className="account-panel-title"><Bell size={18}/><div><h2>Notification preferences</h2><p>Choose which account updates you receive.</p></div></div>{[["emailNotifications","Email notifications"],["pushNotifications","Push notifications"],["tradeNotifications","Trading notifications"]].map(([key,label])=><label className="account-toggle" key={key}><span>{label}</span><input type="checkbox" checked={settings[key as keyof Settings]} onChange={event=>setSettings({...settings,[key]:event.target.checked})}/></label>)}{message&&<p className="account-message">{message}</p>}<button className="account-primary" disabled={loading||saving} onClick={()=>void save()}>{saving?"Saving…":<><CheckCircle2 size={16}/> Save preferences</>}</button></section><section className="account-panel"><div className="account-panel-title"><ShieldCheck size={18}/><div><h2>Security</h2><p>Password and identity verification.</p></div></div><Link className="account-shortcut" href="/kyc"><span><WalletCards size={17}/></span><div><strong>Account verification</strong><small>{kyc.replaceAll("_"," ")}</small></div><b>View</b></Link><form id="change-password" className="account-password" onSubmit={changePassword}><h3><KeyRound size={16}/> Change Password</h3><input type="password" autoComplete="current-password" required placeholder="Current password" value={passwords.currentPassword} onChange={event=>setPasswords({...passwords,currentPassword:event.target.value})}/><input type="password" autoComplete="new-password" required minLength={8} placeholder="New password" value={passwords.newPassword} onChange={event=>setPasswords({...passwords,newPassword:event.target.value})}/><input type="password" autoComplete="new-password" required minLength={8} placeholder="Confirm new password" value={passwords.confirmPassword} onChange={event=>setPasswords({...passwords,confirmPassword:event.target.value})}/>{passwordMessage&&<p className="account-message">{passwordMessage}</p>}<button className="account-primary" disabled={passwordBusy}>{passwordBusy?"Updating…":"Update password"}</button></form></section></div>}
