"use client";
import { useMemo, useState } from "react";
import { X } from "lucide-react";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { formatCurrency } from "@/lib/currency";
import { WalletPortal } from "./wallet-ui";

export function SpotOrderSheet({pair,side,marketPrice,onClose}:{pair:string;side:"BUY"|"SELL";marketPrice:number;onClose:()=>void}){const[type,setType]=useState<"MARKET"|"LIMIT">("MARKET"),[price,setPrice]=useState(String(marketPrice||"")),[amount,setAmount]=useState(""),[message,setMessage]=useState(""),{store,ready,available}=useWalletStore(),effectivePrice=type==="MARKET"?marketPrice:Number(price),quantity=Number(amount),total=useMemo(()=>Number.isFinite(effectivePrice*quantity)?effectivePrice*quantity:0,[effectivePrice,quantity]),balance=ready&&available?store.wallets.spot.balance:0;const submit=()=>{if(!(quantity>0)){setMessage("Enter a valid amount.");return}if(!(effectivePrice>0)){setMessage("Enter a valid limit price.");return}if(side==="BUY"&&total>balance){setMessage("Insufficient Spot Wallet balance.");return}setMessage("Trading execution is not available yet.")};
  return <WalletPortal><div className="market-sheet-backdrop"><section className={`market-order-sheet ${side.toLowerCase()}`} role="dialog" aria-modal="true" aria-label={`${side} ${pair}`}><button className="market-sheet-close" onClick={onClose}><X size={18}/></button><span>{pair}</span><h2>{side==="BUY"?"Buy":"Sell"} {pair.split("/")[0]}</h2><div className="order-type-tabs"><button className={type==="MARKET"?"active":""} onClick={()=>setType("MARKET")}>Market</button><button className={type==="LIMIT"?"active":""} onClick={()=>setType("LIMIT")}>Limit</button></div>{type==="LIMIT"&&<label>Price (USDT)<input inputMode="decimal" value={price} onChange={event=>setPrice(event.target.value)} /></label>}<label>Amount ({pair.split("/")[0]})<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/></label><dl><dt>Available Spot Wallet</dt><dd>{formatCurrency(balance)}</dd><dt>Estimated total</dt><dd>{formatCurrency(total)}</dd></dl>{message&&<p>{message}</p>}<div className="market-sheet-actions"><button onClick={onClose}>Cancel</button><button onClick={submit}>Confirm {side==="BUY"?"Buy":"Sell"}</button></div></section></div></WalletPortal>}
