"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bot, Check, History, LoaderCircle, Menu, MessageCirclePlus, Paperclip, Pencil, Send, Sparkles, TicketCheck, Trash2, X } from "lucide-react";

type Message={id:string;role:"USER"|"ASSISTANT"|"ADMIN";message:string;createdAt:string|number;streaming?:boolean};
type Session={id:string;title:string;unreadCount:number;lastMessageAt:string;createdAt:string;_count:{messages:number}};
type Reply={id:string;message:string;createdAt:number};
type Ticket={id:string;subject:string;category:string;message:string;priority:string;status:string;createdAt:number;hasAttachment:boolean;replies:Reply[]};
const prompts=["How do I deposit?","How do I withdraw?","Referral Income","Level Income","KYC Verification","AI Bot Subscription","Trade Schedule","Salary & Rewards"];
const stamp=(value:string|number)=>new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(value));

export function SupportModule(){
  const[sessions,setSessions]=useState<Session[]>([]),[sessionId,setSessionId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[input,setInput]=useState(""),[sending,setSending]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[ticketOpen,setTicketOpen]=useState(false),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[escalate,setEscalate]=useState(false),[ticketForm,setTicketForm]=useState({subject:"",category:"ACCOUNT",description:"",priority:"NORMAL"});
  const endRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null),composerRef=useRef<HTMLTextAreaElement>(null);
  const scroll=()=>requestAnimationFrame(()=>endRef.current?.scrollIntoView({behavior:"smooth",block:"end"}));
  const loadSessions=useCallback(async()=>{const response=await fetch("/api/support/chats",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to load chats.");setSessions(data.sessions??[])},[]);
  const loadTickets=useCallback(async()=>{const response=await fetch("/api/support",{cache:"no-store"}),data=await response.json();if(response.ok)setTickets(data.tickets??[])},[]);
  useEffect(()=>{Promise.all([loadSessions(),loadTickets()]).catch(error=>setNotice(error instanceof Error?error.message:"Unable to load support.")).finally(()=>setLoading(false))},[loadSessions,loadTickets]);
  useEffect(()=>{scroll()},[messages]);
  const openSession=async(id:string)=>{setHistoryOpen(false);setLoading(true);try{const response=await fetch(`/api/support/chats/${id}`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setSessionId(id);setMessages(data.session.messages);setEscalate(false);setSessions(current=>current.map(item=>item.id===id?{...item,unreadCount:0}:item))}catch(error){setNotice(error instanceof Error?error.message:"Unable to open chat.")}finally{setLoading(false)}};
  const newChat=()=>{setSessionId(null);setMessages([]);setInput("");setEscalate(false);setHistoryOpen(false);composerRef.current?.focus()};
  const send=async(text=input)=>{const clean=text.trim();if(!clean||sending)return;setInput("");setSending(true);setNotice("");setEscalate(false);const localId=`local-${Date.now()}`,assistantId=`stream-${Date.now()}`;setMessages(current=>[...current,{id:localId,role:"USER",message:clean,createdAt:Date.now()},{id:assistantId,role:"ASSISTANT",message:"",createdAt:Date.now(),streaming:true}]);try{const response=await fetch("/api/support/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId:sessionId??undefined,message:clean})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error??"Unable to send message.")}if(!response.body)throw new Error("Streaming is unavailable.");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",nextSession=sessionId;while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const rows=buffer.split("\n");buffer=rows.pop()??"";for(const row of rows){if(!row)continue;const event=JSON.parse(row);if(event.type==="session"){nextSession=event.session.id;setSessionId(event.session.id)}else if(event.type==="delta")setMessages(current=>current.map(item=>item.id===assistantId?{...item,message:item.message+event.delta}:item));else if(event.type==="escalate")setEscalate(true);else if(event.type==="error")throw new Error(event.error);else if(event.type==="done")setMessages(current=>current.map(item=>item.id===assistantId?{...item,id:event.message.id,createdAt:event.message.createdAt,streaming:false}:item))}}await loadSessions();if(nextSession)setSessionId(nextSession)}catch(error){setMessages(current=>current.filter(item=>item.id!==assistantId));setNotice(error instanceof Error?error.message:"Unable to send message.")}finally{setSending(false)}};
  const rename=async(session:Session)=>{const title=window.prompt("Rename chat",session.title)?.trim();if(!title)return;const response=await fetch(`/api/support/chats/${session.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title})});if(response.ok)setSessions(current=>current.map(item=>item.id===session.id?{...item,title}:item))};
  const remove=async(session:Session)=>{if(!window.confirm(`Delete “${session.title}”?`))return;const response=await fetch(`/api/support/chats/${session.id}`,{method:"DELETE"});if(response.ok){setSessions(current=>current.filter(item=>item.id!==session.id));if(sessionId===session.id)newChat()}};
  const createTicket=async(event:React.FormEvent)=>{event.preventDefault();const form=new FormData();form.set("subject",ticketForm.subject);form.set("category",ticketForm.category);form.set("message",ticketForm.description);form.set("priority",ticketForm.priority);if(sessionId)form.set("sessionId",sessionId);const file=fileRef.current?.files?.[0];if(file)form.set("attachment",file);setSending(true);try{const response=await fetch("/api/support",{method:"POST",body:form}),data=await response.json();if(!response.ok)throw new Error(data.error);setTickets(current=>[data.ticket,...current]);setTicketOpen(false);setTicketForm({subject:"",category:"ACCOUNT",description:"",priority:"NORMAL"});setNotice("Support ticket created successfully.")}catch(error){setNotice(error instanceof Error?error.message:"Unable to create ticket.")}finally{setSending(false)}};
  const keyDown=(event:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==="Enter"&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();void send()}};
  return <div className="ai-support-page">
    <header className="ai-support-head"><div className="ai-support-title"><span><Sparkles size={19}/></span><div><h1>AI Support</h1><p><i/>24/7 AI Assistant</p></div></div><div className="ai-support-actions"><button onClick={newChat}><MessageCirclePlus size={16}/><span>New Chat</span></button><button onClick={()=>setHistoryOpen(true)}><History size={16}/><span>Chat History</span>{sessions.some(s=>s.unreadCount>0)&&<b/>}</button></div></header>
    <section className="ai-chat-shell"><div className="ai-chat-identity"><span><Bot size={19}/></span><div><strong>Bitvora Support</strong><small><i/>24/7 Assistant</small></div><button aria-label="Open chat history" onClick={()=>setHistoryOpen(true)}><Menu size={18}/></button></div>
      <div className="ai-conversation" aria-live="polite">{loading&&messages.length===0?<div className="ai-loading"><LoaderCircle size={20}/><span>Loading secure support…</span></div>:messages.length===0?<motion.div className="ai-welcome" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><span><Bot size={27}/></span><h2>How can I help today?</h2><p>Ask about Bitvora or your current account. Your private context stays scoped to this signed-in account.</p><div className="ai-starter-grid">{prompts.map(prompt=><button key={prompt} onClick={()=>void send(prompt)}>{prompt}<Send size={12}/></button>)}</div></motion.div>:<div className="ai-message-list">{messages.map(message=><motion.article key={message.id} className={`ai-message ${message.role.toLowerCase()}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><div className="ai-avatar">{message.role==="USER"?"You":message.role==="ADMIN"?<TicketCheck size={15}/>:<Bot size={15}/>}</div><div><p>{message.message}{message.streaming&&<span className="stream-caret"/>}{message.streaming&&!message.message&&<span className="typing-dots"><i/><i/><i/></span>}</p><time>{message.role==="ADMIN"?"Support team · ":""}{stamp(message.createdAt)}{message.role==="USER"&&<Check size={11}/>}</time></div></motion.article>)}{escalate&&<motion.button initial={{opacity:0}} animate={{opacity:1}} className="ai-escalate" onClick={()=>{setTicketForm(current=>({...current,subject:input||"AI Support assistance",description:"Please help with my AI Support conversation."}));setTicketOpen(true)}}><TicketCheck size={16}/>Create Support Ticket</motion.button>}<div ref={endRef}/></div>}{notice&&<button className="ai-notice" onClick={()=>setNotice("")}>{notice}<X size={13}/></button>}</div>
      <div className="ai-composer"><div><button type="button" aria-label="Attachment is available in support tickets" title="Add an attachment through a support ticket" onClick={()=>setTicketOpen(true)}><Paperclip size={18}/></button><textarea ref={composerRef} value={input} onChange={event=>setInput(event.target.value.slice(0,4000))} onKeyDown={keyDown} rows={1} maxLength={4000} placeholder="Message AI Support…"/><button className="ai-send" disabled={!input.trim()||sending} onClick={()=>void send()} aria-label="Send message">{sending?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>}</button></div><small>AI can make mistakes. Verify important account actions.</small></div>
    </section>
    <AnimatePresence>{historyOpen&&<motion.div className="ai-sheet-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setHistoryOpen(false)}><motion.aside className="ai-history-sheet" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring",damping:28,stiffness:280}} onClick={event=>event.stopPropagation()}><header><div><h2>Chat History</h2><p>Continue where you left off</p></div><button onClick={()=>setHistoryOpen(false)}><X size={18}/></button></header><button className="ai-history-new" onClick={newChat}><MessageCirclePlus size={16}/>New conversation</button><div className="ai-history-list">{sessions.map(session=><article className={session.id===sessionId?"active":""} key={session.id}><button onClick={()=>void openSession(session.id)}><span><MessageCirclePlus size={15}/>{session.unreadCount>0&&<b>{session.unreadCount}</b>}</span><div><strong>{session.title}</strong><small>{session._count.messages} messages · {new Date(session.lastMessageAt).toLocaleDateString()}</small></div></button><div><button aria-label="Rename chat" onClick={()=>void rename(session)}><Pencil size={14}/></button><button aria-label="Delete chat" onClick={()=>void remove(session)}><Trash2 size={14}/></button></div></article>)}{!sessions.length&&<p>No saved conversations yet.</p>}</div><section className="ai-ticket-history"><h3>Support tickets</h3>{tickets.map(ticket=><article key={ticket.id}><div><strong>{ticket.subject}</strong><small>{ticket.category} · {ticket.priority}</small></div><span className={ticket.status.toLowerCase()}>{ticket.status.replace("_"," ")}</span>{ticket.replies.at(-1)&&<p><b>Admin:</b> {ticket.replies.at(-1)?.message}</p>}</article>)}{!tickets.length&&<p>No support tickets yet.</p>}</section></motion.aside></motion.div>}
    {ticketOpen&&<motion.div className="ai-sheet-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setTicketOpen(false)}><motion.form className="ai-ticket-sheet" initial={{opacity:0,scale:.96,y:20}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.97}} onSubmit={createTicket} onClick={event=>event.stopPropagation()}><header><div><h2>Create Support Ticket</h2><p>A support specialist can reply in this conversation.</p></div><button type="button" onClick={()=>setTicketOpen(false)}><X size={18}/></button></header><label>Subject<input required minLength={3} maxLength={120} value={ticketForm.subject} onChange={event=>setTicketForm({...ticketForm,subject:event.target.value})}/></label><div className="ai-ticket-row"><label>Category<select value={ticketForm.category} onChange={event=>setTicketForm({...ticketForm,category:event.target.value})}>{["ACCOUNT","DEPOSIT","WITHDRAWAL","TRADING","AI_BOT","KYC","TECHNICAL","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select value={ticketForm.priority} onChange={event=>setTicketForm({...ticketForm,priority:event.target.value})}>{["LOW","NORMAL","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Description<textarea required minLength={10} maxLength={4000} rows={5} value={ticketForm.description} onChange={event=>setTicketForm({...ticketForm,description:event.target.value})}/></label><label className="ai-ticket-file"><Paperclip size={16}/><span>Attachment <small>JPG, PNG, WebP or PDF · max 5 MB</small></span><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label><button className="ai-ticket-submit" disabled={sending}>{sending?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>}Submit ticket</button></motion.form></motion.div>}</AnimatePresence>
  </div>
}
