"use client";
import { useMemo, useState } from "react";
import { Bell, ChevronDown, ChevronRight, Network, Search, SlidersHorizontal, Star, UserCheck, UserMinus, UserPlus, UsersRound, WalletCards } from "lucide-react";
import { childrenFor, levelBreakdown, referralNotifications, teamMembers, teamTotals, type TeamMember } from "@/lib/referral-team-data";
import { formatCurrency } from "@/lib/currency";
import { useReferralTeamState } from "@/hooks/use-referral-team-state";
import { MemberAvatar, MemberDrawer, NoticeStack, StatusBadge, type DemoNotice } from "./referral-team-ui";

function TreeNode({member,depth,expanded,onToggle,onSelect}:{member:TeamMember;depth:number;expanded:string[];onToggle:(id:string)=>void;onSelect:(member:TeamMember)=>void}){
  const children=childrenFor(member.id);const open=expanded.includes(member.id);
  return <div className="team-tree-branch"><article className="team-tree-node" style={{"--depth":depth} as React.CSSProperties}><button className="tree-toggle" disabled={!children.length} onClick={()=>onToggle(member.id)} aria-label={`${open?"Collapse":"Expand"} ${member.name}`}>{children.length?(open?<ChevronDown size={14}/>:<ChevronRight size={14}/>):<span/>}</button><MemberAvatar member={member} size="sm"/><button className="tree-member" onClick={()=>onSelect(member)}><strong>{member.name}</strong><span>{member.uid} · {member.rank}</span><small>{member.planStatus} · {formatCurrency(member.personalBusiness)}</small></button><StatusBadge active={member.status==="Active"}/></article>{open&&children.length>0&&<div className="team-tree-children">{children.map(child=><TreeNode key={child.id} member={child} depth={Math.min(depth+1,5)} expanded={expanded} onToggle={onToggle} onSelect={onSelect}/>)}</div>}</div>
}

export function TeamModule(){
  const [query,setQuery]=useState("");const [selected,setSelected]=useState<TeamMember|null>(null);const [notices,setNotices]=useState<DemoNotice[]>([]);const [showFilters,setShowFilters]=useState(false);const [page,setPage]=useState(1);
  const {expanded,favourites,filters,setFilters,toggleExpanded,toggleFavourite,hydrated}=useReferralTeamState();
  const ranks=useMemo(()=>["All",...Array.from(new Set(teamMembers.map(member=>member.rank)))],[]);
  const filtered=useMemo(()=>{const text=query.trim().toLowerCase();return teamMembers.filter(member=>(!text||member.name.toLowerCase().includes(text)||member.uid.toLowerCase().includes(text))&&(filters.status==="All"||member.status===filters.status)&&(filters.rank==="All"||member.rank===filters.rank)&&(filters.level==="All"||String(member.level)===filters.level)).sort((a,b)=>filters.sort==="business"?b.teamBusiness-a.teamBusiness:filters.sort==="team-size"?b.totalTeam-a.totalTeam:filters.sort==="income"?b.referralIncome-a.referralIncome:Date.parse(b.joinDate)-Date.parse(a.joinDate))},[query,filters]);
  const pageSize=10,pages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize);const roots=childrenFor("BTV10001");
  const update=(key:string,value:string)=>{setFilters({...filters,[key]:value});setPage(1)};
  return <div className="team-module">
    <header className="rt-page-header"><div><span>Five-level network</span><h1>Team</h1><p>Explore your demo organisation and business.</p></div><button onClick={()=>setNotices(current=>[referralNotifications[4],...current].slice(0,3))}><Bell size={16}/> Demo event</button></header>
    <section className="team-overview"><div><span><Network size={19}/></span><div><small>Total network</small><strong>{teamTotals.total}</strong><p>Members across five levels</p></div></div><div className="team-overview-grid"><article><UsersRound size={15}/><span>Direct team</span><strong>{teamTotals.direct}</strong></article><article><UserCheck size={15}/><span>Active team</span><strong>{teamTotals.active}</strong></article><article><UserMinus size={15}/><span>Inactive team</span><strong>{teamTotals.inactive}</strong></article><article><UserPlus size={15}/><span>New this month</span><strong>{teamTotals.newThisMonth}</strong></article><article className="wide"><WalletCards size={15}/><span>Total team business</span><strong>{formatCurrency(teamTotals.business)}</strong></article></div></section>
    <section><div className="rt-section-title"><div><span>Network distribution</span><h2>Level breakdown</h2></div><b>{teamTotals.total} members</b></div><div className="level-breakdown">{levelBreakdown.map(level=><article key={level.level}><div className="level-index">L{level.level}</div><div className="level-copy"><div><strong>Level {level.level}</strong><span>{level.share}% of network</span></div><div className="level-bar"><i style={{width:`${level.share}%`}}/></div><dl><div><dt>Members</dt><dd>{level.count}</dd></div><div><dt>Active</dt><dd>{level.active}</dd></div><div><dt>Business</dt><dd>{formatCurrency(level.business)}</dd></div><div><dt>Income</dt><dd>{formatCurrency(level.income,{minimumFractionDigits:2})}</dd></div></dl></div></article>)}</div></section>
    <section><div className="rt-section-title"><div><span>Lazy expansion</span><h2>Team tree</h2></div><b>{expanded.length} expanded</b></div><div className="team-tree"><div className="team-tree-root"><span className="rt-avatar lg"><b>AM</b><i className="active"/></span><div><strong>Alex Morgan</strong><p>BV100001 · 2nd Star</p><small>Root user · {formatCurrency(teamTotals.business)} network</small></div></div>{hydrated?roots.map(member=><TreeNode key={member.id} member={member} depth={1} expanded={expanded} onToggle={toggleExpanded} onSelect={setSelected}/>):<div className="rt-tree-loading"><i/><i/><i/></div>}</div><p className="tree-help">Expand only the branches you need. Child nodes load progressively up to Level 5.</p></section>
    <section><div className="rt-section-title"><div><span>Member directory</span><h2>Search team</h2></div><b>{filtered.length} results</b></div><div className="team-search"><label><Search size={16}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search name or user ID"/></label><button className={showFilters?"active":""} onClick={()=>setShowFilters(value=>!value)}><SlidersHorizontal size={16}/><span>Filters</span></button></div>{showFilters&&<div className="team-filters"><label>Status<select value={filters.status} onChange={event=>update("status",event.target.value)}><option>All</option><option>Active</option><option>Inactive</option></select></label><label>Rank<select value={filters.rank} onChange={event=>update("rank",event.target.value)}>{ranks.map(rank=><option key={rank}>{rank}</option>)}</select></label><label>Level<select value={filters.level} onChange={event=>update("level",event.target.value)}><option>All</option>{[1,2,3,4,5].map(level=><option key={level}>{level}</option>)}</select></label><label>Sort by<select value={filters.sort} onChange={event=>update("sort",event.target.value)}><option value="join-date">Join date</option><option value="business">Business</option><option value="team-size">Team size</option><option value="income">Income</option></select></label></div>}<div className="team-directory">{visible.map(member=><article key={member.id}><MemberAvatar member={member}/><button onClick={()=>setSelected(member)}><strong>{member.name}</strong><span>{member.uid} · Level {member.level}</span><small>{member.rank} · {member.totalTeam} team</small></button><aside><StatusBadge active={member.status==="Active"}/><strong>{formatCurrency(member.teamBusiness)}</strong><button onClick={()=>toggleFavourite(member.id)} aria-label="Favourite member"><Star size={14} fill={favourites.includes(member.id)?"currentColor":"none"}/></button></aside></article>)}{!visible.length&&<div className="team-empty"><Search size={20}/><strong>No members found</strong><span>Try changing your search or filters.</span></div>}</div><div className="rt-pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></section>
    <MemberDrawer member={selected} onClose={()=>setSelected(null)} favourite={selected?favourites.includes(selected.id):false} onFavourite={toggleFavourite}/><NoticeStack notices={notices} onClose={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
  </div>
}
