"use client";
import { memo, useCallback, useEffect, useRef, useState } from "react";
import { loadTradingView } from "@/lib/tradingview-loader";
const intervals=[{label:"1m",value:"1"},{label:"5m",value:"5"},{label:"15m",value:"15"},{label:"1D",value:"D"}] as const;
const indicators=[{label:"Moving Average",value:"MASimple@tv-basicstudies"},{label:"EMA",value:"MAExp@tv-basicstudies"},{label:"Bollinger Bands",value:"BollingerBands@tv-basicstudies"},{label:"RSI",value:"RSI@tv-basicstudies"},{label:"MACD",value:"MACD@tv-basicstudies"},{label:"Volume",value:"Volume@tv-basicstudies"}] as const;
function CompactChart(){
  const hostRef=useRef<HTMLDivElement>(null),widgetRef=useRef<{remove?:()=>void}|null>(null),[state,setState]=useState<"loading"|"ready"|"slow"|"unavailable">("loading"),[interval,setIntervalValue]=useState("1"),[indicatorOpen,setIndicatorOpen]=useState(false),[studies,setStudies]=useState<string[]>([]),[attempt,setAttempt]=useState(0);
  useEffect(()=>{const host=hostRef.current;if(!host)return;let disposed=false;setState("loading");try{widgetRef.current?.remove?.()}catch{}host.replaceChildren();const observer=new MutationObserver(()=>{if(host.querySelector("iframe")){clearTimeout(timeout);setState("ready");observer.disconnect()}});observer.observe(host,{childList:true,subtree:true});const timeout=setTimeout(()=>!disposed&&setState("slow"),7000);void loadTradingView().then(()=>{if(disposed||!window.TradingView?.widget)return;widgetRef.current=new window.TradingView.widget({autosize:true,container_id:"bitvora-copy-btc-chart",symbol:"BINANCE:BTCUSDT",interval,studies,timezone:"exchange",theme:"dark",backgroundColor:"rgba(7, 7, 18, 1)",gridColor:"rgba(130, 116, 240, 0.08)",style:"1",locale:"en",withdateranges:false,hide_side_toolbar:true,hide_top_toolbar:true,hide_legend:true,hide_volume:true,allow_symbol_change:false,save_image:false,details:false,calendar:false,hotlist:false})}).catch(()=>!disposed&&setState("unavailable"));return()=>{disposed=true;clearTimeout(timeout);observer.disconnect();try{widgetRef.current?.remove?.()}catch{}widgetRef.current=null;if(host.isConnected)host.replaceChildren()}},[attempt,interval,studies]);
  const toggleStudy=(study:string)=>setStudies(current=>current.includes(study)?current.filter(item=>item!==study):[...current,study]),retry=useCallback(()=>setAttempt(value=>value+1),[]);
  return <section className="copy-btc-chart" aria-label="BTC/USDT live candlestick chart"><div className="copy-btc-chart-head"><strong>BTC/USDT</strong></div><div className="copy-btc-chart-controls" aria-label="Chart controls">{intervals.map(item=><button className={interval===item.value?"active":""} aria-pressed={interval===item.value} onClick={()=>{setIntervalValue(item.value);setIndicatorOpen(false)}} key={item.value}>{item.label}</button>)}<button className={indicatorOpen||studies.length?"active":""} aria-expanded={indicatorOpen} onClick={()=>setIndicatorOpen(value=>!value)}>Indicator{studies.length?` (${studies.length})`:""}</button>{indicatorOpen&&<div className="copy-btc-indicator-menu">{indicators.map(item=><button className={studies.includes(item.value)?"selected":""} aria-pressed={studies.includes(item.value)} onClick={()=>toggleStudy(item.value)} key={item.value}><span>{item.label}</span><i aria-hidden="true"/></button>)}</div>}</div><div className={`copy-btc-chart-host ${state==="ready"?"ready":""}`} id="bitvora-copy-btc-chart" ref={hostRef}/>{state!=="ready"&&<div className="copy-chart-skeleton" aria-hidden="true"><i/><i/><i/><i/><i/><span/></div>}{state==="loading"&&<span className="copy-chart-loading" role="status">Loading live chart</span>}{(state==="slow"||state==="unavailable")&&<div className="copy-chart-fallback" role="status"><strong>{state==="slow"?"Live chart is taking longer than expected.":"Live chart is temporarily unavailable."}</strong><div><button onClick={retry}>Retry</button><a href="https://www.tradingview.com/chart/?symbol=BINANCE%3ABTCUSDT" target="_blank" rel="noreferrer">Open simplified chart</a></div></div>}</section>
}
export const TradingViewCompactChart=memo(CompactChart);
