"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, Search } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import type { WalletTransactionType } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { PageHeader } from "./ui";

const filters:[string,WalletTransactionType|null][]=[["All",null],["Deposits","SPOT_DEPOSIT"],["Referral","SPOT_REFERRAL_INCOME"],["Level","SPOT_LEVEL_INCOME"],["Salary","SPOT_SALARY_INCOME"],["Rewards","SPOT_REWARD_INCOME"],["Spot → Future","SPOT_TO_FUTURE_TRANSFER"],["Future → Spot","FUTURE_TO_SPOT_TRANSFER"],["Early fees","FUTURE_EARLY_TRANSFER_FEE"],["AI Profit","AI_TRADE_PROFIT_CREDITED"]],PAGE_SIZE=6;
const localDate=(timestamp:number,timeZone:string)=>new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(timestamp));

export function WalletHistoryModule(){
  const{store}=useWalletStore(),[filter,setFilter]=useState<WalletTransactionType|null>(null),[query,setQuery]=useState(""),[date,setDate]=useState(""),[page,setPage]=useState(1),[timeZone,setTimeZone]=useState("UTC");
  useEffect(()=>{void fetch("/api/account/state",{cache:"no-store"}).then(response=>response.json()).then(value=>setTimeZone(value.userTimeZone??"UTC"))},[]);
  const filtered=useMemo(()=>store.transactions.filter(item=>(!filter||item.type===filter)&&(!query||`${item.title} ${item.wallet} ${item.reference} ${item.type}`.toLowerCase().includes(query.toLowerCase()))&&(!date||localDate(item.timestamp,timeZone)===date)),[store.transactions,filter,query,date,timeZone]),pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),safe=Math.min(page,pages),visible=filtered.slice((safe-1)*PAGE_SIZE,safe*PAGE_SIZE);
  return <div className="wallet-history-module"><PageHeader eyebrow="Wallet activity" title="Transaction History"/><div className="wallet-history-controls"><label><Search size={16}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search transactions"/></label><label><CalendarDays size={15}/><input type="date" value={date} onChange={event=>{setDate(event.target.value);setPage(1)}}/></label></div><div className="wallet-history-filters">{filters.map(([label,type])=><button className={filter===type?"active":""} onClick={()=>{setFilter(type);setPage(1)}} key={label}>{label}</button>)}</div>{visible.length?<div className="wallet-history-list">{visible.map(item=>{const ai=item.aiTradeDetails;return <article key={item.id}><span className="wallet-tx-icon">{item.amount>=0?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div><div><strong>{item.title}</strong><b>{item.type}</b></div><p>{store.wallets[item.wallet].name} · {ai?`${ai.pair} · ${ai.direction==="CALL"?"BUY":"SELL"} · ${ai.source}`:item.reference}</p><small>{new Intl.DateTimeFormat("en-US",{timeZone,dateStyle:"medium",timeStyle:"short"}).format(new Date(item.timestamp))}</small></div><aside><strong className={item.amount>=0?"positive":"negative"}>{item.amount>=0?"+":""}{formatCurrency(item.amount)}</strong><span>{item.status}</span></aside></article>})}</div>:<div className="wallet-history-empty"><Search size={22}/><h3>No transactions found</h3><p>Try another filter, search term, or date.</p></div>}<nav className="wallet-history-pagination"><button disabled={safe===1} onClick={()=>setPage(value=>Math.max(1,value-1))}><ChevronLeft size={15}/>Previous</button><span>Page {safe} of {pages} · {filtered.length} records</span><button disabled={safe===pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>Next<ChevronRight size={15}/></button></nav></div>;
}
