"use client";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { Check, Copy, RefreshCw, WalletCards } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { creditNowPaymentsDeposit, type WalletTransaction } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { isFinalDepositStatus, NOWPAYMENTS_NETWORKS, type NowPaymentsNetwork } from "@/lib/nowpayments/config";
import { readDepositRecords, upsertDepositRecord, writeDepositRecords, type DemoDepositRecord } from "@/lib/nowpayments/deposit-types";
import { PageHeader } from "./ui";
import { WalletNotices, type WalletNotice } from "./wallet-ui";

type ProviderConfig={enabled:boolean;mock:boolean;minimum:number|null};
type StatusResponse=DemoDepositRecord&{credit:null|{providerPaymentId:string;orderId:string;network:string;amount:number;txHash:string|null;timestamp:number}};
const statusText=(status:DemoDepositRecord["paymentStatus"])=>status==="PARTIALLY_PAID"?"Partial payment received":status.replaceAll("_"," ");
const remaining=(expiresAt:number|null,now:number)=>{if(!expiresAt)return null;const seconds=Math.max(0,Math.floor((expiresAt-now)/1000));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};

export function WalletDepositModule(){const{store,update}=useWalletStore(),[network,setNetwork]=useState<NowPaymentsNetwork>("USDT_TRC20"),[amount,setAmount]=useState(""),[config,setConfig]=useState<ProviderConfig>({enabled:false,mock:false,minimum:null}),[records,setRecords]=useState<DemoDepositRecord[]>([]),[activeId,setActiveId]=useState<string|null>(null),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[loading,setLoading]=useState(false),[notices,setNotices]=useState<WalletNotice[]>([]),[now,setNow]=useState(Date.now()),noticeId=useRef(0),idempotencyKey=useRef<string|null>(null),spot=store.wallets.spot,active=records.find(item=>item.id===activeId)??records[0]??null;
  const notify=useCallback((title:string,text:string)=>{const id=++noticeId.current;setNotices(current=>[...current,{id,title,text}]);setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),4000)},[]);
  const persist=useCallback((record:DemoDepositRecord)=>setRecords(current=>{const next=upsertDepositRecord(current,record);writeDepositRecords(next);return next}),[]);
  useEffect(()=>{const loaded=readDepositRecords();setRecords(loaded);setActiveId(loaded[0]?.id??null)},[]);
  useEffect(()=>{fetch(`/api/deposits/nowpayments/config?network=${network}`,{cache:"no-store"}).then(response=>response.json()).then(value=>setConfig(value as ProviderConfig)).catch(()=>setConfig({enabled:false,mock:false,minimum:null}))},[network]);
  useEffect(()=>{if(!active?.payAddress){setQr("");return}QRCode.toDataURL(active.payAddress,{width:220,margin:1,errorCorrectionLevel:"M"}).then(setQr).catch(()=>setQr(""))},[active?.payAddress]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const reconcile=useCallback((record:StatusResponse)=>{if(record.credit){update(current=>creditNowPaymentsDeposit(current,record.credit!));if(record.creditStatus==="CREDITED")notify(record.mock?"Mock Deposit Completed":"Deposit Completed",`${formatCurrency(record.amountCredited)} credited to Spot Wallet${record.mock?" in development mock mode":""}.`)}persist(record)},[notify,persist,update]);
  const refresh=useCallback(async(record=active,mockStatus?:string)=>{if(!record||loading)return;setLoading(true);try{const query=mockStatus?`?mockStatus=${mockStatus}`:"",response=await fetch(`/api/deposits/nowpayments/${encodeURIComponent(record.providerPaymentId)}${query}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to refresh deposit.");reconcile(payload as StatusResponse)}catch(error){notify("Status Refresh Failed",error instanceof Error?error.message:"Unable to refresh deposit.")}finally{setLoading(false)}},[active,loading,notify,reconcile]);
  useEffect(()=>{if(!active||isFinalDepositStatus(active.paymentStatus))return;const timer=setInterval(()=>void refresh(active),20_000);return()=>clearInterval(timer)},[active,refresh]);
  const create=async()=>{if(loading)return;setLoading(true);idempotencyKey.current??=crypto.randomUUID();try{const response=await fetch("/api/deposits/nowpayments/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount,network,idempotencyKey:idempotencyKey.current})}),payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to create deposit.");const record=payload as DemoDepositRecord;persist(record);setActiveId(record.id);idempotencyKey.current=null;notify(config.mock?"Mock Payment Created":"Payment Created","Use only the selected USDT network and exact payment details.")}catch(error){notify("Deposit Not Created",error instanceof Error?error.message:"Unable to create deposit.")}finally{setLoading(false)}};
  const copy=async()=>{if(!active)return;await navigator.clipboard?.writeText(active.payAddress);setCopied(true);notify("Address Copied",`${NOWPAYMENTS_NETWORKS[active.network].label} address copied.`);setTimeout(()=>setCopied(false),1800)};
  return <div className="wallet-operation">
    <PageHeader eyebrow="Wallet funding" title="Deposit"/>
    <WalletNotices items={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
    <section className="wallet-form-card"><div className="wallet-deposit-head"><span><WalletCards size={19}/></span><div><p>Deposit to</p><strong>Spot Wallet {config.mock?"· DEVELOPMENT MOCK":""}</strong></div><b>{formatCurrency(spot.balance)}</b></div><div className="wallet-network-tabs">{(Object.keys(NOWPAYMENTS_NETWORKS) as NowPaymentsNetwork[]).map(item=><button className={network===item?"active":""} onClick={()=>setNetwork(item)} key={item}>{NOWPAYMENTS_NETWORKS[item].label}</button>)}</div><label className="wallet-amount-field"><span>Deposit amount (USD)</span><div><b>$</b><input type="number" min={config.minimum??0} step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/></div><small>{config.minimum===null?"Minimum unavailable":`Minimum deposit: ${formatCurrency(config.minimum)}`}</small></label><button className="wallet-primary-button" disabled={!config.enabled||loading} onClick={create}>{loading?"Processing…":"Continue / Create Deposit"}</button></section>
    {active&&<section className="wallet-form-card"><div className="wallet-deposit-head"><span><WalletCards size={19}/></span><div><p>Payment ID · {active.providerPaymentId}</p><strong>{NOWPAYMENTS_NETWORKS[active.network].label} · {active.mock?"MOCK · NO REAL FUNDS":"NOWPayments"}</strong></div><b className={`copy-status ${active.paymentStatus.toLowerCase()}`}>{statusText(active.paymentStatus)}</b></div><div className="wallet-qr">{qr?<Image src={qr} width={180} height={180} unoptimized alt="Deposit address QR code"/>:<div/>}<span>Pay exactly {active.payAmount} {active.payCurrency.toUpperCase()}</span>{active.expiresAt&&<small>Expires in {remaining(active.expiresAt,now)}</small>}</div><div className="wallet-address"><span>{active.payAddress}</span><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="wallet-transfer-summary"><div><span>Requested</span><strong>{formatCurrency(active.requestedAmount)}</strong></div><div><span>Actually paid</span><strong>{active.actuallyPaid} {active.payCurrency.toUpperCase()}</strong></div><div><span>Credited</span><strong>{formatCurrency(active.amountCredited)}</strong></div><div><span>Order ID</span><strong>{active.orderId}</strong></div></div><button className="wallet-primary-button" disabled={loading||isFinalDepositStatus(active.paymentStatus)} onClick={()=>void refresh()}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh Status"}</button>{active.mock&&!isFinalDepositStatus(active.paymentStatus)&&<button className="secondary-button mt-3 w-full" onClick={()=>void refresh(active,"finished")}>Simulate Mock FINISHED</button>}</section>}
    <DepositHistory records={records} open={record=>setActiveId(record.id)}/>
  </div>}
function DepositHistory({records,open}:{records:DemoDepositRecord[];open:(record:DemoDepositRecord)=>void}){return <section><div className="wallet-section-heading"><h2>Deposit History</h2></div><div className="wallet-mini-history">{records.map(item=><div role="button" tabIndex={0} onClick={()=>open(item)} onKeyDown={event=>{if(event.key==="Enter")open(item)}} key={item.id}><span className={item.creditStatus==="CREDITED"?"positive":""}>{formatCurrency(item.requestedAmount)}</span><div><strong>{NOWPAYMENTS_NETWORKS[item.network].label} · {item.providerPaymentId}</strong><p>Paid {item.actuallyPaid} · Credited {formatCurrency(item.amountCredited)} · {item.txHash??"No transaction hash"}</p><p>{item.localDateTime??"—"} · {item.orderId}</p></div><b>{statusText(item.paymentStatus)}</b></div>)}</div></section>}
export function WalletMiniHistory({title,items}:{title:string;items:WalletTransaction[]}){return <section><div className="wallet-section-heading"><h2>{title}</h2></div><div className="wallet-mini-history">{items.map(item=><div key={item.id}><span className={item.amount>=0?"positive":"negative"}>{item.amount>=0?"+":""}{formatCurrency(item.amount)}</span><div><strong>{item.title}</strong><p>{item.reference} · {item.localDateTime??"—"}</p></div><b>{item.status}</b></div>)}</div></section>}
