"use client";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { Check, Copy, ExternalLink, RefreshCw, WalletCards } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { formatLocalDateTime } from "@/lib/date-time";
import type { WalletTransaction } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { isFinalDepositStatus, publicDepositStatus } from "@/lib/nowpayments/config";
import type { DemoDepositRecord } from "@/lib/nowpayments/deposit-types";
import { PageHeader } from "./ui";
import { WalletNotices, type WalletNotice } from "./wallet-ui";

type ProviderConfig={enabled:boolean;mock:boolean;minimum:number|null};
const displayStatus=(record:DemoDepositRecord)=>record.status??publicDepositStatus(record.paymentStatus);
const remaining=(expiresAt:number|null,now:number)=>{if(!expiresAt)return null;const seconds=Math.max(0,Math.floor((expiresAt-now)/1000));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};
const explorer=(hash:string)=>`https://bscscan.com/tx/${encodeURIComponent(hash)}`;
const localizeRecord=(record:DemoDepositRecord):DemoDepositRecord=>({...record,localDateTime:formatLocalDateTime(record.createdAt),updatedLocalDateTime:formatLocalDateTime(record.updatedAt),finishedLocalDateTime:record.finishedAt?formatLocalDateTime(record.finishedAt):null,expiresLocalDateTime:record.expiresAt?formatLocalDateTime(record.expiresAt):null});

export function WalletDepositModule(){
  const{store}=useWalletStore(),[amount,setAmount]=useState(""),[config,setConfig]=useState<ProviderConfig>({enabled:false,mock:false,minimum:null}),[records,setRecords]=useState<DemoDepositRecord[]>([]),[activeId,setActiveId]=useState<string|null>(null),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[loading,setLoading]=useState(false),[notices,setNotices]=useState<WalletNotice[]>([]),[now,setNow]=useState(Date.now()),noticeId=useRef(0),idempotencyKey=useRef<string|null>(null),spot=store.wallets.spot,active=records.find(item=>item.id===activeId)??records[0]??null;
  const notify=useCallback((title:string,text:string)=>{const id=++noticeId.current;setNotices(current=>[...current,{id,title,text}]);setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),4000)},[]);
  const persist=useCallback((record:DemoDepositRecord)=>setRecords(current=>[localizeRecord(record),...current.filter(item=>item.id!==record.id)].sort((a,b)=>b.createdAt-a.createdAt)),[]);
  useEffect(()=>{Promise.all([fetch("/api/deposits/nowpayments/config",{cache:"no-store"}).then(r=>r.json()),fetch("/api/deposits/nowpayments",{cache:"no-store"}).then(r=>r.json())]).then(([provider,history])=>{setConfig(provider as ProviderConfig);const loaded=((history.records??[]) as DemoDepositRecord[]).map(localizeRecord);setRecords(loaded);setActiveId(loaded[0]?.id??null)}).catch(()=>setConfig({enabled:false,mock:false,minimum:null}))},[]);
  useEffect(()=>{if(!active?.payAddress){setQr("");return}QRCode.toDataURL(active.payAddress,{width:220,margin:1,errorCorrectionLevel:"M"}).then(setQr).catch(()=>setQr(""))},[active?.payAddress]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const refresh=useCallback(async(record=active,mockStatus?:string)=>{if(!record||loading)return;setLoading(true);try{const response=await fetch(`/api/deposits/nowpayments/${encodeURIComponent(record.providerPaymentId)}${mockStatus?`?mockStatus=${mockStatus}`:""}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to refresh deposit.");persist(payload as DemoDepositRecord);if(displayStatus(payload)==="COMPLETED"){window.dispatchEvent(new CustomEvent("bitvora-wallet-updated"));notify("Deposit Completed",`${payload.amountCredited} USDT credited to Spot Wallet.`)}}catch(error){notify("Status Refresh Failed",error instanceof Error?error.message:"Unable to refresh deposit.")}finally{setLoading(false)}},[active,loading,notify,persist]);
  useEffect(()=>{if(!active||isFinalDepositStatus(active.paymentStatus))return;const timer=setInterval(()=>void refresh(active),20_000);return()=>clearInterval(timer)},[active,refresh]);
  const create=async()=>{if(loading)return;setLoading(true);idempotencyKey.current??=crypto.randomUUID();try{const response=await fetch("/api/deposits/nowpayments/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount,network:"USDT_BEP20",idempotencyKey:idempotencyKey.current})}),payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to create deposit.");persist(payload);setActiveId(payload.id);idempotencyKey.current=null;notify("Deposit Generated","Send only USDT on BEP20 to this address.")}catch(error){notify("Deposit Not Created",error instanceof Error?error.message:"Unable to create deposit.")}finally{setLoading(false)}};
  const copy=async()=>{if(!active)return;await navigator.clipboard?.writeText(active.payAddress);setCopied(true);notify("Address Copied","USDT BEP20 deposit address copied.");setTimeout(()=>setCopied(false),1800)};
  return <div className="wallet-operation"><PageHeader eyebrow="Wallet funding" title="Deposit"/><WalletNotices items={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
    <section className="wallet-form-card"><div className="wallet-deposit-head"><span><WalletCards size={19}/></span><div><p>Deposit to</p><strong>Spot Wallet</strong></div><b>{formatCurrency(spot.balance)}</b></div><div className="wallet-transfer-summary"><div><span>Coin</span><strong>USDT</strong></div><div><span>Network</span><strong>BEP20 (BNB Smart Chain)</strong></div></div><label className="wallet-amount-field"><span>Deposit amount (USDT)</span><div><b>₮</b><input type="number" min={config.minimum??0} step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/></div><small>{config.minimum===null?"Minimum unavailable":`Minimum deposit: ${config.minimum} USDT`}</small></label><button className="wallet-primary-button" disabled={!config.enabled||loading} onClick={create}>{loading?"Generating…":"Generate Deposit"}</button></section>
    {active&&<section className="wallet-form-card"><div className="wallet-deposit-head"><span><WalletCards size={19}/></span><div><p>Payment ID · {active.providerPaymentId}</p><strong>USDT · BEP20 (BNB Smart Chain)</strong></div><b className={`copy-status ${displayStatus(active).toLowerCase()}`}>{displayStatus(active)}</b></div><div className="wallet-qr">{qr?<Image src={qr} width={180} height={180} unoptimized alt="USDT BEP20 deposit QR code"/>:<div/>}<span>Pay exactly {active.payAmount} USDT</span>{active.expiresAt&&<small>Expires in {remaining(active.expiresAt,now)}</small>}</div><div className="wallet-address"><span>{active.payAddress}</span><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="wallet-transfer-summary"><div><span>Exact amount</span><strong>{active.payAmount} USDT</strong></div><div><span>Expiry time</span><strong>{active.expiresAt?active.expiresLocalDateTime??new Date(active.expiresAt).toLocaleString():"Provider controlled"}</strong></div><div><span>TX hash</span><strong>{active.txHash??"Pending"}</strong></div></div><button className="wallet-primary-button" disabled={loading||isFinalDepositStatus(active.paymentStatus)} onClick={()=>void refresh()}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh Status"}</button>{active.mock&&!isFinalDepositStatus(active.paymentStatus)&&<button className="secondary-button mt-3 w-full" onClick={()=>void refresh(active,"finished")}>Simulate Mock Completed</button>}</section>}
    <DepositHistory records={records} open={record=>setActiveId(record.id)}/></div>;
}
function DepositHistory({records,open}:{records:DemoDepositRecord[];open:(record:DemoDepositRecord)=>void}){return <section><div className="wallet-section-heading"><h2>Deposit History</h2></div><div className="wallet-mini-history">{records.map(item=><div role="button" tabIndex={0} onClick={()=>open(item)} onKeyDown={event=>{if(event.key==="Enter")open(item)}} key={item.id}><span className={displayStatus(item)==="COMPLETED"?"positive":""}>{item.payAmount} USDT</span><div><strong>USDT · BEP20</strong><p>{displayStatus(item)} · {item.txHash??"No transaction hash"}</p><p>{item.localDateTime??new Date(item.createdAt).toLocaleString()}</p>{item.txHash&&<a href={explorer(item.txHash)} target="_blank" rel="noreferrer" onClick={event=>event.stopPropagation()}>Explorer <ExternalLink size={12}/></a>}</div><b>{displayStatus(item)}</b></div>)}</div></section>}
export function WalletMiniHistory({title,items}:{title:string;items:WalletTransaction[]}){return <section><div className="wallet-section-heading"><h2>{title}</h2></div><div className="wallet-mini-history">{items.map(item=><div key={item.id}><span className={item.amount>=0?"positive":"negative"}>{item.amount>=0?"+":""}{formatCurrency(item.amount)}</span><div><strong>{item.title}</strong><p>{item.reference} · {item.localDateTime??"—"}</p></div><b>{item.status}</b></div>)}</div></section>}
