"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { Check, Copy, ExternalLink, RefreshCw, WalletCards } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { formatLocalDateTime } from "@/lib/date-time";
import type { WalletTransaction } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { MINIMUM_DEPOSIT_USDT, isFinalDepositStatus, publicDepositStatus } from "@/lib/nowpayments/config";
import type { DemoDepositRecord } from "@/lib/nowpayments/deposit-types";
import { PageHeader } from "./ui";
import { WalletNotices, type WalletNotice } from "./wallet-ui";

type ProviderConfig={enabled:boolean;mock:boolean;minimum:number|null};
const displayStatus=(record:DemoDepositRecord)=>record.walletCreditCompleted||record.creditStatus==="CREDITED"?"Deposit Credited":record.creditStatus==="MANUAL_REVIEW"?"Needs Review":record.paymentStatus==="WAITING"?"Waiting for Payment":["CONFIRMING","CONFIRMED","SENDING"].includes(record.paymentStatus)?"Confirming":record.paymentStatus==="EXPIRED"?"Expired":record.paymentStatus==="FAILED"||record.paymentStatus==="REFUNDED"?"Failed":publicDepositStatus(record.paymentStatus);
const remaining=(expiresAt:number|null,now:number)=>{if(!expiresAt)return null;const seconds=Math.max(0,Math.floor((expiresAt-now)/1000));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`};
const explorer=(hash:string)=>`https://bscscan.com/tx/${encodeURIComponent(hash)}`;
const localizeRecord=(record:DemoDepositRecord):DemoDepositRecord=>({...record,localDateTime:formatLocalDateTime(record.createdAt),updatedLocalDateTime:formatLocalDateTime(record.updatedAt),finishedLocalDateTime:record.finishedAt?formatLocalDateTime(record.finishedAt):null,expiresLocalDateTime:record.expiresAt?formatLocalDateTime(record.expiresAt):null});
const fetchJson=async(url:string,init:RequestInit={},timeoutMs=15_000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal}),payload=await response.json().catch(()=>({error:`Request failed (${response.status}).`}));if(!response.ok)throw new Error(typeof payload?.error==="string"?payload.error:`Request failed (${response.status}).`);return payload}finally{clearTimeout(timer)}};

export function WalletDepositModule(){
  const router=useRouter(),{store}=useWalletStore(),[amount,setAmount]=useState(""),[config,setConfig]=useState<ProviderConfig>({enabled:false,mock:false,minimum:null}),[records,setRecords]=useState<DemoDepositRecord[]>([]),[activeId,setActiveId]=useState<string|null>(null),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[loading,setLoading]=useState(false),[notices,setNotices]=useState<WalletNotice[]>([]),[now,setNow]=useState(Date.now()),[success,setSuccess]=useState<{paymentId:string;amount:number}|null>(null),[redirectSeconds,setRedirectSeconds]=useState(5),noticeId=useRef(0),idempotencyKey=useRef<string|null>(null),successPaymentId=useRef<string|null>(null),spot=store.wallets.spot,active=records.find(item=>item.id===activeId)??records[0]??null;
  const notify=useCallback((title:string,text:string)=>{const id=++noticeId.current;setNotices(current=>[...current,{id,title,text}]);setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),4000)},[]);
  const persist=useCallback((record:DemoDepositRecord)=>setRecords(current=>[localizeRecord(record),...current.filter(item=>item.id!==record.id)].sort((a,b)=>b.createdAt-a.createdAt)),[]);
  const showCredited=useCallback((record:DemoDepositRecord)=>{if(record.walletCreditCompleted!==true||successPaymentId.current===record.providerPaymentId)return;successPaymentId.current=record.providerPaymentId;setRedirectSeconds(5);setSuccess({paymentId:record.providerPaymentId,amount:record.amountCredited});window.dispatchEvent(new CustomEvent("bitvora-wallet-updated"))},[]);
  useEffect(()=>{Promise.all([fetchJson("/api/deposits/nowpayments/config",{cache:"no-store"}),fetchJson("/api/deposits/nowpayments",{cache:"no-store"})]).then(([provider,history])=>{setConfig(provider as ProviderConfig);if(!provider.enabled)notify("Deposits Unavailable","Deposits are disabled by server configuration.");const loaded=((history.records??[]) as DemoDepositRecord[]).map(localizeRecord);setRecords(loaded);setActiveId(loaded[0]?.id??null)}).catch(error=>{setConfig({enabled:false,mock:false,minimum:null});notify("Deposit Service Unavailable",error instanceof Error?error.message:"Unable to load deposit configuration.")})},[notify]);
  useEffect(()=>{if(!active?.payAddress){setQr("");return}QRCode.toDataURL(active.payAddress,{width:220,margin:1,errorCorrectionLevel:"M"}).then(setQr).catch(()=>setQr(""))},[active?.payAddress]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!success)return;const interval=setInterval(()=>setRedirectSeconds(value=>Math.max(0,value-1)),1000),redirect=setTimeout(()=>router.push("/home"),5000);return()=>{clearInterval(interval);clearTimeout(redirect)}},[router,success]);
  const refresh=useCallback(async(record=active,mockStatus?:string)=>{if(!record||loading)return;setLoading(true);try{const payload=await fetchJson(`/api/deposits/nowpayments/${encodeURIComponent(record.providerPaymentId)}${mockStatus?`?mockStatus=${mockStatus}`:""}`,{cache:"no-store"}) as DemoDepositRecord;persist(payload);showCredited(payload);if(payload.walletCreditCompleted)notify("Deposit Credited",`${payload.amountCredited} USDT credited to your Spot Wallet.`)}catch(error){notify("Status Refresh Failed",error instanceof Error?error.message:"Unable to refresh deposit.")}finally{setLoading(false)}},[active,loading,notify,persist,showCredited]);
  useEffect(()=>{if(!active||isFinalDepositStatus(active.paymentStatus))return;const timer=setInterval(()=>void refresh(active),20_000);return()=>clearInterval(timer)},[active,refresh]);
  const create=async()=>{if(loading)return;setLoading(true);idempotencyKey.current??=crypto.randomUUID();try{const payload=await fetchJson("/api/deposits/nowpayments/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount,network:"USDT_BEP20",idempotencyKey:idempotencyKey.current})}) as DemoDepositRecord;persist(payload);setActiveId(payload.id);idempotencyKey.current=null;showCredited(payload);notify(payload.walletCreditCompleted?"Deposit Credited":"Deposit Generated",payload.walletCreditCompleted?`${payload.amountCredited} USDT credited to your Spot Wallet.`:"Send only USDT on BEP20 to this address.")}catch(error){notify("Deposit Not Created",error instanceof Error?error.message:"Unable to create deposit.")}finally{setLoading(false)}};
  const copy=async()=>{if(!active)return;await navigator.clipboard?.writeText(active.payAddress);setCopied(true);notify("Address Copied","USDT BEP20 deposit address copied.");setTimeout(()=>setCopied(false),1800)};
  return <div className="wallet-operation deposit-operation"><PageHeader eyebrow="Wallet funding" title="Deposit"/><WalletNotices items={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
    {success&&<section className="deposit-success" role="status"><strong>Congratulations!</strong><p>Your deposit has been successfully credited.</p><b>{success.amount.toFixed(2)} USDT has been credited to your Spot Wallet.</b><small>Redirecting to Dashboard in {redirectSeconds} seconds…</small></section>}
    <section className="wallet-form-card"><div className="wallet-deposit-head"><span><WalletCards size={19}/></span><div><p>Deposit to</p><strong>Spot Wallet</strong></div><b>{formatCurrency(spot.balance)}</b></div><div className="wallet-transfer-summary"><div><span>Coin</span><strong>USDT</strong></div><div><span>Network</span><strong>BEP20 (BNB Smart Chain)</strong></div></div><label className="wallet-amount-field"><span>Deposit amount (USDT)</span><div><b>$</b><input type="number" min={MINIMUM_DEPOSIT_USDT} step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="1"/></div><small>Minimum deposit: $1.00</small></label><button className="wallet-primary-button" disabled={!config.enabled||loading||!Number.isFinite(Number(amount))||Number(amount)<MINIMUM_DEPOSIT_USDT} onClick={create}>{loading?"Generating…":"Generate Deposit"}</button></section>
    {active&&<section className="wallet-form-card deposit-result-card"><div className="wallet-deposit-head deposit-result-head"><span><WalletCards size={19}/></span><div><p>Payment ID · {active.providerPaymentId}</p><strong>USDT · BEP20 (BNB Smart Chain)</strong></div><b className="copy-status">{displayStatus(active)}</b></div><div className="wallet-qr">{qr?<Image src={qr} width={260} height={260} unoptimized alt="USDT BEP20 deposit QR code"/>:<div/>}<span>Pay exactly {active.requestedAmount} USDT</span>{active.expiresAt&&<small>Expires in {remaining(active.expiresAt,now)}</small>}</div><div className="wallet-address"><span>{active.payAddress}</span><button onClick={copy} aria-label="Copy deposit address">{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="wallet-transfer-summary deposit-result-summary"><div><span>Requested amount</span><strong>{active.requestedAmount} USDT</strong></div><div><span>Received amount</span><strong>{active.actuallyPaid>0?`${active.actuallyPaid} USDT`:"Pending"}</strong></div><div><span>Credited amount</span><strong>{active.amountCredited>0?`${active.amountCredited} USDT`:"Pending"}</strong></div><div><span>Expiry time</span><strong>{active.expiresAt?active.expiresLocalDateTime??new Date(active.expiresAt).toLocaleString():"Provider controlled"}</strong></div><div><span>TX hash</span><strong className="deposit-tx-hash">{active.txHash??"Pending"}</strong></div></div><button className="wallet-primary-button" disabled={loading||active.walletCreditCompleted||isFinalDepositStatus(active.paymentStatus)} onClick={()=>void refresh()}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh Status"}</button>{active.mock&&!active.walletCreditCompleted&&!isFinalDepositStatus(active.paymentStatus)&&<button className="secondary-button mt-3 w-full" onClick={()=>void refresh(active,"finished")}>Simulate Mock Completed</button>}</section>}
    <DepositHistory records={records} open={record=>setActiveId(record.id)}/></div>;
}
function DepositHistory({records,open}:{records:DemoDepositRecord[];open:(record:DemoDepositRecord)=>void}){return <section><div className="wallet-section-heading"><h2>Deposit History</h2></div><div className="wallet-mini-history deposit-history">{records.map(item=><div role="button" tabIndex={0} onClick={()=>open(item)} onKeyDown={event=>{if(event.key==="Enter")open(item)}} key={item.id}><span className={item.walletCreditCompleted?"positive":""}>{item.requestedAmount} USDT</span><div><strong>USDT · BEP20</strong><p>Requested {item.requestedAmount} · Received {item.actuallyPaid||"Pending"} · Credited {item.amountCredited||"Pending"}</p><p>{item.localDateTime??new Date(item.createdAt).toLocaleString()} · Payment ID {item.providerPaymentId}</p>{item.txHash&&<a href={explorer(item.txHash)} target="_blank" rel="noreferrer" onClick={event=>event.stopPropagation()}>Explorer <ExternalLink size={12}/></a>}</div><b>{displayStatus(item)}</b></div>)}</div></section>}
export function WalletMiniHistory({title,items}:{title:string;items:WalletTransaction[]}){return <section><div className="wallet-section-heading"><h2>{title}</h2></div><div className="wallet-mini-history">{items.map(item=>{const deposit=item.type==="NOWPAYMENTS_DEPOSIT";return <div key={item.id}><span className={item.amount>=0?"positive":"negative"}>{item.amount>=0?"+":""}{formatCurrency(item.amount)}</span><div><strong>{deposit?"Crypto Deposit":item.title}</strong><p>{deposit?"USDT · BEP20":item.reference} · {item.localDateTime??"—"}</p></div><b>{item.status}</b></div>})}</div></section>}
