"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ShieldAlert, X } from "lucide-react";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { formatCurrency } from "@/lib/currency";
import { FIXED_WITHDRAWAL_FEE, MINIMUM_WITHDRAWAL_AMOUNT, type WalletStore } from "@/lib/wallet-data";
import { withdrawalKycMessage, type KycStatus } from "@/lib/kyc/kyc-types";
import { PageHeader } from "./ui";
import { WalletMiniHistory } from "./wallet-deposit-module";
import { WalletNotices, WalletPortal, WalletSuccess, type WalletNotice } from "./wallet-ui";

export function WalletWithdrawModule(){
  const{store,replace}=useWalletStore(),network="BEP20" as const,[address,setAddress]=useState(""),[amount,setAmount]=useState(""),[confirm,setConfirm]=useState(false),[success,setSuccess]=useState(false),[notices,setNotices]=useState<WalletNotice[]>([]),[completedAmount,setCompletedAmount]=useState(0),[kycStatus,setKycStatus]=useState<KycStatus>("NOT_SUBMITTED"),noticeId=useRef(0),idempotencyKey=useRef<string|null>(null),wallet=store.wallets.spot,numeric=Number(amount),fee=FIXED_WITHDRAWAL_FEE,netAmount=Math.max(0,numeric-fee),valid=address.trim().length>=8&&numeric>=MINIMUM_WITHDRAWAL_AMOUNT&&numeric<=wallet.balance;
  useEffect(()=>{fetch("/api/kyc/me",{cache:"no-store"}).then(r=>r.json()).then(value=>setKycStatus(value.status??"NOT_SUBMITTED"))},[]);
  const notify=(title:string,text:string)=>{const id=++noticeId.current;setNotices(current=>[...current,{id,title,text}]);setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),3500)};
  const review=()=>{if(numeric<MINIMUM_WITHDRAWAL_AMOUNT){notify("Withdrawal unavailable","Minimum withdrawal amount is $10.");return}if(!valid){notify("Withdrawal unavailable",numeric>wallet.balance?"Insufficient balance.":"Enter a valid address and amount.");return}idempotencyKey.current=crypto.randomUUID();setConfirm(true)};
  const complete=async()=>{const key=idempotencyKey.current??crypto.randomUUID(),response=await fetch("/api/withdrawals/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:numeric,network,address,idempotencyKey:key})}),value=await response.json();if(!response.ok){notify("Withdrawal unavailable",value.error??"Withdrawal request failed.");setConfirm(false);return}replace(value.wallet as WalletStore);window.dispatchEvent(new CustomEvent("bitvora-wallet-updated"));setCompletedAmount(numeric);setConfirm(false);setSuccess(true);setAmount("");setAddress("");idempotencyKey.current=null};
  return <div className="wallet-operation">
    <PageHeader eyebrow="Blockchain withdrawal" title="Withdraw"/><WalletNotices items={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/>
    <section className="wallet-warning-card"><ShieldAlert size={19}/><div><strong>KYC status · {kycStatus.replaceAll("_"," ")}</strong><p>{withdrawalKycMessage(kycStatus)}</p></div></section>
    <section className="wallet-form-card"><label className="wallet-select-field"><span>From wallet</span><select value="spot" disabled><option>Spot Wallet · {formatCurrency(wallet.balance)}</option></select></label><div className="wallet-network-tabs"><button className="active">USDT · BEP20 (BNB Smart Chain)</button></div><label className="wallet-text-field"><span>Withdrawal address</span><input value={address} onChange={event=>setAddress(event.target.value)} placeholder="Enter BEP20 wallet address"/></label><label className="wallet-amount-field"><span>Amount (USDT)</span><div><b>$</b><input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/><button onClick={()=>setAmount(String(wallet.balance))}>MAX</button></div><small>Available: {formatCurrency(wallet.balance)}</small></label><div className="wallet-transfer-summary"><div><span>Minimum Withdrawal</span><strong>$10</strong></div><div><span>Withdrawal Fee</span><strong>$5 (Fixed)</strong></div><div><span>Net Amount to Receive</span><strong>{formatCurrency(netAmount)}</strong></div></div><button className="wallet-primary-button" disabled={kycStatus!=="APPROVED"} onClick={review}><ArrowUpRight size={17}/>Review Withdrawal</button></section>
    <WalletMiniHistory title="Withdrawal History" items={store.transactions.filter(item=>item.type==="SPOT_WITHDRAWAL").slice(0,5)}/>
    {confirm&&<WalletPortal><div className="wallet-modal-backdrop"><div className="wallet-confirm-modal"><button className="wallet-modal-x" onClick={()=>setConfirm(false)}><X size={16}/></button><span><ArrowUpRight size={22}/></span><small>Confirm Withdrawal</small><h2>{formatCurrency(numeric)}</h2><p className="wallet-confirm-address">{address}</p><dl><dt>Coin</dt><dd>USDT</dd><dt>Network</dt><dd>BEP20 (BNB Smart Chain)</dd><dt>Requested Amount</dt><dd>{formatCurrency(numeric)}</dd><dt>Fixed Fee</dt><dd>{formatCurrency(fee)}</dd><dt>Net Amount to Receive</dt><dd>{formatCurrency(netAmount)}</dd></dl><div className="wallet-modal-actions"><button onClick={()=>setConfirm(false)}>Cancel</button><button onClick={()=>void complete()}>Confirm Request</button></div></div></div></WalletPortal>}
    {success&&<WalletSuccess title="Withdrawal Requested" text={`${formatCurrency(completedAmount)} USDT is pending processing on BEP20.`} onDone={()=>setSuccess(false)}/>}</div>
}
