"use client";
import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, LockKeyhole, Send, UnlockKeyhole, WalletCards } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { getFutureMetrics } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { PageHeader } from "./ui";

const signed=(value:number)=>`${value>=0?"+":""}${formatCurrency(value)}`;
export function WalletModule(){const{store,ready}=useWalletStore(),spot=store.wallets.spot,future=store.wallets.future,metrics=getFutureMetrics(store),total=spot.balance+future.balance,income=store.spotIncome;return <div className="wallet-module"><PageHeader eyebrow="Portfolio" title="Wallet overview"/>
  <section className="wallet-overview"><div className="wallet-total"><span>Total Assets</span><h2>{formatCurrency(total)}</h2><p>Spot and Future Wallet</p><div className="wallet-overview-actions"><Link href="/deposit"><ArrowDownLeft size={17}/>Deposit</Link><Link href="/withdraw"><ArrowUpRight size={17}/>Withdraw</Link><Link href="/transfer"><Send size={17}/>Transfer</Link></div></div><div className="wallet-two-count"><strong>2</strong><span>primary wallets</span></div></section>
  <div className="wallet-section-heading"><h2>Primary Wallets</h2><Link href="/history">All activity <ChevronRight size={14}/></Link></div><div className={ready?"wallet-primary-grid":"wallet-primary-grid loading"}>
    <article className="wallet-account-card spot-wallet-card"><div className="wallet-account-top"><span style={{color:spot.color}}><WalletCards size={18}/></span><div><h3>Spot Wallet</h3><p>Main available balance</p></div></div><strong className="wallet-account-balance">{formatCurrency(spot.balance)}</strong><div className="spot-income-grid"><div><span>Deposit</span><b>{formatCurrency(income.deposit)}</b></div><div><span>Referral income</span><b>{formatCurrency(income.referralIncome)}</b></div><div><span>Level income</span><b>{formatCurrency(income.levelIncome)}</b></div><div><span>Salary income</span><b>{formatCurrency(income.salaryIncome)}</b></div><div><span>Reward income</span><b>{formatCurrency(income.rewardIncome)}</b></div><div><span>Future Wallet transfer</span><b>{formatCurrency(income.futureWalletTransfer)}</b></div><div><span>Other income</span><b>{formatCurrency(income.otherIncome)}</b></div></div></article>
    <article className="wallet-account-card future-wallet-card"><div className="wallet-account-top"><span style={{color:future.color}}><WalletCards size={18}/></span><div><h3>Future Wallet</h3><p>AI Copy Trading only</p></div><b className={metrics.futureToSpotUnlocked?"unlocked":"locked"}>{metrics.futureToSpotUnlocked?<UnlockKeyhole size={11}/>:<LockKeyhole size={11}/>} {metrics.futureToSpotUnlocked?"Unlocked":"Early transfer"}</b></div><strong className="wallet-account-balance">{formatCurrency(future.balance)}</strong><div className="future-wallet-stats"><div><span>Principal transferred</span><b>{formatCurrency(metrics.totalFuturePrincipal)}</b></div><div><span>Completed AI profit</span><b>{signed(metrics.totalCompletedTradingProfit)}</b></div><div><span>Required profit</span><b>{formatCurrency(metrics.requiredProfitForUnlock)}</b></div><div><span>Remaining profit</span><b>{formatCurrency(metrics.remainingProfitForUnlock)}</b></div><div><span>Transferable balance</span><b>{formatCurrency(metrics.transferableBalance)}</b></div></div><div className="future-unlock-progress"><div><span>{metrics.futureToSpotUnlocked?"No early-transfer deduction":"20% early-transfer deduction"}</span><b>{metrics.unlockProgressPercentage.toFixed(2)}%</b></div><i><span style={{width:`${metrics.unlockProgressPercentage}%`}}/></i></div></article>
  </div>
  <div className="wallet-section-heading"><h2>Recent Transactions</h2><Link href="/history">View all <ChevronRight size={14}/></Link></div><div className="wallet-recent-list">{store.transactions.slice(0,5).map(item=><div className="wallet-transaction-row" key={item.id}><span className="wallet-tx-icon">{item.amount>=0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</span><div><strong>{item.title}</strong><p>{store.wallets[item.wallet].name} · {new Date(item.timestamp).toLocaleString()}</p></div><div><strong className={item.amount>=0?"positive":"negative"}>{signed(item.amount)}</strong><span>{item.status}</span></div></div>)}</div></div>}
