"use client";
import { useRef, useState } from "react";
import { ArrowRight, ChevronDown, Repeat2, ShieldAlert, ShieldCheck, X } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { getFutureMetrics, getTransferQuote, money, transferBetweenWallets, type WalletId } from "@/lib/wallet-data";
import { useWalletStore } from "@/hooks/use-wallet-store";
import { PageHeader } from "./ui";
import { WalletNotices, WalletPortal, WalletSuccess, type WalletNotice } from "./wallet-ui";

export function WalletTransferModule(){const{store,update}=useWalletStore();const[from,setFrom]=useState<WalletId>("spot"),[amount,setAmount]=useState(""),[confirm,setConfirm]=useState(false),[successText,setSuccessText]=useState(""),[notices,setNotices]=useState<WalletNotice[]>([]);const noticeId=useRef(0),requestKey=useRef(""),processing=useRef(false),to:WalletId=from==="spot"?"future":"spot",source=store.wallets[from],target=store.wallets[to],metrics=getFutureMetrics(store),numeric=money(Number(amount)),quote=getTransferQuote(store,from,numeric),valid=numeric>0&&numeric<=source.balance;const notify=(title:string,text:string)=>{const id=++noticeId.current;setNotices(current=>[...current,{id,title,text}]);setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),3500)};
  const changeFrom=(id:WalletId)=>{setFrom(id);setAmount("");setConfirm(false)};const submit=()=>{if(!valid){notify("Transfer unavailable",numeric>source.balance?"Insufficient wallet balance.":"Enter a valid transfer amount.");return}requestKey.current=`transfer-${Date.now()}-${from}`;setConfirm(true)};
  const complete=async()=>{if(processing.current)return;processing.current=true;try{const response=await fetch("/api/account/genealogy",{cache:"no-store"}),genealogy=await response.json() as {sourceUserId?:string;records?:Array<{id:string;sponsorId:string;uid:string;sponsorUid:string}>};update(current=>transferBetweenWallets(current,from,numeric,requestKey.current,Date.now(),{sourceUserId:genealogy.sourceUserId,genealogy:genealogy.records??[]}));const text=from==="future"?(quote.earlyTransfer?`Future Wallet transfer completed with 20% deduction. ${formatCurrency(quote.netCredit)} was credited to Spot Wallet.`:"Future Wallet transfer completed with no deduction."):`${formatCurrency(numeric)} was moved to Future Wallet.`;setConfirm(false);setSuccessText(text);notify("Transfer Complete",text);setAmount("")}catch(error){notify("Transfer unavailable",error instanceof Error?error.message:"Transfer could not be completed.")}finally{processing.current=false}};
  return <div className="wallet-operation"><PageHeader eyebrow="Internal wallet" title="Transfer funds"/><WalletNotices items={notices} dismiss={id=>setNotices(current=>current.filter(item=>item.id!==id))}/><section className="wallet-form-card"><div className="wallet-transfer-route"><label><span>From wallet</span><div><select value={from} onChange={event=>changeFrom(event.target.value as WalletId)}><option value="spot">Spot Wallet</option><option value="future">Future Wallet</option></select><ChevronDown size={15}/></div><strong>{formatCurrency(source.balance)}</strong></label><span><ArrowRight size={17}/></span><label><span>To wallet</span><div><select value={to} disabled><option>{target.name}</option></select></div><strong>{formatCurrency(target.balance)}</strong></label></div><label className="wallet-amount-field"><span>Transfer amount</span><div><b>$</b><input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/><button onClick={()=>setAmount(String(source.balance))}>MAX</button></div><small>Available: {formatCurrency(source.balance)}</small></label>{from==="spot"?<div className="wallet-direction-note"><strong>For AI Copy Trading</strong><p>Future Wallet after transfer: {formatCurrency(target.balance+(numeric>0?numeric:0))}</p></div>:<div className={`future-transfer-lock ${metrics.futureToSpotUnlocked?"unlocked":"early"}`}><ShieldAlert size={17}/><div><strong>{metrics.futureToSpotUnlocked?"Unlocked":"Early transfer available"}</strong><p>{metrics.futureToSpotUnlocked?"No early-transfer deduction":"20% deduction applies"} · Completed {formatCurrency(metrics.totalCompletedTradingProfit)} of {formatCurrency(metrics.requiredProfitForUnlock)}</p>{!metrics.futureToSpotUnlocked&&<small>{formatCurrency(metrics.remainingProfitForUnlock)} remaining · transfer is still available with deduction.</small>}<i><span style={{width:`${metrics.unlockProgressPercentage}%`}}/></i></div></div>}<div className="wallet-transfer-summary"><div><span>{quote.earlyTransfer?"20% deduction":"Transfer fee"}</span><strong>{formatCurrency(quote.earlyTransferFee)}</strong></div><div><span>You will receive</span><strong>{formatCurrency(valid?quote.netCredit:0)}</strong></div></div><button className="wallet-primary-button" disabled={!valid} onClick={submit}><Repeat2 size={17}/>Review Transfer</button></section><section className="wallet-info-card"><ShieldCheck size={19}/><div><strong>Internal transfers only</strong><p>Future-to-Spot transfers are available before the target with a 20% deduction, and without deduction after the 70% earning target is complete.</p></div></section>
  {confirm&&<WalletPortal><div className="wallet-modal-backdrop" onMouseDown={()=>setConfirm(false)}><div className="wallet-confirm-modal early-transfer-confirm" onMouseDown={event=>event.stopPropagation()}><button className="wallet-modal-x" onClick={()=>setConfirm(false)}><X size={16}/></button><span>{quote.earlyTransfer?<ShieldAlert size={22}/>:<Repeat2 size={22}/>}</span><small>Confirm Transfer</small><h2>{formatCurrency(quote.grossAmount)}</h2>{quote.earlyTransfer&&<p className="early-transfer-warning">Your 70% AI trading earning target is not yet complete. A 20% early-transfer deduction will apply.</p>}<div><p>{source.name}</p><ArrowRight size={16}/><p>{target.name}</p></div><dl><dt>Requested amount</dt><dd>{formatCurrency(quote.grossAmount)}</dd><dt>20% deduction</dt><dd>{formatCurrency(quote.earlyTransferFee)}</dd><dt>Net to Spot Wallet</dt><dd>{formatCurrency(quote.netCredit)}</dd>{from==="future"&&<><dt>Completed AI earning</dt><dd>{formatCurrency(metrics.totalCompletedTradingProfit)}</dd><dt>Required AI earning</dt><dd>{formatCurrency(metrics.requiredProfitForUnlock)}</dd><dt>Remaining earning</dt><dd>{formatCurrency(metrics.remainingProfitForUnlock)}</dd><dt>Current progress</dt><dd>{metrics.unlockProgressPercentage.toFixed(2)}%</dd></>}</dl><div className="wallet-modal-actions"><button onClick={()=>setConfirm(false)}>Cancel</button><button onClick={complete}>{quote.earlyTransfer?"Confirm 20% Deduction":"Confirm Transfer"}</button></div></div></div></WalletPortal>}{successText&&<WalletSuccess title="Transfer Complete" text={successText} onDone={()=>setSuccessText("")}/>}</div>}
