import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertMutationRequest, SUPPORT_MESSAGE_LIMIT } from "@/lib/support-security.server";
import { buildAccountContext, systemInstructions } from "@/lib/ai-support.server";
import { requestOpenAiStream } from "@/lib/openai-support";
export const runtime="nodejs";
const input=z.object({conversationId:z.string().cuid().optional(),message:z.string().trim().min(1).max(SUPPORT_MESSAGE_LIMIT),idempotencyKey:z.string().trim().min(8).max(120)}).strict(),line=(value:unknown)=>`${JSON.stringify(value)}\n`;
const graceful="I couldn't complete that answer right now. Please try again or create a support ticket.";
export async function POST(request:Request){
  try{const user=await requireAuthenticatedUser();assertMutationRequest(request,user.id);const value=input.parse(await request.json());
    const restriction=await prisma.aiSupportRestriction.findUnique({where:{userId:user.id}});if(restriction?.banned)return new Response(line({type:"error",error:"AI chat access has been restricted. Please use a support ticket."}),{status:403,headers:{"content-type":"application/x-ndjson"}});
    const limit=Math.min(60,Math.max(1,Number(process.env.AI_SUPPORT_RATE_LIMIT)||10)),recent=await prisma.chatMessage.count({where:{role:"USER",createdAt:{gte:new Date(Date.now()-60_000)},conversation:{userId:user.id}}});if(recent>=limit)return new Response(line({type:"error",error:"Please wait a moment before sending more messages."}),{status:429,headers:{"content-type":"application/x-ndjson"}});
    const existing=await prisma.chatMessage.findFirst({where:{idempotencyKey:value.idempotencyKey,conversation:{userId:user.id}},include:{conversation:true}});if(existing){const assistant=await prisma.chatMessage.findFirst({where:{conversationId:existing.conversationId,generationId:`generation:${value.idempotencyKey}`}});return new Response(line({type:"replay",session:{id:existing.conversationId,title:existing.conversation.title},message:assistant}),{status:200,headers:{"content-type":"application/x-ndjson","cache-control":"no-store"}})}
    let session=value.conversationId?await prisma.chatSession.findFirst({where:{id:value.conversationId,userId:user.id,deletedAt:null}}):null;if(value.conversationId&&!session)return new Response(line({type:"error",error:"Chat not found."}),{status:404,headers:{"content-type":"application/x-ndjson"}});const now=new Date();session=session??await prisma.chatSession.create({data:{userId:user.id,title:value.message.slice(0,54),lastMessageAt:now}});const generationId=`generation:${value.idempotencyKey}`;
    const created=await prisma.$transaction(async tx=>{const userMessage=await tx.chatMessage.create({data:{conversationId:session!.id,role:"USER",message:value.message,idempotencyKey:value.idempotencyKey}}),assistant=await tx.chatMessage.create({data:{conversationId:session!.id,role:"ASSISTANT",message:"",generationId,generationStatus:"STREAMING",startedAt:now}});await tx.chatSession.update({where:{id:session!.id},data:{lastMessageAt:now}});return{userMessage,assistant}});
    const history=await prisma.chatMessage.findMany({where:{conversationId:session.id,id:{not:created.assistant.id}},orderBy:{createdAt:"desc"},take:20}),account=await buildAccountContext(user.id),instructions=systemInstructions(account),apiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_SUPPORT_MODEL??"gpt-5-mini",encoder=new TextEncoder(),sessionId=session.id,assistantId=created.assistant.id;let upstream:AbortController|undefined,cleanUp:undefined|(()=>void),cancelled=false;
    const cancelGeneration=async(code="CLIENT_CANCELLED")=>{if(cancelled)return;cancelled=true;upstream?.abort(code);cleanUp?.();await prisma.chatMessage.updateMany({where:{id:assistantId,generationStatus:"STREAMING"},data:{message:"Generation stopped.",generationStatus:"CANCELLED",failureCode:code,completedAt:new Date()}})};
    request.signal.addEventListener("abort",()=>void cancelGeneration("CLIENT_DISCONNECTED"),{once:true});
    const stream=new ReadableStream<Uint8Array>({async start(controller){let answer="",lastSequence=-1;const send=(data:unknown)=>{if(!cancelled)controller.enqueue(encoder.encode(line(data)))};send({type:"session",session:{id:sessionId,title:session!.title},generation:{id:generationId,messageId:assistantId,status:"STREAMING"}});
      try{if(!apiKey)throw new Error("AI_NOT_CONFIGURED");const result=await requestOpenAiStream({apiKey,model,chatSessionId:sessionId,userId:user.id,clientSignal:request.signal,body:{model,instructions,input:history.reverse().map(item=>({role:item.role==="ASSISTANT"||item.role==="ADMIN"?"assistant":"user",content:item.message})),stream:true,max_output_tokens:700}});upstream=result.controller;cleanUp=result.cleanup;const reader=result.response.body!.getReader(),decoder=new TextDecoder();let buffer="";while(!cancelled){const{done,value:chunk}=await reader.read();if(done)break;buffer+=decoder.decode(chunk,{stream:true});const events=buffer.split("\n\n");buffer=events.pop()??"";for(const event of events)for(const row of event.split("\n")){if(!row.startsWith("data: "))continue;const raw=row.slice(6);if(raw==="[DONE]")continue;try{const data=JSON.parse(raw) as {type?:string;delta?:string;sequence_number?:number};if(data.type==="response.output_text.delta"&&data.delta){const sequence=data.sequence_number??lastSequence+1;if(sequence<=lastSequence)continue;lastSequence=sequence;answer+=data.delta;send({type:"delta",delta:data.delta,sequence})}}catch{}}}cleanUp?.();if(cancelled)return;if(!answer.trim())throw new Error("AI_EMPTY_RESPONSE");const completedAt=new Date(),updated=await prisma.chatMessage.updateMany({where:{id:assistantId,generationStatus:"STREAMING"},data:{message:answer.slice(0,12000),generationStatus:"COMPLETED",completedAt,failureCode:null}});if(updated.count){await prisma.chatSession.update({where:{id:sessionId},data:{lastMessageAt:completedAt}});send({type:"done",message:{id:assistantId,createdAt:created.assistant.createdAt,status:"COMPLETED"}})}
      }catch(error){cleanUp?.();if(cancelled||request.signal.aborted){await cancelGeneration("CLIENT_DISCONNECTED");try{controller.close()}catch{}return}const code=error instanceof Error?error.message.slice(0,80):"OPENAI_FAILED",message=code==="AI_NOT_CONFIGURED"?"AI Support is not configured right now. Please create a support ticket and the Bitvora team will help you.":graceful,completedAt=new Date();await prisma.chatMessage.updateMany({where:{id:assistantId,generationStatus:"STREAMING"},data:{message,generationStatus:"FAILED",failureCode:code,completedAt}});await prisma.chatSession.update({where:{id:sessionId},data:{lastMessageAt:completedAt}});send({type:"delta",delta:message,sequence:lastSequence+1});send({type:"escalate"});send({type:"done",message:{id:assistantId,createdAt:created.assistant.createdAt,status:"FAILED"}})}finally{try{controller.close()}catch{}}},cancel(){return cancelGeneration("CLIENT_CANCELLED")}});
    return new Response(stream,{headers:{"content-type":"application/x-ndjson; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
  }catch(error){const message=error instanceof z.ZodError?error.issues[0]?.message??"Invalid message.":error instanceof Error&&error.message.startsWith("INVALID_")||error instanceof Error&&error.message==="MISSING_REQUEST_PROVENANCE"?"Request security validation failed.":"Unable to send message.";return new Response(line({type:"error",error:message}),{status:400,headers:{"content-type":"application/x-ndjson"}})}
}
