import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDemoAdmin } from "@/lib/admin/admin-auth.server";
import { prisma } from "@/lib/prisma";
import { approveAdminWithdrawal,rejectAdminWithdrawal,WithdrawalAdminError } from "@/lib/withdrawals/admin.server";
import { adminWithdrawalResponse } from "@/lib/withdrawals/admin-response";
const action=z.discriminatedUnion("action",[
  z.object({action:z.literal("APPROVE"),withdrawalId:z.string().min(1),txHash:z.string(),targetStatus:z.enum(["BROADCASTED","COMPLETED"]).default("BROADCASTED")}),
  z.object({action:z.literal("REJECT"),withdrawalId:z.string().min(1),reason:z.string().min(3).max(500)})
]);
export async function GET(){try{await requireDemoAdmin();const rows=await prisma.withdrawal.findMany({select:{id:true,userId:true,user:{select:{id:true,uid:true,name:true,email:true}},requestedAmount:true,platformFee:true,recipientAmount:true,destinationAddress:true,network:true,createdAt:true,userLocalDate:true,status:true,processingMode:true,rejectionReason:true,txHash:true},orderBy:{createdAt:"desc"},take:500});const counts=new Map<string,number>();const withdrawals=[...rows].reverse().map(row=>{const previousHistoryCount=counts.get(row.userId)??0;counts.set(row.userId,previousHistoryCount+1);return adminWithdrawalResponse(row,previousHistoryCount)}).reverse();return NextResponse.json({withdrawals},{headers:{"Cache-Control":"private, no-store"}})}catch(error){if(error instanceof Error&&(error.message==="UNAUTHENTICATED"||error.message==="FORBIDDEN"))return NextResponse.json({error:"Admin access required."},{status:401,headers:{"Cache-Control":"private, no-store"}});console.error("[admin-withdrawals] list failed",error);return NextResponse.json({error:"Unable to load withdrawals."},{status:500,headers:{"Cache-Control":"private, no-store"}})}}
export async function POST(request:Request){try{const admin=await requireDemoAdmin(),value=action.parse(await request.json()),result=value.action==="APPROVE"?await approveAdminWithdrawal(value.withdrawalId,admin.id,value.txHash,value.targetStatus):await rejectAdminWithdrawal(value.withdrawalId,admin.id,value.reason);return NextResponse.json({withdrawalId:result.id,status:result.status,txHash:result.txHash})}catch(error){if(error instanceof WithdrawalAdminError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({error:error.issues[0]?.message??"Invalid admin action."},{status:400});return NextResponse.json({error:"Admin withdrawal action failed."},{status:500})}}
