export const BUSINESS_TIME_ZONE="Asia/Kolkata";
export const AI_TRADING_STORE_KEY="bitvora-ai-trading-v1";
export type SessionType="REGULAR"|"ADDITIONAL";
export type SessionPhase="UPCOMING"|"LIVE"|"PROCESSING"|"SETTLED";
export type SignalDirection="CALL"|"PUT";
export type TradeStatus="PLACED"|"SETTLED"|"MISSED";
export type TradeSession={id:string;type:SessionType;sequence:1|2|3|"ADDITIONAL";tradingDate:string;scheduledAt:number;liveFrom:number;placementClosesAt:number;settlesAt:number;pair:string;chartSymbol:string;signalDirection:SignalDirection;status:SessionPhase;createdAt:number;updatedAt:number};
export type DailyTradeAssignment={userId:string;userUid:string;tradingDate:string;dailyProfitRate:number;perTradeProfitRate:number;dailyProfitBase:number;createdAt:number};
export type TradePlacementSource="MANUAL"|"AI_BOT";
export type UserTrade={id:string;userId:string;userUid:string;sessionId:string;direction:SignalDirection;balanceSnapshot:number;dailyProfitBase:number;tradeCapital:number;profitRate:number;profitAmount:number;status:TradeStatus;placedAt:number;settledAt:number|null;idempotencyKey:string;placementSource:TradePlacementSource};
export type AdditionalEligibility={additionalTradeEligibilityDate:string|null;additionalTradeUsed:boolean;additionalTradeSessionId:string|null;additionalTradeCompletedAt:number|null};
export type TradingNotificationKind="info"|"success"|"warning";
export type TradingNotification={id:string;userId:string;type:"TRADE_LIVE"|"TRADE_PLACED"|"TRADE_MISSED"|"TRADE_SETTLED"|"PROFIT_CREDITED"|"ADDITIONAL_AVAILABLE"|"TARGET_COMPLETED";title:string;text:string;kind:TradingNotificationKind;createdAt:number};
export type AiTradingStore={version:1;assignments:DailyTradeAssignment[];trades:UserTrade[];additional:AdditionalEligibility;notifications:TradingNotification[];lastEngineAt:number|null};

const pairs=[{pair:"BTC/USDT",chartSymbol:"BINANCE:BTCUSDT"},{pair:"ETH/USDT",chartSymbol:"BINANCE:ETHUSDT"},{pair:"BNB/USDT",chartSymbol:"BINANCE:BNBUSDT"}];
const hash=(value:string)=>{let result=2166136261;for(let index=0;index<value.length;index+=1){result^=value.charCodeAt(index);result=Math.imul(result,16777619)}return result>>>0};
const money=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
const dateParts=(now:number)=>new Intl.DateTimeFormat("en-CA",{timeZone:BUSINESS_TIME_ZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(now));
export const getTradingDate=(now:number)=>dateParts(now);
const scheduledUtc=(date:string,hour:number)=>{const [year,month,day]=date.split("-").map(Number);return Date.UTC(year,month-1,day,hour,0)-330*60_000};
export const getSessionPhase=(session:Pick<TradeSession,"liveFrom"|"placementClosesAt"|"settlesAt">,now:number):SessionPhase=>now<session.liveFrom?"UPCOMING":now<session.placementClosesAt?"LIVE":now<session.settlesAt?"PROCESSING":"SETTLED";
export function createDailySessions(tradingDate:string,now:number):TradeSession[]{const definitions=[{type:"REGULAR" as const,sequence:1 as const,hour:15},{type:"REGULAR" as const,sequence:2 as const,hour:19},{type:"REGULAR" as const,sequence:3 as const,hour:21},{type:"ADDITIONAL" as const,sequence:"ADDITIONAL" as const,hour:22}];return definitions.map(item=>{const id=`AI_SESSION:${tradingDate}:${item.sequence}`,liveFrom=scheduledUtc(tradingDate,item.hour),placementClosesAt=liveFrom+20*60_000,settlesAt=placementClosesAt+10*60_000,pair=pairs[hash(id)%pairs.length],signalDirection:SignalDirection=hash(`${id}:direction`)%2===0?"CALL":"PUT",createdAt=scheduledUtc(tradingDate,0);const session={id,type:item.type,sequence:item.sequence,tradingDate,scheduledAt:liveFrom,liveFrom,placementClosesAt,settlesAt,pair:pair.pair,chartSymbol:pair.chartSymbol,signalDirection,status:"UPCOMING" as SessionPhase,createdAt,updatedAt:now};return{...session,status:getSessionPhase(session,now)}})}
export function createSessionsBetween(from:number,to:number){const start=getTradingDate(from),end=getTradingDate(to),cursor=new Date(`${start}T00:00:00.000Z`),last=new Date(`${end}T00:00:00.000Z`),sessions:TradeSession[]=[];while(cursor<=last){sessions.push(...createDailySessions(cursor.toISOString().slice(0,10),to));cursor.setUTCDate(cursor.getUTCDate()+1)}return sessions}
export function getSessionById(sessionId:string,now:number){const match=/^AI_SESSION:(\d{4}-\d{2}-\d{2}):(1|2|3|ADDITIONAL)$/.exec(sessionId);return match?createDailySessions(match[1],now).find(item=>String(item.sequence)===match[2])??null:null}
export const createEmptyTradingStore=():AiTradingStore=>({version:1,assignments:[],trades:[],notifications:[],lastEngineAt:null,additional:{additionalTradeEligibilityDate:null,additionalTradeUsed:false,additionalTradeSessionId:null,additionalTradeCompletedAt:null}});
export function migrateTradingStore(value:unknown):AiTradingStore{if(!value||typeof value!=="object"||!("version" in value))return createEmptyTradingStore();const current=value as Partial<AiTradingStore>;return{version:1,assignments:current.assignments??[],trades:(current.trades??[]).map(trade=>({...trade,placementSource:trade.placementSource??"MANUAL"})),notifications:current.notifications??[],lastEngineAt:current.lastEngineAt??null,additional:current.additional??createEmptyTradingStore().additional}}
export function addTradingNotification(store:AiTradingStore,notification:TradingNotification){if(store.notifications.some(item=>item.id===notification.id))return store;return{...store,notifications:[notification,...store.notifications].sort((a,b)=>b.createdAt-a.createdAt)}}
const notification=(userId:string,type:TradingNotification["type"],eventId:string,title:string,text:string,kind:TradingNotificationKind,createdAt:number):TradingNotification=>({id:`AI_NOTICE:${type}:${eventId}:${userId}`,userId,type,title,text,kind,createdAt});
export function reconcileSessionNotifications(store:AiTradingStore,sessions:TradeSession[],userId:string,now:number){let next=store;for(const session of sessions){const eligible=session.type==="REGULAR"||store.additional.additionalTradeEligibilityDate===session.tradingDate||store.trades.some(item=>item.userId===userId&&item.sessionId===session.id);if(eligible&&now>=session.liveFrom)next=addTradingNotification(next,notification(userId,"TRADE_LIVE",session.id,"Trade LIVE",`${session.pair} ${session.signalDirection} session is LIVE.`,"info",session.liveFrom));if(session.type==="ADDITIONAL"&&store.additional.additionalTradeEligibilityDate===session.tradingDate)next=addTradingNotification(next,notification(userId,"ADDITIONAL_AVAILABLE",session.id,"Additional Trade available",`Your ${formatSessionLabel(session)} is available.`,"info",session.createdAt))}return next}
export function addTargetCompletedNotification(store:AiTradingStore,userId:string,createdAt:number){return addTradingNotification(store,notification(userId,"TARGET_COMPLETED","70_PERCENT","70% target completed","Future → Spot transfer is now deduction free.","success",createdAt))}
const formatSessionLabel=(session:TradeSession)=>session.type==="ADDITIONAL"?"10:00 PM Additional Trade":"AI trade";
export function ensureAdditionalEligibility(store:AiTradingStore,tradingDate:string,futureBalance:number):AiTradingStore{if(store.additional.additionalTradeEligibilityDate||futureBalance<=0)return store;return{...store,additional:{...store.additional,additionalTradeEligibilityDate:tradingDate}}}
export function getDailyAssignment(store:AiTradingStore,userId:string,userUid:string,tradingDate:string,dailyProfitBase:number,createdAt:number){const existing=store.assignments.find(item=>item.userId===userId&&item.tradingDate===tradingDate);if(existing)return{store,assignment:existing};const dailyProfitRate=Number((1+(hash(`${userUid}:${tradingDate}:regular`)%101)/100).toFixed(2)),assignment:DailyTradeAssignment={userId,userUid,tradingDate,dailyProfitRate,perTradeProfitRate:Number((dailyProfitRate/3).toFixed(6)),dailyProfitBase:money(dailyProfitBase),createdAt};return{store:{...store,assignments:[assignment,...store.assignments]},assignment}}
export const getAdditionalRate=(userUid:string,tradingDate:string)=>Number((.4+(hash(`${userUid}:${tradingDate}:additional`)%11)/100).toFixed(2));
export function canUseAdditional(store:AiTradingStore,session:TradeSession){return session.type==="ADDITIONAL"&&store.additional.additionalTradeEligibilityDate===session.tradingDate&&!store.additional.additionalTradeUsed}
export function placeUserTrade(input:{store:AiTradingStore;session:TradeSession;userId:string;userUid:string;futureBalance:number;now:number;placementSource?:TradePlacementSource}){const{session,userId,userUid,futureBalance,now}=input,direction=session.signalDirection,key=`AI_TRADE:${session.id}:${userId}`;if(getSessionPhase(session,now)!=="LIVE")throw new Error("This trade session is not LIVE.");const duplicate=input.store.trades.find(item=>item.idempotencyKey===key);if(duplicate)return{store:input.store,trade:duplicate,created:false};if(session.type==="ADDITIONAL"&&!canUseAdditional(input.store,session))throw new Error("The Additional Trade is not available for this account.");const tradeCapital=money(futureBalance*.01);if(tradeCapital<=0||futureBalance<tradeCapital)throw new Error("Insufficient available Future Wallet balance.");let store=input.store,profitRate:number,dailyProfitBase:number;if(session.type==="REGULAR"){const assignmentResult=getDailyAssignment(store,userId,userUid,session.tradingDate,futureBalance,now);store=assignmentResult.store;profitRate=assignmentResult.assignment.perTradeProfitRate;dailyProfitBase=assignmentResult.assignment.dailyProfitBase}else{profitRate=getAdditionalRate(userUid,session.tradingDate);dailyProfitBase=money(futureBalance)}const trade:UserTrade={id:key,userId,userUid,sessionId:session.id,direction,balanceSnapshot:money(futureBalance),dailyProfitBase,tradeCapital,profitRate,profitAmount:money(dailyProfitBase*profitRate/100),status:"PLACED",placedAt:now,settledAt:null,idempotencyKey:key,placementSource:input.placementSource??"MANUAL"};store={...store,trades:[trade,...store.trades],additional:session.type==="ADDITIONAL"?{...store.additional,additionalTradeUsed:true,additionalTradeSessionId:session.id}:store.additional};store=addTradingNotification(store,notification(userId,"TRADE_PLACED",session.id,"Trade placed successfully",`${session.pair} ${direction} was placed successfully.`,"success",now));return{store,trade,created:true}}
export function settleUserTrade(store:AiTradingStore,tradeId:string,session:TradeSession,now:number){const trade=store.trades.find(item=>item.id===tradeId);if(!trade)throw new Error("Trade not found.");if(trade.status==="SETTLED")return{store,trade,settled:false};if(trade.status!=="PLACED")throw new Error("Only a placed trade can settle.");if(now<session.settlesAt)throw new Error("Settlement time has not been reached.");const settled={...trade,status:"SETTLED" as const,settledAt:session.settlesAt};let next:AiTradingStore={...store,trades:store.trades.map(item=>item.id===tradeId?settled:item),additional:session.type==="ADDITIONAL"?{...store.additional,additionalTradeCompletedAt:session.settlesAt}:store.additional};next=addTradingNotification(next,notification(trade.userId,"TRADE_SETTLED",session.id,"Trade settled",`${session.pair} trade completed at its scheduled settlement time.`,"success",session.settlesAt));next=addTradingNotification(next,notification(trade.userId,"PROFIT_CREDITED",session.id,"Profit credited",`${money(trade.profitAmount).toFixed(2)} profit was credited to Future Wallet.`,"success",session.settlesAt));return{store:next,trade:settled,settled:true}}
export function markExpiredSessionsMissed(store:AiTradingStore,sessions:TradeSession[],userId:string,userUid:string,now:number){const additions:UserTrade[]=[];let additional=store.additional,next=store;for(const session of sessions){if(now<session.placementClosesAt||store.trades.some(item=>item.sessionId===session.id&&item.userId===userId))continue;if(session.type==="ADDITIONAL"&&!canUseAdditional(store,session))continue;additions.push({id:`AI_MISSED:${session.id}:${userId}`,userId,userUid,sessionId:session.id,direction:session.signalDirection,balanceSnapshot:0,dailyProfitBase:0,tradeCapital:0,profitRate:0,profitAmount:0,status:"MISSED",placedAt:session.placementClosesAt,settledAt:null,idempotencyKey:`AI_TRADE:${session.id}:${userId}`,placementSource:"MANUAL"});next=addTradingNotification(next,notification(userId,"TRADE_MISSED",session.id,"Trade missed",`${session.pair} session closed without placement.`,"warning",session.placementClosesAt));if(session.type==="ADDITIONAL")additional={...additional,additionalTradeUsed:true,additionalTradeSessionId:session.id}}return additions.length?{...next,trades:[...additions,...next.trades],additional}:next}
