import "server-only";
import { createHash,randomBytes } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { getSessionById,getSessionPhase } from "@/lib/ai-trading-engine";
import { getWalletSnapshot } from "@/lib/future-wallet.server";
import { enqueueUserSessionTrade } from "@/lib/ai-trade-scale/orchestrator";
import { resolveUserTimeZone } from "@/lib/timezone.server";
import { boundedApiOperation } from "@/lib/ai-trade-scale/queue";

export type AiIntentCode="SESSION_NOT_FOUND"|"SESSION_NOT_LIVE"|"SIGNAL_EXPIRED"|"WRONG_DIRECTION"|"NOT_ELIGIBLE"|"INSUFFICIENT_FUTURE_BALANCE"|"ALREADY_JOINED"|"ACCOUNT_STATE_UNAVAILABLE"|"INTERNAL_ERROR";
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export class AiIntentError extends Error{constructor(public code:AiIntentCode,message:string,public status=400){super(message)}}
export function publicSignal(session:NonNullable<ReturnType<typeof getSessionById>>){return{id:session.id,pair:session.pair,chartSymbol:session.chartSymbol,signal:session.signalDirection==="CALL"?"BUY":"SELL",direction:session.signalDirection,liveFrom:session.liveFrom,placementClosesAt:session.placementClosesAt,status:getSessionPhase(session,Date.now())}}
async function context(userId:string,sessionId:string,now=Date.now()){const user=await prisma.user.findUniqueOrThrow({where:{id:userId},select:{timezone:true,country:true,additionalTradeEligibility:true}}),timeZone=resolveUserTimeZone(user.timezone,user.country),session=getSessionById(sessionId,now,timeZone);if(!session)throw new AiIntentError("SESSION_NOT_FOUND","Trading session not found.",404);return{user,timeZone,session}}
function additionalAllowed(value:Awaited<ReturnType<typeof context>>){const eligibility=value.user.additionalTradeEligibility,session=value.session;return session.type==="REGULAR"||Boolean(eligibility?.eligible&&eligibility.eligibilityStartedAt.getTime()<=session.liveFrom&&eligibility.eligibilityEndsAt&&eligibility.eligibilityEndsAt.getTime()>session.liveFrom)}

export async function createTradeIntent(user:{id:string;uid:string},sessionId:string){const now=Date.now(),value=await context(user.id,sessionId,now);if(getSessionPhase(value.session,now)!=="LIVE")throw new AiIntentError("SESSION_NOT_LIVE","This trade session is not LIVE.",409);if(!additionalAllowed(value))throw new AiIntentError("NOT_ELIGIBLE","This session is not eligible for this account.",403);const financial=await getWalletSnapshot(user.id);if(!financial.availableFuture.isPositive())throw new AiIntentError("INSUFFICIENT_FUTURE_BALANCE","Insufficient Future Wallet balance.",409);const existing=await prisma.aiFinancialTrade.findFirst({where:{userId:user.id,localTradingDate:value.session.tradingDate,localSessionSlot:String(value.session.sequence)}});if(existing)throw new AiIntentError("ALREADY_JOINED","This session was already joined.",409);const token=randomBytes(32).toString("base64url");await prisma.aiTradeIntent.create({data:{tokenHash:hash(token),userId:user.id,sessionId:value.session.id,expiresAt:new Date(value.session.placementClosesAt)}});return{token,session:publicSignal(value.session)}}
export async function readTradeIntent(userId:string,token:string){const intent=await prisma.aiTradeIntent.findUnique({where:{tokenHash:hash(token)}}),now=Date.now();if(!intent||intent.userId!==userId)throw new AiIntentError("SIGNAL_EXPIRED","Trading signal not found or expired.",410);const value=await context(userId,intent.sessionId,now);if(intent.usedAt||intent.expiresAt.getTime()<=now||getSessionPhase(value.session,now)!=="LIVE")throw new AiIntentError("SIGNAL_EXPIRED","This trading signal has expired.",410);return{intent,session:value.session}}
export async function placeIntentTrade(user:{id:string;uid:string},token:string,requestedSide:"BUY"|"SELL"){
  const tokenHash=hash(token),intent=await prisma.aiTradeIntent.findUnique({where:{tokenHash}}),now=Date.now();if(!intent||intent.userId!==user.id)throw new AiIntentError("SIGNAL_EXPIRED","Trading signal not found or expired.",410);const value=await context(user.id,intent.sessionId,now),requiredSide=value.session.signalDirection==="CALL"?"BUY":"SELL";if(intent.expiresAt.getTime()<=now||getSessionPhase(value.session,now)!=="LIVE")throw new AiIntentError("SIGNAL_EXPIRED","This trading signal has expired.",410);if(requestedSide!==requiredSide)throw new AiIntentError("WRONG_DIRECTION",`This session signal is ${requiredSide}.`,409);if(!additionalAllowed(value))throw new AiIntentError("NOT_ELIGIBLE","This session is not eligible for this account.",403);const consumed=await prisma.aiTradeIntent.updateMany({where:{tokenHash,userId:user.id,usedAt:null,expiresAt:{gt:new Date(now)}},data:{usedAt:new Date(now)}});if(consumed.count!==1&&!intent.usedAt)throw new AiIntentError("SIGNAL_EXPIRED","This trading signal was already used.",409);try{const run=await boundedApiOperation(enqueueUserSessionTrade(user.id,value.session.id,"MANUAL",new Date(now)));return{trade:{id:`QUEUED:${run.id}:${user.id}`,status:"QUEUED",placementSource:"MANUAL",tradeCapital:0},session:publicSignal(value.session),idempotent:run.idempotent,queued:true,jobId:run.bullJobId}}catch(error){if(consumed.count===1)await prisma.aiTradeIntent.updateMany({where:{tokenHash,userId:user.id,usedAt:{not:null}},data:{usedAt:null}});throw error}
}
