import "server-only";
import { createHash, randomBytes } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { canUseAdditional, getSessionById, getSessionPhase, migrateTradingStore, placeUserTrade } from "@/lib/ai-trading-engine";
import { lockFutureTradeCapital, migrateWalletStore } from "@/lib/wallet-data";

const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export class AiIntentError extends Error{constructor(message:string,public status=400){super(message)}}
export function publicSignal(session:NonNullable<ReturnType<typeof getSessionById>>){return{id:session.id,pair:session.pair,chartSymbol:session.chartSymbol,signal:session.signalDirection==="CALL"?"BUY":"SELL",direction:session.signalDirection,liveFrom:session.liveFrom,placementClosesAt:session.placementClosesAt,status:getSessionPhase(session,Date.now())}}
export async function createTradeIntent(user:{id:string;uid:string},sessionId:string){const now=Date.now(),session=getSessionById(sessionId,now);if(!session||getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("This trade session is no longer LIVE.",409);const state=await prisma.userState.findUnique({where:{userId:user.id}}),trading=migrateTradingStore(state?.trading);if(trading.trades.some(item=>item.sessionId===session.id&&item.userId===user.id))throw new AiIntentError("This session was already placed or missed.",409);if(session.type==="ADDITIONAL"&&!canUseAdditional(trading,session))throw new AiIntentError("This session is not eligible for this account.",403);const token=randomBytes(32).toString("base64url");await prisma.aiTradeIntent.create({data:{tokenHash:hash(token),userId:user.id,sessionId:session.id,expiresAt:new Date(session.placementClosesAt)}});return{token,session:publicSignal(session)}}
export async function readTradeIntent(userId:string,token:string){const intent=await prisma.aiTradeIntent.findUnique({where:{tokenHash:hash(token)}}),now=Date.now();if(!intent||intent.userId!==userId||intent.usedAt||intent.expiresAt.getTime()<=now)throw new AiIntentError("This trading signal has expired.",410);const session=getSessionById(intent.sessionId,now);if(!session||getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("This trading session is no longer LIVE.",410);return{intent,session}}
export async function placeIntentTrade(user:{id:string;uid:string},token:string,requestedSide:"BUY"|"SELL"){return prisma.$transaction(async tx=>{const intent=await tx.aiTradeIntent.findUnique({where:{tokenHash:hash(token)}}),now=Date.now();if(!intent||intent.userId!==user.id||intent.usedAt||intent.expiresAt.getTime()<=now)throw new AiIntentError("This trading signal has expired or was already used.",409);const session=getSessionById(intent.sessionId,now);if(!session||getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("The live trade window has closed.",409);const requiredSide=session.signalDirection==="CALL"?"BUY":"SELL";if(requestedSide!==requiredSide)throw new AiIntentError(`This session signal is ${requiredSide}.`,409);const state=await tx.userState.findUnique({where:{userId:user.id}});if(!state)throw new AiIntentError("Account wallet state is unavailable.",409);const wallet=migrateWalletStore(state.wallet),trading=migrateTradingStore(state.trading),placed=placeUserTrade({store:trading,session,userId:user.id,userUid:user.uid,futureBalance:wallet.wallets.future.balance,now});if(!placed.created)throw new AiIntentError(placed.trade.placementSource==="AI_BOT"?"This session was already placed automatically by AI Bot.":"This session was already placed.",409);const trade=placed.trade,nextWallet=lockFutureTradeCapital(wallet,trade.tradeCapital,trade.idempotencyKey,{userUid:user.uid,sessionId:session.id,pair:session.pair,direction:trade.direction,grossFutureBalance:trade.balanceSnapshot,tradeCapital:trade.tradeCapital,profitPercentage:trade.profitRate,profitAmount:trade.profitAmount},now);await tx.userState.update({where:{userId:user.id},data:{wallet:nextWallet as object,trading:placed.store as object}});await tx.aiTradeIntent.updateMany({where:{userId:user.id,sessionId:session.id,usedAt:null},data:{usedAt:new Date(now)}});return{trade,session:publicSignal(session),wallet:nextWallet}})}
