import "server-only";
import { createHash, randomBytes } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { canUseAdditional, getSessionById, getSessionPhase, migrateTradingStore, placeUserTrade, type UserTrade } from "@/lib/ai-trading-engine";
import { lockFutureTradeCapital, migrateWalletStore, type WalletStore } from "@/lib/wallet-data";

export type AiIntentCode="SESSION_NOT_FOUND"|"SESSION_NOT_LIVE"|"SIGNAL_EXPIRED"|"WRONG_DIRECTION"|"NOT_ELIGIBLE"|"INSUFFICIENT_FUTURE_BALANCE"|"ALREADY_JOINED"|"ACCOUNT_STATE_UNAVAILABLE"|"INTERNAL_ERROR";
const hash=(token:string)=>createHash("sha256").update(token).digest("hex"),cents=(value:number)=>Math.round(value*100)/100;
export class AiIntentError extends Error{constructor(public code:AiIntentCode,message:string,public status=400){super(message)}}
const safeLog=(event:string,data:Record<string,unknown>)=>console.info(`[ai-trade] ${event}`,data);
export function publicSignal(session:NonNullable<ReturnType<typeof getSessionById>>){return{id:session.id,pair:session.pair,chartSymbol:session.chartSymbol,signal:session.signalDirection==="CALL"?"BUY":"SELL",direction:session.signalDirection,liveFrom:session.liveFrom,placementClosesAt:session.placementClosesAt,status:getSessionPhase(session,Date.now())}}
function result(trade:UserTrade,session:NonNullable<ReturnType<typeof getSessionById>>,wallet:WalletStore,idempotent=false){return{trade,session:publicSignal(session),wallet,idempotent}}
export async function createTradeIntent(user:{id:string;uid:string},sessionId:string){const now=Date.now(),session=getSessionById(sessionId,now);if(!session)throw new AiIntentError("SESSION_NOT_FOUND","Trading session not found.",404);if(getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("SESSION_NOT_LIVE","This trade session is not LIVE.",409);const state=await prisma.userState.findUnique({where:{userId:user.id}}),trading=migrateTradingStore(state?.trading);if(trading.trades.some(item=>item.sessionId===session.id&&item.userId===user.id))throw new AiIntentError("ALREADY_JOINED","This session was already placed or missed.",409);if(session.type==="ADDITIONAL"&&!canUseAdditional(trading,session))throw new AiIntentError("NOT_ELIGIBLE","This session is not eligible for this account.",403);const token=randomBytes(32).toString("base64url"),intent=await prisma.aiTradeIntent.create({data:{tokenHash:hash(token),userId:user.id,sessionId:session.id,expiresAt:new Date(session.placementClosesAt)}});safeLog("intent_created",{userId:user.id,sessionId:session.id,signalId:intent.id,pair:session.pair,direction:session.signalDirection==="CALL"?"BUY":"SELL",serverNow:now,sessionStart:session.liveFrom,sessionEnd:session.placementClosesAt,authenticated:true,eligible:true});return{token,session:publicSignal(session)}}
export async function readTradeIntent(userId:string,token:string){const intent=await prisma.aiTradeIntent.findUnique({where:{tokenHash:hash(token)}}),now=Date.now();if(!intent||intent.userId!==userId)throw new AiIntentError("SIGNAL_EXPIRED","Trading signal not found or expired.",410);const session=getSessionById(intent.sessionId,now);if(!session)throw new AiIntentError("SESSION_NOT_FOUND","Trading session not found.",404);if(intent.usedAt||intent.expiresAt.getTime()<=now||getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("SIGNAL_EXPIRED","This trading signal has expired.",410);return{intent,session}}
export async function placeIntentTrade(user:{id:string;uid:string},token:string,requestedSide:"BUY"|"SELL"){
  return prisma.$transaction(async tx=>{
    const tokenHash=hash(token),intent=await tx.aiTradeIntent.findUnique({where:{tokenHash}}),now=Date.now();
    if(!intent||intent.userId!==user.id)throw new AiIntentError("SIGNAL_EXPIRED","Trading signal not found or expired.",410);
    const session=getSessionById(intent.sessionId,now);if(!session)throw new AiIntentError("SESSION_NOT_FOUND","Trading session not found.",404);
    const state=await tx.userState.findUnique({where:{userId:user.id}});if(!state)throw new AiIntentError("ACCOUNT_STATE_UNAVAILABLE","Future Wallet account state is unavailable.",409);
    const wallet=migrateWalletStore(state.wallet),trading=migrateTradingStore(state.trading),existing=trading.trades.find(item=>item.userId===user.id&&item.sessionId===session.id),requiredSide=session.signalDirection==="CALL"?"BUY":"SELL",tradeAmount=cents(wallet.wallets.future.balance*.01);
    safeLog("placement_validation",{userId:user.id,sessionId:session.id,signalId:intent.id,pair:session.pair,direction:requiredSide,requestedDirection:requestedSide,serverNow:now,sessionStart:session.liveFrom,sessionEnd:session.placementClosesAt,authenticated:true,eligible:session.type==="REGULAR"||canUseAdditional(trading,session),futureWalletBalance:wallet.wallets.future.balance,tradeAmount,duplicate:Boolean(existing)});
    if(existing){if(existing.status==="PLACED"&&existing.placementSource==="MANUAL")return result(existing,session,wallet,true);throw new AiIntentError("ALREADY_JOINED",existing.placementSource==="AI_BOT"?"This session was already placed automatically by AI Bot.":"This session was already joined.",409)}
    if(intent.usedAt||intent.expiresAt.getTime()<=now)throw new AiIntentError("SIGNAL_EXPIRED","This trading signal has expired or was already used.",410);
    if(getSessionPhase(session,now)!=="LIVE")throw new AiIntentError("SESSION_NOT_LIVE","The live trade window has closed.",409);
    if(requestedSide!==requiredSide)throw new AiIntentError("WRONG_DIRECTION",`This session signal is ${requiredSide}.`,409);
    if(session.type==="ADDITIONAL"&&!canUseAdditional(trading,session))throw new AiIntentError("NOT_ELIGIBLE","This session is not eligible for this account.",403);
    if(tradeAmount<=0||wallet.wallets.future.balance<tradeAmount)throw new AiIntentError("INSUFFICIENT_FUTURE_BALANCE","Insufficient Future Wallet balance.",409);
    let placed;try{placed=placeUserTrade({store:trading,session,userId:user.id,userUid:user.uid,futureBalance:wallet.wallets.future.balance,now})}catch(error){const message=error instanceof Error?error.message:"Trade validation failed.";if(/insufficient/i.test(message))throw new AiIntentError("INSUFFICIENT_FUTURE_BALANCE","Insufficient Future Wallet balance.",409);if(/not LIVE/i.test(message))throw new AiIntentError("SESSION_NOT_LIVE","The live trade window has closed.",409);throw error}
    if(!placed.created)return result(placed.trade,session,wallet,true);
    const trade=placed.trade,nextWallet=lockFutureTradeCapital(wallet,trade.tradeCapital,trade.idempotencyKey,{userUid:user.uid,tradeId:trade.id,sessionId:session.id,pair:session.pair,direction:trade.direction,source:"MANUAL",grossFutureBalance:trade.balanceSnapshot,tradeCapital:trade.tradeCapital,profitPercentage:trade.profitRate,profitAmount:trade.profitAmount},now),consumed=await tx.aiTradeIntent.updateMany({where:{tokenHash,userId:user.id,usedAt:null,expiresAt:{gt:new Date(now)}},data:{usedAt:new Date(now)}});
    if(consumed.count!==1)throw new AiIntentError("SIGNAL_EXPIRED","This trading signal was already used.",409);
    await tx.userState.update({where:{userId:user.id},data:{wallet:nextWallet as object,trading:placed.store as object}});
    safeLog("placement_committed",{userId:user.id,sessionId:session.id,signalId:intent.id,pair:session.pair,direction:requiredSide,serverNow:now,futureWalletBalance:wallet.wallets.future.balance,tradeAmount:trade.tradeCapital,duplicate:false});
    return result(trade,session,nextWallet)
  },{isolationLevel:"Serializable"})
}
