export type OpenAiLog={chatSessionId:string;userId:string;model:string;attempt:number;upstreamStatus:number|null;requestId:string|null;durationMs:number;failureCategory:string};
export type OpenAiRequestOptions={apiKey:string;model:string;body:object;chatSessionId:string;userId:string;clientSignal?:AbortSignal;timeoutMs?:number;maxRetries?:number;fetcher?:typeof fetch;sleep?:(ms:number)=>Promise<void>;random?:()=>number;logger?:(entry:OpenAiLog)=>void};
const transient=new Set([408,409,429,500,502,503,504]);
const failure=(status:number|null,error?:unknown)=>status?`UPSTREAM_${status}`:error instanceof DOMException&&error.name==="AbortError"?"ABORTED":"NETWORK_ERROR";
export async function requestOpenAiStream(options:OpenAiRequestOptions){const fetcher=options.fetcher??fetch,sleep=options.sleep??((ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))),random=options.random??Math.random,logger=options.logger??(entry=>console.error(JSON.stringify({component:"ai-support-openai",...entry}))),timeoutMs=Math.min(120000,Math.max(1000,options.timeoutMs??(Number(process.env.AI_SUPPORT_REQUEST_TIMEOUT_MS)||45000))),maxRetries=Math.min(5,Math.max(0,options.maxRetries??(Number(process.env.AI_SUPPORT_MAX_RETRIES)||2)));let last:unknown;
  for(let attempt=1;attempt<=maxRetries+1;attempt++){const started=Date.now(),controller=new AbortController(),abort=()=>controller.abort("CLIENT_DISCONNECTED");options.clientSignal?.addEventListener("abort",abort,{once:true});const timer=setTimeout(()=>controller.abort("OPENAI_TIMEOUT"),timeoutMs);let status:number|null=null,requestId:string|null=null;
    try{const response=await fetcher("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${options.apiKey}`,"content-type":"application/json"},body:JSON.stringify(options.body),signal:controller.signal});status=response.status;requestId=response.headers.get("x-request-id");if(response.ok&&response.body)return{response,controller,cleanup:()=>{clearTimeout(timer);options.clientSignal?.removeEventListener("abort",abort)}};clearTimeout(timer);options.clientSignal?.removeEventListener("abort",abort);last=new Error(`OPENAI_${status}`);logger({chatSessionId:options.chatSessionId,userId:options.userId,model:options.model,attempt,upstreamStatus:status,requestId,durationMs:Date.now()-started,failureCategory:failure(status)});if(!transient.has(status)||attempt>maxRetries)throw last;
    }catch(error){clearTimeout(timer);options.clientSignal?.removeEventListener("abort",abort);last=error;if(status===null)logger({chatSessionId:options.chatSessionId,userId:options.userId,model:options.model,attempt,upstreamStatus:null,requestId,durationMs:Date.now()-started,failureCategory:failure(null,error)});if(status!==null&&!transient.has(status)||options.clientSignal?.aborted||attempt>maxRetries||error instanceof DOMException&&error.name==="AbortError")throw error}
    const delay=Math.min(8000,300*2**(attempt-1))+Math.floor(random()*250);await sleep(delay);
  }throw last instanceof Error?last:new Error("OPENAI_FAILED")}
