import { ranks } from "./config";

export type RankNode={uid:string;sponsorUid:string;qualifyingFutureCapital:number;currentStar:number;rewardedRanks:number[]};
export type RankEvaluation=RankNode&{qualifiedTeamCount:number;directRankCount:number;newRewardRanks:number[]};
export const isCapitalQualified=(capital:number)=>Math.round(capital*100)>=5000;

export function getUniqueDownline(ownerUid:string,nodes:readonly RankNode[]):RankNode[]{const children=new Map<string,RankNode[]>();for(const node of nodes){if(!node.sponsorUid||node.uid===node.sponsorUid)continue;children.set(node.sponsorUid,[...(children.get(node.sponsorUid)??[]),node])}const result:RankNode[]=[],visited=new Set<string>([ownerUid]),queue=[...(children.get(ownerUid)??[])];while(queue.length){const node=queue.shift()!;if(visited.has(node.uid))continue;visited.add(node.uid);result.push(node);queue.push(...(children.get(node.uid)??[]))}return result}
const highestRank=(owner:RankNode,nodes:readonly RankNode[])=>{const downline=getUniqueDownline(owner.uid,nodes),qualifiedTeamCount=downline.filter(node=>isCapitalQualified(node.qualifyingFutureCapital)).length,directs=nodes.filter(node=>node.sponsorUid===owner.uid&&node.uid!==owner.uid);let star=0,directRankCount=0;for(const rank of ranks){const matching=directs.filter(node=>node.currentStar>=rank.directStars.star).length;if(qualifiedTeamCount>=rank.team&&matching>=rank.directStars.count){star=rank.star;directRankCount=matching}}return{star,qualifiedTeamCount,directRankCount}}
export const evaluateUserRank=(owner:RankNode,nodes:readonly RankNode[])=>highestRank(owner,nodes);
export function evaluateRankNetwork(input:readonly RankNode[]):RankEvaluation[]{let nodes=input.map(node=>({...node,rewardedRanks:[...node.rewardedRanks]}));for(let pass=0;pass<8;pass+=1){let changed=false;const next=nodes.map(node=>{const star=highestRank(node,nodes).star;if(star!==node.currentStar)changed=true;return{...node,currentStar:star}});nodes=next;if(!changed)break}return nodes.map(node=>{const status=highestRank(node,nodes),nextRank=ranks.find(rank=>rank.star>status.star),directRankCount=nextRank?nodes.filter(candidate=>candidate.sponsorUid===node.uid&&candidate.uid!==node.uid&&candidate.currentStar>=nextRank.directStars.star).length:status.directRankCount,newRewardRanks=ranks.filter(rank=>rank.star<=status.star&&!node.rewardedRanks.includes(rank.star)).map(rank=>rank.star);return{...node,currentStar:status.star,qualifiedTeamCount:status.qualifiedTeamCount,directRankCount,newRewardRanks}})}
export const salaryEligible=(node:RankNode)=>node.currentStar>0;
