import "server-only";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { migrateWalletStore, money } from "@/lib/wallet-data";
import { getSafeKycForUser } from "@/lib/kyc/kyc-service.server";
import { aiBotStatus } from "@/lib/ai-bot";
import type { SupportAccountContext } from "@/lib/support-rules";
type TeamRow={totalTeam:bigint;qualifiedTeam:bigint;business:Prisma.Decimal};
export async function buildSupportAccountContext(userId:string):Promise<SupportAccountContext>{const[user,team,kyc]=await Promise.all([prisma.user.findUniqueOrThrow({where:{id:userId},select:{uid:true,sponsor:{select:{uid:true}},state:{select:{wallet:true}},aiBotSubscriptions:{orderBy:{activatedAt:"desc"},take:1}}}),prisma.$queryRaw<TeamRow[]>`WITH RECURSIVE team AS (SELECT u."id",s."wallet",ARRAY[u."id"] AS path FROM "User" u LEFT JOIN "UserState" s ON s."userId"=u."id" WHERE u."sponsorId"=${userId} UNION ALL SELECT u."id",s."wallet",team.path||u."id" FROM "User" u JOIN team ON u."sponsorId"=team."id" LEFT JOIN "UserState" s ON s."userId"=u."id" WHERE NOT u."id"=ANY(team.path)), principal AS (SELECT team."id",GREATEST(0,COALESCE(SUM(CASE WHEN e->>'status'='COMPLETED' AND e->>'wallet'='future' AND e->>'type' IN ('SPOT_TO_FUTURE_TRANSFER','FUTURE_TO_SPOT_TRANSFER','ADMIN_FUTURE_ADJUSTMENT') THEN (e->>'amount')::numeric ELSE 0 END),0)) amount FROM team LEFT JOIN LATERAL jsonb_array_elements(COALESCE(team."wallet"->'transactions','[]'::jsonb)) e ON TRUE GROUP BY team."id") SELECT COUNT(*)::bigint AS "totalTeam",COUNT(*) FILTER(WHERE amount>=50)::bigint AS "qualifiedTeam",COALESCE(SUM(amount),0) AS business FROM principal`,getSafeKycForUser(userId).catch(()=>({status:"UNAVAILABLE" as const}))]),wallet=migrateWalletStore(user.state?.wallet),bot=aiBotStatus(user.aiBotSubscriptions[0]??null),network=team[0],pendingDeposits=wallet.transactions.filter(item=>item.status==="PENDING"&&["SPOT_DEPOSIT","NOWPAYMENTS_DEPOSIT"].includes(item.type)).length,pendingWithdrawals=wallet.transactions.filter(item=>item.status==="PENDING"&&item.type==="SPOT_WITHDRAWAL").length;return{uid:user.uid,spotWallet:money(wallet.wallets.spot.balance),futureWallet:money(wallet.wallets.future.balance),currentRank:wallet.rankAccount.currentStar,referralIncome:money(wallet.spotIncome.referralIncome),levelIncome:money(wallet.spotIncome.levelIncome),salary:money(wallet.spotIncome.salaryIncome),reward:money(wallet.spotIncome.rewardIncome),kycStatus:kyc.status,aiBotStatus:bot.status,botExpiry:bot.expiresAt?new Date(bot.expiresAt).toISOString():null,referralLink:`/register?ref=${user.uid}`,qualifiedTeam:Number(network?.qualifiedTeam??0),totalTeam:Number(network?.totalTeam??0),business:money(Number(network?.business??0)),sponsorUid:user.sponsor?.uid??null,pendingDeposits,pendingWithdrawals}}
