export type SupportRuleDefinition={intentKey:string;category:string;title:string;response:string;keywords:string[];examples:string[];followUps:string[];priority:number;isActive:boolean};
export type MatchableRule=SupportRuleDefinition&{id:string};
export type SupportAccountContext={uid:string;spotWallet:number;futureWallet:number;kycStatus:string;currentRank:number;referralIncome:number;levelIncome:number;salary:number;reward:number;aiBotStatus:string;botExpiry:string|null;referralLink:string;qualifiedTeam:number;totalTeam:number;business:number;sponsorUid:string|null;pendingDeposits:number;pendingWithdrawals:number};
const rule=(intentKey:string,category:string,title:string,response:string,keywords:string[],examples:string[],followUps:string[],priority=50):SupportRuleDefinition=>({intentKey,category,title,response,keywords,examples,followUps,priority,isActive:true});
export const supportRuleSeeds:SupportRuleDefinition[]=[
rule("DEPOSIT","Wallet","Deposit","To deposit, open Wallet, choose Deposit, select the supported network, and follow the displayed payment instructions. Always verify the network and address before sending funds.",["deposit","fund add","paisa add","balance add","usdt jama","wallet recharge","jama karna"],["Deposit kaise karu?","How do I deposit?"],["Deposit pending","Spot Wallet"],80),
rule("WITHDRAWAL","Wallet","Withdrawal","To withdraw, open Wallet, choose Withdraw, enter a supported address and network, and confirm the request. Approved KYC is required. The minimum withdrawal is $10 and the fixed fee is $5.",["withdrawal","withdraw","paisa nikalna","fund nikalna","cash out","nikalna"],["How do I withdraw?","Paisa kaise nikalu?"],["KYC","Withdrawal pending"],80),
rule("SPOT_WALLET","Wallet","Spot Wallet","Spot Wallet holds deposits and eligible earned income. Your current Spot Wallet balance is ${{spotWallet}}.",["spot wallet","spot balance","mera spot","wallet balance","balance kitna"],["Mera Spot balance kitna hai?","What is my Spot Wallet balance?"],["Deposit","Spot to Future transfer"],90),
rule("FUTURE_WALLET","Wallet","Future Wallet","Future Wallet holds capital allocated to Copy Trading and credited trading profit. Your current Future Wallet balance is ${{futureWallet}}.",["future wallet","future balance","copy wallet","mera future"],["Future wallet balance kya hai?"],["Future to Spot transfer","Copy Trading"],90),
rule("SPOT_TO_FUTURE","Transfer","Spot to Future transfer","Open Transfer, choose Spot Wallet as the source and Future Wallet as the destination, enter the amount, review it, and confirm. This moves your own funds and is not income.",["spot to future","spot se future","future me transfer","future wallet me bhejna"],["Spot se Future me kaise transfer karu?"],["$50 qualification rule","Future Wallet"],85),
rule("FUTURE_TO_SPOT","Transfer","Future to Spot transfer","Open Transfer, choose Future Wallet as the source and Spot Wallet as the destination, enter the amount, review any applicable deduction, and confirm.",["future to spot","future se spot","spot me transfer","future wallet se nikalna"],["Future wallet se spot me kaise transfer karu?"],["20% early transfer deduction","70% trading target"],90),
rule("EARLY_TRANSFER_DEDUCTION","Transfer","20% early transfer deduction","A Future-to-Spot transfer made before meeting the trading-profit unlock target receives a 20% early-transfer deduction. The transfer screen shows the exact quote before confirmation.",["20 percent","20%","early transfer","early deduction","transfer deduction","kat gaya"],["Why was 20% deducted?"],["70% trading target","Future to Spot transfer"],95),
rule("TRADING_TARGET","Trading","70% trading target","The Future Wallet unlock target is based on completed trading profit reaching 70% of qualifying Future principal. Principal returns and wallet transfers do not count as trading profit.",["70 percent","70%","trading target","profit target","unlock target","future unlock"],["What is the 70% target?"],["Future to Spot transfer","Copy Trading"],95),
rule("REFERRAL_INCOME","Income","Referral Income","Direct Referral Income is credited according to the configured plan when a referral completes the qualifying event. Your recorded Referral Income is ${{referralIncome}}.",["referral","referral income","direct income","sponsor income","5 percent","5%","direct commission"],["Referral income kitni hai?"],["First qualifying transfer","Referral link"],90),
rule("LEVEL_INCOME","Income","Level Income","Level Income follows the configured five-level plan and qualifying rules. Your recorded Level Income is ${{levelIncome}}.",["level income","level commission","five level","5 level","upar income","network income"],["Level income kya hai?"],["$50 qualification rule","Qualified Team"],90),
rule("FIRST_QUALIFYING_TRANSFER","Income","First qualifying transfer","Referral distribution is tied to the first qualifying Spot-to-Future transfer. Repeating transfers does not repeatedly trigger the same first-transfer reward.",["first qualifying transfer","first transfer","pehla transfer","first spot to future"],["What is the first qualifying transfer?"],["$50 qualification rule","Referral Income"],88),
rule("QUALIFICATION_50","Qualification","$50 qualification rule","A qualifying Spot-to-Future principal amount of at least $50 is required for the applicable referral and team qualification rules.",["50 dollar","$50","50 qualification","minimum 50","qualified amount"],["What is the $50 qualification rule?"],["First qualifying transfer","Qualified Team"],92),
rule("RANK","Rank","Rank","Your current rank is {{currentRank}} Star. Rank changes depend on the configured team and direct-rank conditions and are calculated from authoritative account records.",["rank","star rank","mera rank","rank kya","rank status"],["Mera rank kya hai?"],["Rank not updated","Salary"],90),
rule("SALARY","Rank","Salary","Your recorded Salary Income is ${{salary}}. Salary eligibility and payment follow the configured rank and cycle rules.",["salary","salary income","vetan","salary kitni","salary status"],["Meri salary kitni hai?"],["Rank","Rewards"],85),
rule("REWARDS","Rank","Rewards","Your recorded Reward Income is ${{reward}}. Rank rewards are credited only when the configured achievement conditions are met.",["reward","rewards","reward income","inaam","bonus reward"],["My reward amount"],["Rank","Salary"],85),
rule("QUALIFIED_TEAM","Team","Qualified Team","Your current Qualified Team count is {{qualifiedTeam}}. A member is counted only when the configured qualification conditions are satisfied.",["qualified team","qualified members","active team","yogya team"],["Qualified team kitni hai?"],["Total Team","$50 qualification rule"],88),
rule("TOTAL_TEAM","Team","Total Team","Your current Total Team count is {{totalTeam}}.",["total team","team count","meri team","network size","team kitni"],["Meri total team kitni hai?"],["Qualified Team","Total Business"],82),
rule("TOTAL_BUSINESS","Team","Total Business","Your current team business is ${{business}} based on qualifying retained Future principal.",["total business","team business","business kitna","network business"],["Mera total business kitna hai?"],["Qualified Team","Rank"],88),
rule("AI_BOT_SUBSCRIPTION","AI Bot","AI Bot subscription","Your AI Bot status is {{aiBotStatus}}{{botExpiryText}}. Subscription purchases must be completed from the AI Bot section; Support cannot activate a subscription.",["ai bot subscription","bot subscription","bot status","ai bot active","bot kharidna"],["My AI Bot status"],["Bot expiry","AI Bot sponsor income"],88),
rule("AI_BOT_SPONSOR_INCOME","AI Bot","AI Bot sponsor income","AI Bot Sponsor Income is credited to an eligible direct sponsor according to the configured bot-purchase commission rule. Support can explain the record but cannot create or alter a credit.",["ai bot sponsor income","bot sponsor income","bot commission","bot referral income"],["Bot sponsor income kya hai?"],["AI Bot subscription","Income not received"],92),
rule("COPY_TRADING","Trading","Copy Trading","Copy Trading uses the Future Wallet. Open Copy Trading to view the current eligible session, schedule, trade state, and recorded results. Support cannot place or modify trades.",["copy trading","ai copy trading","copy trade","trading kaise","trade schedule"],["How does Copy Trading work?"],["Current trades","Trade history"],82),
rule("CURRENT_TRADES","Trading","Current trades","Open Copy Trading to see the current session and any active or pending trade. Support is read-only and cannot place, cancel, or alter a trade.",["current trade","active trade","live trade","aaj ka trade","trade chal raha"],["Show my current trade"],["Trade history","Copy Trading"],88),
rule("TRADE_HISTORY","Trading","Trade history","Open Transaction History or Copy Trading history to review completed trade records, profit credits, and timestamps.",["trade history","old trades","previous trade","trading record"],["Where is trade history?"],["Transaction history","Current trades"],85),
rule("KYC","Account","KYC","Your current KYC status is {{kycStatus}}. Open KYC Verification to submit or review documents. Support cannot approve or change KYC.",["kyc","verification","document verify","identity verification","kyc status","document status"],["Mera KYC status kya hai?"],["Withdrawal","Profile"],95),
rule("PROFILE","Account","Profile","Open Profile from the Account menu to view your UID, account identity, team summary, and earned-income total.",["profile","my profile","account profile","profile page"],["Where is my profile?"],["Password and security","KYC"],65),
rule("PASSWORD_SECURITY","Account","Password and security","Open Settings or Profile security to change your password. Use a unique password and never share verification codes or credentials. Support cannot reset a password inside chat.",["password","security","change password","password reset","forgot password","account secure"],["Password kaise change karu?"],["Login problem","Account locked"],88),
rule("REFERRAL_LINK","Referral","Referral link","Your referral link is {{referralLink}}. Share only your own link; Support never substitutes another user’s UID.",["referral link","invite link","refer link","link share","mera link"],["Mera referral link do"],["Sponsor UID","Referral Income"],92),
rule("SPONSOR_UID","Referral","Sponsor UID","Your registered Sponsor UID is {{sponsorUid}}. Sponsor relationships cannot be changed through Support chat.",["sponsor uid","sponsor id","mera sponsor","upline uid","referrer uid"],["Mera sponsor UID kya hai?"],["Referral link","Referral Income"],92),
rule("TRANSACTION_HISTORY","Wallet","Transaction history","Open Transaction History from the Account menu to review deposits, withdrawals, transfers, and income ledger entries.",["transaction history","wallet history","ledger","payment history","all transactions"],["Where is transaction history?"],["Deposit pending","Withdrawal pending"],82),
rule("SUPPORT_TICKET","Support","Support ticket","Use Create Support Ticket for an issue that needs account investigation. Add a clear subject, category, description, priority, and an optional supported attachment.",["support ticket","create ticket","complaint","contact support","help ticket"],["Create a support ticket"],["Create Support Ticket"],75),
rule("ACCOUNT_LOCKED","Security","Account locked","If your account is locked, stop repeated login attempts and create a Support Ticket with your UID and a description. Never include your password or verification code.",["account locked","account block","login locked","id locked","account band"],["My account is locked"],["Login problem","Create Support Ticket"],98),
rule("LOGIN_PROBLEM","Security","Login problem","Check your email and password, confirm Caps Lock is off, and retry once. If access still fails, create a Support Ticket. Never send your password in chat.",["login problem","cannot login","login nahi","sign in issue","password not working"],["Login nahi ho raha"],["Password and security","Create Support Ticket"],92),
rule("DEPOSIT_PENDING","Wallet","Deposit pending","You currently have {{pendingDeposits}} pending deposit record(s). Confirm the network and transaction status. If the expected confirmation time has passed, create a ticket with the payment reference.",["deposit pending","deposit nahi aaya","deposit missing","usdt pending","balance add nahi"],["Mera deposit pending hai"],["Transaction history","Create Support Ticket"],100),
rule("WITHDRAWAL_PENDING","Wallet","Withdrawal pending","You currently have {{pendingWithdrawals}} pending withdrawal record(s). Check Transaction History for status. If it remains pending unexpectedly, create a ticket with the withdrawal reference.",["withdrawal pending","withdraw pending","paisa nahi aaya","withdrawal stuck","cash out pending"],["Mera withdrawal pending hai"],["Transaction history","Create Support Ticket"],100),
rule("INCOME_NOT_RECEIVED","Income","Income not received","First identify the missing income type and check Transaction History. Eligibility and idempotency rules may prevent duplicate credits. Support cannot create a credit; submit a ticket with the source UID and transaction reference for investigation.",["income not received","income nahi aayi","commission missing","referral income kyu nahi aayi","salary missing","reward missing"],["Referral income kyu nahi aayi?"],["Transaction history","Create Support Ticket"],105),
rule("BOT_EXPIRY","AI Bot","Bot expiry","Your AI Bot status is {{aiBotStatus}}{{botExpiryText}}. Open the AI Bot section for subscription details and renewal options.",["bot expiry","bot expire","kab expire","bot validity","expiry date"],["Mera bot kab expire hoga?"],["AI Bot subscription","Create Support Ticket"],100),
rule("RANK_NOT_UPDATED","Rank","Rank not updated","Your recorded rank is {{currentRank}} Star. Rank calculation depends on qualifying team and direct-rank conditions. If all conditions are met but the rank remains unchanged, create a ticket for review.",["rank not updated","rank update nahi","rank missing","star nahi mila"],["Mera rank update nahi hua"],["Qualified Team","Create Support Ticket"],105),
rule("TEAM_MEMBER_NOT_SHOWING","Team","Team member not showing","Refresh the Team page and verify that the member registered with your correct referral link or Sponsor UID. Support cannot move members between sponsors. Create a ticket with the member UID if the relationship appears incorrect.",["team member not showing","member missing","team me nahi","referral not showing","downline missing"],["Team member nahi dikh raha"],["Sponsor UID","Create Support Ticket"],105)
,
rule("RANK_AND_SALARY","Rank","Rank and Salary","Your current rank is {{currentRank}} Star and your recorded Salary Income is ${{salary}}. Rank and salary eligibility follow the configured authoritative conditions and payment cycles.",["rank and salary","rank salary","mera rank aur salary","my rank and salary"],["My rank and salary","Mera rank aur salary kya hai?"],["Rank not updated","Salary"],96)
];
const aliases:Record<string,string[]>={SPOT_WALLET:["wallet","my wallet","mera wallet","spot wallet","spot balance","my spot balance"],FUTURE_WALLET:["future wallet","my future balance"],DEPOSIT:["deposit","deposit karna"],WITHDRAWAL:["withdraw","withdrawal","withdrawal karna"],REFERRAL_INCOME:["referral income","my referral income","mera referral income"],LEVEL_INCOME:["level income","my level income","mera level income"],RANK:["rank","my rank","mera rank"],SALARY:["salary","my salary"],REWARDS:["reward","my reward"],QUALIFIED_TEAM:["qualified team"],TOTAL_TEAM:["total team","my team","mera team","team"],TOTAL_BUSINESS:["total business","my business","mera business","business"],KYC:["kyc","my kyc status"],AI_BOT_SUBSCRIPTION:["ai bot","my ai bot","my ai bot status"],BOT_EXPIRY:["bot expiry"],COPY_TRADING:["copy trading","trade"],CURRENT_TRADES:["current trades"],TRADE_HISTORY:["trade history"],REFERRAL_LINK:["referral link"],SPONSOR_UID:["sponsor uid"],LOGIN_PROBLEM:["login problem"],PASSWORD_SECURITY:["password reset"],DEPOSIT_PENDING:["deposit pending"],WITHDRAWAL_PENDING:["withdrawal pending"],INCOME_NOT_RECEIVED:["income not received"],TEAM_MEMBER_NOT_SHOWING:["team member not showing"],RANK_NOT_UPDATED:["rank not updated"],SUPPORT_TICKET:["create support ticket"],RANK_AND_SALARY:["my rank and salary","rank and salary"]};
const variations:ReadonlyArray<[RegExp,string]>=[[/[’`]/g,"'"],[/\bwhat's\b/g,"what is"],[/\bi'm\b/g,"i am"],[/\bcan't\b/g,"cannot"],[/\bdon't\b/g,"do not"],[/\bwithdrawl\b/g,"withdrawal"],[/\bwithdrwal\b/g,"withdrawal"],[/\breferal\b/g,"referral"],[/\bsalery\b/g,"salary"],[/\bbuss?iness\b/g,"business"],[/\bkyc\b/g,"kyc"],[/\bkaise\s+(?:karu|kare|karen|karna)\b/g,"kaise karna"],[/\bnikalu\b/g,"nikalna"]];
export const SUPPORT_MINIMUM_SCORE=20;
export function normalizeSupportText(value:string){let normalized=value.toLowerCase().normalize("NFKC");for(const[pattern,replacement]of variations)normalized=normalized.replace(pattern,replacement);return normalized.replace(/(\d+(?:\.\d+)?)\s*%/g,"$1 percent").replace(/['’]/g,"").replace(/[^a-z0-9$\s]/g," ").replace(/\s+/g," ").trim()}
export function parseSupportStringArray(value:unknown,field="rule field"){if(!Array.isArray(value)||value.some(item=>typeof item!=="string"))throw new Error(`INVALID_SUPPORT_RULE_JSON:${field}`);return value.map(item=>item.trim()).filter(Boolean)}
export type SupportMatch={rule:MatchableRule;score:number;matchedTerms:string[];matchType:"EXACT_EXAMPLE"|"EXACT_PHRASE"|"KEYWORD_SCORE"};
export type SupportMatchDiagnostics={match:SupportMatch|null;normalizedMessage:string;bestRuleIntent:string|null;bestScore:number;minimumThreshold:number;matchedTerms:string[];fallbackReason:string|null};
export function diagnoseSupportRule(message:string,rules:ReadonlyArray<MatchableRule>,minimum=SUPPORT_MINIMUM_SCORE):SupportMatchDiagnostics{const normalized=normalizeSupportText(message),tokens=new Set(normalized.split(" ").filter(Boolean));let best:SupportMatch|null=null,bestBelow:SupportMatch|null=null;for(const rule of rules){if(!rule.isActive)continue;let score=0,matchType:SupportMatch["matchType"]="KEYWORD_SCORE";const terms=new Set<string>();for(const example of rule.examples){const phrase=normalizeSupportText(example);if(phrase===normalized){score=Math.max(score,1000);terms.add(phrase);matchType="EXACT_EXAMPLE"}else if(phrase&&normalized.includes(phrase)){score=Math.max(score,120+phrase.split(" ").length*10);terms.add(phrase)}}for(const keyword of [...rule.keywords,...(aliases[rule.intentKey]??[])]){const phrase=normalizeSupportText(keyword);if(!phrase)continue;const words=phrase.split(" "),exact=normalized===phrase,included=words.length===1?tokens.has(phrase):normalized.includes(phrase);if(exact){score=Math.max(score,500);terms.add(phrase);if(matchType!=="EXACT_EXAMPLE")matchType="EXACT_PHRASE"}else if(included){score+=words.length===1?24:35+words.length*8;terms.add(phrase)}}const candidate={rule,score:Number(score.toFixed(2)),matchedTerms:[...terms].sort(),matchType};const better=(current:SupportMatch|null)=>!current||candidate.score>current.score||candidate.score===current.score&&(rule.priority>current.rule.priority||rule.priority===current.rule.priority&&rule.intentKey.localeCompare(current.rule.intentKey)<0);if(better(bestBelow))bestBelow=candidate;if(score>=minimum&&better(best))best=candidate}return{match:best,normalizedMessage:normalized,bestRuleIntent:(best??bestBelow)?.rule.intentKey??null,bestScore:(best??bestBelow)?.score??0,minimumThreshold:minimum,matchedTerms:(best??bestBelow)?.matchedTerms??[],fallbackReason:best?null:rules.filter(rule=>rule.isActive).length===0?"NO_ACTIVE_RULES":!normalized?"EMPTY_NORMALIZED_MESSAGE":"LOW_CONFIDENCE"}}
export function matchSupportRule(message:string,rules:ReadonlyArray<MatchableRule>,minimum=SUPPORT_MINIMUM_SCORE){return diagnoseSupportRule(message,rules,minimum).match}
export function databaseRule(value:{id:string;intentKey:string;category:string;title:string;response:string;keywordsJson:unknown;examplesJson:unknown;followUpsJson:unknown;priority:number;isActive:boolean}):MatchableRule{return{id:value.id,intentKey:value.intentKey,category:value.category,title:value.title,response:value.response,keywords:parseSupportStringArray(value.keywordsJson,`${value.intentKey}.keywordsJson`),examples:parseSupportStringArray(value.examplesJson,`${value.intentKey}.examplesJson`),followUps:parseSupportStringArray(value.followUpsJson,`${value.intentKey}.followUpsJson`),priority:value.priority,isActive:value.isActive}}
export function renderSupportResponse(template:string,context:SupportAccountContext){const values:Record<string,string>={uid:context.uid,spotWallet:context.spotWallet.toFixed(2),futureWallet:context.futureWallet.toFixed(2),kycStatus:context.kycStatus,currentRank:String(context.currentRank),referralIncome:context.referralIncome.toFixed(2),levelIncome:context.levelIncome.toFixed(2),salary:context.salary.toFixed(2),reward:context.reward.toFixed(2),aiBotStatus:context.aiBotStatus,botExpiryText:context.botExpiry?` and expires on ${new Date(context.botExpiry).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"})}`:" with no active expiry date",referralLink:context.referralLink,qualifiedTeam:String(context.qualifiedTeam),totalTeam:String(context.totalTeam),business:context.business.toFixed(2),sponsorUid:context.sponsorUid??"not assigned",pendingDeposits:String(context.pendingDeposits),pendingWithdrawals:String(context.pendingWithdrawals)};return template.replace(/\{\{([a-zA-Z]+)\}\}/g,(_,key:string)=>values[key]??"")}
export const FALLBACK_RESPONSE="Sorry, I could not understand your question. Please select a topic below or create a support ticket.";
export const FALLBACK_TOPICS=["How do I deposit?","How do I withdraw?","My Spot balance","My referral income","My level income","My KYC status","My rank and salary","How does Copy Trading work?","My AI Bot status","Create a support ticket"];
