export type LocalTimestamp={timestampUtc:string;localDate:string;localTime:string;localDateTime:string};
const countryZones:Record<string,string>={india:"Asia/Kolkata",bangladesh:"Asia/Dhaka",pakistan:"Asia/Karachi","united arab emirates":"Asia/Dubai",uae:"Asia/Dubai","united kingdom":"Europe/London",uk:"Europe/London","united states":"America/New_York",usa:"America/New_York"};

export function isValidIanaTimeZone(value:unknown):value is string{if(typeof value!=="string"||(!value.includes("/")&&value!=="UTC")||/^[+-]\d/.test(value))return false;try{new Intl.DateTimeFormat("en-US",{timeZone:value}).format(0);return true}catch{return false}}
export function timeZoneForCountry(country:unknown){return typeof country==="string"?countryZones[country.trim().toLowerCase()]??null:null}
export function resolveUserTimeZone(timezone:unknown,country?:unknown){return isValidIanaTimeZone(timezone)?timezone:timeZoneForCountry(country)??"UTC"}
export function formatUserTimestamp(timestamp:Date|number|string,timezone:unknown,country?:unknown):LocalTimestamp{const date=timestamp instanceof Date?timestamp:new Date(timestamp),timeZone=resolveUserTimeZone(timezone,country);if(Number.isNaN(date.getTime()))throw new Error("Invalid UTC timestamp.");const localDate=new Intl.DateTimeFormat("en-GB",{timeZone,day:"2-digit",month:"short",year:"numeric"}).format(date),localTime=new Intl.DateTimeFormat("en-US",{timeZone,hour:"numeric",minute:"2-digit",hour12:true}).format(date);return{timestampUtc:date.toISOString(),localDate,localTime,localDateTime:`${localDate}, ${localTime}`}}
export function localCalendarDate(timestamp:Date|number|string,timezone:unknown,country?:unknown){const date=timestamp instanceof Date?timestamp:new Date(timestamp),timeZone=resolveUserTimeZone(timezone,country),parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date),get=(type:string)=>parts.find(part=>part.type===type)?.value??"";return`${get("year")}-${get("month")}-${get("day")}`}
export function startOfLocalMonthUtc(timestamp:Date|number|string,timezone:unknown,country?:unknown){const date=timestamp instanceof Date?timestamp:new Date(timestamp),timeZone=resolveUserTimeZone(timezone,country),parts=new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"numeric"}).formatToParts(date),year=Number(parts.find(part=>part.type==="year")?.value),month=Number(parts.find(part=>part.type==="month")?.value),wallUtc=Date.UTC(year,month-1,1),offsetAt=(instant:number)=>{const values=new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(instant),read=(type:string)=>Number(values.find(part=>part.type===type)?.value);return Date.UTC(read("year"),read("month")-1,read("day"),read("hour"),read("minute"),read("second"))-instant},first=wallUtc-offsetAt(wallUtc);return new Date(wallUtc-offsetAt(first))}
