import { prisma } from "@/lib/prisma";
import { createDailySessions,migrateTradingStore } from "@/lib/ai-trading-engine";
import { mergeVisibleTrades,type VisibleTrade } from "@/lib/trade-history-compat";
import { resolveAuthoritativeTradeSource,resolveLegacyTradeSource } from "@/lib/trade-source";

const direction=(value:string):"BUY"|"SELL"=>value==="CALL"||value==="BUY"?"BUY":"SELL";

export async function loadVisibleTradeHistory(userId:string,limit=500,now=Date.now()){
  const[state,relational,executions,migrations,failedCreationJobs]=await Promise.all([
    prisma.userState.findUnique({where:{userId},select:{trading:true}}),
    prisma.aiFinancialTrade.findMany({where:{userId},include:{sessionRun:true},orderBy:{officialStartedAt:"desc"},take:limit}),
    prisma.aiBotTradeExecution.findMany({where:{userId},orderBy:{placedAt:"desc"},take:limit}),
    prisma.aiLegacyTradeMigration.findMany({where:{userId,status:"MIGRATED"},select:{sourceId:true,details:true}}),
    prisma.aiTradeJob.findMany({where:{userId,kind:"CREATE",status:{in:["FAILED","DEAD"]}},include:{sessionRun:true},orderBy:{updatedAt:"desc"},take:limit})
  ]);
  const relationalVisible:VisibleTrade[]=relational.map(trade=>({id:trade.id,source:"RELATIONAL",sourceId:trade.id,executionKey:trade.executionKey,sessionId:trade.sessionRun.sessionId,pair:trade.sessionRun.pair,direction:direction(trade.sessionRun.direction),placementSource:resolveAuthoritativeTradeSource({placementSource:trade.placementSource,tradeType:trade.tradeType,sessionTradeType:trade.sessionRun.tradeType}),status:trade.status==="SETTLED"?"SETTLED":trade.status==="FAILED"?"FAILED":"CAPITAL_LOCKED",profitReceived:trade.status==="SETTLED"?Number(trade.profit):null,placedAt:trade.officialStartedAt.getTime(),settledAt:trade.officialSettledAt?.getTime()??null,principal:Number(trade.principal),balanceSnapshot:Number(trade.balanceSnapshot),profitRate:Number(trade.profitRate)}));
  const relationalRunKeys=new Set(relational.map(trade=>`${trade.sessionRunId}:${trade.tradeType}`)),failedVisible:VisibleTrade[]=failedCreationJobs.filter(job=>!relationalRunKeys.has(`${job.sessionRunId}:${job.sessionRun.tradeType}`)).map(job=>({id:`job:${job.id}`,source:"RELATIONAL_JOB",sourceId:job.id,executionKey:job.jobKey,sessionId:job.sessionRun.sessionId,pair:job.sessionRun.pair,direction:direction(job.sessionRun.direction),placementSource:resolveAuthoritativeTradeSource({tradeType:job.sessionRun.tradeType,sessionTradeType:job.sessionRun.tradeType}),status:"FAILED",profitReceived:null,placedAt:job.updatedAt.getTime(),settledAt:null,principal:0,balanceSnapshot:0,profitRate:Number(job.sessionRun.profitRate)}));
  const legacyStore=migrateTradingStore(state?.trading),executionByTradeId=new Map(executions.map(item=>[item.tradeId,item])),legacyVisible:VisibleTrade[]=legacyStore.trades.map(trade=>{const execution=executionByTradeId.get(trade.id),zone=trade.sessionTimeZone??execution?.timeZone??"Asia/Kolkata",session=createDailySessions(new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(trade.placedAt)),trade.placedAt,zone).find(item=>item.id===trade.sessionId),stale=Boolean(session&&now>=session.settlesAt);return{id:`legacy:${trade.id}`,source:"LEGACY_COMPATIBILITY",sourceId:execution?.id??trade.id,executionKey:execution?.executionKey??trade.idempotencyKey,sessionId:trade.sessionId,pair:session?.pair??"AI/USDT",direction:direction(trade.direction),placementSource:resolveLegacyTradeSource({placementSource:trade.placementSource,hasAiBotExecution:Boolean(execution)}),status:trade.status==="SETTLED"?"SETTLED":trade.status==="MISSED"?"MISSED":stale?"FAILED":"CAPITAL_LOCKED",profitReceived:trade.status==="SETTLED"?trade.profitAmount:null,placedAt:trade.placedAt,settledAt:trade.settledAt,principal:trade.tradeCapital,balanceSnapshot:trade.balanceSnapshot,profitRate:trade.profitRate}});
  const representedExecutionIds=new Set(legacyVisible.map(item=>item.sourceId)),executionOnly:VisibleTrade[]=executions.filter(item=>!representedExecutionIds.has(item.id)).map(item=>{const session=createDailySessions(item.tradingDate,item.placedAt.getTime(),item.timeZone).find(value=>value.id===item.sessionId),stale=Boolean(session&&now>=session.settlesAt);return{id:`legacy-execution:${item.id}`,source:"LEGACY_COMPATIBILITY",sourceId:item.id,executionKey:item.executionKey,sessionId:item.sessionId,pair:session?.pair??"AI/USDT",direction:direction(session?.signalDirection??"CALL"),placementSource:"AI_BOT",status:item.status==="SETTLED"?"SETTLED":item.status==="FAILED"||stale?"FAILED":"CAPITAL_LOCKED",profitReceived:null,placedAt:item.placedAt.getTime(),settledAt:item.settledAt?.getTime()??null,principal:0,balanceSnapshot:0,profitRate:0}});
  const migrated=new Set(migrations.flatMap(item=>{const detail=item.details&&typeof item.details==="object"&&!Array.isArray(item.details)?item.details as Record<string,unknown>:null;return[item.sourceId,typeof detail?.legacyTradeId==="string"?detail.legacyTradeId:""]}).filter(Boolean));
  return mergeVisibleTrades([...relationalVisible,...failedVisible],[...legacyVisible,...executionOnly],migrated).slice(0,limit);
}
