import { getUplineChain, teamMembers, type SponsorRecord } from "./referral-team-data";
import { evaluateRankNetwork, type RankNode } from "./rank-engine";
import { ranks } from "./config";

export type WalletId="spot"|"future";
export type WalletTransactionType=
  |"SPOT_DEPOSIT"|"NOWPAYMENTS_DEPOSIT"|"ADMIN_FUND_DEDUCTION"|"SPOT_REFERRAL_INCOME"|"SPOT_LEVEL_INCOME"|"SPOT_SALARY_INCOME"|"ADMIN_FUTURE_ADJUSTMENT"
  |"SPOT_REWARD_INCOME"|"SPOT_FUTURE_TRANSFER_INCOME"|"SPOT_OTHER_INCOME"
  |"SPOT_TO_FUTURE_TRANSFER"|"FUTURE_TO_SPOT_TRANSFER"|"FUTURE_EARLY_TRANSFER_FEE"|"FUTURE_AI_TRADING_PROFIT"|"SPOT_WITHDRAWAL"
  |"AI_BOT_PURCHASE"|"AI_TRADE_CAPITAL_LOCK"|"AI_TRADE_CAPITAL_RETURN"|"AI_REGULAR_TRADE_PROFIT"|"AI_ADDITIONAL_TRADE_PROFIT";
export type TransactionStatus="COMPLETED"|"PENDING"|"DEMO"|"REJECTED";
export type TransferLedgerDetails={grossAmount:number;deductionAmount:number;netAmount:number;progressPercentage:number};
export type WithdrawalLedgerDetails={requestedAmount:number;fee:number;netAmount:number;network:"BEP20"|"TRC20"|"ERC20";address:string};
export type AiTradeLedgerDetails={userUid:string;sessionId:string;pair:string;direction:"CALL"|"PUT";grossFutureBalance:number;tradeCapital:number;profitPercentage:number;profitAmount:number};
export type WalletTransaction={id:string;userId:string;wallet:WalletId;type:WalletTransactionType;title:string;amount:number;balanceBefore:number;balanceAfter:number;status:TransactionStatus;reference:string;timestamp:number;transferDetails?:TransferLedgerDetails;withdrawalDetails?:WithdrawalLedgerDetails;aiTradeDetails?:AiTradeLedgerDetails};
export type SpotIncomeBreakdown={deposit:number;referralIncome:number;levelIncome:number;salaryIncome:number;rewardIncome:number;futureWalletTransfer:number;otherIncome:number};
export type WalletAccount={id:WalletId;name:"Spot Wallet"|"Future Wallet";balance:number;color:string};
export type ReferralQualification={consumed:boolean;firstTransferAmount:number|null;qualified:boolean};
export type RankAccountState={qualifyingFutureCapital:number;currentStar:number;qualifiedTeamCount:number;directRankCount:number;rewardedRanks:number[]};
export type ReferralCommissionType="DIRECT_REFERRAL_INCOME"|"LEVEL_1_INCOME"|"LEVEL_2_INCOME"|"LEVEL_3_INCOME"|"LEVEL_4_INCOME"|"LEVEL_5_INCOME";
export type ReferralCommission={id:string;sourceUserId:string;sourceUserUid:string;recipientUserId:string;recipientUserUid:string;sponsorUid:string;commissionType:ReferralCommissionType;level:number;percentage:number;amount:number;sourceTransferReference:string;timestamp:number;status:"COMPLETED"};
export type WalletStore={version:2;wallets:Record<WalletId,WalletAccount>;spotIncome:SpotIncomeBreakdown;totalFuturePrincipal:number;totalCompletedTradingProfit:number;lockedFutureTradeCapital:number;transactions:WalletTransaction[];processedKeys:string[];referralQualification:ReferralQualification;referralCommissions:ReferralCommission[];referralRecipientSpotBalances:Record<string,number>;rankAccount:RankAccountState};
export type FutureWalletMetrics={totalFuturePrincipal:number;totalCompletedTradingProfit:number;requiredProfitForUnlock:number;remainingProfitForUnlock:number;unlockProgressPercentage:number;futureToSpotUnlocked:boolean;transferableBalance:number};
export type WalletTransferQuote={grossAmount:number;earlyTransferFee:number;netCredit:number;earlyTransfer:boolean;progressPercentage:number};

const cents=(value:number)=>Math.round((Number.isFinite(value)?value:0)*100);
const DEMO_USER_ID="BTV10001";
export const money=(value:number)=>cents(value)/100;
export const addMoney=(a:number,b:number)=>money((cents(a)+cents(b))/100);
export const subtractMoney=(a:number,b:number)=>money((cents(a)-cents(b))/100);
export const MINIMUM_WITHDRAWAL_AMOUNT=10;
export const FIXED_WITHDRAWAL_FEE=5;
export function requestSpotWithdrawal(store:WalletStore,input:{key:string;userId:string;amount:number;network:WithdrawalLedgerDetails["network"];address:string;timestamp:number}){const requestedAmount=money(input.amount);if(requestedAmount<MINIMUM_WITHDRAWAL_AMOUNT)throw new Error("Minimum withdrawal amount is $10.");if(hasProcessed(store,input.key))return store;const before=store.wallets.spot.balance;if(requestedAmount>before)throw new Error("Insufficient Spot Wallet balance.");const fee=FIXED_WITHDRAWAL_FEE,netAmount=subtractMoney(requestedAmount,fee),after=subtractMoney(before,requestedAmount),details:WithdrawalLedgerDetails={requestedAmount,fee,netAmount,network:input.network,address:input.address},record:WalletTransaction={id:`${input.key}:withdrawal`,userId:input.userId,wallet:"spot",type:"SPOT_WITHDRAWAL",title:"Withdrawal requested",amount:-requestedAmount,balanceBefore:before,balanceAfter:after,status:"PENDING",reference:`withdrawal:${input.key}`,timestamp:input.timestamp,withdrawalDetails:details};return{...store,wallets:{...store.wallets,spot:{...store.wallets.spot,balance:after}},transactions:[record,...store.transactions],processedKeys:[input.key,...store.processedKeys]}}
const now=Date.now();
const tx=(id:string,wallet:WalletId,type:WalletTransactionType,title:string,amount:number,before:number,after:number,reference:string,timestamp:number=now):WalletTransaction=>({id,userId:DEMO_USER_ID,wallet,type,title,amount:money(amount),balanceBefore:money(before),balanceAfter:money(after),status:"COMPLETED",reference,timestamp});

export const walletSeed:WalletStore={version:2,wallets:{
  spot:{id:"spot",name:"Spot Wallet",balance:0,color:"#5878ed"},
  future:{id:"future",name:"Future Wallet",balance:0,color:"#6557db"},
},spotIncome:{deposit:0,referralIncome:0,levelIncome:0,salaryIncome:0,rewardIncome:0,futureWalletTransfer:0,otherIncome:0},totalFuturePrincipal:0,totalCompletedTradingProfit:0,lockedFutureTradeCapital:0,processedKeys:[],referralQualification:{consumed:false,firstTransferAmount:null,qualified:false},referralCommissions:[],referralRecipientSpotBalances:{},rankAccount:{qualifyingFutureCapital:0,currentStar:0,qualifiedTeamCount:0,directRankCount:0,rewardedRanks:[]},transactions:[]};

export const WALLET_STORE_KEY="bitvora-wallet-store-v3";
export const LEGACY_WALLET_STORE_KEY="bitvora-wallet-store-v1";
export const cloneWalletSeed=():WalletStore=>JSON.parse(JSON.stringify(walletSeed));
export const getFutureMetrics=(store:WalletStore):FutureWalletMetrics=>{const required=money(store.totalFuturePrincipal*.7),remaining=Math.max(0,subtractMoney(required,store.totalCompletedTradingProfit)),progress=required<=0?100:Math.min(100,Number((store.totalCompletedTradingProfit/required*100).toFixed(2))),unlocked=required<=0||store.totalCompletedTradingProfit>=required;return{totalFuturePrincipal:store.totalFuturePrincipal,totalCompletedTradingProfit:store.totalCompletedTradingProfit,requiredProfitForUnlock:required,remainingProfitForUnlock:remaining,unlockProgressPercentage:progress,futureToSpotUnlocked:unlocked,transferableBalance:store.wallets.future.balance}};
export const hasProcessed=(store:WalletStore,key:string)=>store.processedKeys.includes(key);
export function calculateFirstTransferCommissions(amount:number,reference:string,timestamp=Date.now(),sourceUserId=DEMO_USER_ID,genealogy:readonly SponsorRecord[]=teamMembers):ReferralCommission[]{const value=money(amount);if(value<50)return[];const chain=getUplineChain(sourceUserId,6,genealogy),directSponsor=chain[0];if(!directSponsor)return[];const byId=new Map(genealogy.map(member=>[member.id,member])),uidOf=(id:string)=>id===DEMO_USER_ID?"BV100001":byId.get(id)?.uid??"",sourceUserUid=uidOf(sourceUserId),sponsorUid=uidOf(directSponsor);if(!sourceUserUid||!sponsorUid)return[];const direct:ReferralCommission={id:`${reference}:direct`,sourceUserId,sourceUserUid,recipientUserId:directSponsor,recipientUserUid:sponsorUid,sponsorUid,commissionType:"DIRECT_REFERRAL_INCOME",level:0,percentage:5,amount:money(value*.05),sourceTransferReference:reference,timestamp,status:"COMPLETED"};const levels=chain.slice(1,6).flatMap((recipientUserId,index):ReferralCommission[]=>{const level=index+1,recipientUserUid=uidOf(recipientUserId);return recipientUserUid?[{id:`${reference}:level-${level}`,sourceUserId,sourceUserUid,recipientUserId,recipientUserUid,sponsorUid,commissionType:`LEVEL_${level}_INCOME` as ReferralCommissionType,level,percentage:1,amount:money(value*.01),sourceTransferReference:reference,timestamp,status:"COMPLETED"}]:[]});return[direct,...levels]}
export function getTransferQuote(store:WalletStore,from:WalletId,amount:number):WalletTransferQuote{const gross=money(amount),metrics=getFutureMetrics(store),early=from==="future"&&!metrics.futureToSpotUnlocked,fee=early?money(gross*.2):0;return{grossAmount:gross,earlyTransferFee:fee,netCredit:subtractMoney(gross,fee),earlyTransfer:early,progressPercentage:metrics.unlockProgressPercentage}}
const evaluateCurrentRank=(store:WalletStore,qualifyingFutureCapital:number,currentUid:string,genealogy:readonly SponsorRecord[])=>{const network:RankNode[]=[{uid:currentUid,sponsorUid:genealogy.find(member=>member.uid===currentUid)?.sponsorUid??"",qualifyingFutureCapital,currentStar:store.rankAccount.currentStar,rewardedRanks:store.rankAccount.rewardedRanks},...genealogy.filter(member=>member.uid&&member.uid!==currentUid).map(member=>({uid:member.uid!,sponsorUid:member.sponsorUid??"",qualifyingFutureCapital:member.qualifyingFutureCapital??0,currentStar:member.currentStar??0,rewardedRanks:member.rewardedRanks??[]}))],evaluated=evaluateRankNetwork(network).find(node=>node.uid===currentUid)!,newRewards=evaluated.newRewardRanks.filter(star=>!store.rankAccount.rewardedRanks.includes(star)),rewardAmount=money(newRewards.reduce((sum,star)=>sum+(ranks.find(rank=>rank.star===star)?.reward??0),0));return{rankAccount:{qualifyingFutureCapital,currentStar:evaluated.currentStar,qualifiedTeamCount:evaluated.qualifiedTeamCount,directRankCount:evaluated.directRankCount,rewardedRanks:[...new Set([...store.rankAccount.rewardedRanks,...newRewards])]},newRewards,rewardAmount}}
export function transferBetweenWallets(store:WalletStore,from:WalletId,amount:number,key:string,timestamp=Date.now(),context:{sourceUserId?:string;genealogy?:readonly SponsorRecord[];distributeReferrals?:boolean}={}):WalletStore{
  const value=money(amount);if(hasProcessed(store,key))return store;if(value<=0)throw new Error("Transfer amount must be greater than zero.");
  const to:WalletId=from==="spot"?"future":"spot",source=store.wallets[from],target=store.wallets[to];if(value>source.balance)throw new Error(`Insufficient ${source.name} balance.`);
  const quote=getTransferQuote(store,from,value),sourceAfter=subtractMoney(source.balance,value),targetAfter=addMoney(target.balance,quote.netCredit),type=from==="spot"?"SPOT_TO_FUTURE_TRANSFER":"FUTURE_TO_SPOT_TRANSFER",reference=`wallet-transfer:${key}`,details:TransferLedgerDetails={grossAmount:value,deductionAmount:quote.earlyTransferFee,netAmount:quote.netCredit,progressPercentage:quote.progressPercentage},debit={...tx(`${key}:debit`,from,type,`${source.name} to ${target.name}`,-value,source.balance,sourceAfter,reference,timestamp),transferDetails:details},credit={...tx(`${key}:credit`,to,type,`${source.name} to ${target.name}`,quote.netCredit,target.balance,targetAfter,reference,timestamp),transferDetails:details},fee=quote.earlyTransferFee>0?{...tx(`${key}:fee`,"future","FUTURE_EARLY_TRANSFER_FEE","20% early-transfer deduction",-quote.earlyTransferFee,sourceAfter,sourceAfter,reference,timestamp),transferDetails:details}:null,firstOpportunity=from==="spot"&&!store.referralQualification.consumed,qualified=firstOpportunity&&value>=50,sourceUserId=context.sourceUserId??DEMO_USER_ID,commissions=qualified&&context.distributeReferrals!==false?calculateFirstTransferCommissions(value,reference,timestamp,sourceUserId,context.genealogy??teamMembers):[],recipientBalances=commissions.reduce((balances,commission)=>({...balances,[commission.recipientUserUid]:addMoney(balances[commission.recipientUserUid]??0,commission.amount)}),{...store.referralRecipientSpotBalances});
  const currentUid=context.genealogy?.find(member=>member.id===sourceUserId)?.uid??"",qualifyingCapital=from==="spot"?addMoney(store.rankAccount.qualifyingFutureCapital,value):Math.max(0,subtractMoney(store.rankAccount.qualifyingFutureCapital,Math.min(value,store.rankAccount.qualifyingFutureCapital))),rankResult=evaluateCurrentRank(store,qualifyingCapital,currentUid,context.genealogy??[]),baseSpotBalance=from==="spot"?sourceAfter:targetAfter,finalSpotBalance=addMoney(baseSpotBalance,rankResult.rewardAmount);let runningSpot=baseSpotBalance;const rewardTransactions=rankResult.newRewards.map(star=>{const reward=ranks.find(rank=>rank.star===star)!.reward,before=runningSpot,after=addMoney(before,reward);runningSpot=after;return tx(`STAR_RANK_REWARD:${currentUid}:RANK_${star}`,"spot","SPOT_REWARD_INCOME",`${star} Star achievement reward`,reward,before,after,`STAR_RANK_REWARD:${currentUid}:RANK_${star}`,timestamp)});
  return{...store,wallets:{...store.wallets,[from]:{...source,balance:sourceAfter},[to]:{...target,balance:targetAfter},spot:{...store.wallets.spot,balance:finalSpotBalance}},totalFuturePrincipal:from==="spot"?addMoney(store.totalFuturePrincipal,value):store.totalFuturePrincipal,spotIncome:{...(from==="future"?{...store.spotIncome,futureWalletTransfer:addMoney(store.spotIncome.futureWalletTransfer,quote.netCredit)}:store.spotIncome),rewardIncome:addMoney(store.spotIncome.rewardIncome,rankResult.rewardAmount)},transactions:[debit,credit,...(fee?[fee]:[]),...rewardTransactions,...store.transactions],processedKeys:[key,...store.processedKeys],referralQualification:firstOpportunity?{consumed:true,firstTransferAmount:value,qualified}:store.referralQualification,referralCommissions:[...commissions,...store.referralCommissions],referralRecipientSpotBalances:recipientBalances,rankAccount:rankResult.rankAccount};
}
export function creditFutureTradingProfit(store:WalletStore,amount:number,key:string,timestamp=Date.now()):WalletStore{const value=money(amount);if(hasProcessed(store,key))return store;if(value<=0)throw new Error("Trading profit must be greater than zero.");const before=store.wallets.future.balance,after=addMoney(before,value);return{...store,wallets:{...store.wallets,future:{...store.wallets.future,balance:after}},totalCompletedTradingProfit:addMoney(store.totalCompletedTradingProfit,value),transactions:[tx(`${key}:profit`,"future","FUTURE_AI_TRADING_PROFIT","AI copy trading profit",value,before,after,`ai-trade:${key}`,timestamp),...store.transactions],processedKeys:[key,...store.processedKeys]};}
export function creditSpotDeposit(store:WalletStore,input:{key:string;userId:string;amount:number;title:string;reference:string;timestamp:number;type?:"SPOT_DEPOSIT"|"NOWPAYMENTS_DEPOSIT"}){if(hasProcessed(store,input.key))return store;const amount=money(input.amount);if(amount<=0)throw new Error("Verified deposit amount must be positive.");const before=store.wallets.spot.balance,after=addMoney(before,amount),record:WalletTransaction={id:`${input.key}:credit`,userId:input.userId,wallet:"spot",type:input.type??"SPOT_DEPOSIT",title:input.title,amount,balanceBefore:before,balanceAfter:after,status:"COMPLETED",reference:input.reference,timestamp:input.timestamp};return{...store,wallets:{...store.wallets,spot:{...store.wallets.spot,balance:after}},spotIncome:{...store.spotIncome,deposit:addMoney(store.spotIncome.deposit,amount)},transactions:[record,...store.transactions],processedKeys:[input.key,...store.processedKeys]}}
export function creditNowPaymentsDeposit(store:WalletStore,input:{providerPaymentId:string;orderId:string;network:string;amount:number;txHash:string|null;timestamp:number}){const key=`NOWPAYMENTS_DEPOSIT_CREDIT:${input.providerPaymentId}`;return creditSpotDeposit(store,{key,userId:DEMO_USER_ID,amount:input.amount,title:"NOWPayments USDT deposit",reference:`NOWPayments ${input.providerPaymentId} · ${input.orderId} · ${input.network}${input.txHash?` · ${input.txHash}`:""}`,timestamp:input.timestamp,type:"NOWPAYMENTS_DEPOSIT"})}
export function deductSpotFund(store:WalletStore,input:{key:string;userId:string;amount:number;title:string;reference:string;timestamp:number}){if(hasProcessed(store,input.key))return store;const amount=money(input.amount);if(amount<=0)throw new Error("Deduction amount must be positive.");const before=store.wallets.spot.balance;if(amount>before)throw new Error("Insufficient Spot Wallet balance.");const after=subtractMoney(before,amount),record:WalletTransaction={id:`${input.key}:debit`,userId:input.userId,wallet:"spot",type:"ADMIN_FUND_DEDUCTION",title:input.title,amount:-amount,balanceBefore:before,balanceAfter:after,status:"COMPLETED",reference:input.reference,timestamp:input.timestamp};return{...store,wallets:{...store.wallets,spot:{...store.wallets.spot,balance:after}},transactions:[record,...store.transactions],processedKeys:[input.key,...store.processedKeys]}}
export function purchaseAiBotFromSpot(store:WalletStore,input:{key:string;userId:string;amount:number;timestamp:number}){if(hasProcessed(store,input.key))return store;const amount=money(input.amount);if(amount<=0)throw new Error("AI Bot price must be positive.");const before=store.wallets.spot.balance;if(amount>before)throw new Error("Insufficient Spot Wallet balance.");const after=subtractMoney(before,amount),reference=`ai-bot:${input.key}`,record:WalletTransaction={id:`${input.key}:debit`,userId:input.userId,wallet:"spot",type:"AI_BOT_PURCHASE",title:"AI Bot 30-day subscription",amount:-amount,balanceBefore:before,balanceAfter:after,status:"COMPLETED",reference,timestamp:input.timestamp};return{...store,wallets:{...store.wallets,spot:{...store.wallets.spot,balance:after}},transactions:[record,...store.transactions],processedKeys:[input.key,...store.processedKeys]}}
export function lockFutureTradeCapital(store:WalletStore,amount:number,key:string,details:AiTradeLedgerDetails,timestamp:number):WalletStore{const value=money(amount);if(hasProcessed(store,key))return store;if(value<=0||value>store.wallets.future.balance)throw new Error("Insufficient available Future Wallet balance.");const before=store.wallets.future.balance,after=subtractMoney(before,value),record={...tx(`${key}:lock`,"future","AI_TRADE_CAPITAL_LOCK","AI trade capital locked",-value,before,after,key,timestamp),aiTradeDetails:details};return{...store,wallets:{...store.wallets,future:{...store.wallets.future,balance:after}},lockedFutureTradeCapital:addMoney(store.lockedFutureTradeCapital,value),transactions:[record,...store.transactions],processedKeys:[key,...store.processedKeys]}}
export function settleFutureTrade(store:WalletStore,input:{capital:number;profit:number;key:string;additional:boolean;details:AiTradeLedgerDetails;timestamp:number}):WalletStore{if(hasProcessed(store,input.key))return store;const capital=money(input.capital),profit=money(input.profit);if(capital<=0||store.lockedFutureTradeCapital<capital)throw new Error("Locked trade capital is unavailable.");const before=store.wallets.future.balance,capitalAfter=addMoney(before,capital),profitAfter=addMoney(capitalAfter,profit),capitalRecord={...tx(`${input.key}:capital`,"future","AI_TRADE_CAPITAL_RETURN","AI trade capital returned",capital,before,capitalAfter,input.key,input.timestamp),aiTradeDetails:input.details},profitRecord={...tx(`${input.key}:profit`,"future",input.additional?"AI_ADDITIONAL_TRADE_PROFIT":"AI_REGULAR_TRADE_PROFIT",input.additional?"Additional AI trade profit":"Regular AI trade profit",profit,capitalAfter,profitAfter,input.key,input.timestamp),aiTradeDetails:input.details};return{...store,wallets:{...store.wallets,future:{...store.wallets.future,balance:profitAfter}},lockedFutureTradeCapital:subtractMoney(store.lockedFutureTradeCapital,capital),totalCompletedTradingProfit:addMoney(store.totalCompletedTradingProfit,profit),transactions:[profitRecord,capitalRecord,...store.transactions],processedKeys:[input.key,...store.processedKeys]}}

type LegacyWallet={id:string;name:string;balance:number};
type LegacyTransaction={id:string;type:string;title:string;wallet:string;amount:number;timestamp:number;status:string;detail:string};
type LegacyStore={version:1;wallets:LegacyWallet[];transactions:LegacyTransaction[]};
const legacyType=(item:LegacyTransaction):WalletTransactionType=>{if(item.type==="Trading Profit")return"FUTURE_AI_TRADING_PROFIT";if(item.type==="Deposit")return"SPOT_DEPOSIT";if(item.type==="Referral")return"SPOT_REFERRAL_INCOME";if(item.type==="Salary")return"SPOT_SALARY_INCOME";if(item.type==="Withdrawal")return"SPOT_WITHDRAWAL";if(item.type==="Reward"&&item.detail.toLowerCase().includes("level"))return"SPOT_LEVEL_INCOME";if(item.type==="Reward")return"SPOT_REWARD_INCOME";if(item.type==="Transfer"&&item.wallet.toLowerCase().includes("copy"))return"SPOT_TO_FUTURE_TRANSFER";return"SPOT_OTHER_INCOME"};
export function migrateWalletStore(value:unknown):WalletStore{
  if(value&&typeof value==="object"&&"version" in value){
    if((value as {version:number}).version===2){const current=value as WalletStore,first=current.transactions.filter(item=>item.type==="SPOT_TO_FUTURE_TRANSFER"&&item.wallet==="spot").sort((a,b)=>a.timestamp-b.timestamp)[0],firstAmount=first?Math.abs(first.amount):null,qualification=current.referralQualification??{consumed:Boolean(first),firstTransferAmount:firstAmount,qualified:(firstAmount??0)>=50};return{...current,lockedFutureTradeCapital:current.lockedFutureTradeCapital??0,referralQualification:qualification,referralCommissions:current.referralCommissions??[],referralRecipientSpotBalances:current.referralRecipientSpotBalances??{},rankAccount:current.rankAccount??{qualifyingFutureCapital:current.totalFuturePrincipal,currentStar:0,qualifiedTeamCount:0,directRankCount:0,rewardedRanks:[]}}}
    if((value as {version:number}).version===1){const legacy=value as LegacyStore,byId=(id:string)=>money(legacy.wallets.find(wallet=>wallet.id===id)?.balance??0),futureBalance=byId("copy"),profit=money(legacy.transactions.filter(item=>item.type==="Trading Profit"&&item.status==="Completed").reduce((sum,item)=>sum+Math.max(0,item.amount),0)),spotBalance=money(legacy.wallets.filter(wallet=>wallet.id!=="copy").reduce((sum,wallet)=>sum+wallet.balance,0)),referral=money(legacy.transactions.filter(item=>item.type==="Referral"&&item.amount>0).reduce((sum,item)=>sum+item.amount,0)),level=money(legacy.transactions.filter(item=>item.type==="Reward"&&item.detail.toLowerCase().includes("level")&&item.amount>0).reduce((sum,item)=>sum+item.amount,0)),first=legacy.transactions.filter(item=>item.type==="Transfer"&&item.wallet.toLowerCase().includes("copy")).sort((a,b)=>a.timestamp-b.timestamp)[0],firstAmount=first?Math.abs(first.amount):null,qualified=(firstAmount??0)>=50;return{version:2,wallets:{spot:{...walletSeed.wallets.spot,balance:spotBalance},future:{...walletSeed.wallets.future,balance:futureBalance}},spotIncome:{deposit:byId("funding"),referralIncome:referral,levelIncome:level,salaryIncome:byId("salary"),rewardIncome:Math.max(0,money(byId("reward")-referral-level)),futureWalletTransfer:0,otherIncome:byId("spot")},totalFuturePrincipal:Math.max(0,subtractMoney(futureBalance,profit)),totalCompletedTradingProfit:profit,lockedFutureTradeCapital:0,transactions:legacy.transactions.map(item=>({id:`legacy:${item.id}`,userId:DEMO_USER_ID,wallet:item.wallet.toLowerCase().includes("copy")||item.type==="Trading Profit"?"future":"spot",type:legacyType(item),title:item.title.replace(/Copy Trading/g,"Future").replace(/Copy trade/g,"AI copy trade").replace(/Funding Wallet/g,"Spot Wallet"),amount:money(item.amount),balanceBefore:0,balanceAfter:0,status:item.status==="Completed"?"COMPLETED":item.status==="Demo"?"DEMO":"PENDING",reference:`legacy:${item.id}:${item.detail}`,timestamp:item.timestamp})),processedKeys:[],referralQualification:{consumed:Boolean(first),firstTransferAmount:firstAmount,qualified},referralCommissions:[],referralRecipientSpotBalances:{},rankAccount:{qualifyingFutureCapital:Math.max(0,subtractMoney(futureBalance,profit)),currentStar:2,qualifiedTeamCount:0,directRankCount:0,rewardedRanks:[1,2]}}}
  }
  return cloneWalletSeed();
}
