import { randomBytes, randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { createPayment, getAvailableCurrencies, getMinimumPaymentAmount, getPaymentStatus, NowPaymentsError, type ProviderPayment } from "./client.server";
import { MINIMUM_DEPOSIT_USDT, NOWPAYMENTS_NETWORKS, NOWPAYMENTS_PRICE_CURRENCY, normalizePaymentStatus, type NowPaymentsNetwork } from "./config";
import type { DemoDepositRecord } from "./deposit-types";
import { findDepositByIdempotency, findDepositByPaymentId, saveReconciledDeposit, saveServerDeposit } from "./deposit-store.server";

export const createDepositSchema=z.object({amount:z.coerce.number().finite().positive(),network:z.literal("USDT_BEP20").default("USDT_BEP20"),idempotencyKey:z.string().trim().min(8).max(128)});
export type DepositUser={id:string;uid:string};
const enabled=()=>process.env.NOWPAYMENTS_DEPOSIT_ENABLED==="true";
export const mockEnabled=()=>process.env.NODE_ENV==="test"&&process.env.NOWPAYMENTS_MOCK_MODE==="true";
const callbackUrl=()=>{const base=process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"");if(!base)throw new NowPaymentsError("CALLBACK_URL_MISSING","Public application URL is not configured.",503);return`${base}/api/deposits/nowpayments/ipn`};
const numeric=(value:unknown)=>{const number=Number(value);return Number.isFinite(number)&&number>=0?number:0};
const decimal=(value:unknown)=>{try{const result=new Prisma.Decimal(String(value??0));return result.isNegative()?new Prisma.Decimal(0):result}catch{return new Prisma.Decimal(0)}};
const timestamp=(value:unknown)=>typeof value==="string"&&!Number.isNaN(Date.parse(value))?Date.parse(value):null;
export const normalizeDepositAddress=(address:unknown,network:NowPaymentsNetwork)=>network==="USDT_BEP20"?String(address??"").trim().toLowerCase():String(address??"").trim();
export function analyzeProviderPayment(record:DemoDepositRecord,payment:ProviderPayment){
  const paymentId=String(payment.payment_id),paymentStatus=normalizePaymentStatus(payment.payment_status),payCurrency=String(payment.pay_currency??"").trim().toLowerCase(),expectedCurrency=NOWPAYMENTS_NETWORKS[record.network].payCurrency;
  const localAddress=normalizeDepositAddress(record.payAddress,record.network),providerAddress=normalizeDepositAddress(payment.pay_address,record.network),addressMatch=Boolean(localAddress)&&localAddress===providerAddress;
  const receivedSource=payment.actually_paid??payment.outcome_amount,received=receivedSource===undefined||receivedSource===null?null:decimal(receivedSource),withinTolerance=received?received.sub(decimal(record.requestedAmount)).abs().lte(new Prisma.Decimal("0.10")):null;
  const confirmed=paymentStatus==="FINISHED"||paymentStatus==="PARTIALLY_PAID";
  let reviewReason:string|null=null;
  if(paymentId!==record.providerPaymentId||payment.order_id!==record.orderId)reviewReason="Provider payment ID or order ID does not match the local deposit.";
  else if(payCurrency!==expectedCurrency||String(payment.price_currency??"").trim().toLowerCase()!==NOWPAYMENTS_PRICE_CURRENCY)reviewReason="Provider currency or BEP20 network does not match the local deposit.";
  else if(!addressMatch)reviewReason="Normalized provider pay_address does not match the stored payment address.";
  else if(confirmed&&received===null)reviewReason="Provider marked payment confirmed without a confirmed received amount.";
  else if(confirmed&&withinTolerance===false)reviewReason="Confirmed received amount is outside the approved ±0.10 USDT tolerance.";
  return{paymentId,paymentStatus,payCurrency,addressMatch,localAddress,providerAddress,received,withinTolerance,confirmed,reviewReason};
}
const sanitized=(value:string)=>value.length<=12?value:`${value.slice(0,6)}…${value.slice(-4)}`;
export function reconcileProviderPayment(record:DemoDepositRecord,payment:ProviderPayment){
  const analysis=analyzeProviderPayment(record,payment);
  if(analysis.paymentId!==record.providerPaymentId||payment.order_id!==record.orderId)throw new NowPaymentsError("PAYMENT_MISMATCH","Payment does not match the deposit order.",409);
  const actual=analysis.received?.toNumber()??record.actuallyPaid,payAmount=decimal(payment.pay_amount).toNumber(),review=analysis.reviewReason!==null;
  if(review)console.warn("Deposit requires review",{paymentId:sanitized(record.providerPaymentId),reason:analysis.reviewReason,storedAddress:sanitized(analysis.localAddress),providerAddress:sanitized(analysis.providerAddress),providerStatus:analysis.paymentStatus});
  const creditStatus=review?"MANUAL_REVIEW" as const:analysis.confirmed&&analysis.withinTolerance===true?"CREDITED" as const:record.creditStatus;
  const finishedAt=creditStatus==="CREDITED"?(timestamp(payment.updated_at)??Date.now()):record.finishedAt;
  return{...record,payAmount,paymentStatus:analysis.paymentStatus,actuallyPaid:actual,amountCredited:creditStatus==="CREDITED"?actual:0,creditStatus,adminReviewNote:analysis.reviewReason??record.adminReviewNote,txHash:payment.payin_hash??record.txHash,updatedAt:timestamp(payment.updated_at)??Date.now(),finishedAt};
}
export async function getMinimumForNetwork(network:NowPaymentsNetwork){const config=NOWPAYMENTS_NETWORKS[network];if(mockEnabled())return MINIMUM_DEPOSIT_USDT;const available=(await getAvailableCurrencies()).currencies.map(item=>item.toLowerCase());if(!available.includes(config.payCurrency))throw new NowPaymentsError("CURRENCY_UNAVAILABLE",`${config.label} is temporarily unavailable.`,503);const result=await getMinimumPaymentAmount(config.payCurrency,NOWPAYMENTS_PRICE_CURRENCY);return Math.max(MINIMUM_DEPOSIT_USDT,numeric(result.fiat_equivalent??result.min_amount))}
const pendingCreations=new Map<string,Promise<DemoDepositRecord>>();
async function createDepositOnce(user:DepositUser,input:z.infer<typeof createDepositSchema>){if(!enabled())throw new NowPaymentsError("DEPOSITS_DISABLED","NOWPayments deposits are disabled.",503);const existing=await findDepositByIdempotency(user.id,input.idempotencyKey);if(existing)return existing;if(input.amount<MINIMUM_DEPOSIT_USDT)throw new NowPaymentsError("BELOW_MINIMUM","Minimum deposit amount is $1.",400);const minimum=await getMinimumForNetwork(input.network);if(input.amount<minimum)throw new NowPaymentsError("BELOW_MINIMUM",`Minimum deposit amount is $${minimum}.`,400);const now=Date.now(),orderId=`BITVORA_DEPOSIT:${user.uid}:${now}:${randomBytes(4).toString("hex")}`,network=NOWPAYMENTS_NETWORKS[input.network];let payment:ProviderPayment;if(mockEnabled()){payment={payment_id:`MOCK_NP_${randomUUID()}`,payment_status:"waiting",pay_address:`MOCK_${network.network}_ADDRESS_NOT_FOR_REAL_FUNDS`,price_amount:input.amount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_amount:input.amount,pay_currency:network.payCurrency,order_id:orderId,created_at:new Date(now).toISOString(),expiration_estimate_date:new Date(now+30*60_000).toISOString()}}else payment=await createPayment({price_amount:input.amount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_currency:network.payCurrency,order_id:orderId,order_description:"Bitvora Spot Wallet Deposit",ipn_callback_url:callbackUrl()});const record:DemoDepositRecord={id:`np_${randomUUID()}`,userId:user.id,userUid:user.uid,provider:"NOWPAYMENTS",providerPaymentId:String(payment.payment_id),orderId,requestedAmount:input.amount,payAmount:numeric(payment.pay_amount),payCurrency:String(payment.pay_currency).toLowerCase(),network:input.network,payAddress:payment.pay_address,paymentStatus:normalizePaymentStatus(payment.payment_status),actuallyPaid:numeric(payment.actually_paid),amountCredited:0,creditStatus:"NOT_CREDITED",txHash:payment.payin_hash??null,idempotencyKey:input.idempotencyKey,createdAt:timestamp(payment.created_at)??now,updatedAt:now,finishedAt:null,expiresAt:timestamp(payment.expiration_estimate_date),mock:mockEnabled()};return saveServerDeposit(record)}
export function createDeposit(user:DepositUser,input:z.infer<typeof createDepositSchema>){const lockKey=`${user.id}:${input.idempotencyKey}`,pending=pendingCreations.get(lockKey);if(pending)return pending;const creation=createDepositOnce(user,input).finally(()=>pendingCreations.delete(lockKey));pendingCreations.set(lockKey,creation);return creation}
export const settleProviderPayment=(record:DemoDepositRecord,payment:ProviderPayment)=>saveReconciledDeposit(reconcileProviderPayment(record,payment));
export async function refreshDeposit(user:DepositUser,paymentId:string){const record=await findDepositByPaymentId(paymentId);if(!record||record.userId!==user.id)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(record.mock){if(!mockEnabled())throw new NowPaymentsError("MOCK_DISABLED","Mock payment is unavailable.",409);return record}const payment=await getPaymentStatus(paymentId);return settleProviderPayment(record,payment)}
export async function setMockDepositStatus(user:DepositUser,paymentId:string,status:string){const record=await findDepositByPaymentId(paymentId);if(!record||record.userId!==user.id)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(!record.mock||!mockEnabled())throw new NowPaymentsError("MOCK_DISABLED","Mock status simulation is unavailable.",409);const allowed=["waiting","confirming","confirmed","partially_paid","finished","failed","refunded","expired"];if(!allowed.includes(status))throw new NowPaymentsError("INVALID_MOCK_STATUS","Invalid mock payment status.",400);const paid=status==="finished"?record.payAmount:status==="partially_paid"?record.payAmount/2:0;return saveServerDeposit(reconcileProviderPayment(record,{payment_id:record.providerPaymentId,payment_status:status,pay_address:record.payAddress,price_amount:record.requestedAmount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_amount:record.payAmount,pay_currency:record.payCurrency,order_id:record.orderId,actually_paid:paid,updated_at:new Date().toISOString(),payin_hash:`MOCK_TX_${record.providerPaymentId}`}))}
export async function reconcileIpn(payment:ProviderPayment){const record=await findDepositByPaymentId(String(payment.payment_id));if(!record)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(record.mock)throw new NowPaymentsError("MOCK_MISMATCH","Mock payments cannot accept provider callbacks.",409);return settleProviderPayment(record,payment)}
