import "server-only";
import { randomBytes, randomUUID } from "node:crypto";
import { z } from "zod";
import { createPayment, getAvailableCurrencies, getMinimumPaymentAmount, getPaymentStatus, NowPaymentsError, type ProviderPayment } from "./client.server";
import { NOWPAYMENTS_NETWORKS, NOWPAYMENTS_PRICE_CURRENCY, normalizePaymentStatus, type NowPaymentsNetwork } from "./config";
import type { DemoDepositRecord } from "./deposit-types";
import { findDepositByIdempotency, findDepositByPaymentId, saveServerDeposit } from "./deposit-store.server";

export const createDepositSchema=z.object({amount:z.coerce.number().finite().positive(),network:z.enum(["USDT_BEP20","USDT_TRC20"]),idempotencyKey:z.string().trim().min(8).max(128)});
export type DepositUser={id:string;uid:string};
const enabled=()=>process.env.NOWPAYMENTS_DEPOSIT_ENABLED==="true";
export const mockEnabled=()=>process.env.NODE_ENV!=="production"&&process.env.NOWPAYMENTS_MOCK_MODE==="true";
const callbackUrl=()=>{const base=process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"");if(!base)throw new NowPaymentsError("CALLBACK_URL_MISSING","Public application URL is not configured.",503);return`${base}/api/deposits/nowpayments/ipn`};
const numeric=(value:unknown)=>{const number=Number(value);return Number.isFinite(number)&&number>=0?number:0};
const timestamp=(value:unknown)=>typeof value==="string"&&!Number.isNaN(Date.parse(value))?Date.parse(value):null;
export function reconcileProviderPayment(record:DemoDepositRecord,payment:ProviderPayment){const paymentId=String(payment.payment_id),payCurrency=String(payment.pay_currency??"").toLowerCase(),expected=NOWPAYMENTS_NETWORKS[record.network].payCurrency;if(paymentId!==record.providerPaymentId||payment.order_id!==record.orderId)throw new NowPaymentsError("PAYMENT_MISMATCH","Payment does not match the deposit order.",409);if(payCurrency!==expected||String(payment.price_currency??"").toLowerCase()!==NOWPAYMENTS_PRICE_CURRENCY)throw new NowPaymentsError("CURRENCY_MISMATCH","Payment currency or network does not match the deposit.",409);if(Math.abs(numeric(payment.price_amount)-record.requestedAmount)>.000001||Math.abs(numeric(payment.pay_amount)-record.payAmount)>.000001||payment.pay_address!==record.payAddress)throw new NowPaymentsError("AMOUNT_MISMATCH","Payment amount or address does not match the deposit.",409);const status=normalizePaymentStatus(payment.payment_status),actuallyPaid=numeric(payment.actually_paid),finishedAt=status==="FINISHED"?(timestamp(payment.updated_at)??Date.now()):record.finishedAt,creditStatus=status==="PARTIALLY_PAID"?"MANUAL_REVIEW" as const:status==="FINISHED"&&actuallyPaid>0?"CREDITED" as const:record.creditStatus;return{...record,paymentStatus:status,actuallyPaid,amountCredited:creditStatus==="CREDITED"?actuallyPaid:0,creditStatus,txHash:payment.payin_hash??record.txHash,updatedAt:timestamp(payment.updated_at)??Date.now(),finishedAt}}
export async function getMinimumForNetwork(network:NowPaymentsNetwork){const config=NOWPAYMENTS_NETWORKS[network];if(mockEnabled())return 5;const available=(await getAvailableCurrencies()).currencies.map(item=>item.toLowerCase());if(!available.includes(config.payCurrency))throw new NowPaymentsError("CURRENCY_UNAVAILABLE",`${config.label} is temporarily unavailable.`,503);const result=await getMinimumPaymentAmount(config.payCurrency,NOWPAYMENTS_PRICE_CURRENCY);return numeric(result.fiat_equivalent??result.min_amount)}
const pendingCreations=new Map<string,Promise<DemoDepositRecord>>();
async function createDepositOnce(user:DepositUser,input:z.infer<typeof createDepositSchema>){if(!enabled())throw new NowPaymentsError("DEPOSITS_DISABLED","NOWPayments deposits are disabled.",503);const existing=await findDepositByIdempotency(user.id,input.idempotencyKey);if(existing)return existing;const minimum=await getMinimumForNetwork(input.network);if(input.amount<minimum)throw new NowPaymentsError("BELOW_MINIMUM",`Minimum deposit is ${minimum} USD.`,400);const now=Date.now(),orderId=`BITVORA_DEPOSIT:${user.uid}:${now}:${randomBytes(4).toString("hex")}`,network=NOWPAYMENTS_NETWORKS[input.network];let payment:ProviderPayment;if(mockEnabled()){payment={payment_id:`MOCK_NP_${randomUUID()}`,payment_status:"waiting",pay_address:`MOCK_${network.network}_ADDRESS_NOT_FOR_REAL_FUNDS`,price_amount:input.amount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_amount:input.amount,pay_currency:network.payCurrency,order_id:orderId,created_at:new Date(now).toISOString(),expiration_estimate_date:new Date(now+30*60_000).toISOString()}}else payment=await createPayment({price_amount:input.amount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_currency:network.payCurrency,order_id:orderId,order_description:"Bitvora Spot Wallet Deposit",ipn_callback_url:callbackUrl()});const record:DemoDepositRecord={id:`np_${randomUUID()}`,userId:user.id,userUid:user.uid,provider:"NOWPAYMENTS",providerPaymentId:String(payment.payment_id),orderId,requestedAmount:input.amount,payAmount:numeric(payment.pay_amount),payCurrency:String(payment.pay_currency).toLowerCase(),network:input.network,payAddress:payment.pay_address,paymentStatus:normalizePaymentStatus(payment.payment_status),actuallyPaid:numeric(payment.actually_paid),amountCredited:0,creditStatus:"NOT_CREDITED",txHash:payment.payin_hash??null,idempotencyKey:input.idempotencyKey,createdAt:timestamp(payment.created_at)??now,updatedAt:now,finishedAt:null,expiresAt:timestamp(payment.expiration_estimate_date),mock:mockEnabled()};return saveServerDeposit(record)}
export function createDeposit(user:DepositUser,input:z.infer<typeof createDepositSchema>){const lockKey=`${user.id}:${input.idempotencyKey}`,pending=pendingCreations.get(lockKey);if(pending)return pending;const creation=createDepositOnce(user,input).finally(()=>pendingCreations.delete(lockKey));pendingCreations.set(lockKey,creation);return creation}
export async function refreshDeposit(user:DepositUser,paymentId:string){const record=await findDepositByPaymentId(paymentId);if(!record||record.userId!==user.id)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(record.mock){if(!mockEnabled())throw new NowPaymentsError("MOCK_DISABLED","Mock payment is unavailable.",409);return record}const payment=await getPaymentStatus(paymentId),next=reconcileProviderPayment(record,payment);return saveServerDeposit(next)}
export async function setMockDepositStatus(user:DepositUser,paymentId:string,status:string){const record=await findDepositByPaymentId(paymentId);if(!record||record.userId!==user.id)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(!record.mock||!mockEnabled())throw new NowPaymentsError("MOCK_DISABLED","Mock status simulation is unavailable.",409);const allowed=["waiting","confirming","confirmed","partially_paid","finished","failed","refunded","expired"];if(!allowed.includes(status))throw new NowPaymentsError("INVALID_MOCK_STATUS","Invalid mock payment status.",400);const paid=status==="finished"?record.payAmount:status==="partially_paid"?record.payAmount/2:0;return saveServerDeposit(reconcileProviderPayment(record,{payment_id:record.providerPaymentId,payment_status:status,pay_address:record.payAddress,price_amount:record.requestedAmount,price_currency:NOWPAYMENTS_PRICE_CURRENCY,pay_amount:record.payAmount,pay_currency:record.payCurrency,order_id:record.orderId,actually_paid:paid,updated_at:new Date().toISOString(),payin_hash:`MOCK_TX_${record.providerPaymentId}`}))}
export async function reconcileIpn(payment:ProviderPayment){const record=await findDepositByPaymentId(String(payment.payment_id));if(!record)throw new NowPaymentsError("NOT_FOUND","Deposit not found.",404);if(record.mock)throw new NowPaymentsError("MOCK_MISMATCH","Mock payments cannot accept provider callbacks.",409);return saveServerDeposit(reconcileProviderPayment(record,payment))}
