import { AI_TRADING_STORE_KEY, getSessionById, migrateTradingStore } from "@/lib/ai-trading-engine";
import { ranks } from "@/lib/config";
import { hasProcessed, migrateWalletStore, money, WALLET_STORE_KEY, type WalletId, type WalletStore, type WalletTransaction } from "@/lib/wallet-data";
import { loadUserRegistry, type DemoUser } from "@/lib/user-registry";
import { evaluateRankNetwork, getUniqueDownline, isCapitalQualified, type RankNode } from "@/lib/rank-engine";
import { teamMembers } from "@/lib/referral-team-data";
import type { AdminSnapshot, AdminUserRow } from "./admin-types";
import { displayTimeZone } from "@/lib/date-time";

export const readAdminWallet=()=>{try{return migrateWalletStore(JSON.parse(localStorage.getItem(WALLET_STORE_KEY)??"null"))}catch{return migrateWalletStore(null)}};
export const readAdminTrading=()=>{try{return migrateTradingStore(JSON.parse(localStorage.getItem(AI_TRADING_STORE_KEY)??"null"))}catch{return migrateTradingStore(null)}};
const nodesFor=(users:DemoUser[],wallet:WalletStore):RankNode[]=>users.map(user=>{const member=teamMembers.find(item=>item.uid===user.uid),root=user.uid==="BV100001";return{uid:user.uid,sponsorUid:user.sponsorUid,qualifyingFutureCapital:root?wallet.rankAccount.qualifyingFutureCapital:member?.personalBusiness??0,currentStar:root?wallet.rankAccount.currentStar:Number(member?.rank.match(/\d/)?.[0]??0),rewardedRanks:root?wallet.rankAccount.rewardedRanks:[]}});
export function aggregateAdminData():AdminSnapshot{const registry=loadUserRegistry(),wallet=readAdminWallet(),trading=readAdminTrading(),evaluated=evaluateRankNetwork(nodesFor(registry.users,wallet)),byUid=new Map(evaluated.map(item=>[item.uid,item])),users:AdminUserRow[]=registry.users.map(user=>{const rank=byUid.get(user.uid)!,member=teamMembers.find(item=>item.uid===user.uid),root=user.uid==="BV100001",principal=root?wallet.totalFuturePrincipal:member?.personalBusiness??0,profit=root?wallet.totalCompletedTradingProfit:0,required=money(principal*.7),progress=required?Math.min(100,Number((profit/required*100).toFixed(2))):0;return{id:user.id,uid:user.uid,name:user.name,email:user.email,sponsorUid:user.sponsorUid,createdAt:user.createdAt,spotBalance:root?wallet.wallets.spot.balance:0,futureBalance:root?wallet.wallets.future.balance:member?.personalBusiness??0,lockedCapital:root?wallet.lockedFutureTradeCapital:0,qualifyingPrincipal:principal,completedAiProfit:profit,progress,currentStar:rank.currentStar,highestStar:Math.max(rank.currentStar,...rank.rewardedRanks,0),qualifiedTeamSize:rank.qualifiedTeamCount,active:root||member?.status==="Active",qualified:isCapitalQualified(principal)}}),transactions=wallet.transactions,metrics={totalRegisteredUsers:users.length,activeUsers:users.filter(item=>item.active).length,qualifiedUsers:users.filter(item=>item.qualified).length,totalSpotBalance:users.reduce((sum,item)=>sum+item.spotBalance,0),totalFutureBalance:users.reduce((sum,item)=>sum+item.futureBalance,0),totalLockedCapital:users.reduce((sum,item)=>sum+item.lockedCapital,0),totalAiProfit:users.reduce((sum,item)=>sum+item.completedAiProfit,0),directIncome:transactions.filter(item=>item.type==="SPOT_REFERRAL_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),levelIncome:transactions.filter(item=>item.type==="SPOT_LEVEL_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),rankRewards:transactions.filter(item=>item.type==="SPOT_REWARD_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),salaryPaid:transactions.filter(item=>item.type==="SPOT_SALARY_INCOME").reduce((sum,item)=>sum+Math.max(0,item.amount),0),pendingWithdrawals:0,completedWithdrawals:0};return{users,wallet,trades:trading.trades.length,settledTrades:trading.trades.filter(item=>item.status==="SETTLED").length,missedTrades:trading.trades.filter(item=>item.status==="MISSED").length,metrics}}
export function searchAdminUsers(users:AdminUserRow[],query:string){const value=query.trim().toLowerCase();return value?users.filter(user=>[user.uid,user.name,user.email,user.sponsorUid].some(item=>item.toLowerCase().includes(value))):users}
export function adjustWallet(store:WalletStore,input:{uid:string;wallet:WalletId;operation:"CREDIT"|"DEBIT";amount:number;reason:string;idempotencyKey:string;adminId:string;adjustPrincipal:boolean;timestamp?:number}){const amount=money(input.amount),key=`ADMIN_WALLET_ADJUSTMENT:${input.idempotencyKey}`;if(hasProcessed(store,key))return store;if(amount<=0)throw new Error("Amount must be positive.");if(!input.reason.trim())throw new Error("Reason is required.");const account=store.wallets[input.wallet],signed=input.operation==="CREDIT"?amount:-amount,after=money(account.balance+signed);if(after<0)throw new Error("Debit exceeds available balance.");const timestamp=input.timestamp??Date.now(),transaction:WalletTransaction={id:key,userId:input.uid,wallet:input.wallet,type:input.wallet==="spot"?"SPOT_OTHER_INCOME":"ADMIN_FUTURE_ADJUSTMENT",title:`Admin ${input.operation.toLowerCase()} adjustment`,amount:signed,balanceBefore:account.balance,balanceAfter:after,status:"COMPLETED",reference:`${key} · ${input.adminId} · ${input.reason}`,timestamp},principal=input.wallet==="future"&&input.adjustPrincipal?money(store.totalFuturePrincipal+signed):store.totalFuturePrincipal;if(principal<0)throw new Error("Principal cannot be negative.");return{...store,wallets:{...store.wallets,[input.wallet]:{...account,balance:after}},totalFuturePrincipal:principal,rankAccount:input.wallet==="future"&&input.adjustPrincipal?{...store.rankAccount,qualifyingFutureCapital:principal}:store.rankAccount,spotIncome:input.wallet==="spot"&&input.operation==="CREDIT"?{...store.spotIncome,otherIncome:money(store.spotIncome.otherIncome+amount)}:store.spotIncome,transactions:[transaction,...store.transactions],processedKeys:[key,...store.processedKeys]}}
export function adminTradingRows(){const trading=readAdminTrading(),now=Date.now(),timeZone=displayTimeZone();return trading.trades.map(trade=>({trade,session:getSessionById(trade.sessionId,now,trade.sessionTimeZone??timeZone)})).filter(item=>item.session)}
export function genealogyDiagnostics(users:Pick<AdminUserRow,"uid"|"sponsorUid">[]){const uids=new Set<string>(),duplicates:string[]=[],broken:string[]=[],loops:string[]=[];for(const user of users){if(uids.has(user.uid))duplicates.push(user.uid);uids.add(user.uid)}for(const user of users)if(user.sponsorUid&&!uids.has(user.sponsorUid))broken.push(user.uid);const sponsors=new Map(users.map(item=>[item.uid,item.sponsorUid]));for(const user of users){const seen=new Set([user.uid]);let current=user.sponsorUid;while(current){if(seen.has(current)){loops.push(user.uid);break}seen.add(current);current=sponsors.get(current)??""}}return{duplicates:[...new Set(duplicates)],broken:[...new Set(broken)],loops:[...new Set(loops)]}}
export function recalculateRanks(users:AdminUserRow[]){const nodes=users.map(user=>({uid:user.uid,sponsorUid:user.sponsorUid,qualifyingFutureCapital:user.qualifyingPrincipal,currentStar:user.currentStar,rewardedRanks:Array.from({length:user.highestStar},(_,index)=>index+1)}));return evaluateRankNetwork(nodes)}
export function safeCsv(rows:Record<string,unknown>[]){if(!rows.length)return"";const blocked=/secret|password|api.?key|token/i,headers=Object.keys(rows[0]).filter(key=>!blocked.test(key)),escape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;return[headers.map(escape).join(","),...rows.map(row=>headers.map(key=>escape(row[key])).join(","))].join("\r\n")}
export const rankPlan=ranks;
export function downlineFor(uid:string,users:AdminUserRow[]){return getUniqueDownline(uid,users.map(item=>({uid:item.uid,sponsorUid:item.sponsorUid,qualifyingFutureCapital:item.qualifyingPrincipal,currentStar:item.currentStar,rewardedRanks:[]})))}
