"use client";
import { useEffect, useState } from "react";

export type DepthLevel={price:number;quantity:number};
export type RecentTrade={id:number;price:number;amount:number;time:number;side:"BUY"|"SELL"};
type StreamState={bids:DepthLevel[];asks:DepthLevel[];trades:RecentTrade[];connected:boolean;unsupported:boolean};
const empty:StreamState={bids:[],asks:[],trades:[],connected:false,unsupported:false};

export function useBinanceMarketStream(symbol:string){const[state,setState]=useState<StreamState>(empty);useEffect(()=>{if(!/^[A-Z0-9]+USDT$/.test(symbol)){setState({...empty,unsupported:true});return}let socket:WebSocket|undefined,reconnect:ReturnType<typeof setTimeout>|undefined,flush:ReturnType<typeof setTimeout>|undefined,closed=false,attempt=0;let latestDepth:{bids:[string,string][];asks:[string,string][]}|undefined,pendingTrades:RecentTrade[]=[];const commit=()=>{flush=undefined;setState(current=>({bids:latestDepth?latestDepth.bids.map(([price,quantity])=>({price:Number(price),quantity:Number(quantity)})):current.bids,asks:latestDepth?latestDepth.asks.map(([price,quantity])=>({price:Number(price),quantity:Number(quantity)})):current.asks,trades:pendingTrades.length?[...pendingTrades.reverse(),...current.trades].slice(0,40):current.trades,connected:true,unsupported:false}));pendingTrades=[]};const scheduleCommit=()=>{if(!flush)flush=setTimeout(commit,150)};const connect=()=>{if(closed)return;const stream=symbol.toLowerCase();socket=new WebSocket(`wss://data-stream.binance.vision/stream?streams=${stream}@depth20@100ms/${stream}@trade`);socket.onopen=()=>{attempt=0;setState(current=>({...current,connected:true,unsupported:false}))};socket.onmessage=event=>{try{const message=JSON.parse(String(event.data)) as {stream:string;data:{bids:[string,string][];asks:[string,string][];t:number;p:string;q:string;T:number;m:boolean}};if(message.stream.includes("@depth20")){latestDepth=message.data;scheduleCommit()}else if(message.stream.endsWith("@trade")){pendingTrades.push({id:Number(message.data.t),price:Number(message.data.p),amount:Number(message.data.q),time:Number(message.data.T),side:message.data.m?"SELL":"BUY"});scheduleCommit()}}catch{}};socket.onerror=()=>socket?.close();socket.onclose=()=>{setState(current=>({...current,connected:false}));if(!closed){const delay=Math.min(30000,1000*2**attempt++);reconnect=setTimeout(connect,delay)}}};connect();return()=>{closed=true;if(reconnect)clearTimeout(reconnect);if(flush)clearTimeout(flush);socket?.close();socket=undefined}},[symbol]);return state}
