"use client";
import { useEffect, useState } from "react";
import type { TradeSession } from "@/lib/ai-trading-engine";

export type CurrentAiSession={id:string;sequence:1|2|3|"ADDITIONAL";type:"REGULAR"|"ADDITIONAL";scheduledAt:number;liveStartsAt:number;liveEndsAt:number;startTime:number;displayStartTime:string;displayLiveWindow:string;countdownTarget:number;pair:string;signal:"BUY"|"SELL";eligible:boolean;status:"UPCOMING"|"LIVE"|"MISSED"|"JOINED"|"COMPLETED";blockReason:string|null;placementSource:"MANUAL"|"AI_BOT"|null};
export type DisplayTradeSession=TradeSession&{displayStartTime:string;displayLiveWindow:string;displaySettlementTime:string};
export type FutureWalletSummary={balance:number;todayNetChange:number};
export type AiTradeListItem={id:string;pair:string;direction:"BUY"|"SELL";placementSource:"MANUAL"|"AI_BOT";sourceLabel:"Manual"|"AI Bot";status:"CAPITAL_LOCKED"|"PENDING_SETTLEMENT"|"SETTLING"|"SETTLED"|"FAILED"|"CANCELLED"|"MISSED";tradeCapital:number;principalReturned:number|null;profitReceived:number|null;placedAt:number;settledAt:number|null;missedAt:number|null};

export function useAiTrading(_userId:string,_userUid:string,_futureBalance:number){
  const[sessions,setSessions]=useState<DisplayTradeSession[]>([]),[currentSession,setCurrentSession]=useState<CurrentAiSession|null>(null),[currentTrades,setCurrentTrades]=useState<AiTradeListItem[]>([]),[tradeHistory,setTradeHistory]=useState<AiTradeListItem[]>([]),[futureWalletSummary,setFutureWalletSummary]=useState<FutureWalletSummary|null>(null),[bonus,setBonus]=useState<{active:boolean;availableToday:boolean;expiresAt:number|null}>({active:false,availableToday:false,expiresAt:null}),[offset,setOffset]=useState(0),[tick,setTick]=useState(()=>Date.now()),[ready,setReady]=useState(false),now=tick+offset;
  useEffect(()=>{let active=true;const synchronize=async()=>{try{const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone,response=await fetch("/api/ai-trading",{cache:"no-store",headers:{"x-user-timezone":timeZone}}),payload=await response.json() as {serverNow:number;sessions:DisplayTradeSession[];currentSession:CurrentAiSession|null;currentTrades:AiTradeListItem[];tradeHistory:AiTradeListItem[];futureWalletBalance:number;todayFutureWalletNetChange:number;bonus:{active:boolean;availableToday:boolean;expiresAt:number|null}};if(!response.ok)throw new Error("Session unavailable");if(!active)return;setOffset(payload.serverNow-Date.now());setSessions(payload.sessions);setCurrentSession(payload.currentSession);setCurrentTrades(payload.currentTrades);setTradeHistory(payload.tradeHistory);setBonus(payload.bonus);setFutureWalletSummary({balance:payload.futureWalletBalance,todayNetChange:payload.todayFutureWalletNetChange});setReady(true)}catch{if(!active)return;setCurrentSession(null);setCurrentTrades([]);setTradeHistory([]);setFutureWalletSummary(null);setReady(true)}};const sync=()=>void synchronize();void synchronize();window.addEventListener("bitvora-wallet-updated",sync);const syncTimer=setInterval(sync,5_000),clockTimer=setInterval(()=>setTick(Date.now()),1_000);return()=>{active=false;window.removeEventListener("bitvora-wallet-updated",sync);clearInterval(syncTimer);clearInterval(clockTimer)}},[]);
  return{sessions,currentSession,currentTrades,tradeHistory,futureWalletSummary,bonus,now,ready}
}
