import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { migrateWalletStore } from "@/lib/wallet-data";
import { calculatePrincipal,calculateProfit,existingProfitRate,TRADE_PERCENTAGE } from "./amount";
import { TradeJobError } from "./errors";
const lockKey=(id:string)=>`TRADE_LOCK:${id}`,returnKey=(id:string)=>`TRADE_PRINCIPAL_RETURN:${id}`,profitKey=(id:string)=>`TRADE_PROFIT:${id}`;
export async function createTradeForUser(sessionRunId:string,userId:string){return prisma.$transaction(async tx=>{
  const run=await tx.tradeSessionRun.findUniqueOrThrow({where:{id:sessionRunId}});const subscription=await tx.aiBotSubscription.findFirst({where:{userId,status:"ACTIVE",activatedAt:{lte:run.scheduledStartAt},expiresAt:{gt:run.scheduledStartAt}},orderBy:{activatedAt:"desc"},select:{id:true}});if(!subscription)throw new TradeJobError("SUBSCRIPTION_EXPIRED",false);
  const user=await tx.user.findUniqueOrThrow({where:{id:userId},select:{uid:true,state:{select:{wallet:true}}}});let wallet=await tx.aiFinancialWallet.findUnique({where:{userId}});if(!wallet){const legacy=migrateWalletStore(user.state?.wallet);wallet=await tx.aiFinancialWallet.create({data:{userId,availableFuture:new Prisma.Decimal(String(legacy.wallets.future.balance)),lockedFuture:new Prisma.Decimal(String(legacy.lockedFutureTradeCapital)),completedProfit:new Prisma.Decimal(String(legacy.totalCompletedTradingProfit))}})}
  await tx.$queryRaw`SELECT "userId" FROM "AiFinancialWallet" WHERE "userId"=${userId} FOR UPDATE`;wallet=await tx.aiFinancialWallet.findUniqueOrThrow({where:{userId}});const executionKey=`${userId}:${run.localTradingDate}:${run.sessionId}:${run.tradeType}`;const duplicate=await tx.aiFinancialTrade.findUnique({where:{executionKey}});if(duplicate)return duplicate;
  const principal=calculatePrincipal(wallet.availableFuture),rate=existingProfitRate(user.uid,run.localTradingDate,run.sessionId.endsWith("ADDITIONAL")?"ADDITIONAL":"REGULAR"),profit=calculateProfit(wallet.availableFuture,rate),tradeId=crypto.randomUUID(),availableAfter=wallet.availableFuture.sub(principal),lockedAfter=wallet.lockedFuture.add(principal);
  const trade=await tx.aiFinancialTrade.create({data:{id:tradeId,executionKey,sessionRunId,userId,subscriptionId:subscription.id,tradeType:run.tradeType,balanceSnapshot:wallet.availableFuture,tradePercentage:TRADE_PERCENTAGE,principal,profitRate:rate,profit,status:"LOCKED",officialStartedAt:run.scheduledStartAt}});await tx.aiFinancialWallet.update({where:{userId},data:{availableFuture:availableAfter,lockedFuture:lockedAfter,version:{increment:1}}});await tx.aiWalletLedger.create({data:{idempotencyKey:lockKey(trade.id),userId,tradeId:trade.id,operation:"PRINCIPAL_LOCK",amount:principal.neg(),availableBefore:wallet.availableFuture,availableAfter,lockedBefore:wallet.lockedFuture,lockedAfter,officialAt:run.scheduledStartAt}});await tx.aiOutboxEvent.create({data:{idempotencyKey:`TRADE_NOTIFICATION:${trade.id}:STARTED`,aggregateType:"TRADE",aggregateId:trade.id,userId,eventType:"TRADE_STARTED",payload:{tradeId:trade.id,sessionRunId}}});await tx.tradeSessionRun.update({where:{id:sessionRunId},data:{totalStarted:{increment:1}}});return trade
 },{isolationLevel:"Serializable",timeout:10_000,maxWait:5_000})}
export async function settleTrade(tradeId:string){return prisma.$transaction(async tx=>{
  await tx.$queryRaw`SELECT "id" FROM "AiFinancialTrade" WHERE "id"=${tradeId} FOR UPDATE`;const trade=await tx.aiFinancialTrade.findUnique({where:{id:tradeId},include:{sessionRun:true}});if(!trade)throw new TradeJobError("PERMANENT_VALIDATION",false,"Trade not found");if(trade.status==="SETTLED")return trade;await tx.$queryRaw`SELECT "userId" FROM "AiFinancialWallet" WHERE "userId"=${trade.userId} FOR UPDATE`;const wallet=await tx.aiFinancialWallet.findUniqueOrThrow({where:{userId:trade.userId}});if(wallet.lockedFuture.lt(trade.principal))throw new TradeJobError("PERMANENT_VALIDATION",false,"Locked principal invariant failed");
  const principalExists=await tx.aiWalletLedger.findUnique({where:{idempotencyKey:returnKey(trade.id)}}),profitExists=await tx.aiWalletLedger.findUnique({where:{idempotencyKey:profitKey(trade.id)}});if(principalExists||profitExists)throw new TradeJobError("PERMANENT_VALIDATION",false,"Partial settlement ledger detected; reconciliation required");const afterPrincipal=wallet.availableFuture.add(trade.principal),afterProfit=afterPrincipal.add(trade.profit),lockedAfter=wallet.lockedFuture.sub(trade.principal),officialAt=trade.sessionRun.officialSettledAt;
  await tx.aiWalletLedger.createMany({data:[{idempotencyKey:returnKey(trade.id),userId:trade.userId,tradeId:trade.id,operation:"PRINCIPAL_RETURN",amount:trade.principal,availableBefore:wallet.availableFuture,availableAfter:afterPrincipal,lockedBefore:wallet.lockedFuture,lockedAfter,officialAt},{idempotencyKey:profitKey(trade.id),userId:trade.userId,tradeId:trade.id,operation:"PROFIT_CREDIT",amount:trade.profit,availableBefore:afterPrincipal,availableAfter:afterProfit,lockedBefore:lockedAfter,lockedAfter,officialAt}]});await tx.aiFinancialWallet.update({where:{userId:trade.userId},data:{availableFuture:afterProfit,lockedFuture:lockedAfter,completedProfit:{increment:trade.profit},version:{increment:1}}});const settled=await tx.aiFinancialTrade.update({where:{id:trade.id},data:{status:"SETTLED",officialSettledAt:officialAt,processingSettledAt:new Date()}});await tx.aiOutboxEvent.createMany({data:[{idempotencyKey:`TRADE_NOTIFICATION:${trade.id}:SETTLED`,aggregateType:"TRADE",aggregateId:trade.id,userId:trade.userId,eventType:"TRADE_SETTLED",payload:{tradeId:trade.id,officialSettledAt:officialAt.toISOString()}},{idempotencyKey:`TRADE_NOTIFICATION:${trade.id}:PROFIT`,aggregateType:"TRADE",aggregateId:trade.id,userId:trade.userId,eventType:"PROFIT_CREDITED",payload:{tradeId:trade.id,amount:trade.profit.toString()}}],skipDuplicates:true});await tx.tradeSessionRun.update({where:{id:trade.sessionRunId},data:{totalSettled:{increment:1}}});return settled
 },{isolationLevel:"Serializable",timeout:10_000,maxWait:5_000})}
