import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { createDailySessions,getTradingDate } from "@/lib/ai-trading-engine";
import { aiTradeScaleConfig,queues } from "./config";
import { jobOptions,settlementQueue,tradeQueue } from "./queue";
const OFFICIAL_ZONE=process.env.AI_TRADE_OFFICIAL_TIME_ZONE??"Asia/Kolkata";
export async function openDueSessions(now=new Date()) {const date=getTradingDate(now.getTime(),OFFICIAL_ZONE),sessions=createDailySessions(date,now.getTime(),OFFICIAL_ZONE).filter(s=>now.getTime()>=s.liveFrom&&now.getTime()<s.placementClosesAt);for(const session of sessions){const hash=[...session.id].reduce((v,c)=>Math.imul(v^c.charCodeAt(0),16777619)>>>0,2166136261),officialRate=new Prisma.Decimal(100+(hash%101)).div(100).div(3).toDecimalPlaces(6);const run=await prisma.tradeSessionRun.upsert({where:{localTradingDate_sessionId_tradeType:{localTradingDate:date,sessionId:session.id,tradeType:"AI_BOT"}},create:{sessionId:session.id,localTradingDate:date,tradeType:"AI_BOT",timeZone:OFFICIAL_ZONE,scheduledStartAt:new Date(session.liveFrom),referencePriceAt:new Date(session.liveFrom),scheduledSettleAt:new Date(session.settlesAt),officialSettledAt:new Date(session.settlesAt),pair:session.pair,direction:session.signalDirection,profitRate:officialRate,resultSource:`EXISTING_DETERMINISTIC_RULE:${session.id}`},update:{},select:{id:true,status:true}});if(run.status==="QUEUING")await enqueueEligible(run.id,new Date(session.liveFrom))}}
export async function enqueueEligible(sessionRunId:string,eligibleAt:Date){let cursor:string|undefined,total=0;for(;;){const rows=await prisma.user.findMany({where:{aiBotSubscriptions:{some:{status:"ACTIVE",activatedAt:{lte:eligibleAt},expiresAt:{gt:eligibleAt}}}},orderBy:{id:"asc"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{}),select:{id:true}});if(!rows.length)break;for(const row of rows){const jobKey=`CREATE:${sessionRunId}:${row.id}`,dbJob=await prisma.aiTradeJob.upsert({where:{jobKey},create:{jobKey,queueName:queues.trade,sessionRunId,userId:row.id,kind:"CREATE"},update:{},select:{id:true,status:true}});if(dbJob.status==="QUEUED")await tradeQueue.add("create-trade",{dbJobId:dbJob.id,sessionRunId,userId:row.id},{...jobOptions,jobId:jobKey});total++;cursor=row.id}if(rows.length<aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE)break}await prisma.tradeSessionRun.update({where:{id:sessionRunId},data:{totalEligible:total,totalQueued:total,status:"RUNNING",queueCompletedAt:new Date()}})}
export async function enqueueDueSettlements(now=new Date()){const runs=await prisma.tradeSessionRun.findMany({where:{status:{in:["RUNNING","PARTIAL_FAILURE"]},scheduledSettleAt:{lte:now}},select:{id:true}});for(const run of runs){await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"SETTLING"}});let cursor:string|undefined;for(;;){const trades=await prisma.aiFinancialTrade.findMany({where:{sessionRunId:run.id,status:{in:["LOCKED","SETTLING"]}},orderBy:{id:"asc"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{}),select:{id:true,userId:true}});if(!trades.length)break;for(const trade of trades){const jobKey=`SETTLE:${trade.id}`,dbJob=await prisma.aiTradeJob.upsert({where:{jobKey},create:{jobKey,queueName:queues.settlement,sessionRunId:run.id,userId:trade.userId,tradeId:trade.id,kind:"SETTLE"},update:{},select:{id:true,status:true}});if(dbJob.status==="QUEUED")await settlementQueue.add("settle-trade",{dbJobId:dbJob.id,tradeId:trade.id},{...jobOptions,jobId:jobKey})}cursor=trades.at(-1)!.id;if(trades.length<aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE)break}}}
export async function recoverQueuedJobs(){const jobs=await prisma.aiTradeJob.findMany({where:{status:"QUEUED"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,orderBy:{id:"asc"}});for(const job of jobs){const queue=job.kind==="CREATE"?tradeQueue:settlementQueue;await queue.add(job.kind==="CREATE"?"create-trade":"settle-trade",job.kind==="CREATE"?{dbJobId:job.id,sessionRunId:job.sessionRunId,userId:job.userId}:{dbJobId:job.id,tradeId:job.tradeId},{...jobOptions,jobId:job.jobKey})}}
export async function finalizeSessions(){const runs=await prisma.tradeSessionRun.findMany({where:{status:{in:["SETTLING","PARTIAL_FAILURE"]}},select:{id:true,totalEligible:true}});for(const run of runs){const [pending,dead,trades,settled]=await Promise.all([prisma.aiTradeJob.count({where:{sessionRunId:run.id,status:{in:["QUEUED","RUNNING","FAILED"]}}}),prisma.aiTradeJob.count({where:{sessionRunId:run.id,status:"DEAD"}}),prisma.aiFinancialTrade.count({where:{sessionRunId:run.id}}),prisma.aiFinancialTrade.count({where:{sessionRunId:run.id,status:"SETTLED"}})]);if(pending===0&&dead===0&&trades===run.totalEligible&&settled===trades)await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"COMPLETED",completedAt:new Date()}});else if(dead>0)await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"PARTIAL_FAILURE"}})}}
