import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { createDailySessions,getSessionById,getTradingDate,type TradeSession } from "@/lib/ai-trading-engine";
import { resolveUserTimeZone } from "@/lib/timezone.server";
import { aiTradeScaleConfig,queues } from "./config";
import { addAiQueueJob,boundedQueueOperation,getSettlementQueue,getTradeQueue,jobOptions } from "./queue";
import { isAdditionalTradeEligible } from "./eligibility";

const slot=(session:TradeSession)=>String(session.sequence);
const runSessionKey=(session:TradeSession)=>`${session.id}:${session.timeZone}`;
const resultRate=(session:TradeSession)=>{const hash=[...runSessionKey(session)].reduce((v,c)=>Math.imul(v^c.charCodeAt(0),16777619)>>>0,2166136261);return session.type==="ADDITIONAL"?new Prisma.Decimal(40+(hash%11)).div(100):new Prisma.Decimal(100+(hash%101)).div(100).div(3).toDecimalPlaces(6)};
type ScheduleUser={timezone:string;country:string|null;additionalTradeEligibility:{eligible:boolean;eligibilityStartedAt:Date;eligibilityEndsAt:Date|null}|null;aiBotSubscriptions:Array<{activatedAt:Date;expiresAt:Date}>};
export function scheduleSessionsForUser(user:ScheduleUser,now=new Date(),catchUpHours=aiTradeScaleConfig.AI_TRADE_CATCH_UP_HOURS){
  const timeZone=resolveUserTimeZone(user.timezone,user.country),sessions=createDailySessions(getTradingDate(now.getTime(),timeZone),now.getTime(),timeZone),catchUpMs=catchUpHours*60*60_000;
  return sessions.map(session=>{const subscriptionEligible=user.aiBotSubscriptions.some(subscription=>subscription.activatedAt.getTime()<=session.liveFrom&&subscription.expiresAt.getTime()>session.liveFrom),additionalEligible=session.type==="REGULAR"||isAdditionalTradeEligible(user.additionalTradeEligibility,session.liveFrom),due=session.liveFrom<=now.getTime(),insideCatchUp=due&&now.getTime()-session.liveFrom<=catchUpMs;return{session,subscriptionEligible,additionalEligible,due,insideCatchUp,shouldEnqueue:subscriptionEligible&&additionalEligible&&insideCatchUp}})
}

export async function ensureRun(session:TradeSession,tradeType="AI_BOT"){
  return prisma.tradeSessionRun.upsert({where:{localTradingDate_sessionId_tradeType:{localTradingDate:session.tradingDate,sessionId:runSessionKey(session),tradeType}},create:{sessionId:runSessionKey(session),localTradingDate:session.tradingDate,tradeType,sessionType:session.type,localSessionSlot:slot(session),timeZone:session.timeZone,scheduledStartAt:new Date(session.liveFrom),referencePriceAt:new Date(session.liveFrom),scheduledSettleAt:new Date(session.settlesAt),officialSettledAt:new Date(session.settlesAt),pair:session.pair,direction:session.signalDirection,profitRate:resultRate(session),resultSource:`EXISTING_DETERMINISTIC_RULE:${runSessionKey(session)}`},update:{},select:{id:true,status:true,localTradingDate:true,sessionId:true}})
}

type EnqueueRun={id:string;localTradingDate:string;localSessionSlot:string;tradeType:string};
export const creationJobKey=(run:EnqueueRun,userId:string)=>`CREATE:${userId}:${run.localTradingDate}:${run.localSessionSlot}:${run.tradeType}`;
export const createBullJobId=(run:EnqueueRun,userId:string)=>`ai-trade-create__${userId}__${run.localTradingDate}__${run.localSessionSlot}__${run.tradeType}`;
export const tradeExecutionKey=(run:EnqueueRun,userId:string)=>`AI_TRADE:${userId}:${run.localTradingDate}:${run.localSessionSlot}:${run.tradeType}`;
export const settlementBullJobId=(tradeId:string)=>`ai-trade-settle__${tradeId}`;
export function resolveRecoveryBullJobId(job:{kind:string;userId:string|null;bullJobId:string|null;jobKey:string;sessionRunId:string;sessionRun:{localTradingDate:string;localSessionSlot:string;tradeType:string}}){
  if(job.kind==="CREATE"&&job.userId)return{jobId:createBullJobId({...job.sessionRun,id:job.sessionRunId},job.userId),source:"createBullJobId()" as const};
  if(job.bullJobId)return{jobId:job.bullJobId,source:"job.bullJobId" as const};
  return{jobId:job.jobKey.replaceAll(":","__"),source:"job.jobKey" as const};
}

async function enqueueUser(run:EnqueueRun,userId:string){
  const tradeQueue=getTradeQueue();
  const jobKey=creationJobKey(run,userId),bullJobId=createBullJobId(run,userId),existing=await prisma.aiTradeJob.findFirst({where:{OR:[{jobKey},{sessionRunId:run.id,userId,kind:"CREATE"}]},select:{id:true,status:true,jobKey:true,bullJobId:true}});
  if(existing){const recoverable=["QUEUED","FAILED"].includes(existing.status);if(recoverable){if(existing.bullJobId!==bullJobId)await prisma.aiTradeJob.update({where:{id:existing.id},data:{bullJobId}});await boundedQueueOperation(addAiQueueJob(()=>tradeQueue.add("create-trade",{dbJobId:existing.id,sessionRunId:run.id,userId},{...jobOptions,jobId:bullJobId}),{queueName:queues.trade,jobName:"create-trade",jobId:bullJobId,caller:"RECOVERABLE_CREATION",jobIdSource:"createBullJobId()",dbJobId:existing.id,jobKey:existing.jobKey,storedBullJobId:existing.bullJobId,sessionRunId:run.id,userId,localTradingDate:run.localTradingDate,localSessionSlot:run.localSessionSlot,tradeType:run.tradeType}))}return{created:false,enqueued:recoverable,status:existing.status,jobKey:existing.jobKey,bullJobId}}
  const dbJob=await prisma.aiTradeJob.create({data:{jobKey,bullJobId,queueName:queues.trade,sessionRunId:run.id,userId,kind:"CREATE"},select:{id:true}});
  await boundedQueueOperation(addAiQueueJob(()=>tradeQueue.add("create-trade",{dbJobId:dbJob.id,sessionRunId:run.id,userId},{...jobOptions,jobId:bullJobId}),{queueName:queues.trade,jobName:"create-trade",jobId:bullJobId,caller:"NEW_CREATION",jobIdSource:"createBullJobId()",dbJobId:dbJob.id,jobKey,storedBullJobId:bullJobId,sessionRunId:run.id,userId,localTradingDate:run.localTradingDate,localSessionSlot:run.localSessionSlot,tradeType:run.tradeType}));
  return{created:true,enqueued:true,status:"QUEUED",jobKey,bullJobId}
}

export async function enqueueEligible(sessionRunId:string,eligibleAt:Date){
  const run=await prisma.tradeSessionRun.findUniqueOrThrow({where:{id:sessionRunId}});let cursor:string|undefined,total=0;
  for(;;){const rows=await prisma.user.findMany({where:{timezone:run.timeZone,aiBotSubscriptions:{some:{status:"ACTIVE",activatedAt:{lte:eligibleAt},expiresAt:{gt:eligibleAt}}},...(run.sessionType==="ADDITIONAL"?{additionalTradeEligibility:{is:{eligible:true,eligibilityStartedAt:{lte:eligibleAt},eligibilityEndsAt:{gt:eligibleAt}}}}:{})},orderBy:{id:"asc"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{}),select:{id:true}});if(!rows.length)break;for(const row of rows){if((await enqueueUser(run,row.id)).created)total++}cursor=rows.at(-1)!.id;if(rows.length<aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE)break}
  const counts=await prisma.aiTradeJob.count({where:{sessionRunId,kind:"CREATE"}});await prisma.tradeSessionRun.update({where:{id:sessionRunId},data:{totalEligible:counts,totalQueued:counts,status:"RUNNING",queueCompletedAt:new Date()}});return total
}

export async function openDueSessions(now=new Date(),onlyUserId?:string){
  let cursor:string|undefined;const touched=new Set<string>();let enqueued=0,considered=0;
  const catchUpMs=aiTradeScaleConfig.AI_TRADE_CATCH_UP_HOURS*60*60_000;
  for(;;){const users=await prisma.user.findMany({where:{...(onlyUserId?{id:onlyUserId}:{}),aiBotSubscriptions:{some:{status:"ACTIVE",activatedAt:{lte:now},expiresAt:{gt:new Date(now.getTime()-catchUpMs)}}}},orderBy:{id:"asc"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{}),select:{id:true,timezone:true,country:true,additionalTradeEligibility:true,aiBotSubscriptions:{where:{status:"ACTIVE",activatedAt:{lte:now},expiresAt:{gt:new Date(now.getTime()-catchUpMs)}},select:{activatedAt:true,expiresAt:true}}}});if(!users.length)break;
    for(const user of users){for(const item of scheduleSessionsForUser(user,now)){if(!item.shouldEnqueue)continue;considered++;const run=await ensureRun(item.session),result=await enqueueUser({...run,localSessionSlot:slot(item.session),tradeType:"AI_BOT"},user.id);if(result.enqueued)touched.add(run.id);if(result.created)enqueued++}}
    cursor=users.at(-1)!.id;if(users.length<aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE)break
  }
  for(const id of touched){const count=await prisma.aiTradeJob.count({where:{sessionRunId:id,kind:"CREATE"}});await prisma.tradeSessionRun.update({where:{id},data:{totalEligible:count,totalQueued:count,status:"RUNNING",queueCompletedAt:new Date()}})}
  return{considered,enqueued,catchUpHours:aiTradeScaleConfig.AI_TRADE_CATCH_UP_HOURS}
}

export async function enqueueUserSessionTrade(userId:string,sessionId:string,tradeType:"AI_BOT"|"MANUAL",now=new Date()){
  const user=await prisma.user.findUniqueOrThrow({where:{id:userId},select:{timezone:true,country:true,additionalTradeEligibility:true}}),timeZone=resolveUserTimeZone(user.timezone,user.country),session=getSessionById(sessionId,now.getTime(),timeZone);if(!session||now.getTime()<session.liveFrom||now.getTime()>=session.placementClosesAt)throw new Error("SESSION_NOT_LIVE");
  if(session.type==="ADDITIONAL"){const value=user.additionalTradeEligibility;if(!(value?.eligible&&value.eligibilityStartedAt.getTime()<=session.liveFrom&&value.eligibilityEndsAt&&value.eligibilityEndsAt.getTime()>session.liveFrom))throw new Error("NOT_ELIGIBLE")}
  const run=await ensureRun(session,tradeType),result=await enqueueUser({...run,localSessionSlot:slot(session),tradeType},userId),count=await prisma.aiTradeJob.count({where:{sessionRunId:run.id,kind:"CREATE"}});await prisma.tradeSessionRun.update({where:{id:run.id},data:{totalEligible:count,totalQueued:count,status:"RUNNING",queueCompletedAt:new Date()}});return{...run,idempotent:!result.created,jobKey:result.jobKey,bullJobId:result.bullJobId}
}

export async function enqueueDueSettlements(now=new Date()){const runs=await prisma.tradeSessionRun.findMany({where:{status:{in:["RUNNING","PARTIAL_FAILURE"]},scheduledSettleAt:{lte:now}},select:{id:true,localTradingDate:true,localSessionSlot:true,tradeType:true}});for(const run of runs){await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"SETTLING"}});let cursor:string|undefined;for(;;){const trades=await prisma.aiFinancialTrade.findMany({where:{sessionRunId:run.id,status:{in:["LOCKED","SETTLING"]}},orderBy:{id:"asc"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{}),select:{id:true,userId:true}});if(!trades.length)break;for(const trade of trades){const jobKey=`SETTLE:${trade.id}`,bullJobId=settlementBullJobId(trade.id),dbJob=await prisma.aiTradeJob.upsert({where:{jobKey},create:{jobKey,bullJobId,queueName:queues.settlement,sessionRunId:run.id,userId:trade.userId,tradeId:trade.id,kind:"SETTLE"},update:{},select:{id:true,status:true,bullJobId:true}});if(dbJob.status==="QUEUED")await boundedQueueOperation(addAiQueueJob(()=>getSettlementQueue().add("settle-trade",{dbJobId:dbJob.id,tradeId:trade.id},{...jobOptions,jobId:bullJobId}),{queueName:queues.settlement,jobName:"settle-trade",jobId:bullJobId,caller:"SETTLEMENT",jobIdSource:"settlement key",dbJobId:dbJob.id,jobKey,storedBullJobId:dbJob.bullJobId,sessionRunId:run.id,userId:trade.userId,localTradingDate:run.localTradingDate,localSessionSlot:run.localSessionSlot,tradeType:run.tradeType}))}cursor=trades.at(-1)!.id;if(trades.length<aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE)break}}}
export async function recoverQueuedJobs(){const jobs=await prisma.aiTradeJob.findMany({where:{status:"QUEUED"},take:aiTradeScaleConfig.AI_TRADE_ENQUEUE_BATCH_SIZE,orderBy:{id:"asc"},include:{sessionRun:{select:{localTradingDate:true,localSessionSlot:true,tradeType:true}}}});for(const job of jobs){const queue=job.kind==="CREATE"?getTradeQueue():getSettlementQueue(),resolved=resolveRecoveryBullJobId(job),regeneratedBullJobId=job.kind==="CREATE"&&job.userId?createBullJobId({...job.sessionRun,id:job.sessionRunId},job.userId):null;if(process.env.AI_TRADE_ENQUEUE_DIAGNOSTICS==="true")console.info(JSON.stringify({event:"ai_orchestrator_recovered_job",databaseId:job.id,kind:job.kind,status:job.status,jobKey:job.jobKey,bullJobId:job.bullJobId,regeneratedBullJobId,finalJobId:resolved.jobId,enqueueCaller:"QUEUED_JOB_RECOVERY"}));await boundedQueueOperation(addAiQueueJob(()=>queue.add(job.kind==="CREATE"?"create-trade":"settle-trade",job.kind==="CREATE"?{dbJobId:job.id,sessionRunId:job.sessionRunId,userId:job.userId}:{dbJobId:job.id,tradeId:job.tradeId},{...jobOptions,jobId:resolved.jobId}),{queueName:job.queueName,jobName:job.kind==="CREATE"?"create-trade":"settle-trade",jobId:resolved.jobId,caller:"QUEUED_JOB_RECOVERY",jobIdSource:resolved.source,dbJobId:job.id,jobKey:job.jobKey,storedBullJobId:job.bullJobId,sessionRunId:job.sessionRunId,userId:job.userId,localTradingDate:job.sessionRun.localTradingDate,localSessionSlot:job.sessionRun.localSessionSlot,tradeType:job.sessionRun.tradeType}))}}
export async function finalizeSessions(){const runs=await prisma.tradeSessionRun.findMany({where:{status:{in:["SETTLING","PARTIAL_FAILURE"]}},select:{id:true,totalEligible:true}});for(const run of runs){const[pending,dead,trades,settled]=await Promise.all([prisma.aiTradeJob.count({where:{sessionRunId:run.id,status:{in:["QUEUED","RUNNING","FAILED"]}}}),prisma.aiTradeJob.count({where:{sessionRunId:run.id,status:"DEAD"}}),prisma.aiFinancialTrade.count({where:{sessionRunId:run.id}}),prisma.aiFinancialTrade.count({where:{sessionRunId:run.id,status:"SETTLED"}})]);if(pending===0&&dead===0&&trades===run.totalEligible&&settled===trades)await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"COMPLETED",completedAt:new Date()}});else if(dead>0)await prisma.tradeSessionRun.update({where:{id:run.id},data:{status:"PARTIAL_FAILURE"}})}}
