import { Job,Worker } from "bullmq";
import { prisma } from "@/lib/prisma";
import { aiTradeScaleConfig,queues } from "./config";
import { deadLetterQueue,getRedisConnection,jobOptions } from "./queue";
import { classify } from "./errors";
import { createTradeForUser,settleTrade } from "./financial";
async function execute(job:Job,kind:"CREATE"|"SETTLE"){const started=Date.now(),{dbJobId}=job.data;await prisma.aiTradeJob.update({where:{id:dbJobId},data:{status:"RUNNING",attempts:job.attemptsMade+1,startedAt:new Date()}});try{const result=kind==="CREATE"?await createTradeForUser(job.data.sessionRunId,job.data.userId):await settleTrade(job.data.tradeId);await prisma.aiTradeJob.update({where:{id:dbJobId},data:{status:"COMPLETED",completedAt:new Date(),failureCode:null,failureMessage:null}});console.info(JSON.stringify({event:"ai_trade_job_completed",sessionRunId:kind==="CREATE"?job.data.sessionRunId:undefined,tradeId:kind==="SETTLE"?job.data.tradeId:result.id,userId:job.data.userId,jobId:job.id,attempt:job.attemptsMade+1,duration:Date.now()-started}));return result}catch(raw){const error=classify(raw),last=!error.transient||job.attemptsMade+1>=aiTradeScaleConfig.AI_TRADE_MAX_RETRIES;await prisma.aiTradeJob.update({where:{id:dbJobId},data:{status:last?"DEAD":"FAILED",failureCode:error.code,failureMessage:error.message.slice(0,500)}});if(last){await deadLetterQueue.add("dead-letter",{sourceQueue:job.queueName,jobId:job.id,dbJobId,errorCode:error.code},{...jobOptions,attempts:1});const db=await prisma.aiTradeJob.findUnique({where:{id:dbJobId},select:{sessionRunId:true}});if(db)await prisma.tradeSessionRun.update({where:{id:db.sessionRunId},data:{totalFailed:{increment:1},status:"PARTIAL_FAILURE"}})}console.error(JSON.stringify({event:"ai_trade_job_failed",tradeId:job.data.tradeId,userId:job.data.userId,jobId:job.id,attempt:job.attemptsMade+1,duration:Date.now()-started,failureCode:error.code}));if(error.transient&&!last)throw error;return null}}
export const createTradeWorker=()=>new Worker(queues.trade,j=>execute(j,"CREATE"),{connection:getRedisConnection(),concurrency:aiTradeScaleConfig.AI_TRADE_QUEUE_CONCURRENCY});
export const createSettlementWorker=()=>new Worker(queues.settlement,j=>execute(j,"SETTLE"),{connection:getRedisConnection(),concurrency:aiTradeScaleConfig.AI_TRADE_SETTLEMENT_CONCURRENCY});
