import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { findKycByUid, findKycByUserId, KYC_UPLOAD_DIR, saveKycRecord } from "./kyc-store.server";
import { kycMetadataSchema, requiresBack, validateKycFile } from "./kyc-validation";
import { maskDocumentNumber, type KycDocumentKind, type KycNotification, type KycRecord, type KycStatus } from "./kyc-types";
export class KycError extends Error{constructor(public code:string,message:string,public status=400){super(message)}}
const notice=(record:Pick<KycRecord,"userUid"|"submissionVersion">,type:"SUBMITTED"|"APPROVED"|"REJECTED",title:string,message:string):KycNotification=>({id:`KYC_${type}:${record.userUid}:${record.submissionVersion}`,title,message,createdAt:Date.now()});
const safeRecord=(record:KycRecord|null)=>record?{id:record.id,userUid:record.userUid,fullName:record.fullName,dateOfBirth:record.dateOfBirth,country:record.country,residentialAddress:record.residentialAddress,documentType:record.documentType,maskedDocumentNumber:maskDocumentNumber(record.documentNumber),status:record.status,submittedAt:record.submittedAt,reviewedAt:record.reviewedAt,reviewedBy:record.reviewedBy,rejectionReason:record.rejectionReason,submissionVersion:record.submissionVersion,hasBack:Boolean(record.documentBackPath),notifications:record.notifications}: {status:"NOT_SUBMITTED" as const,submissionVersion:0,notifications:[]};
export const getSafeKycForUser=async(userId:string)=>safeRecord(await findKycByUserId(userId));
const submissions=new Map<string,Promise<unknown>>();
async function exclusiveSubmission<T>(userId:string,work:()=>Promise<T>){
  const previous=submissions.get(userId)??Promise.resolve(),current=previous.catch(()=>undefined).then(work);
  submissions.set(userId,current);
  try{return await current}finally{if(submissions.get(userId)===current)submissions.delete(userId)}
}
export async function submitKyc(user:{id:string;uid:string},form:FormData){return exclusiveSubmission(user.id,async()=>{
  const existing=await findKycByUserId(user.id);if(existing?.status==="PENDING")throw new KycError("KYC_PENDING","Your documents are under review.",409);if(existing?.status==="APPROVED")throw new KycError("KYC_APPROVED_LOCKED","Approved KYC cannot be replaced.",409);
  const metadata=kycMetadataSchema.parse(Object.fromEntries(["fullName","dateOfBirth","country","residentialAddress","documentType","documentNumber"].map(key=>[key,String(form.get(key)??"")]))),front=await validateKycFile(form.get("front") instanceof File?form.get("front") as File:undefined,"Front image"),selfie=await validateKycFile(form.get("selfie") instanceof File?form.get("selfie") as File:undefined,"Selfie image"),backValue=form.get("back"),back=backValue instanceof File&&backValue.size?await validateKycFile(backValue,"Back image"):null;
  if(requiresBack(metadata.documentType)&&!back)throw new KycError("KYC_BACK_REQUIRED","Back image is required for this document type.");
  const version=(existing?.submissionVersion??0)+1,folder=`${user.uid}-v${version}-${randomUUID()}`,saved:string[]=[];
  try{
    await mkdir(KYC_UPLOAD_DIR,{recursive:true});
    const save=async(kind:KycDocumentKind,file:Awaited<ReturnType<typeof validateKycFile>>)=>{const name=`${folder}-${kind}.${file.extension}`;await writeFile(path.join(KYC_UPLOAD_DIR,name),Buffer.from(await file.file.arrayBuffer()),{flag:"wx"});saved.push(name);return name};
    const frontPath=await save("front",front),selfiePath=await save("selfie",selfie),backPath=back?await save("back",back):null,now=Date.now(),before=existing?.status??"NOT_SUBMITTED",base={userUid:user.uid,submissionVersion:version},notification=notice(base,"SUBMITTED","KYC Submitted","Your KYC documents were submitted and are under review."),record:KycRecord={id:existing?.id??`KYC:${user.uid}`,userId:user.id,userUid:user.uid,...metadata,documentFrontPath:frontPath,documentBackPath:backPath,selfiePath,documentMimeTypes:{front:front.mime,back:back?.mime??null,selfie:selfie.mime},status:"PENDING",submittedAt:now,reviewedAt:null,reviewedBy:null,rejectionReason:null,submissionVersion:version,createdAt:existing?.createdAt??now,updatedAt:now,history:[{id:`KYC_${existing?"RESUBMITTED":"SUBMITTED"}:${user.uid}:${version}`,action:existing?"RESUBMITTED":"SUBMITTED",actor:user.uid,beforeStatus:before,afterStatus:"PENDING",reason:null,timestamp:now,submissionVersion:version},...(existing?.history??[])],notifications:[notification,...(existing?.notifications??[])]};
    await saveKycRecord(record);return safeRecord(record);
  }catch(error){await Promise.all(saved.map(name=>rm(path.join(KYC_UPLOAD_DIR,name),{force:true}).catch(()=>undefined)));throw error}
})}
export async function reviewKyc(uid:string,action:"APPROVE"|"REJECT",adminId:string,reason?:string){const record=await findKycByUid(uid);if(!record)throw new KycError("KYC_NOT_FOUND","KYC record not found.",404);const target:KycStatus=action==="APPROVE"?"APPROVED":"REJECTED";if(record.status===target)return{record,changed:false};if(record.status!=="PENDING")throw new KycError("KYC_NOT_PENDING","Only pending KYC can be reviewed.",409);const cleanReason=reason?.trim()??"";if(action==="REJECT"&&cleanReason.length<3)throw new KycError("REJECTION_REASON_REQUIRED","A rejection reason is required.");const now=Date.now(),notification=action==="APPROVE"?notice(record,"APPROVED","KYC Approved","Your KYC verification has been approved successfully."):notice(record,"REJECTED","KYC Rejected",`Your KYC was rejected: ${cleanReason}. You may correct the information and resubmit.`),next:KycRecord={...record,status:target,reviewedAt:now,reviewedBy:adminId,rejectionReason:action==="REJECT"?cleanReason:null,updatedAt:now,history:[{id:`KYC_${target}:${uid}:${record.submissionVersion}`,action:target,actor:adminId,beforeStatus:"PENDING",afterStatus:target,reason:action==="REJECT"?cleanReason:null,timestamp:now,submissionVersion:record.submissionVersion},...record.history],notifications:record.notifications.some(item=>item.id===notification.id)?record.notifications:[notification,...record.notifications]};await saveKycRecord(next);return{record:next,changed:true}}
export async function assertWithdrawalKycEligibility(userId:string){const record=await findKycByUserId(userId);if(record?.status!=="APPROVED")throw new KycError("KYC_REQUIRED_FOR_WITHDRAWAL","Your KYC must be approved before you can request a withdrawal.",403);return record}
export async function getKycDocument(record:KycRecord,kind:KycDocumentKind){const relative=kind==="front"?record.documentFrontPath:kind==="back"?record.documentBackPath:record.selfiePath;if(!relative)throw new KycError("DOCUMENT_NOT_FOUND","Document not found.",404);if(path.basename(relative)!==relative)throw new KycError("INVALID_DOCUMENT_PATH","Invalid document path.",400);const full=path.resolve(KYC_UPLOAD_DIR,relative),root=path.resolve(KYC_UPLOAD_DIR);if(!full.startsWith(`${root}${path.sep}`))throw new KycError("INVALID_DOCUMENT_PATH","Invalid document path.",400);return{bytes:await readFile(full),mime:record.documentMimeTypes[kind]??"application/octet-stream"}}
