"use client";
import { useEffect, useRef, useState } from "react";
import { formatLocalDateTime } from "@/lib/date-time";

type Banner={id:string;title:string;imageUrl:string;status:"DRAFT"|"ACTIVE"|"INACTIVE"|"EXPIRED";isActive:boolean;startsAt:string|null;expiresAt:string|null;fileSize:number;width:number;height:number;createdAt:string};
type Dimensions={width:number;height:number};
const local=(value:string|null)=>value?formatLocalDateTime(value):"Not set",acceptedTypes=new Set(["image/jpeg","image/jpg","image/png","image/webp"]),toUtc=(value:string)=>value?new Date(value).toISOString():"";

export function BannerManagement(){
  const[banners,setBanners]=useState<Banner[]>([]),[title,setTitle]=useState(""),[startsAt,setStartsAt]=useState(""),[expiresAt,setExpiresAt]=useState(""),[file,setFile]=useState<File|null>(null),[sourcePreview,setSourcePreview]=useState(""),[processedPreview,setProcessedPreview]=useState(""),[dimensions,setDimensions]=useState<Dimensions|null>(null),[replaceId,setReplaceId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),uploadKey=useRef(crypto.randomUUID());
  const load=()=>fetch("/api/admin/banners",{cache:"no-store"}).then(async response=>{const value=await response.json();if(response.ok)setBanners(value.banners??[])});
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(!file){setSourcePreview("");setDimensions(null);return}if(!acceptedTypes.has(file.type.toLowerCase())){setMessage("We could not process this image. Please try another JPG, PNG, or WEBP file.");return}const url=URL.createObjectURL(file),image=new Image();setSourcePreview(url);setProcessedPreview("");image.onload=()=>{const next={width:image.naturalWidth,height:image.naturalHeight},ratio=next.width/next.height;setDimensions(next);if(next.width>=next.height||ratio<.50||ratio>.62)setMessage("Please upload a portrait banner image.");else setMessage("")};image.onerror=()=>{setDimensions(null);setMessage("We could not process this image. Please try another JPG, PNG, or WEBP file.")};image.src=url;return()=>URL.revokeObjectURL(url)},[file]);
  const choose=(selected:File|null)=>{if(selected&&selected!==file)uploadKey.current=crypto.randomUUID();setFile(selected)};
  const upload=async()=>{if(!file)return setMessage("Choose a JPG, PNG, or WEBP banner image.");if(!dimensions)return setMessage("We could not process this image. Please try another JPG, PNG, or WEBP file.");const ratio=dimensions.width/dimensions.height;if(dimensions.width>=dimensions.height||ratio<.50||ratio>.62)return setMessage("Please upload a portrait banner image.");setBusy(true);setMessage("");try{const form=new FormData();form.set("image",file);form.set("title",title);form.set("startsAt",toUtc(startsAt));form.set("expiresAt",toUtc(expiresAt));form.set("replaceId",replaceId);form.set("uploadKey",uploadKey.current);const response=await fetch("/api/admin/banners",{method:"POST",body:form}),value=await response.json();if(!response.ok){setMessage(value.error??"Upload failed.");return}const banner=value.banner as Banner;setMessage(replaceId?"Banner image replaced successfully.":"Banner uploaded successfully as a draft.");setProcessedPreview(`${banner.imageUrl}?preview=${Date.now()}`);setFile(null);setReplaceId("");uploadKey.current=crypto.randomUUID();await load()}catch{setMessage("We could not process this image. Please try another JPG, PNG, or WEBP file.")}finally{setBusy(false)}};
  const act=async(id:string,action:"ACTIVATE"|"DEACTIVATE")=>{setBusy(true);const response=await fetch(`/api/admin/banners/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})}),value=await response.json();setMessage(response.ok?`Banner ${action.toLowerCase()}d.`:value.error??"Action failed.");await load();setBusy(false)};
  const remove=async(id:string)=>{if(!confirm("Delete this banner and its stored image?"))return;setBusy(true);const response=await fetch(`/api/admin/banners/${id}`,{method:"DELETE"});setMessage(response.ok?"Banner deleted.":"Delete failed.");await load();setBusy(false)};
  const preview=sourcePreview||processedPreview;
  return <div className="banner-admin"><section className="admin-form banner-upload-form"><h2>{replaceId?"Replace banner image":"Upload portrait banner"}</h2><input placeholder="Admin reference title" value={title} onChange={event=>setTitle(event.target.value)} disabled={Boolean(replaceId)}/><label>Start date/time<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)} disabled={Boolean(replaceId)}/></label><label>Expiry date/time<input type="datetime-local" value={expiresAt} onChange={event=>setExpiresAt(event.target.value)} disabled={Boolean(replaceId)}/></label><input type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={event=>choose(event.target.files?.[0]??null)}/>{replaceId&&<button onClick={()=>setReplaceId("")}>Cancel replacement</button>}<button onClick={upload} disabled={busy}>{busy?"Saving…":replaceId?"Replace image":"Upload draft"}</button>{file&&<p>{file.name} · {(file.size/1024/1024).toFixed(2)} MB{dimensions?` · ${dimensions.width}×${dimensions.height}`:" · Reading dimensions…"}</p>}{message&&<p className="banner-admin-message">{message}</p>}</section>{preview&&<section className="admin-card banner-preview"><h2>Final 9:16 crop preview</h2><img src={preview} alt="Final cropped banner preview"/><p>The center area shown here will be saved at 1080×1920. Maximum upload size: 8 MB.</p></section>}<section className="admin-card"><h2>Current active banner</h2>{banners.find(item=>item.isActive)?<BannerCard banner={banners.find(item=>item.isActive)!} busy={busy} act={act} remove={remove} replace={setReplaceId}/>:<p>No active banner.</p>}</section><section className="admin-card banner-history"><h2>Banner history</h2>{banners.map(banner=><BannerCard key={banner.id} banner={banner} busy={busy} act={act} remove={remove} replace={setReplaceId}/>)}</section></div>
}

function BannerCard({banner,busy,act,remove,replace}:{banner:Banner;busy:boolean;act:(id:string,action:"ACTIVATE"|"DEACTIVATE")=>void;remove:(id:string)=>void;replace:(id:string)=>void}){return <article><img src={banner.imageUrl} alt={banner.title}/><div><strong>{banner.title}</strong><span>{banner.status} · {banner.width}×{banner.height} · {(banner.fileSize/1024/1024).toFixed(2)} MB</span><span>Start: {local(banner.startsAt)} · Expiry: {local(banner.expiresAt)}</span><span>Created: {local(banner.createdAt)}</span><div><button disabled={busy} onClick={()=>act(banner.id,banner.isActive?"DEACTIVATE":"ACTIVATE")}>{banner.isActive?"Deactivate":"Activate"}</button><button disabled={busy} onClick={()=>replace(banner.id)}>Replace image</button><button disabled={busy} onClick={()=>remove(banner.id)}>Delete</button></div></div></article>}
