"use client";
import { useEffect,useState } from "react";
import { formatCurrency } from "@/lib/currency";
import { formatLocalDateTime } from "@/lib/date-time";

type Cycle={id:string;cycleKey:string;scheduledAt:string;status:string;totalCandidates:number;totalEligible:number;totalPaid:number;totalSkipped:number;totalFailed:number;totalAmount:string;startedAt:string|null;completedAt:string|null};
type Payment={id:string;evaluatedRank:number;salaryAmount:string;eligibilitySnapshotJson:unknown;paymentStatus:string;skipReason:string|null;paidAt:string|null;ledgerKey:string;user:{uid:string;name:string}};
type CycleDetail=Cycle&{payments:Payment[]};

export function SalaryManagement(){
  const[cycles,setCycles]=useState<Cycle[]>([]),[detail,setDetail]=useState<CycleDetail|null>(null),[message,setMessage]=useState("");
  const load=()=>fetch("/api/admin/salary",{cache:"no-store"}).then(response=>response.json() as Promise<Cycle[]>).then(setCycles);
  useEffect(()=>{void load()},[]);
  const open=(id:string)=>fetch(`/api/admin/salary?cycleId=${id}`,{cache:"no-store"}).then(response=>response.json() as Promise<CycleDetail>).then(setDetail);
  const action=async(body:object)=>{const response=await fetch("/api/admin/salary",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await response.json() as {message?:string;error?:string};setMessage(data.message??data.error??"");await load();if(detail)await open(detail.id)};
  const exportCsv=()=>{if(!detail)return;const rows=["UID,Rank,Amount,Status,Skip Reason,Paid At,Ledger",...detail.payments.map(payment=>[payment.user.uid,payment.evaluatedRank,payment.salaryAmount,payment.paymentStatus,payment.skipReason??"",payment.paidAt??"",payment.ledgerKey].map(value=>`"${String(value).replaceAll('"','""')}"`).join(","))],blob=new Blob([rows.join("\n")],{type:"text/csv"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`${detail.cycleKey}.csv`;anchor.click();URL.revokeObjectURL(url)};
  return <div className="admin-page"><header className="admin-page-head"><div><small>Recurring current-rank income</small><h1>Salary Management</h1></div><button onClick={exportCsv} disabled={!detail}>Export CSV</button></header>{message&&<div className="admin-banner">{message}</div>}<div className="admin-table-wrap"><table><thead><tr><th>Cycle</th><th>Scheduled</th><th>Status</th><th>Candidates</th><th>Eligible</th><th>Paid</th><th>Skipped</th><th>Failed</th><th>Total</th><th>Duration</th></tr></thead><tbody>{cycles.map(cycle=><tr key={cycle.id} onClick={()=>void open(cycle.id)}><td>{cycle.cycleKey}</td><td>{formatLocalDateTime(cycle.scheduledAt)}</td><td>{cycle.status}</td><td>{cycle.totalCandidates}</td><td>{cycle.totalEligible}</td><td>{cycle.totalPaid}</td><td>{cycle.totalSkipped}</td><td>{cycle.totalFailed}</td><td>{formatCurrency(Number(cycle.totalAmount))}</td><td>{cycle.completedAt&&cycle.startedAt?`${new Date(cycle.completedAt).getTime()-new Date(cycle.startedAt).getTime()} ms`:"—"}</td></tr>)}</tbody></table></div>{detail&&<><button onClick={()=>void action({action:"RECONCILE",cycleId:detail.id})}>Reconcile cycle</button><div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Rank</th><th>Salary</th><th>Snapshot</th><th>Status</th><th>Skip reason</th><th>Paid</th><th>Ledger</th><th>Action</th></tr></thead><tbody>{detail.payments.map(payment=><tr key={payment.id}><td>{payment.user.uid}<small>{payment.user.name}</small></td><td>{payment.evaluatedRank} Star</td><td>{formatCurrency(Number(payment.salaryAmount))}</td><td><small>{JSON.stringify(payment.eligibilitySnapshotJson)}</small></td><td>{payment.paymentStatus}</td><td>{payment.skipReason??"—"}</td><td>{formatLocalDateTime(payment.paidAt)}</td><td>{payment.ledgerKey}</td><td>{payment.paymentStatus==="FAILED"&&<button onClick={()=>void action({action:"RETRY",cycleId:detail.id,paymentId:payment.id})}>Retry</button>}</td></tr>)}</tbody></table></div></>}</div>
}
