"use client";
import { useEffect,useState } from "react";
type Row={id:string;user:{id:string;uid:string;name:string;email:string};requestedAmount:string;platformFee:string;recipientAmount:string;destinationAddress:string;network:string;createdAt:string;userLocalDate:string;status:string;processingMode:string;previousHistoryCount:number;rejectionReason:string|null;txHash:string|null};
export function WithdrawalAdminPanel(){
  const[rows,setRows]=useState<Row[]>([]),[hashes,setHashes]=useState<Record<string,string>>({}),[targets,setTargets]=useState<Record<string,"BROADCASTED"|"COMPLETED">>({}),[reasons,setReasons]=useState<Record<string,string>>({}),[message,setMessage]=useState("");
  const load=()=>fetch("/api/admin/withdrawals",{cache:"no-store"}).then(r=>r.json()).then(value=>setRows(value.withdrawals??[]));
  useEffect(()=>{void load()},[]);
  const action=async(body:Record<string,string>)=>{const response=await fetch("/api/admin/withdrawals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json();setMessage(response.ok?"Withdrawal updated.":value.error??"Action failed.");if(response.ok)await load()};
  return <><div className="admin-banner">Admin approval is available only for ADMIN_FALLBACK withdrawals. Automatic withdrawals cannot be approved here.</div>{message&&<div className="admin-banner">{message}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr>{["User","Wallet","Requested / Fee / Recipient","Destination","Network","Request date / Local date","Status / Mode","History","Action"].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.user.name}<small>{row.user.email} · {row.user.uid} · {row.user.id}</small></td><td>Spot</td><td>{row.requestedAmount}<small>Fee {row.platformFee} · Recipient {row.recipientAmount}</small></td><td><small>{row.destinationAddress}</small></td><td>{row.network}</td><td>{new Date(row.createdAt).toLocaleString()}<small>{row.userLocalDate}</small></td><td>{row.status}<small>{row.processingMode}</small></td><td>{row.previousHistoryCount} previous</td><td>{row.status==="PENDING_ADMIN_REVIEW"&&row.processingMode==="ADMIN_FALLBACK"?<div><input aria-label="Transaction hash" placeholder="0x transaction hash" value={hashes[row.id]??""} onChange={event=>setHashes(v=>({...v,[row.id]:event.target.value}))}/><select aria-label="Approval status" value={targets[row.id]??"BROADCASTED"} onChange={event=>setTargets(v=>({...v,[row.id]:event.target.value as "BROADCASTED"|"COMPLETED"}))}><option value="BROADCASTED">Broadcasted</option><option value="COMPLETED">Completed</option></select><button onClick={()=>void action({action:"APPROVE",withdrawalId:row.id,txHash:hashes[row.id]??"",targetStatus:targets[row.id]??"BROADCASTED"})}>Approve</button><input aria-label="Rejection reason" placeholder="Rejection reason" value={reasons[row.id]??""} onChange={event=>setReasons(v=>({...v,[row.id]:event.target.value}))}/><button onClick={()=>void action({action:"REJECT",withdrawalId:row.id,reason:reasons[row.id]??""})}>Reject</button></div>:<small>{row.txHash??row.rejectionReason??"No action available"}</small>}</td></tr>)}</tbody></table></div></>
}
