import "dotenv/config";
import { prisma } from "@/lib/prisma";
import { getWalletReadSnapshot } from "@/lib/future-wallet.server";
import { formatUserTimestamp,resolveUserTimeZone } from "@/lib/timezone.server";
import { aiTradeScaleConfig,queues } from "@/lib/ai-trade-scale/config";
import { createBullJobId,creationJobKey,scheduleSessionsForUser } from "@/lib/ai-trade-scale/orchestrator";
import { closeAiTradeQueues,getRedisConnection,getTradeQueue } from "@/lib/ai-trade-scale/queue";

const argument=process.argv.find(value=>value.startsWith("--user="))?.slice("--user=".length).trim();
const bounded=<T>(operation:Promise<T>,milliseconds=5_000)=>Promise.race<T>([operation,new Promise<T>((_,reject)=>setTimeout(()=>reject(new Error(`Timed out after ${milliseconds}ms`)),milliseconds))]);

async function main(){
  if(!argument)throw new Error("Usage: npm run ai-trade:runtime-diagnose -- --user=<USER_ID_OR_EMAIL>");
  const now=new Date(),catchUpBoundary=new Date(now.getTime()-aiTradeScaleConfig.AI_TRADE_CATCH_UP_HOURS*60*60_000),user=await prisma.user.findFirst({where:{OR:[{id:argument},{email:{equals:argument,mode:"insensitive"}},{uid:{equals:argument.toUpperCase(),mode:"insensitive"}}]},select:{id:true,uid:true,email:true,timezone:true,country:true,additionalTradeEligibility:true,aiBotSubscriptions:{where:{status:"ACTIVE",activatedAt:{lte:now},expiresAt:{gt:catchUpBoundary}},orderBy:{activatedAt:"desc"},select:{id:true,status:true,activatedAt:true,expiresAt:true}}}});
  if(!user)throw new Error("User not found.");
  const timeZone=resolveUserTimeZone(user.timezone,user.country),wallet=await getWalletReadSnapshot(user.id),schedule=scheduleSessionsForUser(user,now),slots=await Promise.all(schedule.map(async item=>{
    const sessionKey=`${item.session.id}:${item.session.timeZone}`,run=await prisma.tradeSessionRun.findUnique({where:{localTradingDate_sessionId_tradeType:{localTradingDate:item.session.tradingDate,sessionId:sessionKey,tradeType:"AI_BOT"}},select:{id:true,status:true,localTradingDate:true,localSessionSlot:true,tradeType:true,totalEligible:true,totalQueued:true,totalStarted:true,totalFailed:true}});
    const trade=run?await prisma.aiFinancialTrade.findUnique({where:{userId_sessionRunId_tradeType:{userId:user.id,sessionRunId:run.id,tradeType:"AI_BOT"}},select:{id:true,executionKey:true,status:true,failureCode:true,createdAt:true}}):null,job=run?await prisma.aiTradeJob.findFirst({where:{OR:[{jobKey:creationJobKey(run,user.id)},{sessionRunId:run.id,userId:user.id,kind:"CREATE"}]},select:{id:true,jobKey:true,bullJobId:true,status:true,attempts:true,failureCode:true,failureMessage:true}}):null;
    const skippedReason=trade?"TRADE_EXISTS":job?`JOB_${job.status}`:!item.due?"FUTURE_SESSION":!item.insideCatchUp?"OUTSIDE_CATCH_UP_WINDOW":!item.subscriptionEligible?"SUBSCRIPTION_NOT_ACTIVE_AT_SLOT":!item.additionalEligible?"ADDITIONAL_WINDOW_INELIGIBLE":!wallet.authoritativeReady?wallet.missingWallet?"RELATIONAL_WALLET_MISSING":"OPENING_LEDGER_MISSING":!wallet.availableFuture.isPositive()?"INSUFFICIENT_AUTHORITATIVE_FUTURE":"DUE_NOT_ENQUEUED";
    return{slot:item.session.sequence,type:item.session.type,expectedLocal:formatUserTimestamp(item.session.liveFrom,timeZone).localDateTime,due:item.due,insideCatchUp:item.insideCatchUp,eligible:item.subscriptionEligible&&item.additionalEligible,sessionId:item.session.id,sessionKey,expectedBullJobId:run?createBullJobId(run,user.id):null,run,job,trade,skippedReason}
  }));
  const latestFailure=await prisma.aiTradeJob.findFirst({where:{userId:user.id,status:{in:["FAILED","DEAD"]}},orderBy:{updatedAt:"desc"},select:{jobKey:true,bullJobId:true,queueName:true,status:true,attempts:true,failureCode:true,failureMessage:true,updatedAt:true}});
  let redis:{healthy:boolean;ping?:string;error?:string}={healthy:false},queueCounts:Record<string,number>|null=null;
  try{const ping=await bounded(getRedisConnection().ping()),queue=getTradeQueue();redis={healthy:ping==="PONG",ping};queueCounts=await bounded(queue.getJobCounts("waiting","active","delayed","failed","completed"))}catch(error){redis={healthy:false,error:error instanceof Error?error.message:"Unknown Redis error"}}
  const retryDeployedAt=process.env.AI_TRADE_40001_RETRY_DEPLOYED_AT?new Date(process.env.AI_TRADE_40001_RETRY_DEPLOYED_AT):null,failureContext=latestFailure?{failedAt:latestFailure.updatedAt,ageMs:now.getTime()-latestFailure.updatedAt.getTime(),relativeToRetryDeployment:retryDeployedAt&&!Number.isNaN(retryDeployedAt.getTime())?(latestFailure.updatedAt<retryDeployedAt?"HISTORICAL_PRE_RETRY_DEPLOYMENT":"FRESH_POST_RETRY_DEPLOYMENT"):"DEPLOYMENT_TIMESTAMP_NOT_CONFIGURED"}:null;
  console.log(JSON.stringify({readOnly:true,currentUtc:now.toISOString(),catchUpPolicy:{currentLocalDateOnly:true,hours:aiTradeScaleConfig.AI_TRADE_CATCH_UP_HOURS},user:{id:user.id,uid:user.uid,email:user.email,storedTimezone:user.timezone,resolvedTimezone:timeZone,currentLocalTime:formatUserTimestamp(now,timeZone).localDateTime},activeAiBotSubscriptions:user.aiBotSubscriptions,authoritativeFutureWallet:{ready:wallet.authoritativeReady,source:wallet.source,availableFuture:wallet.availableFuture.toString(),missingWallet:wallet.missingWallet,missingOpeningLedger:wallet.missingOpeningLedger},slots,redis:{urlConfigured:Boolean(process.env.REDIS_URL),queueNames:queues,...redis},tradeQueue:{counts:queueCounts},serializationRetry:{active:true,sqlState:"40001",maximumRetries:5,deployedAt:retryDeployedAt,successEvent:"ai_trade_serialization_retry_succeeded"},latestWorkerError:latestFailure?{...latestFailure,context:failureContext}:null,legacyNewTradesEnabled:process.env.LEGACY_AI_TRADE_ALLOW_NEW==="YES"},null,2));
}

main().catch(error=>{console.error(JSON.stringify({readOnly:true,error:error instanceof Error?error.message:"Unknown diagnostic failure"},null,2));process.exitCode=1}).finally(async()=>{await closeAiTradeQueues().catch(()=>{});await prisma.$disconnect()});
