import "dotenv/config";
import { prisma } from "@/lib/prisma";
import { loadVisibleTradeHistory } from "@/lib/trade-history-compat.server";
import { closeAiTradeQueues,getSettlementQueue } from "@/lib/ai-trade-scale/queue";
import { createDailySessions,getTradingDate } from "@/lib/ai-trading-engine";
import { resolveUserTimeZone } from "@/lib/timezone.server";
import { resolveAuthoritativeTradeSource,tradeSourceLabel } from "@/lib/trade-source";

const argument=process.argv.find(value=>value.startsWith("--user="))?.slice(7).trim();
const classify=(value:{createdAt:Date;scheduledStartAt:Date;scheduledSettleAt:Date;status:string;returned:boolean;profited:boolean},now:Date)=>{
  if(value.createdAt<value.scheduledStartAt)return"FUTURE_SESSION_CREATED_EARLY";
  if(value.returned!==value.profited)return"MANUAL_REVIEW";
  if(value.returned&&value.profited&&value.status!=="SETTLED")return"SETTLED_STATUS_STALE";
  if(value.status==="SETTLED")return"MANUAL_REVIEW";
  if(value.scheduledSettleAt<=now)return"OVERDUE_SETTLEMENT";
  if(["LOCKED","SETTLING"].includes(value.status))return"VALID_ACTIVE";
  return"MANUAL_REVIEW";
};
async function main(){
  if(!argument)throw new Error("Usage: npm run ai-trade:active-audit -- --user=<USER_ID_OR_EMAIL>");
  const user=await prisma.user.findFirst({where:{OR:[{id:argument},{email:{equals:argument,mode:"insensitive"}},{uid:{equals:argument.toUpperCase(),mode:"insensitive"}}]},select:{id:true,uid:true,timezone:true,country:true}});
  if(!user)throw new Error("User not found.");
  const now=new Date(),trades=await prisma.aiFinancialTrade.findMany({where:{userId:user.id},include:{sessionRun:true},orderBy:{createdAt:"asc"}}),visible=await loadVisibleTradeHistory(user.id,500),settlementQueue=getSettlementQueue(),rows=[];
  for(const trade of trades){
    const sessionId=/^AI_SESSION:\d{4}-\d{2}-\d{2}:(?:1|2|3|ADDITIONAL)/.exec(trade.sessionRun.sessionId)?.[0]??trade.sessionRun.sessionId,[lock,principalReturn,profitCredit,settlementJob,creationJob,manualIntent,subscription]=await Promise.all([
      prisma.aiWalletLedger.findUnique({where:{idempotencyKey:`TRADE_LOCK:${trade.id}`},select:{id:true,idempotencyKey:true,amount:true,createdAt:true}}),
      prisma.aiWalletLedger.findUnique({where:{idempotencyKey:`TRADE_PRINCIPAL_RETURN:${trade.id}`},select:{id:true,idempotencyKey:true,amount:true,createdAt:true}}),
      prisma.aiWalletLedger.findUnique({where:{idempotencyKey:`TRADE_PROFIT:${trade.id}`},select:{id:true,idempotencyKey:true,amount:true,createdAt:true}}),
      prisma.aiTradeJob.findUnique({where:{jobKey:`SETTLE:${trade.id}`}}),
      prisma.aiTradeJob.findFirst({where:{sessionRunId:trade.sessionRunId,userId:user.id,kind:"CREATE"},orderBy:{createdAt:"desc"}}),
      prisma.aiTradeIntent.findFirst({where:{userId:user.id,sessionId,usedAt:{not:null}},orderBy:{usedAt:"desc"},select:{id:true,createdAt:true,usedAt:true}}),
      trade.subscriptionId?prisma.aiBotSubscription.findUnique({where:{id:trade.subscriptionId},select:{id:true,status:true,activatedAt:true,expiresAt:true}}):null
    ]),bullJobId=settlementJob?.bullJobId??null,bullJob=bullJobId?await settlementQueue.getJob(bullJobId):null,redisState=bullJob?await bullJob.getState():null,resolvedSource=resolveAuthoritativeTradeSource({placementSource:trade.placementSource,tradeType:trade.tradeType,sessionTradeType:trade.sessionRun.tradeType}),apiLabel=tradeSourceLabel(resolvedSource,"RELATIONAL");
    rows.push({classification:classify({createdAt:trade.createdAt,scheduledStartAt:trade.sessionRun.scheduledStartAt,scheduledSettleAt:trade.sessionRun.scheduledSettleAt,status:trade.status,returned:Boolean(principalReturn),profited:Boolean(profitCredit)},now),tradeId:trade.id,source:resolvedSource,sourceProvenance:{authoritativeDatabaseSource:{aiFinancialTradeTradeType:trade.tradeType,aiFinancialTradePlacementSource:trade.placementSource,subscriptionId:trade.subscriptionId},jobSource:creationJob&&{id:creationJob.id,kind:creationJob.kind,jobKey:creationJob.jobKey,status:creationJob.status},sessionSource:{tradeSessionRunId:trade.sessionRun.id,tradeType:trade.sessionRun.tradeType,sessionType:trade.sessionRun.sessionType},manualIntent,aiBotSubscription:subscription,apiReturnedSource:resolvedSource,apiReturnedLabel:apiLabel,uiRenderedLabel:apiLabel,labelConverter:"lib/trade-source.ts:tradeSourceLabel",sourceConsistency:resolvedSource==="MANUAL"&&!manualIntent?"MANUAL_WITHOUT_USED_INTENT_REVIEW":resolvedSource==="AI_BOT"&&!subscription?"AI_BOT_WITHOUT_LINKED_SUBSCRIPTION_REVIEW":"CONSISTENT"},localDate:trade.localTradingDate,localSlot:trade.localSessionSlot,actualCreatedAt:trade.createdAt,scheduledSessionTime:trade.sessionRun.scheduledStartAt,status:trade.status,principal:trade.principal.toString(),principalLockLedger:lock&&{id:lock.id,idempotencyKey:lock.idempotencyKey,amount:lock.amount.toString(),createdAt:lock.createdAt},settlementJobId:settlementJob?.id??null,settlementBullJobId:bullJobId,settlementDueTime:trade.sessionRun.scheduledSettleAt,settlementJobRedisState:redisState,principalReturnLedger:principalReturn&&{id:principalReturn.id,idempotencyKey:principalReturn.idempotencyKey,amount:principalReturn.amount.toString(),createdAt:principalReturn.createdAt},profitCreditLedger:profitCredit&&{id:profitCredit.id,idempotencyKey:profitCredit.idempotencyKey,amount:profitCredit.amount.toString(),createdAt:profitCredit.createdAt},uiStatusSource:"RELATIONAL"});
  }
  const timeZone=resolveUserTimeZone(user.timezone,user.country),legacy=visible.filter(trade=>trade.source==="LEGACY_COMPATIBILITY").map(trade=>{const localDate=getTradingDate(trade.placedAt,timeZone),session=createDailySessions(localDate,trade.placedAt,timeZone).find(value=>value.id===trade.sessionId),label=tradeSourceLabel(trade.placementSource,"LEGACY_COMPATIBILITY");return{classification:"LEGACY_DISPLAY_ONLY",tradeId:trade.id,source:trade.placementSource,sourceProvenance:{authoritativeDatabaseSource:null,jobSource:null,sessionSource:null,legacyCompatibilitySource:trade.source,apiReturnedSource:trade.placementSource,apiReturnedLabel:label,uiRenderedLabel:label,labelConverter:"lib/trade-source.ts:tradeSourceLabel"},localDate,localSlot:trade.sessionId.split(":").at(-1)??null,actualCreatedAt:new Date(trade.placedAt),scheduledSessionTime:session?new Date(session.liveFrom):null,status:trade.status,principal:String(trade.principal),principalLockLedger:null,settlementJobId:null,settlementBullJobId:null,settlementDueTime:session?new Date(session.settlesAt):null,settlementJobRedisState:null,principalReturnLedger:null,profitCreditLedger:null,uiStatusSource:"LEGACY_COMPATIBILITY"}}),failedJobs=await prisma.aiTradeJob.findMany({where:{userId:user.id,kind:"CREATE",status:{in:["FAILED","DEAD"]}},include:{sessionRun:true}});
  const failed=failedJobs.filter(job=>!trades.some(trade=>trade.sessionRunId===job.sessionRunId&&trade.tradeType===job.sessionRun.tradeType)).map(job=>{const source=resolveAuthoritativeTradeSource({tradeType:job.sessionRun.tradeType,sessionTradeType:job.sessionRun.tradeType}),label=tradeSourceLabel(source,"RELATIONAL_JOB");return{classification:"FAILED_NO_TRADE",tradeId:null,source,sourceProvenance:{authoritativeDatabaseSource:null,jobSource:{id:job.id,kind:job.kind,jobKey:job.jobKey,status:job.status},sessionSource:{tradeSessionRunId:job.sessionRun.id,tradeType:job.sessionRun.tradeType,sessionType:job.sessionRun.sessionType},apiReturnedSource:source,apiReturnedLabel:label,uiRenderedLabel:label,labelConverter:"lib/trade-source.ts:tradeSourceLabel"},localDate:job.sessionRun.localTradingDate,localSlot:job.sessionRun.localSessionSlot,actualCreatedAt:job.createdAt,scheduledSessionTime:job.sessionRun.scheduledStartAt,status:job.status,principal:null,principalLockLedger:null,settlementJobId:null,settlementBullJobId:null,settlementDueTime:job.sessionRun.scheduledSettleAt,settlementJobRedisState:null,principalReturnLedger:null,profitCreditLedger:null,uiStatusSource:"RELATIONAL_JOB",creationJob:{id:job.id,failureCode:job.failureCode,failureMessage:job.failureMessage,failedAt:job.updatedAt}}});
  console.log(JSON.stringify({readOnly:true,generatedAt:now,user:{id:user.id,uid:user.uid,persistedTimezone:user.timezone},trades:[...rows,...failed,...legacy]},null,2));
}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1}).finally(async()=>{await closeAiTradeQueues().catch(()=>{});await prisma.$disconnect()});
