import "dotenv/config";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { createDailySessions,migrateTradingStore } from "@/lib/ai-trading-engine";
import { ensureFutureWallet } from "@/lib/future-wallet.server";
const apply=process.argv.includes("--apply");
async function main(){const executions=await prisma.aiBotTradeExecution.findMany({include:{user:{select:{state:{select:{trading:true}}}},subscription:true},orderBy:{createdAt:"asc"}}),result={mode:apply?"APPLY":"DRY_RUN",alreadyRepresented:0,pending:0,completedHistory:0,inconsistent:0,migrated:0};
  for(const execution of executions){if(await prisma.aiLegacyTradeMigration.findUnique({where:{sourceType_sourceId:{sourceType:"AI_BOT_EXECUTION",sourceId:execution.id}}})){result.alreadyRepresented++;continue}const legacy=migrateTradingStore(execution.user.state?.trading).trades.find(item=>item.id===execution.tradeId);if(!legacy){result.inconsistent++;if(apply)await prisma.aiLegacyTradeMigration.create({data:{sourceType:"AI_BOT_EXECUTION",sourceId:execution.id,userId:execution.userId,classification:"INCONSISTENT",status:"MANUAL_REVIEW",details:{reason:"TRADE_NOT_FOUND"}}});continue}const classification=execution.status==="SETTLED"||legacy.status==="SETTLED"?"COMPLETED_HISTORY_ONLY":"PENDING";if(classification==="PENDING")result.pending++;else result.completedHistory++;if(!apply)continue;
    await prisma.$transaction(async tx=>{await ensureFutureWallet(tx,execution.userId);const wallet=await tx.aiFinancialWallet.findUniqueOrThrow({where:{userId:execution.userId}}),session=createDailySessions(execution.tradingDate,execution.placedAt.getTime(),execution.timeZone).find(item=>item.id===execution.sessionId);if(!session)throw new Error(`Legacy session unavailable: ${execution.id}`);const run=await tx.tradeSessionRun.upsert({where:{localTradingDate_sessionId_tradeType:{localTradingDate:execution.tradingDate,sessionId:`${session.id}:${execution.timeZone}`,tradeType:"AI_BOT"}},create:{sessionId:`${session.id}:${execution.timeZone}`,localTradingDate:execution.tradingDate,tradeType:"AI_BOT",sessionType:session.type,localSessionSlot:String(session.sequence),timeZone:execution.timeZone,scheduledStartAt:new Date(session.liveFrom),referencePriceAt:new Date(session.liveFrom),scheduledSettleAt:new Date(session.settlesAt),officialSettledAt:new Date(session.settlesAt),pair:session.pair,direction:session.signalDirection,profitRate:new Prisma.Decimal(String(legacy.profitRate)),resultSource:"LEGACY_MIGRATION",status:classification==="PENDING"?"RUNNING":"COMPLETED"},update:{}}),existing=await tx.aiFinancialTrade.findUnique({where:{executionKey:`LEGACY:${execution.executionKey}`}});let tradeId=existing?.id;if(!existing){if(classification==="PENDING"&&wallet.lockedFuture.lt(new Prisma.Decimal(String(legacy.tradeCapital))))throw new Error(`Legacy lock unavailable: ${execution.id}`);const trade=await tx.aiFinancialTrade.create({data:{executionKey:`LEGACY:${execution.executionKey}`,sessionRunId:run.id,userId:execution.userId,subscriptionId:execution.subscriptionId,tradeType:"AI_BOT",placementSource:"AI_BOT",userTimeZone:execution.timeZone,localTradingDate:execution.tradingDate,localSessionSlot:String(session.sequence),balanceSnapshot:new Prisma.Decimal(String(legacy.balanceSnapshot)),tradePercentage:new Prisma.Decimal(1),principal:new Prisma.Decimal(String(legacy.tradeCapital)),profitRate:new Prisma.Decimal(String(legacy.profitRate)),profit:new Prisma.Decimal(String(legacy.profitAmount)),status:classification==="PENDING"?"LOCKED":"SETTLED",officialStartedAt:execution.placedAt,officialSettledAt:classification==="PENDING"?null:execution.settledAt??new Date(session.settlesAt),processingSettledAt:classification==="PENDING"?null:execution.updatedAt,failureCode:classification==="PENDING"?null:"LEGACY_HISTORY_ONLY"}});tradeId=trade.id}await tx.aiLegacyTradeMigration.create({data:{sourceType:"AI_BOT_EXECUTION",sourceId:execution.id,userId:execution.userId,authoritativeTradeId:tradeId,classification,status:"MIGRATED",details:{legacyTradeId:legacy.id,noBalanceMutation:true}}})},{isolationLevel:"Serializable"});result.migrated++}
  console.log(JSON.stringify(result,null,2))}
void main().finally(()=>prisma.$disconnect());
