import "dotenv/config";
import { createDailySessions, FIRST_DEPOSIT_BONUS_MS, getTradingDate, migrateTradingStore } from "@/lib/ai-trading-engine";
import { tradingPlan } from "@/lib/config";
import { prisma } from "@/lib/prisma";
import { resolveUserTimeZone } from "@/lib/timezone.server";

const repair=process.argv.includes("--repair-recent-missed"),now=Date.now();
async function main(){
  const subscriptions=await prisma.aiBotSubscription.findMany({where:{status:"ACTIVE",activatedAt:{lte:new Date(now)},expiresAt:{gt:new Date(now)}},orderBy:{activatedAt:"desc"},select:{id:true,userId:true,user:{select:{uid:true,timezone:true,country:true,state:{select:{trading:true}}}}}}),seen=new Set<string>();
  for(const subscription of subscriptions){if(seen.has(subscription.userId))continue;seen.add(subscription.userId);const user=subscription.user,timeZone=resolveUserTimeZone(user.timezone,user.country),tradingDate=getTradingDate(now,timeZone),sessions=createDailySessions(tradingDate,now,timeZone),firstDeposit=await prisma.nowPaymentsDeposit.findFirst({where:{userId:subscription.userId,credited:true,confirmedAt:{not:null},usdtAmount:{gte:tradingPlan.workingPlan}},select:{confirmedAt:true},orderBy:{confirmedAt:"asc"}}),eligible=sessions.filter(session=>session.type==="REGULAR"||Boolean(firstDeposit?.confirmedAt&&session.liveFrom>=firstDeposit.confirmedAt.getTime()&&session.liveFrom<firstDeposit.confirmedAt.getTime()+FIRST_DEPOSIT_BONUS_MS)),store=migrateTradingStore(user.state?.trading),trades=store.trades.filter(item=>eligible.some(session=>session.id===item.sessionId)),executions=await prisma.aiBotTradeExecution.findMany({where:{userId:subscription.userId,tradingDate}}),duplicates=[...new Set(trades.map(item=>item.sessionId).filter((id,index,all)=>all.indexOf(id)!==index))],incorrectMissed=trades.filter(item=>item.status==="MISSED"&&executions.some(execution=>execution.sessionId===item.sessionId));
    console.log(JSON.stringify({userId:subscription.userId,uid:user.uid,timeZone,tradingDate,subscriptionId:subscription.id,eligibleSessions:eligible.map(item=>item.id),aiBotTrades:trades.filter(item=>item.placementSource==="AI_BOT").map(item=>({sessionId:item.sessionId,status:item.status,tradeId:item.id})),missedSessions:trades.filter(item=>item.status==="MISSED").map(item=>item.sessionId),incorrectlyMissed:incorrectMissed.map(item=>item.sessionId),duplicateSessions:duplicates,settlements:executions.map(item=>({sessionId:item.sessionId,status:item.status,settledAt:item.settledAt}))}));
    if(repair&&incorrectMissed.length){const removeIds=new Set(incorrectMissed.map(item=>item.id)),sessionIds=new Set(incorrectMissed.map(item=>item.sessionId));await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "UserState" WHERE "userId"=${subscription.userId} FOR UPDATE`;const current=await tx.userState.findUniqueOrThrow({where:{userId:subscription.userId}}),locked=migrateTradingStore(current.trading),next={...locked,trades:locked.trades.filter(item=>!removeIds.has(item.id)),notifications:locked.notifications.filter(item=>!(item.type==="TRADE_MISSED"&&sessionIds.has(item.id.split(":").slice(2,-1).join(":"))))};await tx.userState.update({where:{userId:subscription.userId},data:{trading:next as object}})},{isolationLevel:"Serializable"});console.log(JSON.stringify({repair:"REMOVED_DUPLICATE_MISSED_ONLY",userId:subscription.userId,count:incorrectMissed.length}))}
  }
  console.log(JSON.stringify({mode:repair?"REPAIR_DUPLICATE_MISSED":"DRY_RUN",activeBotUsers:seen.size,noHistoricalProfitCredited:true}));
}
void main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>prisma.$disconnect());
