import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ensureFutureWallet,reconcileLegacyMirror } from "@/lib/future-wallet.server";
import { migrateWalletStore } from "@/lib/wallet-data";
const apply=process.argv.includes("--apply"),auditOnly=process.argv.includes("--audit");
async function main(){const users=await prisma.user.findMany({orderBy:{id:"asc"},select:{id:true,uid:true,state:{select:{wallet:true}},financialWallet:true}}),rows=[];let exact=0,mirrorMismatch=0,missingWallet=0,missingLedger=0,negative=0,lockMismatch=0,ambiguous=0,repaired=0;
  for(const user of users){const legacy=migrateWalletStore(user.state?.wallet),financial=user.financialWallet,ledger=financial?await prisma.aiWalletLedger.findMany({where:{userId:user.id},orderBy:[{officialAt:"asc"},{createdAt:"asc"},{id:"asc"}]}):[],pending=financial?await prisma.aiFinancialTrade.aggregate({where:{userId:user.id,status:{in:["LOCKED","SETTLING"]}},_sum:{principal:true}}):null,last=ledger.at(-1),reasons:string[]=[];if(!financial){missingWallet++;reasons.push("MISSING_FINANCIAL_WALLET")}else{if(financial.availableFuture.isNegative()||financial.lockedFuture.isNegative()){negative++;reasons.push("NEGATIVE_BALANCE")}if(!ledger.length){missingLedger++;reasons.push("MISSING_LEDGER")}if(last&&(!last.availableAfter.eq(financial.availableFuture)||!last.lockedAfter.eq(financial.lockedFuture)))reasons.push("LEDGER_TAIL_MISMATCH");if(!(pending?._sum.principal??new Prisma.Decimal(0)).eq(financial.lockedFuture)){lockMismatch++;reasons.push("LOCK_MISMATCH")}if(!new Prisma.Decimal(String(legacy.wallets.future.balance)).eq(financial.availableFuture)||!new Prisma.Decimal(String(legacy.lockedFutureTradeCapital)).eq(financial.lockedFuture)){mirrorMismatch++;reasons.push("MIRROR_MISMATCH")}}
    const safe=!reasons.some(reason=>["NEGATIVE_BALANCE","LEDGER_TAIL_MISMATCH","LOCK_MISMATCH"].includes(reason));if(!safe)ambiguous++;else if(!reasons.length)exact++;if(apply&&!auditOnly&&safe){await prisma.$transaction(async tx=>{await ensureFutureWallet(tx,user.id);await reconcileLegacyMirror(tx,user.id)},{isolationLevel:"Serializable"});repaired++}rows.push({userId:user.id,uid:user.uid,reasons,safeToRepair:safe,jsonAvailable:legacy.wallets.future.balance,jsonLocked:legacy.lockedFutureTradeCapital,relationalAvailable:financial?.availableFuture.toString()??null,relationalLocked:financial?.lockedFuture.toString()??null,ledgerAvailable:last?.availableAfter.toString()??null,ledgerLocked:last?.lockedAfter.toString()??null,pendingTradeLocked:pending?._sum.principal?.toString()??"0"})}
  const report={mode:auditOnly?"AUDIT":apply?"APPLY":"DRY_RUN",totals:{users:users.length,exact,mirrorMismatch,missingWallet,missingLedger,negative,lockMismatch,ambiguous,repaired},rows};await writeFile(`future-wallet-audit-${Date.now()}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report.totals,null,2));if(ambiguous)process.exitCode=2}
void main().finally(()=>prisma.$disconnect());
