import { Prisma, PrismaClient } from "@prisma/client";
import { ranks } from "../lib/config";
import { calculateDescendantBusiness, evaluateAuthoritativeNetwork, recalculateAuthoritativeNetwork, unmetConditions } from "../lib/rank-recalculation.server";
import { migrateWalletStore } from "../lib/wallet-data";

const prisma=new PrismaClient(),uid=process.argv.find(value=>value.startsWith("--uid="))?.slice(6).trim().toUpperCase(),apply=process.argv.includes("--apply");
if(!uid||!/^BV\d{6}$/.test(uid))throw new Error("Pass one specific UID, for example --uid=BV003588.");
const targetUid=uid;

async function snapshot(){const users=await prisma.user.findMany({select:{id:true,uid:true,sponsorUid:true,state:{select:{wallet:true,trading:true}}}}),parent=users.find(user=>user.uid===targetUid);if(!parent)throw new Error(`User ${targetUid} was not found.`);const network=evaluateAuthoritativeNetwork(users),evaluation=network.evaluations.get(targetUid)!,wallet=migrateWalletStore(parent.state?.wallet),directs=users.filter(user=>user.sponsorUid===targetUid).map(user=>{const principal=network.principals.get(user.id)!;return{uid:user.uid,retainedFuturePrincipal:principal.retainedFuturePrincipal,qualified:principal.qualified,sourceLedgerReferences:principal.sourceReferences,reason:principal.reason}}),businessRebuild=calculateDescendantBusiness(targetUid,users),downlineUids=new Set(businessRebuild.includedDescendants.map(member=>member.uid)),qualifiedTeam=users.filter(user=>downlineUids.has(user.uid)&&network.principals.get(user.id)?.qualified).length,nextRank=ranks.find(rank=>rank.star>evaluation.currentStar);return{users,parent,wallet,evaluation,report:{uid:targetUid,businessRebuild,directMembers:directs,parent:{directCount:directs.length,qualifiedDirectCount:directs.filter(member=>member.qualified).length,totalTeamCount:businessRebuild.descendantCount,totalQualifiedTeamCount:qualifiedTeam,currentRank:wallet.rankAccount.currentStar,calculatedRank:evaluation.currentStar,salaryStatus:evaluation.currentStar>0?"ELIGIBLE":"NOT_ELIGIBLE",rewardStatus:evaluation.newRewardRanks.length?`MISSING:${evaluation.newRewardRanks.join(",")}`:"CURRENT",unmetConditions:unmetConditions(evaluation),nextRank:nextRank?.star??null}}}};

async function main(){const before=await snapshot();if(!apply){console.log(JSON.stringify({mode:"DRY_RUN",...before.report},null,2));return}const results=await prisma.$transaction(tx=>recalculateAuthoritativeNetwork(tx),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}),after=await snapshot(),changed=results.find(result=>result.uid===targetUid);console.log(JSON.stringify({mode:"APPLY",before:before.report,after:after.report,recalculation:changed},null,2))}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>prisma.$disconnect());
