import "dotenv/config";
import { access } from "node:fs/promises";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
const prisma=new PrismaClient();
type Level="PASS"|"WARN"|"FAIL";const results:Array<{level:Level;name:string;detail:string}>=[];const add=(level:Level,name:string,detail:string)=>results.push({level,name,detail});let dbOkay=false;
const requiredTables=["ChatSession","ChatMessage","SupportTicket","SupportReply","SupportAuditLog","AiSupportRestriction"],requiredIndexes=["ChatSession_userId_deletedAt_lastMessageAt_id_idx","ChatMessage_conversationId_createdAt_id_idx","ChatMessage_generationStatus_startedAt_idx","SupportTicket_userId_updatedAt_id_idx","SupportTicket_status_updatedAt_id_idx","SupportAuditLog_chatSessionId_createdAt_id_idx"],requiredForeignKeys=["ChatSession_userId_fkey","ChatMessage_conversationId_fkey","SupportReply_ticketId_fkey","SupportAuditLog_adminUserId_fkey","SupportAuditLog_targetUserId_fkey"];
async function main(){if(!process.env.DATABASE_URL)add("FAIL","DATABASE_URL","Missing");else{add("PASS","DATABASE_URL","Present (value hidden)");try{await prisma.$queryRaw`SELECT 1`;dbOkay=true;add("PASS","PostgreSQL","Reachable");const tables=await prisma.$queryRaw<Array<{name:string}>>`SELECT tablename AS name FROM pg_tables WHERE schemaname=current_schema()`,tableSet=new Set(tables.map(v=>v.name));for(const name of requiredTables)add(tableSet.has(name)?"PASS":"FAIL",`Table ${name}`,tableSet.has(name)?"Exists":"Missing");const indexes=await prisma.$queryRaw<Array<{name:string}>>`SELECT indexname AS name FROM pg_indexes WHERE schemaname=current_schema()`,indexSet=new Set(indexes.map(v=>v.name));for(const name of requiredIndexes)add(indexSet.has(name)?"PASS":"FAIL",`Index ${name}`,indexSet.has(name)?"Exists":"Missing");const keys=await prisma.$queryRaw<Array<{name:string}>>`SELECT conname AS name FROM pg_constraint WHERE contype='f'`,keySet=new Set(keys.map(v=>v.name));for(const name of requiredForeignKeys)add(keySet.has(name)?"PASS":"FAIL",`Foreign key ${name}`,keySet.has(name)?"Exists":"Missing");for(const name of ["20260721023000_ai_support_chat","20260721033000_ai_support_hardening"]){const migration=await prisma.$queryRaw<Array<{finished_at:Date|null;rolled_back_at:Date|null}>>`SELECT finished_at,rolled_back_at FROM "_prisma_migrations" WHERE migration_name=${name} ORDER BY started_at DESC LIMIT 1`;add(migration[0]?.finished_at&&!migration[0]?.rolled_back_at?"PASS":"FAIL",`Migration ${name}`,migration[0]?.finished_at?"Applied":"Not applied")}}catch(error){add("FAIL","PostgreSQL checks",error instanceof Error?error.message.split("\n")[0]:"Connection failed")}}
  add(process.env.OPENAI_API_KEY?"PASS":"FAIL","OPENAI_API_KEY",process.env.OPENAI_API_KEY?"Present (value hidden)":"Missing");add(process.env.OPENAI_SUPPORT_MODEL?"PASS":"FAIL","OPENAI_SUPPORT_MODEL",process.env.OPENAI_SUPPORT_MODEL||"Missing");add(process.env.AUTH_SECRET?"PASS":"FAIL","AUTH_SECRET",process.env.AUTH_SECRET?"Present (value hidden)":"Missing");add(process.env.NEXTAUTH_URL?.startsWith("https://")?"PASS":"WARN","Secure auth URL",process.env.NEXTAUTH_URL?.startsWith("https://")?"HTTPS configured":"NEXTAUTH_URL is missing or is not HTTPS");add(dbOkay?"PASS":"FAIL","Attachment storage",dbOkay?"PostgreSQL binary storage reachable":"PostgreSQL attachment storage unavailable");try{await access(path.join(process.cwd(),"ecosystem.config.js"));add("PASS","PM2 configuration","ecosystem.config.js available")}catch{add("FAIL","PM2 configuration","ecosystem.config.js missing")}const counts={PASS:0,WARN:0,FAIL:0};for(const item of results){counts[item.level]++;console.log(`${item.level.padEnd(4)} ${item.name}: ${item.detail}`)}console.log(`\nSummary: PASS=${counts.PASS} WARN=${counts.WARN} FAIL=${counts.FAIL}`);await prisma.$disconnect();if(counts.FAIL)process.exitCode=1}
void main().catch(async error=>{console.error(`FAIL production check: ${error instanceof Error?error.message:"Unknown error"}`);await prisma.$disconnect();process.exitCode=1});
