const target=(await fetch("http://127.0.0.1:9223/json").then(r=>r.json())).find(item=>item.type==="page");
if(!target)throw new Error("No DevTools page");
const ws=new WebSocket(target.webSocketDebuggerUrl),pending=new Map(),events=[];let id=0;
await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});
const send=(method,params={})=>new Promise((resolve,reject)=>{const call=++id;pending.set(call,{resolve,reject});ws.send(JSON.stringify({id:call,method,params}))});
ws.onmessage=({data})=>{const message=JSON.parse(data);if(message.id){const call=pending.get(message.id);if(!call)return;pending.delete(message.id);message.error?call.reject(new Error(message.error.message)):call.resolve(message.result);return}events.push(message);if(message.method==="Fetch.requestPaused"){const session={user:{id:"nav-user",uid:"BV999999",name:"Nav Test",email:"nav@example.com",role:"USER"},expires:"2099-01-01T00:00:00.000Z"};void send("Fetch.fulfillRequest",{requestId:message.params.requestId,responseCode:200,responseHeaders:[{name:"content-type",value:"application/json"}],body:btoa(JSON.stringify(session))})}};
const evaluate=async expression=>(await send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true})).result.value;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const waitFor=async expression=>{for(let n=0;n<600;n++){if(await evaluate(expression))return;await delay(100)}throw new Error(`Timeout: ${expression}; state=${JSON.stringify(await evaluate("({path:location.pathname,html:document.body.innerText.slice(0,200)})"))}`)};
await send("Runtime.enable");await send("Page.enable");await send("Log.enable");await send("Fetch.enable",{patterns:[{urlPattern:"*/api/auth/session*"}]});await send("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:false});
await send("Page.navigate",{url:"http://127.0.0.1:3001/copy-trading"});await waitFor(`location.pathname==="/copy-trading"&&getComputedStyle(document.querySelector('nav[aria-label="Primary navigation"]')).position==="fixed"`);await delay(600);
const inspect=()=>evaluate(`(()=>[...document.querySelectorAll('nav[aria-label="Primary navigation"] a')].map(link=>{const r=link.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,hit=document.elementFromPoint(x,y);const chain=[];for(let node=hit;node;node=node.parentElement){const s=getComputedStyle(node);chain.push({tag:node.tagName,class:String(node.className),position:s.position,zIndex:s.zIndex,pointerEvents:s.pointerEvents,width:s.width,height:s.height})}return{label:link.textContent.trim(),href:link.getAttribute('href'),point:{x,y},hit:{tag:hit?.tagName,class:String(hit?.className),href:hit?.closest('a')?.getAttribute('href')},chain}}))()`);
const before=await inspect(),routes=[];
for(const href of ["/dashboard","/markets","/team","/profile"]){await send("Page.navigate",{url:"http://127.0.0.1:3001/copy-trading"});await waitFor(`location.pathname==="/copy-trading"&&document.querySelector('a[href="${href}"]')`);await delay(400);const point=await evaluate(`(()=>{const r=document.querySelector('a[href="${href}"]').getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);await send("Input.dispatchMouseEvent",{type:"mousePressed",x:point.x,y:point.y,button:"left",clickCount:1});await send("Input.dispatchMouseEvent",{type:"mouseReleased",x:point.x,y:point.y,button:"left",clickCount:1});await waitFor(`location.pathname==="${href}"`);routes.push({href,pathname:await evaluate("location.pathname")})}
const errors=events.filter(event=>event.method==="Runtime.exceptionThrown"||(event.method==="Log.entryAdded"&&event.params.entry.level==="error")).map(event=>event.params);
console.log(JSON.stringify({before,routes,errors},null,2));ws.close();
