import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { prisma } from "@/lib/prisma";

const MAX_BYTES=8*1024*1024;
export const BANNER_UPLOAD_DIR=process.env.BANNER_UPLOAD_DIR?path.resolve(process.env.BANNER_UPLOAD_DIR):path.join(process.cwd(),".data","banner-uploads");
const formats:Record<string,{extension:string;magic:(b:Buffer)=>boolean}>={
  "image/png":{extension:"png",magic:b=>b.length>24&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))},
  "image/jpeg":{extension:"jpg",magic:b=>b.length>4&&b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9},
  "image/webp":{extension:"webp",magic:b=>b.length>30&&b.toString("ascii",0,4)==="RIFF"&&b.toString("ascii",8,12)==="WEBP"},
};

export class BannerError extends Error{constructor(message:string,public status=400){super(message)}}
function dimensions(buffer:Buffer,mime:string){
  if(mime==="image/png")return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};
  if(mime==="image/jpeg"){let offset=2;while(offset+9<buffer.length){if(buffer[offset]!==0xff){offset++;continue}const marker=buffer[offset+1],length=buffer.readUInt16BE(offset+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{height:buffer.readUInt16BE(offset+5),width:buffer.readUInt16BE(offset+7)};if(length<2)break;offset+=2+length}throw new BannerError("Unable to read JPEG dimensions.")}
  const kind=buffer.toString("ascii",12,16);if(kind==="VP8X")return{width:1+buffer.readUIntLE(24,3),height:1+buffer.readUIntLE(27,3)};if(kind==="VP8L"){const bits=buffer.readUInt32LE(21);return{width:(bits&0x3fff)+1,height:((bits>>14)&0x3fff)+1}}if(kind==="VP8 ")return{width:buffer.readUInt16LE(26)&0x3fff,height:buffer.readUInt16LE(28)&0x3fff};throw new BannerError("Unable to read WEBP dimensions.");
}
export async function validateBannerFile(value:FormDataEntryValue|null){if(!(value instanceof File)||!value.size)throw new BannerError("Choose a banner image.");if(value.size>MAX_BYTES)throw new BannerError("Banner must be 8 MB or smaller.");const format=formats[value.type];if(!format)throw new BannerError("Banner must be JPEG, PNG, or WEBP.");const bytes=Buffer.from(await value.arrayBuffer());if(!format.magic(bytes))throw new BannerError("The uploaded file content does not match its image type.");const size=dimensions(bytes,value.type);if(!size.width||!size.height||Math.abs(size.width/size.height-9/16)>.006)throw new BannerError(`Banner must use a 9:16 portrait ratio. Received ${size.width}×${size.height}.`);return{bytes,mimeType:value.type,fileSize:value.size,width:size.width,height:size.height,extension:format.extension}}
export function dates(startsAt:string,expiresAt:string){const start=startsAt?new Date(startsAt):null,end=expiresAt?new Date(expiresAt):null;if(start&&Number.isNaN(start.getTime())||end&&Number.isNaN(end.getTime()))throw new BannerError("Enter valid start and expiry dates.");if(start&&end&&end<=start)throw new BannerError("Expiry must be later than the start time.");return{startsAt:start,expiresAt:end}}
export async function createBanner(adminId:string,form:FormData){const title=String(form.get("title")??"").trim();if(!title||title.length>120)throw new BannerError("Enter a title up to 120 characters.");const file=await validateBannerFile(form.get("image")),range=dates(String(form.get("startsAt")??""),String(form.get("expiresAt")??"")),id=randomUUID(),name=`${id}.${file.extension}`;await mkdir(BANNER_UPLOAD_DIR,{recursive:true});await writeFile(path.join(BANNER_UPLOAD_DIR,name),file.bytes,{flag:"wx"});try{return await prisma.$transaction(async tx=>{const banner=await tx.banner.create({data:{id,title,imageUrl:`/api/banners/${id}/image`,imagePath:name,mimeType:file.mimeType,fileSize:file.fileSize,width:file.width,height:file.height,...range,createdByAdminId:adminId}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_CREATED",metadata:{title,fileSize:file.fileSize,width:file.width,height:file.height}}});return banner})}catch(error){await unlink(path.join(BANNER_UPLOAD_DIR,name)).catch(()=>{});throw error}}
export async function replaceBannerFile(id:string,adminId:string,form:FormData){const current=await prisma.banner.findUnique({where:{id}});if(!current)throw new BannerError("Banner not found.",404);const file=await validateBannerFile(form.get("image")),name=`${id}-${randomUUID()}.${file.extension}`;await mkdir(BANNER_UPLOAD_DIR,{recursive:true});await writeFile(path.join(BANNER_UPLOAD_DIR,name),file.bytes,{flag:"wx"});try{const banner=await prisma.$transaction(async tx=>{const value=await tx.banner.update({where:{id},data:{imagePath:name,mimeType:file.mimeType,fileSize:file.fileSize,width:file.width,height:file.height}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_IMAGE_REPLACED",metadata:{fileSize:file.fileSize,width:file.width,height:file.height}}});return value});await unlink(path.join(BANNER_UPLOAD_DIR,current.imagePath)).catch(()=>{});return banner}catch(error){await unlink(path.join(BANNER_UPLOAD_DIR,name)).catch(()=>{});throw error}}
export async function activateBanner(id:string,adminId:string){const now=new Date();return prisma.$transaction(async tx=>{const target=await tx.banner.findUnique({where:{id}});if(!target)throw new BannerError("Banner not found.",404);if(target.expiresAt&&target.expiresAt<=now)throw new BannerError("An expired banner cannot be activated.");await tx.banner.updateMany({where:{isActive:true,id:{not:id}},data:{isActive:false,status:"INACTIVE"}});const banner=await tx.banner.update({where:{id},data:{isActive:true,status:"ACTIVE"}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_ACTIVATED",metadata:{previousActiveDeactivated:true}}});return banner})}
export async function deactivateBanner(id:string,adminId:string){return prisma.$transaction(async tx=>{const banner=await tx.banner.update({where:{id},data:{isActive:false,status:"INACTIVE"}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_DEACTIVATED"}});return banner})}
export async function updateBanner(id:string,adminId:string,input:{title?:string;startsAt?:string;expiresAt?:string}){const range=dates(input.startsAt??"",input.expiresAt??"");return prisma.$transaction(async tx=>{const banner=await tx.banner.update({where:{id},data:{title:input.title?.trim(),...range}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_UPDATED",metadata:input}});return banner})}
export async function deleteBanner(id:string,adminId:string){const banner=await prisma.$transaction(async tx=>{const value=await tx.banner.findUnique({where:{id}});if(!value)throw new BannerError("Banner not found.",404);await tx.bannerAuditLog.create({data:{adminId,action:"BANNER_DELETED",metadata:{bannerId:id,title:value.title}}});await tx.banner.delete({where:{id}});return value});await unlink(path.join(BANNER_UPLOAD_DIR,banner.imagePath)).catch(()=>{});return banner}
export async function activeBanner(){const now=new Date();await prisma.banner.updateMany({where:{isActive:true,expiresAt:{lte:now}},data:{isActive:false,status:"EXPIRED"}});return prisma.banner.findFirst({where:{isActive:true,status:"ACTIVE",AND:[{OR:[{startsAt:null},{startsAt:{lte:now}}]},{OR:[{expiresAt:null},{expiresAt:{gt:now}}]}]},orderBy:{updatedAt:"desc"}})}
export async function bannerBytes(imagePath:string){const resolved=path.resolve(BANNER_UPLOAD_DIR,imagePath);if(path.dirname(resolved)!==path.resolve(BANNER_UPLOAD_DIR))throw new BannerError("Invalid banner path.",403);return readFile(resolved)}
