import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { prisma } from "@/lib/prisma";
import { BannerImageError, processBannerImage } from "./banner-image.server";

export const BANNER_UPLOAD_DIR=process.env.BANNER_UPLOAD_DIR?path.resolve(process.env.BANNER_UPLOAD_DIR):path.join(process.cwd(),".data","banner-uploads");

export class BannerError extends Error{constructor(message:string,public status=400){super(message)}}
export async function validateBannerFile(value:FormDataEntryValue|null){try{return await processBannerImage(value)}catch(error){if(error instanceof BannerImageError)throw new BannerError(error.message,error.code==="TOO_LARGE"?413:400);throw error}}
export const BANNER_START_PAST_TOLERANCE_MS=5*60*1000;
export function dates(startsAt:string,expiresAt:string,now=Date.now()){const requestedStart=startsAt?new Date(startsAt):null,end=expiresAt?new Date(expiresAt):null;if(requestedStart&&Number.isNaN(requestedStart.getTime())||end&&Number.isNaN(end.getTime()))throw new BannerError("Enter valid start and expiry dates.");if(requestedStart&&requestedStart.getTime()<now-BANNER_START_PAST_TOLERANCE_MS)throw new BannerError(`Start time is more than 5 minutes in the past. Server current time: ${new Date(now).toISOString()}.`);const start=requestedStart&&requestedStart.getTime()<now?new Date(now):requestedStart;if(end&&end.getTime()<=(start?.getTime()??now))throw new BannerError("Expiry must be later than the start time.");return{startsAt:start,expiresAt:end}}
export async function createBanner(adminId:string,form:FormData){const title=String(form.get("title")??"").trim(),uploadKey=String(form.get("uploadKey")??"").trim();if(!title||title.length>120)throw new BannerError("Enter a title up to 120 characters.");if(!/^[a-zA-Z0-9-]{16,100}$/.test(uploadKey))throw new BannerError("Invalid upload retry key.");const duplicate=await prisma.banner.findUnique({where:{uploadKey}});if(duplicate)return duplicate;const file=await validateBannerFile(form.get("image")),range=dates(String(form.get("startsAt")??""),String(form.get("expiresAt")??"")),id=randomUUID(),name=`${id}.${file.extension}`;await mkdir(BANNER_UPLOAD_DIR,{recursive:true});await writeFile(path.join(BANNER_UPLOAD_DIR,name),file.bytes,{flag:"wx"});try{return await prisma.$transaction(async tx=>{const banner=await tx.banner.create({data:{id,title,uploadKey,imageUrl:`/api/banners/${id}/image`,imagePath:name,mimeType:file.mimeType,fileSize:file.fileSize,width:file.width,height:file.height,...range,createdByAdminId:adminId}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_CREATED",metadata:{title,fileSize:file.fileSize,width:file.width,height:file.height,sourceWidth:file.sourceWidth,sourceHeight:file.sourceHeight}}});return banner})}catch(error){await unlink(path.join(BANNER_UPLOAD_DIR,name)).catch(()=>{});const existing=await prisma.banner.findUnique({where:{uploadKey}});if(existing)return existing;throw error}}
export async function replaceBannerFile(id:string,adminId:string,form:FormData){const current=await prisma.banner.findUnique({where:{id}});if(!current)throw new BannerError("Banner not found.",404);const file=await validateBannerFile(form.get("image")),name=`${id}-${randomUUID()}.${file.extension}`;await mkdir(BANNER_UPLOAD_DIR,{recursive:true});await writeFile(path.join(BANNER_UPLOAD_DIR,name),file.bytes,{flag:"wx"});try{const banner=await prisma.$transaction(async tx=>{const value=await tx.banner.update({where:{id},data:{imagePath:name,mimeType:file.mimeType,fileSize:file.fileSize,width:file.width,height:file.height}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_IMAGE_REPLACED",metadata:{fileSize:file.fileSize,width:file.width,height:file.height}}});return value});await unlink(path.join(BANNER_UPLOAD_DIR,current.imagePath)).catch(()=>{});return banner}catch(error){await unlink(path.join(BANNER_UPLOAD_DIR,name)).catch(()=>{});throw error}}
export async function activateBanner(id:string,adminId:string){const now=new Date();return prisma.$transaction(async tx=>{const target=await tx.banner.findUnique({where:{id}});if(!target)throw new BannerError("Banner not found.",404);if(target.expiresAt&&target.expiresAt<=now)throw new BannerError("An expired banner cannot be activated.");await tx.banner.updateMany({where:{isActive:true,id:{not:id}},data:{isActive:false,status:"INACTIVE"}});const banner=await tx.banner.update({where:{id},data:{isActive:true,status:"ACTIVE"}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_ACTIVATED",metadata:{previousActiveDeactivated:true}}});return banner})}
export async function deactivateBanner(id:string,adminId:string){return prisma.$transaction(async tx=>{const banner=await tx.banner.update({where:{id},data:{isActive:false,status:"INACTIVE"}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_DEACTIVATED"}});return banner})}
export async function updateBanner(id:string,adminId:string,input:{title?:string;startsAt?:string;expiresAt?:string}){const range=dates(input.startsAt??"",input.expiresAt??"");return prisma.$transaction(async tx=>{const banner=await tx.banner.update({where:{id},data:{title:input.title?.trim(),...range}});await tx.bannerAuditLog.create({data:{bannerId:id,adminId,action:"BANNER_UPDATED",metadata:input}});return banner})}
export async function deleteBanner(id:string,adminId:string){const banner=await prisma.$transaction(async tx=>{const value=await tx.banner.findUnique({where:{id}});if(!value)throw new BannerError("Banner not found.",404);await tx.bannerAuditLog.create({data:{adminId,action:"BANNER_DELETED",metadata:{bannerId:id,title:value.title}}});await tx.banner.delete({where:{id}});return value});await unlink(path.join(BANNER_UPLOAD_DIR,banner.imagePath)).catch(()=>{});return banner}
export async function activeBanner(){const now=new Date();await prisma.banner.updateMany({where:{isActive:true,expiresAt:{lte:now}},data:{isActive:false,status:"EXPIRED"}});return prisma.banner.findFirst({where:{isActive:true,status:"ACTIVE",AND:[{OR:[{startsAt:null},{startsAt:{lte:now}}]},{OR:[{expiresAt:null},{expiresAt:{gt:now}}]}]},orderBy:{updatedAt:"desc"}})}
export async function bannerBytes(imagePath:string){const resolved=path.resolve(BANNER_UPLOAD_DIR,imagePath);if(path.dirname(resolved)!==path.resolve(BANNER_UPLOAD_DIR))throw new BannerError("Invalid banner path.",403);return readFile(resolved)}
