import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertMutationRequest } from "@/lib/support-security.server";
import { decodeCursor, encodeCursor, pageSize } from "@/lib/support-pagination";
const rename=z.object({title:z.string().trim().min(1).max(80)}).strict();
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireAuthenticatedUser(),{id}=await params,url=new URL(request.url),take=pageSize(url.searchParams.get("limit")),cursor=decodeCursor(url.searchParams.get("cursor")),session=await prisma.chatSession.findFirst({where:{id,userId:user.id,deletedAt:null},select:{id:true,title:true,unreadCount:true,lastMessageAt:true,createdAt:true}});if(!session)return NextResponse.json({error:"Chat not found."},{status:404});const rows=await prisma.chatMessage.findMany({where:{conversationId:id,...(cursor?{OR:[{createdAt:{lt:cursor.at}},{createdAt:cursor.at,id:{lt:cursor.id}}]}:{})},orderBy:[{createdAt:"desc"},{id:"desc"}],take:take+1}),hasMore=rows.length>take,page=hasMore?rows.slice(0,take):rows,last=page.at(-1);if(session.unreadCount)await prisma.chatSession.update({where:{id},data:{unreadCount:0}});return NextResponse.json({session:{...session,unreadCount:0,messages:page.reverse()},nextCursor:hasMore&&last?encodeCursor(last.createdAt,last.id):null},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Authentication required."},{status:401})}}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireAuthenticatedUser();assertMutationRequest(request,user.id);const{id}=await params,value=rename.parse(await request.json()),result=await prisma.chatSession.updateMany({where:{id,userId:user.id,deletedAt:null},data:{title:value.title}});if(!result.count)return NextResponse.json({error:"Chat not found."},{status:404});return NextResponse.json({message:"Chat renamed."})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Enter a valid chat name.":"Unable to rename chat."},{status:400})}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireAuthenticatedUser();assertMutationRequest(request,user.id);const{id}=await params,result=await prisma.chatSession.updateMany({where:{id,userId:user.id,deletedAt:null},data:{deletedAt:new Date()}});if(!result.count)return NextResponse.json({error:"Chat not found."},{status:404});return NextResponse.json({message:"Chat deleted."})}catch{return NextResponse.json({error:"Unable to delete chat."},{status:400})}}
