import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { AiIntentError, createTradeIntent, placeIntentTrade, publicSignal, readTradeIntent } from "@/lib/ai-trade-intent.server";
const createInput=z.object({sessionId:z.string().min(8).max(160)}),placeInput=z.object({token:z.string().min(32).max(200),side:z.enum(["BUY","SELL"])});
function failure(error:unknown){if(error instanceof AiIntentError)return NextResponse.json({code:error.code,error:error.message},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({code:"INVALID_REQUEST",error:error.issues[0]?.message??"Invalid trading request."},{status:400});if(error instanceof Error&&error.message==="UNAUTHENTICATED")return NextResponse.json({code:"UNAUTHENTICATED",error:"Authentication required. Please sign in again."},{status:401});console.error("[ai-trade] request_failed",{errorType:error instanceof Error?error.name:typeof error,errorCode:typeof error==="object"&&error&&"code" in error?String(error.code):undefined});return NextResponse.json({code:"INTERNAL_ERROR",error:"Unable to place the trade because the server transaction failed. Please retry."},{status:500})}
export async function GET(request:Request){try{const user=await requireAuthenticatedUser(),token=new URL(request.url).searchParams.get("token")??"",value=await readTradeIntent(user.id,token);return NextResponse.json({session:publicSignal(value.session)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){try{const user=await requireAuthenticatedUser(),value=createInput.parse(await request.json());return NextResponse.json(await createTradeIntent({id:user.id,uid:user.uid},value.sessionId),{status:201})}catch(error){return failure(error)}}
export async function PUT(request:Request){try{const user=await requireAuthenticatedUser(),value=placeInput.parse(await request.json());return NextResponse.json(await placeIntentTrade({id:user.id,uid:user.uid},value.token,value.side))}catch(error){return failure(error)}}
