import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { AiIntentError, createTradeIntent, placeIntentTrade, publicSignal, readTradeIntent } from "@/lib/ai-trade-intent.server";
import { prisma } from "@/lib/prisma";
import { formatUserTimestamp, resolveUserTimeZone } from "@/lib/timezone.server";
const createInput=z.object({sessionId:z.string().min(8).max(160)}),placeInput=z.object({token:z.string().min(32).max(200),side:z.enum(["BUY","SELL"])});
async function localizedSession(userId:string,session:ReturnType<typeof publicSignal>){const profile=await prisma.user.findUnique({where:{id:userId},select:{timezone:true,country:true}}),timeZone=resolveUserTimeZone(profile?.timezone,profile?.country);return{...session,displayStartTime:formatUserTimestamp(session.liveFrom,timeZone).localTime}}
function failure(error:unknown){if(error instanceof AiIntentError)return NextResponse.json({code:error.code,error:error.message},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({code:"INVALID_REQUEST",error:error.issues[0]?.message??"Invalid trading request."},{status:400});if(error instanceof Error&&error.message==="UNAUTHENTICATED")return NextResponse.json({code:"UNAUTHENTICATED",error:"Authentication required. Please sign in again."},{status:401});console.error("[ai-trade] request_failed",{errorType:error instanceof Error?error.name:typeof error,errorCode:typeof error==="object"&&error&&"code" in error?String(error.code):undefined});return NextResponse.json({code:"INTERNAL_ERROR",error:"Unable to place the trade because the server transaction failed. Please retry."},{status:500})}
export async function GET(request:Request){try{const user=await requireAuthenticatedUser(),token=new URL(request.url).searchParams.get("token")??"",value=await readTradeIntent(user.id,token);return NextResponse.json({session:await localizedSession(user.id,publicSignal(value.session))},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){try{const user=await requireAuthenticatedUser(),value=createInput.parse(await request.json()),result=await createTradeIntent({id:user.id,uid:user.uid},value.sessionId);return NextResponse.json({...result,session:await localizedSession(user.id,result.session)},{status:201})}catch(error){return failure(error)}}
export async function PUT(request:Request){try{const user=await requireAuthenticatedUser(),value=placeInput.parse(await request.json()),result=await placeIntentTrade({id:user.id,uid:user.uid},value.token,value.side);return NextResponse.json({...result,session:await localizedSession(user.id,result.session)})}catch(error){return failure(error)}}
