import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminUser } from "@/lib/auth/server";
import { prisma } from "@/lib/prisma";
import { assertSameOrigin } from "@/lib/support-security.server";
const action=z.discriminatedUnion("action",[
  z.object({action:z.literal("REPLY"),ticketId:z.string().min(1),message:z.string().trim().min(1).max(4000),status:z.enum(["OPEN","IN_PROGRESS","RESOLVED","CLOSED"])}),
  z.object({action:z.literal("STATUS"),ticketId:z.string().min(1),status:z.enum(["OPEN","IN_PROGRESS","RESOLVED","CLOSED"])}),
  z.object({action:z.literal("BAN"),userId:z.string().min(1),banned:z.boolean(),reason:z.string().trim().max(500)})
]);
const optionalUrl=z.union([z.literal(""),z.string().url().max(500)]),configInput=z.object({supportEmail:z.union([z.literal(""),z.string().email().max(254)]),whatsappUrl:optionalUrl,telegramUrl:optionalUrl,helpCenterUrl:optionalUrl}).strict(),nullable=(value:string)=>value||null;
export async function GET(){try{await requireAdminUser();const[tickets,conversations,configuration]=await Promise.all([prisma.supportTicket.findMany({include:{user:{select:{id:true,uid:true,name:true,email:true,supportRestrictions:true}},replies:{orderBy:{createdAt:"asc"}}},orderBy:{updatedAt:"desc"},take:300}),prisma.chatSession.findMany({where:{deletedAt:null},include:{user:{select:{id:true,uid:true,name:true,email:true,supportRestrictions:true}},messages:{orderBy:{createdAt:"asc"},take:100}},orderBy:{lastMessageAt:"desc"},take:200}),prisma.supportConfiguration.findUnique({where:{id:"default"}})]);return NextResponse.json({tickets:tickets.map(t=>({...t,attachmentData:undefined,hasAttachment:Boolean(t.attachmentName)})),conversations,configuration:configuration??{supportEmail:"",whatsappUrl:"",telegramUrl:"",helpCenterUrl:""}},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Admin access required."},{status:401})}}
export async function PATCH(request:Request){try{assertSameOrigin(request);const admin=await requireAdminUser(),value=action.parse(await request.json());if(value.action==="BAN"){await prisma.aiSupportRestriction.upsert({where:{userId:value.userId},create:{userId:value.userId,banned:value.banned,reason:nullable(value.reason)},update:{banned:value.banned,reason:nullable(value.reason)}});return NextResponse.json({message:value.banned?"AI chat access restricted.":"AI chat access restored."})}const ticket=await prisma.supportTicket.findUnique({where:{id:value.ticketId}});if(!ticket)return NextResponse.json({error:"Ticket not found."},{status:404});if(value.action==="STATUS"){await prisma.supportTicket.update({where:{id:ticket.id},data:{status:value.status}});return NextResponse.json({message:"Ticket status updated."})}await prisma.$transaction(async tx=>{await tx.supportReply.create({data:{ticketId:ticket.id,adminId:admin.id,message:value.message}});await tx.supportTicket.update({where:{id:ticket.id},data:{status:value.status,adminReply:value.message}});if(ticket.sessionId){const reply=await tx.chatMessage.create({data:{conversationId:ticket.sessionId,role:"ADMIN",message:value.message}});await tx.chatSession.update({where:{id:ticket.sessionId},data:{unreadCount:{increment:1},lastMessageAt:reply.createdAt}})}});return NextResponse.json({message:"Reply sent to the conversation."})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message??"Invalid update.":"Unable to update support."},{status:400})}}
export async function PUT(request:Request){try{assertSameOrigin(request);await requireAdminUser();const value=configInput.parse(await request.json()),configuration=await prisma.supportConfiguration.upsert({where:{id:"default"},create:{id:"default",supportEmail:nullable(value.supportEmail),whatsappUrl:nullable(value.whatsappUrl),telegramUrl:nullable(value.telegramUrl),helpCenterUrl:nullable(value.helpCenterUrl)},update:{supportEmail:nullable(value.supportEmail),whatsappUrl:nullable(value.whatsappUrl),telegramUrl:nullable(value.telegramUrl),helpCenterUrl:nullable(value.helpCenterUrl)}});return NextResponse.json({configuration,message:"Support contact settings saved."})}catch{return NextResponse.json({error:"Unable to save support settings."},{status:400})}}
